version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "America/Toronto"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
    commit-message:
      prefix: "ci"
    groups:
      github-actions-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/demo/commonjs-demo"
      - "/apps/browser-extension"
      - "/apps/gatekeeper-client"
      - "/apps/herald-client"
      - "/apps/keymaster-client"
      - "/apps/react-wallet"
      - "/services/drawbridge/server"
      - "/services/explorer"
      - "/services/gatekeeper/server"
      - "/services/herald"
      - "/services/herald/server"
      - "/services/keymaster/server"
      - "/services/mediators/hyperswarm"
      - "/services/mediators/satoshi"
      - "/services/satoshi-wallet/server"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "05:00"
      timezone: "America/Toronto"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
      - "javascript"
    commit-message:
      prefix: "deps"
    groups:
      npm_and_yarn:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
