FROM node:24-bullseye-slim

WORKDIR /app

COPY package*.json ./
COPY packages/ ./packages/

RUN npm ci
RUN npm run build

COPY services/mediators/filecoin-wallet ./wallet/

RUN cd wallet && npm ci && npm run build

WORKDIR /app/wallet

ARG GIT_COMMIT=unknown
ENV GIT_COMMIT=$GIT_COMMIT

EXPOSE 4242 4243

CMD ["node", "dist/wallet-api.js"]
