FROM node:24-bullseye-slim

WORKDIR /app

COPY package*.json ./
COPY packages/ ./packages/

RUN npm ci
RUN npm run build

COPY services/mediators/filecoin ./filecoin/
WORKDIR /app/filecoin
RUN npm ci && npm run build

ARG GIT_COMMIT=unknown
ENV GIT_COMMIT=$GIT_COMMIT

EXPOSE 4244 4245

CMD ["node", "dist/filecoin-mediator.js"]
