# Use the official Node.js as the base image
FROM node:22.15.0-bullseye-slim

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./
COPY packages/ ./packages/

# Install dependencies
RUN npm ci
RUN npm run build

COPY services/drawbridge ./drawbridge/

RUN cd drawbridge/server && npm ci && npm run build

WORKDIR /app/drawbridge

# Run...
CMD ["node", "server/dist/drawbridge-api.js"]
