services:
  btc-signet-node:
    image: ghcr.io/archetech/bitcoin-core:v28.0-multiarch
    volumes:
      - ./data/btc-signet:/root/.bitcoin
    ports:
      - 127.0.0.1:38332:38332

  btc-signet-wallet:
    build:
      context: .
      dockerfile: Dockerfile.wallet
      args:
        GIT_COMMIT: ${GIT_COMMIT:-unknown}
    image: ghcr.io/archetech/wallet
    environment:
      - ARCHON_WALLET_PORT=4240
      - ARCHON_WALLET_METRICS_PORT=4241
      - ARCHON_WALLET_NETWORK=signet
      - ARCHON_WALLET_BTC_HOST=btc-signet-node
      - ARCHON_WALLET_BTC_PORT=38332
      - ARCHON_WALLET_BTC_USER=${ARCHON_SIGNET_USER}
      - ARCHON_WALLET_BTC_PASS=${ARCHON_SIGNET_PASS}
      - ARCHON_NODE_ID=${ARCHON_NODE_ID}
      - ARCHON_KEYMASTER_URL=http://keymaster:4226
      - ARCHON_ADMIN_API_KEY=${ARCHON_ADMIN_API_KEY}
    user: "${ARCHON_UID}:${ARCHON_GID}"
    ports:
      - "127.0.0.1:4240:4240"
      - "127.0.0.1:4241:4241"
    depends_on:
      keymaster:
        condition: service_started

  btc-signet-mediator:
    build:
      context: .
      dockerfile: Dockerfile.satoshi
      args:
        GIT_COMMIT: ${GIT_COMMIT:-unknown}
    image: ghcr.io/archetech/satoshi-mediator
    environment:
      - ARCHON_GATEKEEPER_URL=http://gatekeeper:4224
      - ARCHON_KEYMASTER_URL=http://keymaster:4226
      - ARCHON_MONGODB_URL=mongodb://mongodb:27017
      - ARCHON_REDIS_URL=redis://redis:6379
      - ARCHON_ADMIN_API_KEY=${ARCHON_ADMIN_API_KEY}
      - ARCHON_NODE_ID=${ARCHON_NODE_ID}
      - ARCHON_SAT_CHAIN=BTC:signet
      - ARCHON_SAT_NETWORK=testnet
      - ARCHON_SAT_HOST=btc-signet-node
      - ARCHON_SAT_PORT=38332
      - ARCHON_SAT_START_BLOCK=${ARCHON_SIGNET_START_BLOCK}
      - ARCHON_SAT_USER=${ARCHON_SIGNET_USER}
      - ARCHON_SAT_PASS=${ARCHON_SIGNET_PASS}
      - ARCHON_WALLET_URL=http://btc-signet-wallet:4240
      - ARCHON_SAT_IMPORT_INTERVAL=${ARCHON_SIGNET_IMPORT_INTERVAL}
      - ARCHON_SAT_EXPORT_INTERVAL=${ARCHON_SIGNET_EXPORT_INTERVAL}
      - ARCHON_SAT_FEE_BLOCK_TARGET=${ARCHON_SIGNET_FEE_BLOCK_TARGET}
      - ARCHON_SAT_FEE_FALLBACK_SAT_BYTE=${ARCHON_SIGNET_FEE_FALLBACK_SAT_BYTE}
      - ARCHON_SAT_FEE_MAX=${ARCHON_SIGNET_FEE_MAX}
      - ARCHON_SAT_RBF_ENABLED=${ARCHON_SIGNET_RBF_ENABLED}
      - ARCHON_SAT_REIMPORT=${ARCHON_SIGNET_REIMPORT}
      - ARCHON_SAT_DB=${ARCHON_SIGNET_DB}
      - ARCHON_SAT_METRICS_PORT=4236
    ports:
      - "127.0.0.1:4236:4236"
    volumes:
      - ./data:/app/satoshi/data
    user: "${ARCHON_UID}:${ARCHON_GID}"
    depends_on:
      - btc-signet-node
      - gatekeeper
      - keymaster
      - btc-signet-wallet
