#!/usr/bin/env bash
set -e

export GIT_COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")

docker compose -f docker/compose/minimal.yml down
docker compose -f docker/compose/minimal.yml build "$@"
docker compose -f docker/compose/minimal.yml up "$@"
