#!/bin/bash

set -e

# Change to the project root, assuming the script is in ./scripts/
cd "$(git rev-parse --show-toplevel)"

touch .env

ENV_FILE=".env"

echo "Generating .env file at project root..."

cat > "$ENV_FILE" <<EOL
# Auto-generated .env file

# General
ARCHON_UID=1000
ARCHON_GID=1000
ARCHON_NODE_NAME=archon-quality
ARCHON_NODE_ID=archon-quality
ARCHON_PROTOCOL=/ARCHON/test


# Gatekeeper
ARCHON_GATEKEEPER_PORT=4224
ARCHON_GATEKEEPER_DID_PREFIX=did:cid
ARCHON_GATEKEEPER_DB=redis
ARCHON_GATEKEEPER_REGISTRIES=local
ARCHON_GATEKEEPER_GC_INTERVAL=60
ARCHON_GATEKEEPER_STATUS_INTERVAL=1
ARCHON_GATEKEEPER_SERVE_CLIENT=true

# Keymaster
ARCHON_KEYMASTER_PORT=4226
ARCHON_KEYMASTER_DB=redis
ARCHON_ENCRYPTED_PASSPHRASE=passphrase
ARCHON_KEYMASTER_SERVE_CLIENT=true
ARCHON_WALLET_CACHE=false
ARCHON_DEFAULT_REGISTRY=local
ARCHON_DISABLE_SEARCH=true

# CLI
ARCHON_GATEKEEPER_URL=http://localhost:4224
ARCHON_KEYMASTER_URL=http://localhost:4226

# Hyperswarm
ARCHON_HYPR_EXPORT_INTERVAL=2
ARCHON_PROTOCOL=/ARCHON/testing

# Bitcoin mediator
ARCHON_BTC_HOST=localhost
ARCHON_BTC_CHAIN=BTC
ARCHON_BTC_NETWORK=bitcoin
ARCHON_BTC_START_BLOCK=927970
ARCHON_BTC_PORT=8332
ARCHON_BTC_USER=bitcoin
ARCHON_BTC_PASS=bitcoin
ARCHON_BTC_WALLET=archon
ARCHON_BTC_IMPORT_INTERVAL=1
ARCHON_BTC_EXPORT_INTERVAL=1
ARCHON_BTC_FEE_BLOCK_TARGET=1
ARCHON_BTC_FEE_FALLBACK_SAT_BYTE=10
ARCHON_BTC_FEE_MAX=0.00010000
ARCHON_BTC_RBF_ENABLED=true
ARCHON_BTC_REIMPORT=true
ARCHON_BTC_DB=json

# Bitcoin testnet4 mediator
ARCHON_BTC_T4_HOST=localhost
ARCHON_BTC_T4_CHAIN=BTC:testnet4
ARCHON_BTC_T4_NETWORK=testnet
ARCHON_BTC_T4_START_BLOCK=38000
ARCHON_BTC_T4_PORT=48332
ARCHON_BTC_T4_USER=testnet4
ARCHON_BTC_T4_PASS=testnet4
ARCHON_BTC_T4_WALLET=archon
ARCHON_BTC_T4_IMPORT_INTERVAL=1
ARCHON_BTC_T4_EXPORT_INTERVAL=1
ARCHON_BTC_T4_FEE_BLOCK_TARGET=1
ARCHON_BTC_T4_FEE_FALLBACK_SAT_BYTE=10
ARCHON_BTC_T4_FEE_MAX=0.00000600
ARCHON_BTC_T4_RBF_ENABLED=false
ARCHON_BTC_T4_REIMPORT=true
ARCHON_BTC_T4_DB=json

# BTC signet mediator
ARCHON_SIGNET_HOST=localhost
ARCHON_SIGNET_START_BLOCK=251900
ARCHON_SIGNET_PORT=38332
ARCHON_SIGNET_USER=signet
ARCHON_SIGNET_PASS=signet
ARCHON_SIGNET_WALLET=archon
ARCHON_SIGNET_IMPORT_INTERVAL=1
ARCHON_SIGNET_EXPORT_INTERVAL=1
ARCHON_SIGNET_FEE_BLOCK_TARGET=1
ARCHON_SIGNET_FEE_FALLBACK_SAT_BYTE=10
ARCHON_SIGNET_FEE_MAX=0.00003000
ARCHON_SIGNET_RBF_ENABLED=false
ARCHON_SIGNET_REIMPORT=true
ARCHON_SIGNET_DB=json

# BTC signet inscribed mediator
ARCHON_SIGNET_INS_HOST=localhost
ARCHON_SIGNET_INS_START_BLOCK=262868
ARCHON_SIGNET_INS_PORT=38332
ARCHON_SIGNET_INS_USER=signet
ARCHON_SIGNET_INS_PASS=signet
ARCHON_SIGNET_INS_WALLET=archon
ARCHON_SIGNET_INS_IMPORT_INTERVAL=1
ARCHON_SIGNET_INS_EXPORT_INTERVAL=1
ARCHON_SIGNET_INS_FEE_BLOCK_TARGET=1
ARCHON_SIGNET_INS_FEE_FALLBACK_SAT_BYTE=10
ARCHON_SIGNET_INS_FEE_MAX=0.00200000
ARCHON_SIGNET_INS_RBF_ENABLED=false
ARCHON_SIGNET_INS_REIMPORT=true
ARCHON_SIGNET_INS_DB=json

# IPFS mediator
ARCHON_IPFS_INTERVAL=60
ARCHON_IPFS_BATCH_SIZE=100
ARCHON_IPFS_CONCURRENCY=10
EOL

echo ".env file created with the following content:"
cat "$ENV_FILE"
