-- Generated by generate-integrated-agent-fixtures.mjs; do not edit.
import IntegratedAgentConvergence
set_option warningAsError true
set_option maxRecDepth 10000
set_option maxHeartbeats 8000000
namespace Archon.AssetControllerFixtures
def atoms0 : Nat → String := (fun i => ["{\"@context\":[\"https://www.w3.org/ns/did/v1\"],\"id\":\"did:cid:bagaaiera5sq6vrqmdai6j4ipubm544igndxaldhl7fu4kiqd54ozqme3undq\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaiera5sq6vrqmdai6j4ipubm544igndxaldhl7fu4kiqd54ozqme3undq\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"azJ09248a2vKqs80FWCLG3Xw5xc9UF4sd_DImBsaxDw\",\"y\":\"215hdHiCRD7Q-DyAt5zcT4YLjdXFhm6y8bAbbia4Ne4\"}}],\"authentication\":[\"#key-1\"],\"assertionMethod\":[\"#key-1\"],\"capabilityInvocation\":[\"#key-1\"]}", "{\"id\":\"did:cid:bagaaiera5sq6vrqmdai6j4ipubm544igndxaldhl7fu4kiqd54ozqme3undq\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaiera5sq6vrqmdai6j4ipubm544igndxaldhl7fu4kiqd54ozqme3undq\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"7c8q6jrR_99AQxXwI0id7tkVCZwTRPf9g4S1Y329QGk\",\"y\":\"8by6qVswtkb9OzuzZqAMBsVV-9Nh4Oci2VAxcqKFaQY\"}}]}", "{\"id\":\"did:cid:bagaaiera5sq6vrqmdai6j4ipubm544igndxaldhl7fu4kiqd54ozqme3undq\"}", "{\"version\":1,\"type\":\"agent\",\"registry\":\"hyperswarm\"}", "{}"].getD i (""))
def methods0 : Nat → List VerificationMethod := (fun i => [[⟨0, 0⟩], [⟨0, 1⟩], [], [], []].getD i ([]))
def documents0 : Nat → Nat := (fun i => [1, 0, 4].getD i (4))
def graph0 : DocumentGraph := {
  size := 3
  root := 1
  initialDocument := 1
  parent := (fun i => [some 1, none, some 0].getD i (none))
  depth := (fun i => [1, 0, 2].getD i (0))
  action := (fun i => [AgentAction.rotate 0, AgentAction.keep, AgentAction.deactivate].getD i (AgentAction.keep))
  documents := (fun i => [[⟨0, 1⟩], [⟨0, 0⟩], []].getD i ([]))
  named := (fun i => [0, 0, 0].getD i (0))
  signatureValid := fun i k => ((fun i => [[true, false, false, false], [true, false, false, false], [false, true, false, false]].getD i ([]))) i |>.getD k false
}
theorem methods_agree0 : ∀ i, methods0 (documents0 i) = graph0.documents i := by
  intro i
  cases i with
  | zero => rfl
  | succ i =>
    cases i with
    | zero => rfl
    | succ i =>
      cases i with
      | zero => rfl
      | succ i =>
        rfl
theorem ordered0 : AncestryOrdered (documentAgent graph0) := by
  intro i p parent
  by_cases bound : i < 3
  · have cases : i = 0 ∨ i = 1 ∨ i = 2 := by omega
    rcases cases with rfl | rfl | rfl <;> simp [documentAgent, graph0] at parent
    all_goals subst p; decide
  · have outside : 3 ≤ i := by omega
    simp only [documentAgent, graph0] at parent
    rw [List.getD_eq_getElem?_getD, List.getElem?_eq_none (by simpa using outside)] at parent
    simp at parent
theorem bounded0 : DepthBounded (documentAgent graph0) := by
  intro i bound
  have small : i < 3 := bound
  have checked : ∀ i : Fin 3, (documentAgent graph0).depth i.val < (documentAgent graph0).size := by decide
  exact checked ⟨i, small⟩
theorem parents0 : AgentParentBounded graph0 := by
  intro i p bound parent
  have small : i < 3 := bound
  have cases : i = 0 ∨ i = 1 ∨ i = 2 := by omega
  rcases cases with rfl | rfl | rfl <;> simp [graph0] at parent
  all_goals subst p; decide
def patch0 : Nat → ComponentPatch Nat Nat := (fun i => [⟨none, none⟩, ⟨none, none⟩, ⟨none, none⟩].getD i (⟨none, none⟩))
def registry0 : Nat → Nat := (fun i => [6, 6, 6, 3, 6].getD i (6))
def receipts0 : RegistryReceipts := {
  size := 0
  owner := (fun i => [].getD i (3))
  registry := (fun i => [].getD i (6))
  chain := (fun i => [true, true, true, false, false, false].getD i (false))
  accepted := fun _ => true
}
abbrev anchors0 := componentAnchors graph0 patch0 registry0 3 receipts0
abbrev model0 := componentEvents graph0 anchors0
def positions0 : Nat → List Nat := (fun i => [].getD i ([]))
theorem ranks0 : RegistryCidRanks (componentRegistry graph0 patch0 registry0 3) receipts0 positions0 := by
  intro x y xv yv same
  have xb : x < 0 := eligible_lt _ _ _ xv
  have yb : y < 0 := eligible_lt _ _ _ yv
  have checked : ∀ x y : Fin 0,
      eligible (registryAnchors (componentRegistry graph0 patch0 registry0 3) receipts0) (receipts0.owner x.val) x.val = true →
      eligible (registryAnchors (componentRegistry graph0 patch0 registry0 3) receipts0) (receipts0.owner y.val) y.val = true →
      receipts0.registry x.val = receipts0.registry y.val →
      (x.val < y.val ↔ compare (positions0 x.val) (positions0 y.val) = .lt ∨
        (compare (positions0 x.val) (positions0 y.val) = .eq ∧ receipts0.owner x.val < receipts0.owner y.val)) := by decide
  exact checked ⟨x, xb⟩ ⟨y, yb⟩ xv yv same
def operationTime0 : Nat → Int := (fun i => [1788999600000, 1788998460000, 1788999900000].getD i (0))
def chainFacts0 : Nat → ChainReceiptView := (fun i => [].getD i (⟨0, [], 0, false⟩))
def atoms1 : Nat → String := (fun i => ["{\"@context\":[\"https://www.w3.org/ns/did/v1\"],\"id\":\"did:cid:bagaaiera4oi64gqrmf2ut5dsq2a6kv376mvgsjpjyaf23hpmsuvicu4bdd7q\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaiera4oi64gqrmf2ut5dsq2a6kv376mvgsjpjyaf23hpmsuvicu4bdd7q\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"MAemGeO4kBa-f3jOK_Hb21lXKC6jN4jeuIuyMumLmlA\",\"y\":\"iWcPPQGrI3j02b0_ocPHCHj6OptQ9kGWskmn6StCooo\"}}],\"authentication\":[\"#key-1\"],\"assertionMethod\":[\"#key-1\"],\"capabilityInvocation\":[\"#key-1\"]}", "{\"id\":\"did:cid:bagaaiera4oi64gqrmf2ut5dsq2a6kv376mvgsjpjyaf23hpmsuvicu4bdd7q\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaiera4oi64gqrmf2ut5dsq2a6kv376mvgsjpjyaf23hpmsuvicu4bdd7q\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"uVwknYT0F-PjlaEnQlQotUBnHMFYgeuCjBe3IqU_xZk\",\"y\":\"4hyl5WyQ80CYjTkzrMdr64Mv1kyrB43fPOcykjAx0ag\"}},{\"id\":\"#key-2\",\"controller\":\"did:cid:bagaaiera4oi64gqrmf2ut5dsq2a6kv376mvgsjpjyaf23hpmsuvicu4bdd7q\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"MAemGeO4kBa-f3jOK_Hb21lXKC6jN4jeuIuyMumLmlA\",\"y\":\"iWcPPQGrI3j02b0_ocPHCHj6OptQ9kGWskmn6StCooo\"}}]}", "{\"id\":\"did:cid:bagaaiera4oi64gqrmf2ut5dsq2a6kv376mvgsjpjyaf23hpmsuvicu4bdd7q\"}", "{\"version\":1,\"type\":\"agent\",\"registry\":\"hyperswarm\"}", "{}"].getD i (""))
def methods1 : Nat → List VerificationMethod := (fun i => [[⟨0, 2⟩], [⟨0, 3⟩, ⟨1, 2⟩], [], [], []].getD i ([]))
def documents1 : Nat → Nat := (fun i => [0, 1].getD i (4))
def graph1 : DocumentGraph := {
  size := 2
  root := 0
  initialDocument := 0
  parent := (fun i => [none, some 0].getD i (none))
  depth := (fun i => [0, 1].getD i (0))
  action := (fun i => [AgentAction.keep, AgentAction.rotate 1].getD i (AgentAction.keep))
  documents := (fun i => [[⟨0, 2⟩], [⟨0, 3⟩, ⟨1, 2⟩]].getD i ([]))
  named := (fun i => [0, 0].getD i (0))
  signatureValid := fun i k => ((fun i => [[false, false, true, false], [false, false, true, false]].getD i ([]))) i |>.getD k false
}
theorem methods_agree1 : ∀ i, methods1 (documents1 i) = graph1.documents i := by
  intro i
  cases i with
  | zero => rfl
  | succ i =>
    cases i with
    | zero => rfl
    | succ i =>
      rfl
theorem ordered1 : AncestryOrdered (documentAgent graph1) := by
  intro i p parent
  by_cases bound : i < 2
  · have cases : i = 0 ∨ i = 1 := by omega
    rcases cases with rfl | rfl <;> simp [documentAgent, graph1] at parent
    all_goals subst p; decide
  · have outside : 2 ≤ i := by omega
    simp only [documentAgent, graph1] at parent
    rw [List.getD_eq_getElem?_getD, List.getElem?_eq_none (by simpa using outside)] at parent
    simp at parent
theorem bounded1 : DepthBounded (documentAgent graph1) := by
  intro i bound
  have small : i < 2 := bound
  have checked : ∀ i : Fin 2, (documentAgent graph1).depth i.val < (documentAgent graph1).size := by decide
  exact checked ⟨i, small⟩
theorem parents1 : AgentParentBounded graph1 := by
  intro i p bound parent
  have small : i < 2 := bound
  have cases : i = 0 ∨ i = 1 := by omega
  rcases cases with rfl | rfl <;> simp [graph1] at parent
  all_goals subst p; decide
def patch1 : Nat → ComponentPatch Nat Nat := (fun i => [⟨none, none⟩, ⟨none, none⟩].getD i (⟨none, none⟩))
def registry1 : Nat → Nat := (fun i => [6, 6, 6, 3, 6].getD i (6))
def receipts1 : RegistryReceipts := {
  size := 0
  owner := (fun i => [].getD i (2))
  registry := (fun i => [].getD i (6))
  chain := (fun i => [true, true, true, false, false, false].getD i (false))
  accepted := fun _ => true
}
abbrev anchors1 := componentAnchors graph1 patch1 registry1 3 receipts1
abbrev model1 := componentEvents graph1 anchors1
def positions1 : Nat → List Nat := (fun i => [].getD i ([]))
theorem ranks1 : RegistryCidRanks (componentRegistry graph1 patch1 registry1 3) receipts1 positions1 := by
  intro x y xv yv same
  have xb : x < 0 := eligible_lt _ _ _ xv
  have yb : y < 0 := eligible_lt _ _ _ yv
  have checked : ∀ x y : Fin 0,
      eligible (registryAnchors (componentRegistry graph1 patch1 registry1 3) receipts1) (receipts1.owner x.val) x.val = true →
      eligible (registryAnchors (componentRegistry graph1 patch1 registry1 3) receipts1) (receipts1.owner y.val) y.val = true →
      receipts1.registry x.val = receipts1.registry y.val →
      (x.val < y.val ↔ compare (positions1 x.val) (positions1 y.val) = .lt ∨
        (compare (positions1 x.val) (positions1 y.val) = .eq ∧ receipts1.owner x.val < receipts1.owner y.val)) := by decide
  exact checked ⟨x, xb⟩ ⟨y, yb⟩ xv yv same
def operationTime1 : Nat → Int := (fun i => [1788998460000, 1789001100000].getD i (0))
def chainFacts1 : Nat → ChainReceiptView := (fun i => [].getD i (⟨0, [], 0, false⟩))
def atoms2 : Nat → String := (fun i => ["{\"@context\":[\"https://www.w3.org/ns/did/v1\"],\"id\":\"did:cid:bagaaiera3vmxxmjer3kfx6b6pzlfn5m6ah3t7wkodpaukz5nz2hfmx73yirq\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaiera3vmxxmjer3kfx6b6pzlfn5m6ah3t7wkodpaukz5nz2hfmx73yirq\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"azJ09248a2vKqs80FWCLG3Xw5xc9UF4sd_DImBsaxDw\",\"y\":\"215hdHiCRD7Q-DyAt5zcT4YLjdXFhm6y8bAbbia4Ne4\"}}],\"authentication\":[\"#key-1\"],\"assertionMethod\":[\"#key-1\"],\"capabilityInvocation\":[\"#key-1\"]}", "{\"id\":\"did:cid:bagaaiera3vmxxmjer3kfx6b6pzlfn5m6ah3t7wkodpaukz5nz2hfmx73yirq\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaiera3vmxxmjer3kfx6b6pzlfn5m6ah3t7wkodpaukz5nz2hfmx73yirq\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"7c8q6jrR_99AQxXwI0id7tkVCZwTRPf9g4S1Y329QGk\",\"y\":\"8by6qVswtkb9OzuzZqAMBsVV-9Nh4Oci2VAxcqKFaQY\"}}]}", "{\"id\":\"did:cid:bagaaiera3vmxxmjer3kfx6b6pzlfn5m6ah3t7wkodpaukz5nz2hfmx73yirq\"}", "{\"version\":1,\"type\":\"agent\",\"registry\":\"pin\"}", "{}"].getD i (""))
def methods2 : Nat → List VerificationMethod := (fun i => [[⟨0, 0⟩], [⟨0, 1⟩], [], [], []].getD i ([]))
def documents2 : Nat → Nat := (fun i => [0, 4, 1].getD i (4))
def graph2 : DocumentGraph := {
  size := 3
  root := 0
  initialDocument := 0
  parent := (fun i => [none, some 2, some 0].getD i (none))
  depth := (fun i => [0, 2, 1].getD i (0))
  action := (fun i => [AgentAction.keep, AgentAction.deactivate, AgentAction.rotate 2].getD i (AgentAction.keep))
  documents := (fun i => [[⟨0, 0⟩], [], [⟨0, 1⟩]].getD i ([]))
  named := (fun i => [0, 0, 0].getD i (0))
  signatureValid := fun i k => ((fun i => [[true, false, false, false], [false, true, false, false], [true, false, false, false]].getD i ([]))) i |>.getD k false
}
theorem methods_agree2 : ∀ i, methods2 (documents2 i) = graph2.documents i := by
  intro i
  cases i with
  | zero => rfl
  | succ i =>
    cases i with
    | zero => rfl
    | succ i =>
      cases i with
      | zero => rfl
      | succ i =>
        rfl
theorem ordered2 : AncestryOrdered (documentAgent graph2) := by
  intro i p parent
  by_cases bound : i < 3
  · have cases : i = 0 ∨ i = 1 ∨ i = 2 := by omega
    rcases cases with rfl | rfl | rfl <;> simp [documentAgent, graph2] at parent
    all_goals subst p; decide
  · have outside : 3 ≤ i := by omega
    simp only [documentAgent, graph2] at parent
    rw [List.getD_eq_getElem?_getD, List.getElem?_eq_none (by simpa using outside)] at parent
    simp at parent
theorem bounded2 : DepthBounded (documentAgent graph2) := by
  intro i bound
  have small : i < 3 := bound
  have checked : ∀ i : Fin 3, (documentAgent graph2).depth i.val < (documentAgent graph2).size := by decide
  exact checked ⟨i, small⟩
theorem parents2 : AgentParentBounded graph2 := by
  intro i p bound parent
  have small : i < 3 := bound
  have cases : i = 0 ∨ i = 1 ∨ i = 2 := by omega
  rcases cases with rfl | rfl | rfl <;> simp [graph2] at parent
  all_goals subst p; decide
def patch2 : Nat → ComponentPatch Nat Nat := (fun i => [⟨none, none⟩, ⟨none, none⟩, ⟨none, none⟩].getD i (⟨none, none⟩))
def registry2 : Nat → Nat := (fun i => [6, 6, 6, 5, 6].getD i (6))
def receipts2 : RegistryReceipts := {
  size := 0
  owner := (fun i => [].getD i (3))
  registry := (fun i => [].getD i (6))
  chain := (fun i => [true, true, true, false, false, false].getD i (false))
  accepted := fun _ => true
}
abbrev anchors2 := componentAnchors graph2 patch2 registry2 3 receipts2
abbrev model2 := componentEvents graph2 anchors2
def positions2 : Nat → List Nat := (fun i => [].getD i ([]))
theorem ranks2 : RegistryCidRanks (componentRegistry graph2 patch2 registry2 3) receipts2 positions2 := by
  intro x y xv yv same
  have xb : x < 0 := eligible_lt _ _ _ xv
  have yb : y < 0 := eligible_lt _ _ _ yv
  have checked : ∀ x y : Fin 0,
      eligible (registryAnchors (componentRegistry graph2 patch2 registry2 3) receipts2) (receipts2.owner x.val) x.val = true →
      eligible (registryAnchors (componentRegistry graph2 patch2 registry2 3) receipts2) (receipts2.owner y.val) y.val = true →
      receipts2.registry x.val = receipts2.registry y.val →
      (x.val < y.val ↔ compare (positions2 x.val) (positions2 y.val) = .lt ∨
        (compare (positions2 x.val) (positions2 y.val) = .eq ∧ receipts2.owner x.val < receipts2.owner y.val)) := by decide
  exact checked ⟨x, xb⟩ ⟨y, yb⟩ xv yv same
def operationTime2 : Nat → Int := (fun i => [1788998460000, 1788999900000, 1788999600000].getD i (0))
def chainFacts2 : Nat → ChainReceiptView := (fun i => [].getD i (⟨0, [], 0, false⟩))
def atoms3 : Nat → String := (fun i => ["{\"@context\":[\"https://www.w3.org/ns/did/v1\"],\"id\":\"did:cid:bagaaieraex7v3ixh2ldsapl4ztc5lsrdxo4dvb7ctnfv6lycejkzgp72om5q\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaieraex7v3ixh2ldsapl4ztc5lsrdxo4dvb7ctnfv6lycejkzgp72om5q\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"MAemGeO4kBa-f3jOK_Hb21lXKC6jN4jeuIuyMumLmlA\",\"y\":\"iWcPPQGrI3j02b0_ocPHCHj6OptQ9kGWskmn6StCooo\"}}],\"authentication\":[\"#key-1\"],\"assertionMethod\":[\"#key-1\"],\"capabilityInvocation\":[\"#key-1\"]}", "{\"id\":\"did:cid:bagaaieraex7v3ixh2ldsapl4ztc5lsrdxo4dvb7ctnfv6lycejkzgp72om5q\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaieraex7v3ixh2ldsapl4ztc5lsrdxo4dvb7ctnfv6lycejkzgp72om5q\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"uVwknYT0F-PjlaEnQlQotUBnHMFYgeuCjBe3IqU_xZk\",\"y\":\"4hyl5WyQ80CYjTkzrMdr64Mv1kyrB43fPOcykjAx0ag\"}},{\"id\":\"#key-2\",\"controller\":\"did:cid:bagaaieraex7v3ixh2ldsapl4ztc5lsrdxo4dvb7ctnfv6lycejkzgp72om5q\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"MAemGeO4kBa-f3jOK_Hb21lXKC6jN4jeuIuyMumLmlA\",\"y\":\"iWcPPQGrI3j02b0_ocPHCHj6OptQ9kGWskmn6StCooo\"}}]}", "{\"id\":\"did:cid:bagaaieraex7v3ixh2ldsapl4ztc5lsrdxo4dvb7ctnfv6lycejkzgp72om5q\"}", "{\"version\":1,\"type\":\"agent\",\"registry\":\"pin\"}", "{}"].getD i (""))
def methods3 : Nat → List VerificationMethod := (fun i => [[⟨0, 2⟩], [⟨0, 3⟩, ⟨1, 2⟩], [], [], []].getD i ([]))
def documents3 : Nat → Nat := (fun i => [0, 1].getD i (4))
def graph3 : DocumentGraph := {
  size := 2
  root := 0
  initialDocument := 0
  parent := (fun i => [none, some 0].getD i (none))
  depth := (fun i => [0, 1].getD i (0))
  action := (fun i => [AgentAction.keep, AgentAction.rotate 1].getD i (AgentAction.keep))
  documents := (fun i => [[⟨0, 2⟩], [⟨0, 3⟩, ⟨1, 2⟩]].getD i ([]))
  named := (fun i => [0, 0].getD i (0))
  signatureValid := fun i k => ((fun i => [[false, false, true, false], [false, false, true, false]].getD i ([]))) i |>.getD k false
}
theorem methods_agree3 : ∀ i, methods3 (documents3 i) = graph3.documents i := by
  intro i
  cases i with
  | zero => rfl
  | succ i =>
    cases i with
    | zero => rfl
    | succ i =>
      rfl
theorem ordered3 : AncestryOrdered (documentAgent graph3) := by
  intro i p parent
  by_cases bound : i < 2
  · have cases : i = 0 ∨ i = 1 := by omega
    rcases cases with rfl | rfl <;> simp [documentAgent, graph3] at parent
    all_goals subst p; decide
  · have outside : 2 ≤ i := by omega
    simp only [documentAgent, graph3] at parent
    rw [List.getD_eq_getElem?_getD, List.getElem?_eq_none (by simpa using outside)] at parent
    simp at parent
theorem bounded3 : DepthBounded (documentAgent graph3) := by
  intro i bound
  have small : i < 2 := bound
  have checked : ∀ i : Fin 2, (documentAgent graph3).depth i.val < (documentAgent graph3).size := by decide
  exact checked ⟨i, small⟩
theorem parents3 : AgentParentBounded graph3 := by
  intro i p bound parent
  have small : i < 2 := bound
  have cases : i = 0 ∨ i = 1 := by omega
  rcases cases with rfl | rfl <;> simp [graph3] at parent
  all_goals subst p; decide
def patch3 : Nat → ComponentPatch Nat Nat := (fun i => [⟨none, none⟩, ⟨none, none⟩].getD i (⟨none, none⟩))
def registry3 : Nat → Nat := (fun i => [6, 6, 6, 5, 6].getD i (6))
def receipts3 : RegistryReceipts := {
  size := 0
  owner := (fun i => [].getD i (2))
  registry := (fun i => [].getD i (6))
  chain := (fun i => [true, true, true, false, false, false].getD i (false))
  accepted := fun _ => true
}
abbrev anchors3 := componentAnchors graph3 patch3 registry3 3 receipts3
abbrev model3 := componentEvents graph3 anchors3
def positions3 : Nat → List Nat := (fun i => [].getD i ([]))
theorem ranks3 : RegistryCidRanks (componentRegistry graph3 patch3 registry3 3) receipts3 positions3 := by
  intro x y xv yv same
  have xb : x < 0 := eligible_lt _ _ _ xv
  have yb : y < 0 := eligible_lt _ _ _ yv
  have checked : ∀ x y : Fin 0,
      eligible (registryAnchors (componentRegistry graph3 patch3 registry3 3) receipts3) (receipts3.owner x.val) x.val = true →
      eligible (registryAnchors (componentRegistry graph3 patch3 registry3 3) receipts3) (receipts3.owner y.val) y.val = true →
      receipts3.registry x.val = receipts3.registry y.val →
      (x.val < y.val ↔ compare (positions3 x.val) (positions3 y.val) = .lt ∨
        (compare (positions3 x.val) (positions3 y.val) = .eq ∧ receipts3.owner x.val < receipts3.owner y.val)) := by decide
  exact checked ⟨x, xb⟩ ⟨y, yb⟩ xv yv same
def operationTime3 : Nat → Int := (fun i => [1788998460000, 1789001100000].getD i (0))
def chainFacts3 : Nat → ChainReceiptView := (fun i => [].getD i (⟨0, [], 0, false⟩))
def atoms4 : Nat → String := (fun i => ["{\"@context\":[\"https://www.w3.org/ns/did/v1\"],\"id\":\"did:cid:bagaaiera57hwhybwstloq7egfsgzrqfsfwu22nlomgolxzj4uz4dxyq5elfq\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaiera57hwhybwstloq7egfsgzrqfsfwu22nlomgolxzj4uz4dxyq5elfq\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"azJ09248a2vKqs80FWCLG3Xw5xc9UF4sd_DImBsaxDw\",\"y\":\"215hdHiCRD7Q-DyAt5zcT4YLjdXFhm6y8bAbbia4Ne4\"}}],\"authentication\":[\"#key-1\"],\"assertionMethod\":[\"#key-1\"],\"capabilityInvocation\":[\"#key-1\"]}", "{\"id\":\"did:cid:bagaaiera57hwhybwstloq7egfsgzrqfsfwu22nlomgolxzj4uz4dxyq5elfq\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaiera57hwhybwstloq7egfsgzrqfsfwu22nlomgolxzj4uz4dxyq5elfq\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"7c8q6jrR_99AQxXwI0id7tkVCZwTRPf9g4S1Y329QGk\",\"y\":\"8by6qVswtkb9OzuzZqAMBsVV-9Nh4Oci2VAxcqKFaQY\"}}]}", "{\"id\":\"did:cid:bagaaiera57hwhybwstloq7egfsgzrqfsfwu22nlomgolxzj4uz4dxyq5elfq\"}", "{\"version\":1,\"type\":\"agent\",\"registry\":\"BTC:signet\"}", "{}"].getD i (""))
def methods4 : Nat → List VerificationMethod := (fun i => [[⟨0, 0⟩], [⟨0, 1⟩], [], [], []].getD i ([]))
def documents4 : Nat → Nat := (fun i => [0, 4, 1].getD i (4))
def graph4 : DocumentGraph := {
  size := 3
  root := 0
  initialDocument := 0
  parent := (fun i => [none, some 2, some 0].getD i (none))
  depth := (fun i => [0, 2, 1].getD i (0))
  action := (fun i => [AgentAction.keep, AgentAction.deactivate, AgentAction.rotate 2].getD i (AgentAction.keep))
  documents := (fun i => [[⟨0, 0⟩], [], [⟨0, 1⟩]].getD i ([]))
  named := (fun i => [0, 0, 0].getD i (0))
  signatureValid := fun i k => ((fun i => [[true, false, false, false], [false, true, false, false], [true, false, false, false]].getD i ([]))) i |>.getD k false
}
theorem methods_agree4 : ∀ i, methods4 (documents4 i) = graph4.documents i := by
  intro i
  cases i with
  | zero => rfl
  | succ i =>
    cases i with
    | zero => rfl
    | succ i =>
      cases i with
      | zero => rfl
      | succ i =>
        rfl
theorem ordered4 : AncestryOrdered (documentAgent graph4) := by
  intro i p parent
  by_cases bound : i < 3
  · have cases : i = 0 ∨ i = 1 ∨ i = 2 := by omega
    rcases cases with rfl | rfl | rfl <;> simp [documentAgent, graph4] at parent
    all_goals subst p; decide
  · have outside : 3 ≤ i := by omega
    simp only [documentAgent, graph4] at parent
    rw [List.getD_eq_getElem?_getD, List.getElem?_eq_none (by simpa using outside)] at parent
    simp at parent
theorem bounded4 : DepthBounded (documentAgent graph4) := by
  intro i bound
  have small : i < 3 := bound
  have checked : ∀ i : Fin 3, (documentAgent graph4).depth i.val < (documentAgent graph4).size := by decide
  exact checked ⟨i, small⟩
theorem parents4 : AgentParentBounded graph4 := by
  intro i p bound parent
  have small : i < 3 := bound
  have cases : i = 0 ∨ i = 1 ∨ i = 2 := by omega
  rcases cases with rfl | rfl | rfl <;> simp [graph4] at parent
  all_goals subst p; decide
def patch4 : Nat → ComponentPatch Nat Nat := (fun i => [⟨none, none⟩, ⟨none, none⟩, ⟨none, none⟩].getD i (⟨none, none⟩))
def registry4 : Nat → Nat := (fun i => [6, 6, 6, 0, 6].getD i (6))
def receipts4 : RegistryReceipts := {
  size := 4
  owner := (fun i => [0, 2, 1, 2].getD i (3))
  registry := (fun i => [0, 0, 0, 0].getD i (6))
  chain := (fun i => [true, true, true, false, false, false].getD i (false))
  accepted := fun _ => true
}
abbrev anchors4 := componentAnchors graph4 patch4 registry4 3 receipts4
abbrev model4 := componentEvents graph4 anchors4
def positions4 : Nat → List Nat := (fun i => [[1, 0, 0], [20, 0, 0], [25, 0, 0], [35, 0, 0]].getD i ([]))
theorem ranks4 : RegistryCidRanks (componentRegistry graph4 patch4 registry4 3) receipts4 positions4 := by
  intro x y xv yv same
  have xb : x < 4 := eligible_lt _ _ _ xv
  have yb : y < 4 := eligible_lt _ _ _ yv
  have checked : ∀ x y : Fin 4,
      eligible (registryAnchors (componentRegistry graph4 patch4 registry4 3) receipts4) (receipts4.owner x.val) x.val = true →
      eligible (registryAnchors (componentRegistry graph4 patch4 registry4 3) receipts4) (receipts4.owner y.val) y.val = true →
      receipts4.registry x.val = receipts4.registry y.val →
      (x.val < y.val ↔ compare (positions4 x.val) (positions4 y.val) = .lt ∨
        (compare (positions4 x.val) (positions4 y.val) = .eq ∧ receipts4.owner x.val < receipts4.owner y.val)) := by decide
  exact checked ⟨x, xb⟩ ⟨y, yb⟩ xv yv same
def operationTime4 : Nat → Int := (fun i => [1788998460000, 1788999900000, 1788999600000].getD i (0))
def chainFacts4 : Nat → ChainReceiptView := (fun i => [⟨0, [1, 0, 0], 1788998460000, true⟩, ⟨0, [20, 0, 0], 1789000500000, true⟩, ⟨0, [25, 0, 0], 1789000800000, true⟩, ⟨0, [35, 0, 0], 1789000500000, true⟩].getD i (⟨0, [], 0, false⟩))
def atoms5 : Nat → String := (fun i => ["{\"@context\":[\"https://www.w3.org/ns/did/v1\"],\"id\":\"did:cid:bagaaiera6ksp4ehvtwcauvuxybgh5c245ukuirdznphdw26gkdevf4vvry5a\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaiera6ksp4ehvtwcauvuxybgh5c245ukuirdznphdw26gkdevf4vvry5a\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"MAemGeO4kBa-f3jOK_Hb21lXKC6jN4jeuIuyMumLmlA\",\"y\":\"iWcPPQGrI3j02b0_ocPHCHj6OptQ9kGWskmn6StCooo\"}}],\"authentication\":[\"#key-1\"],\"assertionMethod\":[\"#key-1\"],\"capabilityInvocation\":[\"#key-1\"]}", "{\"id\":\"did:cid:bagaaiera6ksp4ehvtwcauvuxybgh5c245ukuirdznphdw26gkdevf4vvry5a\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaiera6ksp4ehvtwcauvuxybgh5c245ukuirdznphdw26gkdevf4vvry5a\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"uVwknYT0F-PjlaEnQlQotUBnHMFYgeuCjBe3IqU_xZk\",\"y\":\"4hyl5WyQ80CYjTkzrMdr64Mv1kyrB43fPOcykjAx0ag\"}},{\"id\":\"#key-2\",\"controller\":\"did:cid:bagaaiera6ksp4ehvtwcauvuxybgh5c245ukuirdznphdw26gkdevf4vvry5a\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"MAemGeO4kBa-f3jOK_Hb21lXKC6jN4jeuIuyMumLmlA\",\"y\":\"iWcPPQGrI3j02b0_ocPHCHj6OptQ9kGWskmn6StCooo\"}}]}", "{\"id\":\"did:cid:bagaaiera6ksp4ehvtwcauvuxybgh5c245ukuirdznphdw26gkdevf4vvry5a\"}", "{\"version\":1,\"type\":\"agent\",\"registry\":\"BTC:signet\"}", "{}"].getD i (""))
def methods5 : Nat → List VerificationMethod := (fun i => [[⟨0, 2⟩], [⟨0, 3⟩, ⟨1, 2⟩], [], [], []].getD i ([]))
def documents5 : Nat → Nat := (fun i => [0, 1].getD i (4))
def graph5 : DocumentGraph := {
  size := 2
  root := 0
  initialDocument := 0
  parent := (fun i => [none, some 0].getD i (none))
  depth := (fun i => [0, 1].getD i (0))
  action := (fun i => [AgentAction.keep, AgentAction.rotate 1].getD i (AgentAction.keep))
  documents := (fun i => [[⟨0, 2⟩], [⟨0, 3⟩, ⟨1, 2⟩]].getD i ([]))
  named := (fun i => [0, 0].getD i (0))
  signatureValid := fun i k => ((fun i => [[false, false, true, false], [false, false, true, false]].getD i ([]))) i |>.getD k false
}
theorem methods_agree5 : ∀ i, methods5 (documents5 i) = graph5.documents i := by
  intro i
  cases i with
  | zero => rfl
  | succ i =>
    cases i with
    | zero => rfl
    | succ i =>
      rfl
theorem ordered5 : AncestryOrdered (documentAgent graph5) := by
  intro i p parent
  by_cases bound : i < 2
  · have cases : i = 0 ∨ i = 1 := by omega
    rcases cases with rfl | rfl <;> simp [documentAgent, graph5] at parent
    all_goals subst p; decide
  · have outside : 2 ≤ i := by omega
    simp only [documentAgent, graph5] at parent
    rw [List.getD_eq_getElem?_getD, List.getElem?_eq_none (by simpa using outside)] at parent
    simp at parent
theorem bounded5 : DepthBounded (documentAgent graph5) := by
  intro i bound
  have small : i < 2 := bound
  have checked : ∀ i : Fin 2, (documentAgent graph5).depth i.val < (documentAgent graph5).size := by decide
  exact checked ⟨i, small⟩
theorem parents5 : AgentParentBounded graph5 := by
  intro i p bound parent
  have small : i < 2 := bound
  have cases : i = 0 ∨ i = 1 := by omega
  rcases cases with rfl | rfl <;> simp [graph5] at parent
  all_goals subst p; decide
def patch5 : Nat → ComponentPatch Nat Nat := (fun i => [⟨none, none⟩, ⟨none, none⟩].getD i (⟨none, none⟩))
def registry5 : Nat → Nat := (fun i => [6, 6, 6, 0, 6].getD i (6))
def receipts5 : RegistryReceipts := {
  size := 2
  owner := (fun i => [0, 1].getD i (2))
  registry := (fun i => [0, 0].getD i (6))
  chain := (fun i => [true, true, true, false, false, false].getD i (false))
  accepted := fun _ => true
}
abbrev anchors5 := componentAnchors graph5 patch5 registry5 3 receipts5
abbrev model5 := componentEvents graph5 anchors5
def positions5 : Nat → List Nat := (fun i => [[1, 1, 0], [45, 0, 0]].getD i ([]))
theorem ranks5 : RegistryCidRanks (componentRegistry graph5 patch5 registry5 3) receipts5 positions5 := by
  intro x y xv yv same
  have xb : x < 2 := eligible_lt _ _ _ xv
  have yb : y < 2 := eligible_lt _ _ _ yv
  have checked : ∀ x y : Fin 2,
      eligible (registryAnchors (componentRegistry graph5 patch5 registry5 3) receipts5) (receipts5.owner x.val) x.val = true →
      eligible (registryAnchors (componentRegistry graph5 patch5 registry5 3) receipts5) (receipts5.owner y.val) y.val = true →
      receipts5.registry x.val = receipts5.registry y.val →
      (x.val < y.val ↔ compare (positions5 x.val) (positions5 y.val) = .lt ∨
        (compare (positions5 x.val) (positions5 y.val) = .eq ∧ receipts5.owner x.val < receipts5.owner y.val)) := by decide
  exact checked ⟨x, xb⟩ ⟨y, yb⟩ xv yv same
def operationTime5 : Nat → Int := (fun i => [1788998460000, 1789001100000].getD i (0))
def chainFacts5 : Nat → ChainReceiptView := (fun i => [⟨0, [1, 1, 0], 1788998460000, true⟩, ⟨0, [45, 0, 0], 1789001100000, true⟩].getD i (⟨0, [], 0, false⟩))
def atoms6 : Nat → String := (fun i => ["{\"@context\":[\"https://www.w3.org/ns/did/v1\"],\"id\":\"did:cid:bagaaierar2sdnel4fhnzi2xm3og66zvqtl2fy5wdmqglc457fzcpxvy2zoqa\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaierar2sdnel4fhnzi2xm3og66zvqtl2fy5wdmqglc457fzcpxvy2zoqa\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"azJ09248a2vKqs80FWCLG3Xw5xc9UF4sd_DImBsaxDw\",\"y\":\"215hdHiCRD7Q-DyAt5zcT4YLjdXFhm6y8bAbbia4Ne4\"}}],\"authentication\":[\"#key-1\"],\"assertionMethod\":[\"#key-1\"],\"capabilityInvocation\":[\"#key-1\"]}", "{\"id\":\"did:cid:bagaaierar2sdnel4fhnzi2xm3og66zvqtl2fy5wdmqglc457fzcpxvy2zoqa\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaierar2sdnel4fhnzi2xm3og66zvqtl2fy5wdmqglc457fzcpxvy2zoqa\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"7c8q6jrR_99AQxXwI0id7tkVCZwTRPf9g4S1Y329QGk\",\"y\":\"8by6qVswtkb9OzuzZqAMBsVV-9Nh4Oci2VAxcqKFaQY\"}}]}", "{\"id\":\"did:cid:bagaaierar2sdnel4fhnzi2xm3og66zvqtl2fy5wdmqglc457fzcpxvy2zoqa\"}", "{\"version\":1,\"type\":\"agent\",\"registry\":\"ZEC:testnet\"}", "{}"].getD i (""))
def methods6 : Nat → List VerificationMethod := (fun i => [[⟨0, 0⟩], [⟨0, 1⟩], [], [], []].getD i ([]))
def documents6 : Nat → Nat := (fun i => [0, 4, 1].getD i (4))
def graph6 : DocumentGraph := {
  size := 3
  root := 0
  initialDocument := 0
  parent := (fun i => [none, some 2, some 0].getD i (none))
  depth := (fun i => [0, 2, 1].getD i (0))
  action := (fun i => [AgentAction.keep, AgentAction.deactivate, AgentAction.rotate 2].getD i (AgentAction.keep))
  documents := (fun i => [[⟨0, 0⟩], [], [⟨0, 1⟩]].getD i ([]))
  named := (fun i => [0, 0, 0].getD i (0))
  signatureValid := fun i k => ((fun i => [[true, false, false, false], [false, true, false, false], [true, false, false, false]].getD i ([]))) i |>.getD k false
}
theorem methods_agree6 : ∀ i, methods6 (documents6 i) = graph6.documents i := by
  intro i
  cases i with
  | zero => rfl
  | succ i =>
    cases i with
    | zero => rfl
    | succ i =>
      cases i with
      | zero => rfl
      | succ i =>
        rfl
theorem ordered6 : AncestryOrdered (documentAgent graph6) := by
  intro i p parent
  by_cases bound : i < 3
  · have cases : i = 0 ∨ i = 1 ∨ i = 2 := by omega
    rcases cases with rfl | rfl | rfl <;> simp [documentAgent, graph6] at parent
    all_goals subst p; decide
  · have outside : 3 ≤ i := by omega
    simp only [documentAgent, graph6] at parent
    rw [List.getD_eq_getElem?_getD, List.getElem?_eq_none (by simpa using outside)] at parent
    simp at parent
theorem bounded6 : DepthBounded (documentAgent graph6) := by
  intro i bound
  have small : i < 3 := bound
  have checked : ∀ i : Fin 3, (documentAgent graph6).depth i.val < (documentAgent graph6).size := by decide
  exact checked ⟨i, small⟩
theorem parents6 : AgentParentBounded graph6 := by
  intro i p bound parent
  have small : i < 3 := bound
  have cases : i = 0 ∨ i = 1 ∨ i = 2 := by omega
  rcases cases with rfl | rfl | rfl <;> simp [graph6] at parent
  all_goals subst p; decide
def patch6 : Nat → ComponentPatch Nat Nat := (fun i => [⟨none, none⟩, ⟨none, none⟩, ⟨none, none⟩].getD i (⟨none, none⟩))
def registry6 : Nat → Nat := (fun i => [6, 6, 6, 2, 6].getD i (6))
def receipts6 : RegistryReceipts := {
  size := 4
  owner := (fun i => [0, 2, 1, 2].getD i (3))
  registry := (fun i => [2, 2, 2, 2].getD i (6))
  chain := (fun i => [true, true, true, false, false, false].getD i (false))
  accepted := fun _ => true
}
abbrev anchors6 := componentAnchors graph6 patch6 registry6 3 receipts6
abbrev model6 := componentEvents graph6 anchors6
def positions6 : Nat → List Nat := (fun i => [[1, 0, 0], [20, 0, 0], [25, 0, 0], [35, 0, 0]].getD i ([]))
theorem ranks6 : RegistryCidRanks (componentRegistry graph6 patch6 registry6 3) receipts6 positions6 := by
  intro x y xv yv same
  have xb : x < 4 := eligible_lt _ _ _ xv
  have yb : y < 4 := eligible_lt _ _ _ yv
  have checked : ∀ x y : Fin 4,
      eligible (registryAnchors (componentRegistry graph6 patch6 registry6 3) receipts6) (receipts6.owner x.val) x.val = true →
      eligible (registryAnchors (componentRegistry graph6 patch6 registry6 3) receipts6) (receipts6.owner y.val) y.val = true →
      receipts6.registry x.val = receipts6.registry y.val →
      (x.val < y.val ↔ compare (positions6 x.val) (positions6 y.val) = .lt ∨
        (compare (positions6 x.val) (positions6 y.val) = .eq ∧ receipts6.owner x.val < receipts6.owner y.val)) := by decide
  exact checked ⟨x, xb⟩ ⟨y, yb⟩ xv yv same
def operationTime6 : Nat → Int := (fun i => [1788998460000, 1788999900000, 1788999600000].getD i (0))
def chainFacts6 : Nat → ChainReceiptView := (fun i => [⟨2, [1, 0, 0], 1788998460000, true⟩, ⟨2, [20, 0, 0], 1788999600000, true⟩, ⟨2, [25, 0, 0], 1788999900000, true⟩, ⟨2, [35, 0, 0], 1789000500000, true⟩].getD i (⟨0, [], 0, false⟩))
def atoms7 : Nat → String := (fun i => ["{\"@context\":[\"https://www.w3.org/ns/did/v1\"],\"id\":\"did:cid:bagaaiera5yvxzpg7i3cw53hpjo5yugldzkp6a4ilazoa3rhq4dgbcp7sogeq\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaiera5yvxzpg7i3cw53hpjo5yugldzkp6a4ilazoa3rhq4dgbcp7sogeq\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"MAemGeO4kBa-f3jOK_Hb21lXKC6jN4jeuIuyMumLmlA\",\"y\":\"iWcPPQGrI3j02b0_ocPHCHj6OptQ9kGWskmn6StCooo\"}}],\"authentication\":[\"#key-1\"],\"assertionMethod\":[\"#key-1\"],\"capabilityInvocation\":[\"#key-1\"]}", "{\"id\":\"did:cid:bagaaiera5yvxzpg7i3cw53hpjo5yugldzkp6a4ilazoa3rhq4dgbcp7sogeq\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaiera5yvxzpg7i3cw53hpjo5yugldzkp6a4ilazoa3rhq4dgbcp7sogeq\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"uVwknYT0F-PjlaEnQlQotUBnHMFYgeuCjBe3IqU_xZk\",\"y\":\"4hyl5WyQ80CYjTkzrMdr64Mv1kyrB43fPOcykjAx0ag\"}},{\"id\":\"#key-2\",\"controller\":\"did:cid:bagaaiera5yvxzpg7i3cw53hpjo5yugldzkp6a4ilazoa3rhq4dgbcp7sogeq\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"MAemGeO4kBa-f3jOK_Hb21lXKC6jN4jeuIuyMumLmlA\",\"y\":\"iWcPPQGrI3j02b0_ocPHCHj6OptQ9kGWskmn6StCooo\"}}]}", "{\"id\":\"did:cid:bagaaiera5yvxzpg7i3cw53hpjo5yugldzkp6a4ilazoa3rhq4dgbcp7sogeq\"}", "{\"version\":1,\"type\":\"agent\",\"registry\":\"ZEC:testnet\"}", "{}"].getD i (""))
def methods7 : Nat → List VerificationMethod := (fun i => [[⟨0, 2⟩], [⟨0, 3⟩, ⟨1, 2⟩], [], [], []].getD i ([]))
def documents7 : Nat → Nat := (fun i => [0, 1].getD i (4))
def graph7 : DocumentGraph := {
  size := 2
  root := 0
  initialDocument := 0
  parent := (fun i => [none, some 0].getD i (none))
  depth := (fun i => [0, 1].getD i (0))
  action := (fun i => [AgentAction.keep, AgentAction.rotate 1].getD i (AgentAction.keep))
  documents := (fun i => [[⟨0, 2⟩], [⟨0, 3⟩, ⟨1, 2⟩]].getD i ([]))
  named := (fun i => [0, 0].getD i (0))
  signatureValid := fun i k => ((fun i => [[false, false, true, false], [false, false, true, false]].getD i ([]))) i |>.getD k false
}
theorem methods_agree7 : ∀ i, methods7 (documents7 i) = graph7.documents i := by
  intro i
  cases i with
  | zero => rfl
  | succ i =>
    cases i with
    | zero => rfl
    | succ i =>
      rfl
theorem ordered7 : AncestryOrdered (documentAgent graph7) := by
  intro i p parent
  by_cases bound : i < 2
  · have cases : i = 0 ∨ i = 1 := by omega
    rcases cases with rfl | rfl <;> simp [documentAgent, graph7] at parent
    all_goals subst p; decide
  · have outside : 2 ≤ i := by omega
    simp only [documentAgent, graph7] at parent
    rw [List.getD_eq_getElem?_getD, List.getElem?_eq_none (by simpa using outside)] at parent
    simp at parent
theorem bounded7 : DepthBounded (documentAgent graph7) := by
  intro i bound
  have small : i < 2 := bound
  have checked : ∀ i : Fin 2, (documentAgent graph7).depth i.val < (documentAgent graph7).size := by decide
  exact checked ⟨i, small⟩
theorem parents7 : AgentParentBounded graph7 := by
  intro i p bound parent
  have small : i < 2 := bound
  have cases : i = 0 ∨ i = 1 := by omega
  rcases cases with rfl | rfl <;> simp [graph7] at parent
  all_goals subst p; decide
def patch7 : Nat → ComponentPatch Nat Nat := (fun i => [⟨none, none⟩, ⟨none, none⟩].getD i (⟨none, none⟩))
def registry7 : Nat → Nat := (fun i => [6, 6, 6, 2, 6].getD i (6))
def receipts7 : RegistryReceipts := {
  size := 2
  owner := (fun i => [0, 1].getD i (2))
  registry := (fun i => [2, 2].getD i (6))
  chain := (fun i => [true, true, true, false, false, false].getD i (false))
  accepted := fun _ => true
}
abbrev anchors7 := componentAnchors graph7 patch7 registry7 3 receipts7
abbrev model7 := componentEvents graph7 anchors7
def positions7 : Nat → List Nat := (fun i => [[1, 1, 0], [45, 0, 0]].getD i ([]))
theorem ranks7 : RegistryCidRanks (componentRegistry graph7 patch7 registry7 3) receipts7 positions7 := by
  intro x y xv yv same
  have xb : x < 2 := eligible_lt _ _ _ xv
  have yb : y < 2 := eligible_lt _ _ _ yv
  have checked : ∀ x y : Fin 2,
      eligible (registryAnchors (componentRegistry graph7 patch7 registry7 3) receipts7) (receipts7.owner x.val) x.val = true →
      eligible (registryAnchors (componentRegistry graph7 patch7 registry7 3) receipts7) (receipts7.owner y.val) y.val = true →
      receipts7.registry x.val = receipts7.registry y.val →
      (x.val < y.val ↔ compare (positions7 x.val) (positions7 y.val) = .lt ∨
        (compare (positions7 x.val) (positions7 y.val) = .eq ∧ receipts7.owner x.val < receipts7.owner y.val)) := by decide
  exact checked ⟨x, xb⟩ ⟨y, yb⟩ xv yv same
def operationTime7 : Nat → Int := (fun i => [1788998460000, 1789001100000].getD i (0))
def chainFacts7 : Nat → ChainReceiptView := (fun i => [⟨2, [1, 1, 0], 1788998460000, true⟩, ⟨2, [45, 0, 0], 1789001100000, true⟩].getD i (⟨0, [], 0, false⟩))
def atoms8 : Nat → String := (fun i => ["{\"@context\":[\"https://www.w3.org/ns/did/v1\"],\"id\":\"did:cid:bagaaieraemvw5oudbuiivxxlk72xps245ayvdtgcwc76owqbmxpmikdx2pja\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaieraemvw5oudbuiivxxlk72xps245ayvdtgcwc76owqbmxpmikdx2pja\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"azJ09248a2vKqs80FWCLG3Xw5xc9UF4sd_DImBsaxDw\",\"y\":\"215hdHiCRD7Q-DyAt5zcT4YLjdXFhm6y8bAbbia4Ne4\"}}],\"authentication\":[\"#key-1\"],\"assertionMethod\":[\"#key-1\"],\"capabilityInvocation\":[\"#key-1\"]}", "{\"id\":\"did:cid:bagaaieraemvw5oudbuiivxxlk72xps245ayvdtgcwc76owqbmxpmikdx2pja\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaieraemvw5oudbuiivxxlk72xps245ayvdtgcwc76owqbmxpmikdx2pja\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"7c8q6jrR_99AQxXwI0id7tkVCZwTRPf9g4S1Y329QGk\",\"y\":\"8by6qVswtkb9OzuzZqAMBsVV-9Nh4Oci2VAxcqKFaQY\"}}]}", "{\"id\":\"did:cid:bagaaieraemvw5oudbuiivxxlk72xps245ayvdtgcwc76owqbmxpmikdx2pja\"}", "{\"version\":1,\"type\":\"agent\",\"registry\":\"local\"}", "{}"].getD i (""))
def methods8 : Nat → List VerificationMethod := (fun i => [[⟨0, 0⟩], [⟨0, 1⟩], [], [], []].getD i ([]))
def documents8 : Nat → Nat := (fun i => [4, 0, 1].getD i (4))
def graph8 : DocumentGraph := {
  size := 3
  root := 1
  initialDocument := 1
  parent := (fun i => [some 2, none, some 1].getD i (none))
  depth := (fun i => [2, 0, 1].getD i (0))
  action := (fun i => [AgentAction.deactivate, AgentAction.keep, AgentAction.rotate 2].getD i (AgentAction.keep))
  documents := (fun i => [[], [⟨0, 0⟩], [⟨0, 1⟩]].getD i ([]))
  named := (fun i => [0, 0, 0].getD i (0))
  signatureValid := fun i k => ((fun i => [[false, true, false, false], [true, false, false, false], [true, false, false, false]].getD i ([]))) i |>.getD k false
}
theorem methods_agree8 : ∀ i, methods8 (documents8 i) = graph8.documents i := by
  intro i
  cases i with
  | zero => rfl
  | succ i =>
    cases i with
    | zero => rfl
    | succ i =>
      cases i with
      | zero => rfl
      | succ i =>
        rfl
theorem ordered8 : AncestryOrdered (documentAgent graph8) := by
  intro i p parent
  by_cases bound : i < 3
  · have cases : i = 0 ∨ i = 1 ∨ i = 2 := by omega
    rcases cases with rfl | rfl | rfl <;> simp [documentAgent, graph8] at parent
    all_goals subst p; decide
  · have outside : 3 ≤ i := by omega
    simp only [documentAgent, graph8] at parent
    rw [List.getD_eq_getElem?_getD, List.getElem?_eq_none (by simpa using outside)] at parent
    simp at parent
theorem bounded8 : DepthBounded (documentAgent graph8) := by
  intro i bound
  have small : i < 3 := bound
  have checked : ∀ i : Fin 3, (documentAgent graph8).depth i.val < (documentAgent graph8).size := by decide
  exact checked ⟨i, small⟩
theorem parents8 : AgentParentBounded graph8 := by
  intro i p bound parent
  have small : i < 3 := bound
  have cases : i = 0 ∨ i = 1 ∨ i = 2 := by omega
  rcases cases with rfl | rfl | rfl <;> simp [graph8] at parent
  all_goals subst p; decide
def patch8 : Nat → ComponentPatch Nat Nat := (fun i => [⟨none, none⟩, ⟨none, none⟩, ⟨none, none⟩].getD i (⟨none, none⟩))
def registry8 : Nat → Nat := (fun i => [6, 6, 6, 4, 6].getD i (6))
def receipts8 : RegistryReceipts := {
  size := 0
  owner := (fun i => [].getD i (3))
  registry := (fun i => [].getD i (6))
  chain := (fun i => [true, true, true, false, false, false].getD i (false))
  accepted := fun _ => true
}
abbrev anchors8 := componentAnchors graph8 patch8 registry8 3 receipts8
abbrev model8 := componentEvents graph8 anchors8
def positions8 : Nat → List Nat := (fun i => [].getD i ([]))
theorem ranks8 : RegistryCidRanks (componentRegistry graph8 patch8 registry8 3) receipts8 positions8 := by
  intro x y xv yv same
  have xb : x < 0 := eligible_lt _ _ _ xv
  have yb : y < 0 := eligible_lt _ _ _ yv
  have checked : ∀ x y : Fin 0,
      eligible (registryAnchors (componentRegistry graph8 patch8 registry8 3) receipts8) (receipts8.owner x.val) x.val = true →
      eligible (registryAnchors (componentRegistry graph8 patch8 registry8 3) receipts8) (receipts8.owner y.val) y.val = true →
      receipts8.registry x.val = receipts8.registry y.val →
      (x.val < y.val ↔ compare (positions8 x.val) (positions8 y.val) = .lt ∨
        (compare (positions8 x.val) (positions8 y.val) = .eq ∧ receipts8.owner x.val < receipts8.owner y.val)) := by decide
  exact checked ⟨x, xb⟩ ⟨y, yb⟩ xv yv same
def operationTime8 : Nat → Int := (fun i => [1788999900000, 1788998460000, 1788999600000].getD i (0))
def chainFacts8 : Nat → ChainReceiptView := (fun i => [].getD i (⟨0, [], 0, false⟩))
def atoms9 : Nat → String := (fun i => ["{\"@context\":[\"https://www.w3.org/ns/did/v1\"],\"id\":\"did:cid:bagaaierandwgmfyt5vkhylbwwb3dvcsdih6agitgvrotytitpduqp5zfjq7q\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaierandwgmfyt5vkhylbwwb3dvcsdih6agitgvrotytitpduqp5zfjq7q\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"MAemGeO4kBa-f3jOK_Hb21lXKC6jN4jeuIuyMumLmlA\",\"y\":\"iWcPPQGrI3j02b0_ocPHCHj6OptQ9kGWskmn6StCooo\"}}],\"authentication\":[\"#key-1\"],\"assertionMethod\":[\"#key-1\"],\"capabilityInvocation\":[\"#key-1\"]}", "{\"id\":\"did:cid:bagaaierandwgmfyt5vkhylbwwb3dvcsdih6agitgvrotytitpduqp5zfjq7q\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaierandwgmfyt5vkhylbwwb3dvcsdih6agitgvrotytitpduqp5zfjq7q\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"uVwknYT0F-PjlaEnQlQotUBnHMFYgeuCjBe3IqU_xZk\",\"y\":\"4hyl5WyQ80CYjTkzrMdr64Mv1kyrB43fPOcykjAx0ag\"}},{\"id\":\"#key-2\",\"controller\":\"did:cid:bagaaierandwgmfyt5vkhylbwwb3dvcsdih6agitgvrotytitpduqp5zfjq7q\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"MAemGeO4kBa-f3jOK_Hb21lXKC6jN4jeuIuyMumLmlA\",\"y\":\"iWcPPQGrI3j02b0_ocPHCHj6OptQ9kGWskmn6StCooo\"}}]}", "{\"id\":\"did:cid:bagaaierandwgmfyt5vkhylbwwb3dvcsdih6agitgvrotytitpduqp5zfjq7q\"}", "{\"version\":1,\"type\":\"agent\",\"registry\":\"local\"}", "{}"].getD i (""))
def methods9 : Nat → List VerificationMethod := (fun i => [[⟨0, 2⟩], [⟨0, 3⟩, ⟨1, 2⟩], [], [], []].getD i ([]))
def documents9 : Nat → Nat := (fun i => [0, 1].getD i (4))
def graph9 : DocumentGraph := {
  size := 2
  root := 0
  initialDocument := 0
  parent := (fun i => [none, some 0].getD i (none))
  depth := (fun i => [0, 1].getD i (0))
  action := (fun i => [AgentAction.keep, AgentAction.rotate 1].getD i (AgentAction.keep))
  documents := (fun i => [[⟨0, 2⟩], [⟨0, 3⟩, ⟨1, 2⟩]].getD i ([]))
  named := (fun i => [0, 0].getD i (0))
  signatureValid := fun i k => ((fun i => [[false, false, true, false], [false, false, true, false]].getD i ([]))) i |>.getD k false
}
theorem methods_agree9 : ∀ i, methods9 (documents9 i) = graph9.documents i := by
  intro i
  cases i with
  | zero => rfl
  | succ i =>
    cases i with
    | zero => rfl
    | succ i =>
      rfl
theorem ordered9 : AncestryOrdered (documentAgent graph9) := by
  intro i p parent
  by_cases bound : i < 2
  · have cases : i = 0 ∨ i = 1 := by omega
    rcases cases with rfl | rfl <;> simp [documentAgent, graph9] at parent
    all_goals subst p; decide
  · have outside : 2 ≤ i := by omega
    simp only [documentAgent, graph9] at parent
    rw [List.getD_eq_getElem?_getD, List.getElem?_eq_none (by simpa using outside)] at parent
    simp at parent
theorem bounded9 : DepthBounded (documentAgent graph9) := by
  intro i bound
  have small : i < 2 := bound
  have checked : ∀ i : Fin 2, (documentAgent graph9).depth i.val < (documentAgent graph9).size := by decide
  exact checked ⟨i, small⟩
theorem parents9 : AgentParentBounded graph9 := by
  intro i p bound parent
  have small : i < 2 := bound
  have cases : i = 0 ∨ i = 1 := by omega
  rcases cases with rfl | rfl <;> simp [graph9] at parent
  all_goals subst p; decide
def patch9 : Nat → ComponentPatch Nat Nat := (fun i => [⟨none, none⟩, ⟨none, none⟩].getD i (⟨none, none⟩))
def registry9 : Nat → Nat := (fun i => [6, 6, 6, 4, 6].getD i (6))
def receipts9 : RegistryReceipts := {
  size := 0
  owner := (fun i => [].getD i (2))
  registry := (fun i => [].getD i (6))
  chain := (fun i => [true, true, true, false, false, false].getD i (false))
  accepted := fun _ => true
}
abbrev anchors9 := componentAnchors graph9 patch9 registry9 3 receipts9
abbrev model9 := componentEvents graph9 anchors9
def positions9 : Nat → List Nat := (fun i => [].getD i ([]))
theorem ranks9 : RegistryCidRanks (componentRegistry graph9 patch9 registry9 3) receipts9 positions9 := by
  intro x y xv yv same
  have xb : x < 0 := eligible_lt _ _ _ xv
  have yb : y < 0 := eligible_lt _ _ _ yv
  have checked : ∀ x y : Fin 0,
      eligible (registryAnchors (componentRegistry graph9 patch9 registry9 3) receipts9) (receipts9.owner x.val) x.val = true →
      eligible (registryAnchors (componentRegistry graph9 patch9 registry9 3) receipts9) (receipts9.owner y.val) y.val = true →
      receipts9.registry x.val = receipts9.registry y.val →
      (x.val < y.val ↔ compare (positions9 x.val) (positions9 y.val) = .lt ∨
        (compare (positions9 x.val) (positions9 y.val) = .eq ∧ receipts9.owner x.val < receipts9.owner y.val)) := by decide
  exact checked ⟨x, xb⟩ ⟨y, yb⟩ xv yv same
def operationTime9 : Nat → Int := (fun i => [1788998460000, 1789001100000].getD i (0))
def chainFacts9 : Nat → ChainReceiptView := (fun i => [].getD i (⟨0, [], 0, false⟩))
def atoms10 : Nat → String := (fun i => ["{\"@context\":[\"https://www.w3.org/ns/did/v1\"],\"id\":\"did:cid:bagaaiera2qfhjr265ikupaibqdfa4v77wyoffbqwu54wsetqot2hf5d3ohlq\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaiera2qfhjr265ikupaibqdfa4v77wyoffbqwu54wsetqot2hf5d3ohlq\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"azJ09248a2vKqs80FWCLG3Xw5xc9UF4sd_DImBsaxDw\",\"y\":\"215hdHiCRD7Q-DyAt5zcT4YLjdXFhm6y8bAbbia4Ne4\"}}],\"authentication\":[\"#key-1\"],\"assertionMethod\":[\"#key-1\"],\"capabilityInvocation\":[\"#key-1\"]}", "{\"id\":\"did:cid:bagaaiera2qfhjr265ikupaibqdfa4v77wyoffbqwu54wsetqot2hf5d3ohlq\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaiera2qfhjr265ikupaibqdfa4v77wyoffbqwu54wsetqot2hf5d3ohlq\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"7c8q6jrR_99AQxXwI0id7tkVCZwTRPf9g4S1Y329QGk\",\"y\":\"8by6qVswtkb9OzuzZqAMBsVV-9Nh4Oci2VAxcqKFaQY\"}}]}", "{\"id\":\"did:cid:bagaaiera2qfhjr265ikupaibqdfa4v77wyoffbqwu54wsetqot2hf5d3ohlq\"}", "{\"version\":1,\"type\":\"agent\",\"registry\":\"hyperswarm\"}", "{}"].getD i (""))
def methods10 : Nat → List VerificationMethod := (fun i => [[⟨0, 0⟩], [⟨0, 1⟩], [], [], []].getD i ([]))
def documents10 : Nat → Nat := (fun i => [1, 0, 4].getD i (4))
def graph10 : DocumentGraph := {
  size := 3
  root := 1
  initialDocument := 1
  parent := (fun i => [some 1, none, some 0].getD i (none))
  depth := (fun i => [1, 0, 2].getD i (0))
  action := (fun i => [AgentAction.rotate 0, AgentAction.keep, AgentAction.deactivate].getD i (AgentAction.keep))
  documents := (fun i => [[⟨0, 1⟩], [⟨0, 0⟩], []].getD i ([]))
  named := (fun i => [0, 0, 0].getD i (0))
  signatureValid := fun i k => ((fun i => [[true, false, false, false], [true, false, false, false], [false, true, false, false]].getD i ([]))) i |>.getD k false
}
theorem methods_agree10 : ∀ i, methods10 (documents10 i) = graph10.documents i := by
  intro i
  cases i with
  | zero => rfl
  | succ i =>
    cases i with
    | zero => rfl
    | succ i =>
      cases i with
      | zero => rfl
      | succ i =>
        rfl
theorem ordered10 : AncestryOrdered (documentAgent graph10) := by
  intro i p parent
  by_cases bound : i < 3
  · have cases : i = 0 ∨ i = 1 ∨ i = 2 := by omega
    rcases cases with rfl | rfl | rfl <;> simp [documentAgent, graph10] at parent
    all_goals subst p; decide
  · have outside : 3 ≤ i := by omega
    simp only [documentAgent, graph10] at parent
    rw [List.getD_eq_getElem?_getD, List.getElem?_eq_none (by simpa using outside)] at parent
    simp at parent
theorem bounded10 : DepthBounded (documentAgent graph10) := by
  intro i bound
  have small : i < 3 := bound
  have checked : ∀ i : Fin 3, (documentAgent graph10).depth i.val < (documentAgent graph10).size := by decide
  exact checked ⟨i, small⟩
theorem parents10 : AgentParentBounded graph10 := by
  intro i p bound parent
  have small : i < 3 := bound
  have cases : i = 0 ∨ i = 1 ∨ i = 2 := by omega
  rcases cases with rfl | rfl | rfl <;> simp [graph10] at parent
  all_goals subst p; decide
def patch10 : Nat → ComponentPatch Nat Nat := (fun i => [⟨none, none⟩, ⟨none, none⟩, ⟨none, none⟩].getD i (⟨none, none⟩))
def registry10 : Nat → Nat := (fun i => [6, 6, 6, 3, 6].getD i (6))
def receipts10 : RegistryReceipts := {
  size := 0
  owner := (fun i => [].getD i (3))
  registry := (fun i => [].getD i (6))
  chain := (fun i => [true, true, true, false, false, false].getD i (false))
  accepted := fun _ => true
}
abbrev anchors10 := componentAnchors graph10 patch10 registry10 3 receipts10
abbrev model10 := componentEvents graph10 anchors10
def positions10 : Nat → List Nat := (fun i => [].getD i ([]))
theorem ranks10 : RegistryCidRanks (componentRegistry graph10 patch10 registry10 3) receipts10 positions10 := by
  intro x y xv yv same
  have xb : x < 0 := eligible_lt _ _ _ xv
  have yb : y < 0 := eligible_lt _ _ _ yv
  have checked : ∀ x y : Fin 0,
      eligible (registryAnchors (componentRegistry graph10 patch10 registry10 3) receipts10) (receipts10.owner x.val) x.val = true →
      eligible (registryAnchors (componentRegistry graph10 patch10 registry10 3) receipts10) (receipts10.owner y.val) y.val = true →
      receipts10.registry x.val = receipts10.registry y.val →
      (x.val < y.val ↔ compare (positions10 x.val) (positions10 y.val) = .lt ∨
        (compare (positions10 x.val) (positions10 y.val) = .eq ∧ receipts10.owner x.val < receipts10.owner y.val)) := by decide
  exact checked ⟨x, xb⟩ ⟨y, yb⟩ xv yv same
def operationTime10 : Nat → Int := (fun i => [1788999600000, 1788998460000, 1788999900000].getD i (0))
def chainFacts10 : Nat → ChainReceiptView := (fun i => [].getD i (⟨0, [], 0, false⟩))
def atoms11 : Nat → String := (fun i => ["{\"@context\":[\"https://www.w3.org/ns/did/v1\"],\"id\":\"did:cid:bagaaieravjlqcywmnao4aq6kgqaf2bhtqyvidfoohagjoyzyijcagak4qyta\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaieravjlqcywmnao4aq6kgqaf2bhtqyvidfoohagjoyzyijcagak4qyta\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"MAemGeO4kBa-f3jOK_Hb21lXKC6jN4jeuIuyMumLmlA\",\"y\":\"iWcPPQGrI3j02b0_ocPHCHj6OptQ9kGWskmn6StCooo\"}}],\"authentication\":[\"#key-1\"],\"assertionMethod\":[\"#key-1\"],\"capabilityInvocation\":[\"#key-1\"]}", "{\"id\":\"did:cid:bagaaieravjlqcywmnao4aq6kgqaf2bhtqyvidfoohagjoyzyijcagak4qyta\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaieravjlqcywmnao4aq6kgqaf2bhtqyvidfoohagjoyzyijcagak4qyta\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"uVwknYT0F-PjlaEnQlQotUBnHMFYgeuCjBe3IqU_xZk\",\"y\":\"4hyl5WyQ80CYjTkzrMdr64Mv1kyrB43fPOcykjAx0ag\"}},{\"id\":\"#key-2\",\"controller\":\"did:cid:bagaaieravjlqcywmnao4aq6kgqaf2bhtqyvidfoohagjoyzyijcagak4qyta\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"MAemGeO4kBa-f3jOK_Hb21lXKC6jN4jeuIuyMumLmlA\",\"y\":\"iWcPPQGrI3j02b0_ocPHCHj6OptQ9kGWskmn6StCooo\"}}]}", "{\"id\":\"did:cid:bagaaieravjlqcywmnao4aq6kgqaf2bhtqyvidfoohagjoyzyijcagak4qyta\"}", "{\"version\":1,\"type\":\"agent\",\"registry\":\"hyperswarm\"}", "{}"].getD i (""))
def methods11 : Nat → List VerificationMethod := (fun i => [[⟨0, 2⟩], [⟨0, 3⟩, ⟨1, 2⟩], [], [], []].getD i ([]))
def documents11 : Nat → Nat := (fun i => [1, 0].getD i (4))
def graph11 : DocumentGraph := {
  size := 2
  root := 1
  initialDocument := 1
  parent := (fun i => [some 1, none].getD i (none))
  depth := (fun i => [1, 0].getD i (0))
  action := (fun i => [AgentAction.rotate 0, AgentAction.keep].getD i (AgentAction.keep))
  documents := (fun i => [[⟨0, 3⟩, ⟨1, 2⟩], [⟨0, 2⟩]].getD i ([]))
  named := (fun i => [0, 0].getD i (0))
  signatureValid := fun i k => ((fun i => [[false, false, true, false], [false, false, true, false]].getD i ([]))) i |>.getD k false
}
theorem methods_agree11 : ∀ i, methods11 (documents11 i) = graph11.documents i := by
  intro i
  cases i with
  | zero => rfl
  | succ i =>
    cases i with
    | zero => rfl
    | succ i =>
      rfl
theorem ordered11 : AncestryOrdered (documentAgent graph11) := by
  intro i p parent
  by_cases bound : i < 2
  · have cases : i = 0 ∨ i = 1 := by omega
    rcases cases with rfl | rfl <;> simp [documentAgent, graph11] at parent
    all_goals subst p; decide
  · have outside : 2 ≤ i := by omega
    simp only [documentAgent, graph11] at parent
    rw [List.getD_eq_getElem?_getD, List.getElem?_eq_none (by simpa using outside)] at parent
    simp at parent
theorem bounded11 : DepthBounded (documentAgent graph11) := by
  intro i bound
  have small : i < 2 := bound
  have checked : ∀ i : Fin 2, (documentAgent graph11).depth i.val < (documentAgent graph11).size := by decide
  exact checked ⟨i, small⟩
theorem parents11 : AgentParentBounded graph11 := by
  intro i p bound parent
  have small : i < 2 := bound
  have cases : i = 0 ∨ i = 1 := by omega
  rcases cases with rfl | rfl <;> simp [graph11] at parent
  all_goals subst p; decide
def patch11 : Nat → ComponentPatch Nat Nat := (fun i => [⟨none, none⟩, ⟨none, none⟩].getD i (⟨none, none⟩))
def registry11 : Nat → Nat := (fun i => [6, 6, 6, 3, 6].getD i (6))
def receipts11 : RegistryReceipts := {
  size := 0
  owner := (fun i => [].getD i (2))
  registry := (fun i => [].getD i (6))
  chain := (fun i => [true, true, true, false, false, false].getD i (false))
  accepted := fun _ => true
}
abbrev anchors11 := componentAnchors graph11 patch11 registry11 3 receipts11
abbrev model11 := componentEvents graph11 anchors11
def positions11 : Nat → List Nat := (fun i => [].getD i ([]))
theorem ranks11 : RegistryCidRanks (componentRegistry graph11 patch11 registry11 3) receipts11 positions11 := by
  intro x y xv yv same
  have xb : x < 0 := eligible_lt _ _ _ xv
  have yb : y < 0 := eligible_lt _ _ _ yv
  have checked : ∀ x y : Fin 0,
      eligible (registryAnchors (componentRegistry graph11 patch11 registry11 3) receipts11) (receipts11.owner x.val) x.val = true →
      eligible (registryAnchors (componentRegistry graph11 patch11 registry11 3) receipts11) (receipts11.owner y.val) y.val = true →
      receipts11.registry x.val = receipts11.registry y.val →
      (x.val < y.val ↔ compare (positions11 x.val) (positions11 y.val) = .lt ∨
        (compare (positions11 x.val) (positions11 y.val) = .eq ∧ receipts11.owner x.val < receipts11.owner y.val)) := by decide
  exact checked ⟨x, xb⟩ ⟨y, yb⟩ xv yv same
def operationTime11 : Nat → Int := (fun i => [1789001100000, 1788998460000].getD i (0))
def chainFacts11 : Nat → ChainReceiptView := (fun i => [].getD i (⟨0, [], 0, false⟩))
def atoms12 : Nat → String := (fun i => ["{\"@context\":[\"https://www.w3.org/ns/did/v1\"],\"id\":\"did:cid:bagaaierakahhmej7idkbq5cjvs5ovfa23mgcqhlfdh6lqwfed7wlirqjdh6a\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaierakahhmej7idkbq5cjvs5ovfa23mgcqhlfdh6lqwfed7wlirqjdh6a\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"azJ09248a2vKqs80FWCLG3Xw5xc9UF4sd_DImBsaxDw\",\"y\":\"215hdHiCRD7Q-DyAt5zcT4YLjdXFhm6y8bAbbia4Ne4\"}}],\"authentication\":[\"#key-1\"],\"assertionMethod\":[\"#key-1\"],\"capabilityInvocation\":[\"#key-1\"]}", "{\"id\":\"did:cid:bagaaierakahhmej7idkbq5cjvs5ovfa23mgcqhlfdh6lqwfed7wlirqjdh6a\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaierakahhmej7idkbq5cjvs5ovfa23mgcqhlfdh6lqwfed7wlirqjdh6a\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"7c8q6jrR_99AQxXwI0id7tkVCZwTRPf9g4S1Y329QGk\",\"y\":\"8by6qVswtkb9OzuzZqAMBsVV-9Nh4Oci2VAxcqKFaQY\"}}]}", "{\"id\":\"did:cid:bagaaierakahhmej7idkbq5cjvs5ovfa23mgcqhlfdh6lqwfed7wlirqjdh6a\"}", "{\"version\":1,\"type\":\"agent\",\"registry\":\"pin\"}", "{}"].getD i (""))
def methods12 : Nat → List VerificationMethod := (fun i => [[⟨0, 0⟩], [⟨0, 1⟩], [], [], []].getD i ([]))
def documents12 : Nat → Nat := (fun i => [4, 0, 1].getD i (4))
def graph12 : DocumentGraph := {
  size := 3
  root := 1
  initialDocument := 1
  parent := (fun i => [some 2, none, some 1].getD i (none))
  depth := (fun i => [2, 0, 1].getD i (0))
  action := (fun i => [AgentAction.deactivate, AgentAction.keep, AgentAction.rotate 2].getD i (AgentAction.keep))
  documents := (fun i => [[], [⟨0, 0⟩], [⟨0, 1⟩]].getD i ([]))
  named := (fun i => [0, 0, 0].getD i (0))
  signatureValid := fun i k => ((fun i => [[false, true, false, false], [true, false, false, false], [true, false, false, false]].getD i ([]))) i |>.getD k false
}
theorem methods_agree12 : ∀ i, methods12 (documents12 i) = graph12.documents i := by
  intro i
  cases i with
  | zero => rfl
  | succ i =>
    cases i with
    | zero => rfl
    | succ i =>
      cases i with
      | zero => rfl
      | succ i =>
        rfl
theorem ordered12 : AncestryOrdered (documentAgent graph12) := by
  intro i p parent
  by_cases bound : i < 3
  · have cases : i = 0 ∨ i = 1 ∨ i = 2 := by omega
    rcases cases with rfl | rfl | rfl <;> simp [documentAgent, graph12] at parent
    all_goals subst p; decide
  · have outside : 3 ≤ i := by omega
    simp only [documentAgent, graph12] at parent
    rw [List.getD_eq_getElem?_getD, List.getElem?_eq_none (by simpa using outside)] at parent
    simp at parent
theorem bounded12 : DepthBounded (documentAgent graph12) := by
  intro i bound
  have small : i < 3 := bound
  have checked : ∀ i : Fin 3, (documentAgent graph12).depth i.val < (documentAgent graph12).size := by decide
  exact checked ⟨i, small⟩
theorem parents12 : AgentParentBounded graph12 := by
  intro i p bound parent
  have small : i < 3 := bound
  have cases : i = 0 ∨ i = 1 ∨ i = 2 := by omega
  rcases cases with rfl | rfl | rfl <;> simp [graph12] at parent
  all_goals subst p; decide
def patch12 : Nat → ComponentPatch Nat Nat := (fun i => [⟨none, none⟩, ⟨none, none⟩, ⟨none, none⟩].getD i (⟨none, none⟩))
def registry12 : Nat → Nat := (fun i => [6, 6, 6, 5, 6].getD i (6))
def receipts12 : RegistryReceipts := {
  size := 0
  owner := (fun i => [].getD i (3))
  registry := (fun i => [].getD i (6))
  chain := (fun i => [true, true, true, false, false, false].getD i (false))
  accepted := fun _ => true
}
abbrev anchors12 := componentAnchors graph12 patch12 registry12 3 receipts12
abbrev model12 := componentEvents graph12 anchors12
def positions12 : Nat → List Nat := (fun i => [].getD i ([]))
theorem ranks12 : RegistryCidRanks (componentRegistry graph12 patch12 registry12 3) receipts12 positions12 := by
  intro x y xv yv same
  have xb : x < 0 := eligible_lt _ _ _ xv
  have yb : y < 0 := eligible_lt _ _ _ yv
  have checked : ∀ x y : Fin 0,
      eligible (registryAnchors (componentRegistry graph12 patch12 registry12 3) receipts12) (receipts12.owner x.val) x.val = true →
      eligible (registryAnchors (componentRegistry graph12 patch12 registry12 3) receipts12) (receipts12.owner y.val) y.val = true →
      receipts12.registry x.val = receipts12.registry y.val →
      (x.val < y.val ↔ compare (positions12 x.val) (positions12 y.val) = .lt ∨
        (compare (positions12 x.val) (positions12 y.val) = .eq ∧ receipts12.owner x.val < receipts12.owner y.val)) := by decide
  exact checked ⟨x, xb⟩ ⟨y, yb⟩ xv yv same
def operationTime12 : Nat → Int := (fun i => [1788999900000, 1788998460000, 1788999600000].getD i (0))
def chainFacts12 : Nat → ChainReceiptView := (fun i => [].getD i (⟨0, [], 0, false⟩))
def atoms13 : Nat → String := (fun i => ["{\"@context\":[\"https://www.w3.org/ns/did/v1\"],\"id\":\"did:cid:bagaaierajzz3us3silq3wa7polpbjxa6su6bbov4xfj3ao6u3fxzeiqctbta\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaierajzz3us3silq3wa7polpbjxa6su6bbov4xfj3ao6u3fxzeiqctbta\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"MAemGeO4kBa-f3jOK_Hb21lXKC6jN4jeuIuyMumLmlA\",\"y\":\"iWcPPQGrI3j02b0_ocPHCHj6OptQ9kGWskmn6StCooo\"}}],\"authentication\":[\"#key-1\"],\"assertionMethod\":[\"#key-1\"],\"capabilityInvocation\":[\"#key-1\"]}", "{\"id\":\"did:cid:bagaaierajzz3us3silq3wa7polpbjxa6su6bbov4xfj3ao6u3fxzeiqctbta\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaierajzz3us3silq3wa7polpbjxa6su6bbov4xfj3ao6u3fxzeiqctbta\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"uVwknYT0F-PjlaEnQlQotUBnHMFYgeuCjBe3IqU_xZk\",\"y\":\"4hyl5WyQ80CYjTkzrMdr64Mv1kyrB43fPOcykjAx0ag\"}},{\"id\":\"#key-2\",\"controller\":\"did:cid:bagaaierajzz3us3silq3wa7polpbjxa6su6bbov4xfj3ao6u3fxzeiqctbta\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"MAemGeO4kBa-f3jOK_Hb21lXKC6jN4jeuIuyMumLmlA\",\"y\":\"iWcPPQGrI3j02b0_ocPHCHj6OptQ9kGWskmn6StCooo\"}}]}", "{\"id\":\"did:cid:bagaaierajzz3us3silq3wa7polpbjxa6su6bbov4xfj3ao6u3fxzeiqctbta\"}", "{\"version\":1,\"type\":\"agent\",\"registry\":\"pin\"}", "{}"].getD i (""))
def methods13 : Nat → List VerificationMethod := (fun i => [[⟨0, 2⟩], [⟨0, 3⟩, ⟨1, 2⟩], [], [], []].getD i ([]))
def documents13 : Nat → Nat := (fun i => [1, 0].getD i (4))
def graph13 : DocumentGraph := {
  size := 2
  root := 1
  initialDocument := 1
  parent := (fun i => [some 1, none].getD i (none))
  depth := (fun i => [1, 0].getD i (0))
  action := (fun i => [AgentAction.rotate 0, AgentAction.keep].getD i (AgentAction.keep))
  documents := (fun i => [[⟨0, 3⟩, ⟨1, 2⟩], [⟨0, 2⟩]].getD i ([]))
  named := (fun i => [0, 0].getD i (0))
  signatureValid := fun i k => ((fun i => [[false, false, true, false], [false, false, true, false]].getD i ([]))) i |>.getD k false
}
theorem methods_agree13 : ∀ i, methods13 (documents13 i) = graph13.documents i := by
  intro i
  cases i with
  | zero => rfl
  | succ i =>
    cases i with
    | zero => rfl
    | succ i =>
      rfl
theorem ordered13 : AncestryOrdered (documentAgent graph13) := by
  intro i p parent
  by_cases bound : i < 2
  · have cases : i = 0 ∨ i = 1 := by omega
    rcases cases with rfl | rfl <;> simp [documentAgent, graph13] at parent
    all_goals subst p; decide
  · have outside : 2 ≤ i := by omega
    simp only [documentAgent, graph13] at parent
    rw [List.getD_eq_getElem?_getD, List.getElem?_eq_none (by simpa using outside)] at parent
    simp at parent
theorem bounded13 : DepthBounded (documentAgent graph13) := by
  intro i bound
  have small : i < 2 := bound
  have checked : ∀ i : Fin 2, (documentAgent graph13).depth i.val < (documentAgent graph13).size := by decide
  exact checked ⟨i, small⟩
theorem parents13 : AgentParentBounded graph13 := by
  intro i p bound parent
  have small : i < 2 := bound
  have cases : i = 0 ∨ i = 1 := by omega
  rcases cases with rfl | rfl <;> simp [graph13] at parent
  all_goals subst p; decide
def patch13 : Nat → ComponentPatch Nat Nat := (fun i => [⟨none, none⟩, ⟨none, none⟩].getD i (⟨none, none⟩))
def registry13 : Nat → Nat := (fun i => [6, 6, 6, 5, 6].getD i (6))
def receipts13 : RegistryReceipts := {
  size := 0
  owner := (fun i => [].getD i (2))
  registry := (fun i => [].getD i (6))
  chain := (fun i => [true, true, true, false, false, false].getD i (false))
  accepted := fun _ => true
}
abbrev anchors13 := componentAnchors graph13 patch13 registry13 3 receipts13
abbrev model13 := componentEvents graph13 anchors13
def positions13 : Nat → List Nat := (fun i => [].getD i ([]))
theorem ranks13 : RegistryCidRanks (componentRegistry graph13 patch13 registry13 3) receipts13 positions13 := by
  intro x y xv yv same
  have xb : x < 0 := eligible_lt _ _ _ xv
  have yb : y < 0 := eligible_lt _ _ _ yv
  have checked : ∀ x y : Fin 0,
      eligible (registryAnchors (componentRegistry graph13 patch13 registry13 3) receipts13) (receipts13.owner x.val) x.val = true →
      eligible (registryAnchors (componentRegistry graph13 patch13 registry13 3) receipts13) (receipts13.owner y.val) y.val = true →
      receipts13.registry x.val = receipts13.registry y.val →
      (x.val < y.val ↔ compare (positions13 x.val) (positions13 y.val) = .lt ∨
        (compare (positions13 x.val) (positions13 y.val) = .eq ∧ receipts13.owner x.val < receipts13.owner y.val)) := by decide
  exact checked ⟨x, xb⟩ ⟨y, yb⟩ xv yv same
def operationTime13 : Nat → Int := (fun i => [1789001100000, 1788998460000].getD i (0))
def chainFacts13 : Nat → ChainReceiptView := (fun i => [].getD i (⟨0, [], 0, false⟩))
def atoms14 : Nat → String := (fun i => ["{\"@context\":[\"https://www.w3.org/ns/did/v1\"],\"id\":\"did:cid:bagaaierapxkglolarrs7tw6q4c32zy7fycf7owfnr5kbnwqthbhk4gjf7kfq\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaierapxkglolarrs7tw6q4c32zy7fycf7owfnr5kbnwqthbhk4gjf7kfq\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"azJ09248a2vKqs80FWCLG3Xw5xc9UF4sd_DImBsaxDw\",\"y\":\"215hdHiCRD7Q-DyAt5zcT4YLjdXFhm6y8bAbbia4Ne4\"}}],\"authentication\":[\"#key-1\"],\"assertionMethod\":[\"#key-1\"],\"capabilityInvocation\":[\"#key-1\"]}", "{\"id\":\"did:cid:bagaaierapxkglolarrs7tw6q4c32zy7fycf7owfnr5kbnwqthbhk4gjf7kfq\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaierapxkglolarrs7tw6q4c32zy7fycf7owfnr5kbnwqthbhk4gjf7kfq\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"7c8q6jrR_99AQxXwI0id7tkVCZwTRPf9g4S1Y329QGk\",\"y\":\"8by6qVswtkb9OzuzZqAMBsVV-9Nh4Oci2VAxcqKFaQY\"}}]}", "{\"id\":\"did:cid:bagaaierapxkglolarrs7tw6q4c32zy7fycf7owfnr5kbnwqthbhk4gjf7kfq\"}", "{\"version\":1,\"type\":\"agent\",\"registry\":\"BTC:signet\"}", "{}"].getD i (""))
def methods14 : Nat → List VerificationMethod := (fun i => [[⟨0, 0⟩], [⟨0, 1⟩], [], [], []].getD i ([]))
def documents14 : Nat → Nat := (fun i => [1, 4, 0].getD i (4))
def graph14 : DocumentGraph := {
  size := 3
  root := 2
  initialDocument := 2
  parent := (fun i => [some 2, some 0, none].getD i (none))
  depth := (fun i => [1, 2, 0].getD i (0))
  action := (fun i => [AgentAction.rotate 0, AgentAction.deactivate, AgentAction.keep].getD i (AgentAction.keep))
  documents := (fun i => [[⟨0, 1⟩], [], [⟨0, 0⟩]].getD i ([]))
  named := (fun i => [0, 0, 0].getD i (0))
  signatureValid := fun i k => ((fun i => [[true, false, false, false], [false, true, false, false], [true, false, false, false]].getD i ([]))) i |>.getD k false
}
theorem methods_agree14 : ∀ i, methods14 (documents14 i) = graph14.documents i := by
  intro i
  cases i with
  | zero => rfl
  | succ i =>
    cases i with
    | zero => rfl
    | succ i =>
      cases i with
      | zero => rfl
      | succ i =>
        rfl
theorem ordered14 : AncestryOrdered (documentAgent graph14) := by
  intro i p parent
  by_cases bound : i < 3
  · have cases : i = 0 ∨ i = 1 ∨ i = 2 := by omega
    rcases cases with rfl | rfl | rfl <;> simp [documentAgent, graph14] at parent
    all_goals subst p; decide
  · have outside : 3 ≤ i := by omega
    simp only [documentAgent, graph14] at parent
    rw [List.getD_eq_getElem?_getD, List.getElem?_eq_none (by simpa using outside)] at parent
    simp at parent
theorem bounded14 : DepthBounded (documentAgent graph14) := by
  intro i bound
  have small : i < 3 := bound
  have checked : ∀ i : Fin 3, (documentAgent graph14).depth i.val < (documentAgent graph14).size := by decide
  exact checked ⟨i, small⟩
theorem parents14 : AgentParentBounded graph14 := by
  intro i p bound parent
  have small : i < 3 := bound
  have cases : i = 0 ∨ i = 1 ∨ i = 2 := by omega
  rcases cases with rfl | rfl | rfl <;> simp [graph14] at parent
  all_goals subst p; decide
def patch14 : Nat → ComponentPatch Nat Nat := (fun i => [⟨none, none⟩, ⟨none, none⟩, ⟨none, none⟩].getD i (⟨none, none⟩))
def registry14 : Nat → Nat := (fun i => [6, 6, 6, 0, 6].getD i (6))
def receipts14 : RegistryReceipts := {
  size := 4
  owner := (fun i => [2, 0, 1, 0].getD i (3))
  registry := (fun i => [0, 0, 0, 0].getD i (6))
  chain := (fun i => [true, true, true, false, false, false].getD i (false))
  accepted := fun _ => true
}
abbrev anchors14 := componentAnchors graph14 patch14 registry14 3 receipts14
abbrev model14 := componentEvents graph14 anchors14
def positions14 : Nat → List Nat := (fun i => [[1, 0, 0], [20, 0, 0], [25, 0, 0], [35, 0, 0]].getD i ([]))
theorem ranks14 : RegistryCidRanks (componentRegistry graph14 patch14 registry14 3) receipts14 positions14 := by
  intro x y xv yv same
  have xb : x < 4 := eligible_lt _ _ _ xv
  have yb : y < 4 := eligible_lt _ _ _ yv
  have checked : ∀ x y : Fin 4,
      eligible (registryAnchors (componentRegistry graph14 patch14 registry14 3) receipts14) (receipts14.owner x.val) x.val = true →
      eligible (registryAnchors (componentRegistry graph14 patch14 registry14 3) receipts14) (receipts14.owner y.val) y.val = true →
      receipts14.registry x.val = receipts14.registry y.val →
      (x.val < y.val ↔ compare (positions14 x.val) (positions14 y.val) = .lt ∨
        (compare (positions14 x.val) (positions14 y.val) = .eq ∧ receipts14.owner x.val < receipts14.owner y.val)) := by decide
  exact checked ⟨x, xb⟩ ⟨y, yb⟩ xv yv same
def operationTime14 : Nat → Int := (fun i => [1788999600000, 1788999900000, 1788998460000].getD i (0))
def chainFacts14 : Nat → ChainReceiptView := (fun i => [⟨0, [1, 0, 0], 1788998460000, true⟩, ⟨0, [20, 0, 0], 1789000500000, true⟩, ⟨0, [25, 0, 0], 1789000800000, true⟩, ⟨0, [35, 0, 0], 1789000500000, true⟩].getD i (⟨0, [], 0, false⟩))
def atoms15 : Nat → String := (fun i => ["{\"@context\":[\"https://www.w3.org/ns/did/v1\"],\"id\":\"did:cid:bagaaierafnvcugehelccjphplzgyysyzuqc3ho6pepaknf6labdfgkvspxxa\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaierafnvcugehelccjphplzgyysyzuqc3ho6pepaknf6labdfgkvspxxa\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"MAemGeO4kBa-f3jOK_Hb21lXKC6jN4jeuIuyMumLmlA\",\"y\":\"iWcPPQGrI3j02b0_ocPHCHj6OptQ9kGWskmn6StCooo\"}}],\"authentication\":[\"#key-1\"],\"assertionMethod\":[\"#key-1\"],\"capabilityInvocation\":[\"#key-1\"]}", "{\"id\":\"did:cid:bagaaierafnvcugehelccjphplzgyysyzuqc3ho6pepaknf6labdfgkvspxxa\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaierafnvcugehelccjphplzgyysyzuqc3ho6pepaknf6labdfgkvspxxa\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"uVwknYT0F-PjlaEnQlQotUBnHMFYgeuCjBe3IqU_xZk\",\"y\":\"4hyl5WyQ80CYjTkzrMdr64Mv1kyrB43fPOcykjAx0ag\"}},{\"id\":\"#key-2\",\"controller\":\"did:cid:bagaaierafnvcugehelccjphplzgyysyzuqc3ho6pepaknf6labdfgkvspxxa\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"MAemGeO4kBa-f3jOK_Hb21lXKC6jN4jeuIuyMumLmlA\",\"y\":\"iWcPPQGrI3j02b0_ocPHCHj6OptQ9kGWskmn6StCooo\"}}]}", "{\"id\":\"did:cid:bagaaierafnvcugehelccjphplzgyysyzuqc3ho6pepaknf6labdfgkvspxxa\"}", "{\"version\":1,\"type\":\"agent\",\"registry\":\"BTC:signet\"}", "{}"].getD i (""))
def methods15 : Nat → List VerificationMethod := (fun i => [[⟨0, 2⟩], [⟨0, 3⟩, ⟨1, 2⟩], [], [], []].getD i ([]))
def documents15 : Nat → Nat := (fun i => [0, 1].getD i (4))
def graph15 : DocumentGraph := {
  size := 2
  root := 0
  initialDocument := 0
  parent := (fun i => [none, some 0].getD i (none))
  depth := (fun i => [0, 1].getD i (0))
  action := (fun i => [AgentAction.keep, AgentAction.rotate 1].getD i (AgentAction.keep))
  documents := (fun i => [[⟨0, 2⟩], [⟨0, 3⟩, ⟨1, 2⟩]].getD i ([]))
  named := (fun i => [0, 0].getD i (0))
  signatureValid := fun i k => ((fun i => [[false, false, true, false], [false, false, true, false]].getD i ([]))) i |>.getD k false
}
theorem methods_agree15 : ∀ i, methods15 (documents15 i) = graph15.documents i := by
  intro i
  cases i with
  | zero => rfl
  | succ i =>
    cases i with
    | zero => rfl
    | succ i =>
      rfl
theorem ordered15 : AncestryOrdered (documentAgent graph15) := by
  intro i p parent
  by_cases bound : i < 2
  · have cases : i = 0 ∨ i = 1 := by omega
    rcases cases with rfl | rfl <;> simp [documentAgent, graph15] at parent
    all_goals subst p; decide
  · have outside : 2 ≤ i := by omega
    simp only [documentAgent, graph15] at parent
    rw [List.getD_eq_getElem?_getD, List.getElem?_eq_none (by simpa using outside)] at parent
    simp at parent
theorem bounded15 : DepthBounded (documentAgent graph15) := by
  intro i bound
  have small : i < 2 := bound
  have checked : ∀ i : Fin 2, (documentAgent graph15).depth i.val < (documentAgent graph15).size := by decide
  exact checked ⟨i, small⟩
theorem parents15 : AgentParentBounded graph15 := by
  intro i p bound parent
  have small : i < 2 := bound
  have cases : i = 0 ∨ i = 1 := by omega
  rcases cases with rfl | rfl <;> simp [graph15] at parent
  all_goals subst p; decide
def patch15 : Nat → ComponentPatch Nat Nat := (fun i => [⟨none, none⟩, ⟨none, none⟩].getD i (⟨none, none⟩))
def registry15 : Nat → Nat := (fun i => [6, 6, 6, 0, 6].getD i (6))
def receipts15 : RegistryReceipts := {
  size := 2
  owner := (fun i => [0, 1].getD i (2))
  registry := (fun i => [0, 0].getD i (6))
  chain := (fun i => [true, true, true, false, false, false].getD i (false))
  accepted := fun _ => true
}
abbrev anchors15 := componentAnchors graph15 patch15 registry15 3 receipts15
abbrev model15 := componentEvents graph15 anchors15
def positions15 : Nat → List Nat := (fun i => [[1, 1, 0], [45, 0, 0]].getD i ([]))
theorem ranks15 : RegistryCidRanks (componentRegistry graph15 patch15 registry15 3) receipts15 positions15 := by
  intro x y xv yv same
  have xb : x < 2 := eligible_lt _ _ _ xv
  have yb : y < 2 := eligible_lt _ _ _ yv
  have checked : ∀ x y : Fin 2,
      eligible (registryAnchors (componentRegistry graph15 patch15 registry15 3) receipts15) (receipts15.owner x.val) x.val = true →
      eligible (registryAnchors (componentRegistry graph15 patch15 registry15 3) receipts15) (receipts15.owner y.val) y.val = true →
      receipts15.registry x.val = receipts15.registry y.val →
      (x.val < y.val ↔ compare (positions15 x.val) (positions15 y.val) = .lt ∨
        (compare (positions15 x.val) (positions15 y.val) = .eq ∧ receipts15.owner x.val < receipts15.owner y.val)) := by decide
  exact checked ⟨x, xb⟩ ⟨y, yb⟩ xv yv same
def operationTime15 : Nat → Int := (fun i => [1788998460000, 1789001100000].getD i (0))
def chainFacts15 : Nat → ChainReceiptView := (fun i => [⟨0, [1, 1, 0], 1788998460000, true⟩, ⟨0, [45, 0, 0], 1789001100000, true⟩].getD i (⟨0, [], 0, false⟩))
def atoms16 : Nat → String := (fun i => ["{\"@context\":[\"https://www.w3.org/ns/did/v1\"],\"id\":\"did:cid:bagaaieraigz6tbg42k2obtbjeblznvfpkmd2hpkx4p4m5vbz5immpf6f7hia\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaieraigz6tbg42k2obtbjeblznvfpkmd2hpkx4p4m5vbz5immpf6f7hia\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"azJ09248a2vKqs80FWCLG3Xw5xc9UF4sd_DImBsaxDw\",\"y\":\"215hdHiCRD7Q-DyAt5zcT4YLjdXFhm6y8bAbbia4Ne4\"}}],\"authentication\":[\"#key-1\"],\"assertionMethod\":[\"#key-1\"],\"capabilityInvocation\":[\"#key-1\"]}", "{\"id\":\"did:cid:bagaaieraigz6tbg42k2obtbjeblznvfpkmd2hpkx4p4m5vbz5immpf6f7hia\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaieraigz6tbg42k2obtbjeblznvfpkmd2hpkx4p4m5vbz5immpf6f7hia\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"7c8q6jrR_99AQxXwI0id7tkVCZwTRPf9g4S1Y329QGk\",\"y\":\"8by6qVswtkb9OzuzZqAMBsVV-9Nh4Oci2VAxcqKFaQY\"}}]}", "{\"id\":\"did:cid:bagaaieraigz6tbg42k2obtbjeblznvfpkmd2hpkx4p4m5vbz5immpf6f7hia\"}", "{\"version\":1,\"type\":\"agent\",\"registry\":\"ZEC:testnet\"}", "{}"].getD i (""))
def methods16 : Nat → List VerificationMethod := (fun i => [[⟨0, 0⟩], [⟨0, 1⟩], [], [], []].getD i ([]))
def documents16 : Nat → Nat := (fun i => [0, 1, 4].getD i (4))
def graph16 : DocumentGraph := {
  size := 3
  root := 0
  initialDocument := 0
  parent := (fun i => [none, some 0, some 1].getD i (none))
  depth := (fun i => [0, 1, 2].getD i (0))
  action := (fun i => [AgentAction.keep, AgentAction.rotate 1, AgentAction.deactivate].getD i (AgentAction.keep))
  documents := (fun i => [[⟨0, 0⟩], [⟨0, 1⟩], []].getD i ([]))
  named := (fun i => [0, 0, 0].getD i (0))
  signatureValid := fun i k => ((fun i => [[true, false, false, false], [true, false, false, false], [false, true, false, false]].getD i ([]))) i |>.getD k false
}
theorem methods_agree16 : ∀ i, methods16 (documents16 i) = graph16.documents i := by
  intro i
  cases i with
  | zero => rfl
  | succ i =>
    cases i with
    | zero => rfl
    | succ i =>
      cases i with
      | zero => rfl
      | succ i =>
        rfl
theorem ordered16 : AncestryOrdered (documentAgent graph16) := by
  intro i p parent
  by_cases bound : i < 3
  · have cases : i = 0 ∨ i = 1 ∨ i = 2 := by omega
    rcases cases with rfl | rfl | rfl <;> simp [documentAgent, graph16] at parent
    all_goals subst p; decide
  · have outside : 3 ≤ i := by omega
    simp only [documentAgent, graph16] at parent
    rw [List.getD_eq_getElem?_getD, List.getElem?_eq_none (by simpa using outside)] at parent
    simp at parent
theorem bounded16 : DepthBounded (documentAgent graph16) := by
  intro i bound
  have small : i < 3 := bound
  have checked : ∀ i : Fin 3, (documentAgent graph16).depth i.val < (documentAgent graph16).size := by decide
  exact checked ⟨i, small⟩
theorem parents16 : AgentParentBounded graph16 := by
  intro i p bound parent
  have small : i < 3 := bound
  have cases : i = 0 ∨ i = 1 ∨ i = 2 := by omega
  rcases cases with rfl | rfl | rfl <;> simp [graph16] at parent
  all_goals subst p; decide
def patch16 : Nat → ComponentPatch Nat Nat := (fun i => [⟨none, none⟩, ⟨none, none⟩, ⟨none, none⟩].getD i (⟨none, none⟩))
def registry16 : Nat → Nat := (fun i => [6, 6, 6, 2, 6].getD i (6))
def receipts16 : RegistryReceipts := {
  size := 4
  owner := (fun i => [0, 1, 2, 1].getD i (3))
  registry := (fun i => [2, 2, 2, 2].getD i (6))
  chain := (fun i => [true, true, true, false, false, false].getD i (false))
  accepted := fun _ => true
}
abbrev anchors16 := componentAnchors graph16 patch16 registry16 3 receipts16
abbrev model16 := componentEvents graph16 anchors16
def positions16 : Nat → List Nat := (fun i => [[1, 0, 0], [20, 0, 0], [25, 0, 0], [35, 0, 0]].getD i ([]))
theorem ranks16 : RegistryCidRanks (componentRegistry graph16 patch16 registry16 3) receipts16 positions16 := by
  intro x y xv yv same
  have xb : x < 4 := eligible_lt _ _ _ xv
  have yb : y < 4 := eligible_lt _ _ _ yv
  have checked : ∀ x y : Fin 4,
      eligible (registryAnchors (componentRegistry graph16 patch16 registry16 3) receipts16) (receipts16.owner x.val) x.val = true →
      eligible (registryAnchors (componentRegistry graph16 patch16 registry16 3) receipts16) (receipts16.owner y.val) y.val = true →
      receipts16.registry x.val = receipts16.registry y.val →
      (x.val < y.val ↔ compare (positions16 x.val) (positions16 y.val) = .lt ∨
        (compare (positions16 x.val) (positions16 y.val) = .eq ∧ receipts16.owner x.val < receipts16.owner y.val)) := by decide
  exact checked ⟨x, xb⟩ ⟨y, yb⟩ xv yv same
def operationTime16 : Nat → Int := (fun i => [1788998460000, 1788999600000, 1788999900000].getD i (0))
def chainFacts16 : Nat → ChainReceiptView := (fun i => [⟨2, [1, 0, 0], 1788998460000, true⟩, ⟨2, [20, 0, 0], 1788999600000, true⟩, ⟨2, [25, 0, 0], 1788999900000, true⟩, ⟨2, [35, 0, 0], 1789000500000, true⟩].getD i (⟨0, [], 0, false⟩))
def atoms17 : Nat → String := (fun i => ["{\"@context\":[\"https://www.w3.org/ns/did/v1\"],\"id\":\"did:cid:bagaaieraleidmwtyj6u727hwqg3mqrl6oznjpd3u2hol34cuhyvhvszcnbrq\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaieraleidmwtyj6u727hwqg3mqrl6oznjpd3u2hol34cuhyvhvszcnbrq\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"MAemGeO4kBa-f3jOK_Hb21lXKC6jN4jeuIuyMumLmlA\",\"y\":\"iWcPPQGrI3j02b0_ocPHCHj6OptQ9kGWskmn6StCooo\"}}],\"authentication\":[\"#key-1\"],\"assertionMethod\":[\"#key-1\"],\"capabilityInvocation\":[\"#key-1\"]}", "{\"id\":\"did:cid:bagaaieraleidmwtyj6u727hwqg3mqrl6oznjpd3u2hol34cuhyvhvszcnbrq\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaieraleidmwtyj6u727hwqg3mqrl6oznjpd3u2hol34cuhyvhvszcnbrq\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"uVwknYT0F-PjlaEnQlQotUBnHMFYgeuCjBe3IqU_xZk\",\"y\":\"4hyl5WyQ80CYjTkzrMdr64Mv1kyrB43fPOcykjAx0ag\"}},{\"id\":\"#key-2\",\"controller\":\"did:cid:bagaaieraleidmwtyj6u727hwqg3mqrl6oznjpd3u2hol34cuhyvhvszcnbrq\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"MAemGeO4kBa-f3jOK_Hb21lXKC6jN4jeuIuyMumLmlA\",\"y\":\"iWcPPQGrI3j02b0_ocPHCHj6OptQ9kGWskmn6StCooo\"}}]}", "{\"id\":\"did:cid:bagaaieraleidmwtyj6u727hwqg3mqrl6oznjpd3u2hol34cuhyvhvszcnbrq\"}", "{\"version\":1,\"type\":\"agent\",\"registry\":\"ZEC:testnet\"}", "{}"].getD i (""))
def methods17 : Nat → List VerificationMethod := (fun i => [[⟨0, 2⟩], [⟨0, 3⟩, ⟨1, 2⟩], [], [], []].getD i ([]))
def documents17 : Nat → Nat := (fun i => [0, 1].getD i (4))
def graph17 : DocumentGraph := {
  size := 2
  root := 0
  initialDocument := 0
  parent := (fun i => [none, some 0].getD i (none))
  depth := (fun i => [0, 1].getD i (0))
  action := (fun i => [AgentAction.keep, AgentAction.rotate 1].getD i (AgentAction.keep))
  documents := (fun i => [[⟨0, 2⟩], [⟨0, 3⟩, ⟨1, 2⟩]].getD i ([]))
  named := (fun i => [0, 0].getD i (0))
  signatureValid := fun i k => ((fun i => [[false, false, true, false], [false, false, true, false]].getD i ([]))) i |>.getD k false
}
theorem methods_agree17 : ∀ i, methods17 (documents17 i) = graph17.documents i := by
  intro i
  cases i with
  | zero => rfl
  | succ i =>
    cases i with
    | zero => rfl
    | succ i =>
      rfl
theorem ordered17 : AncestryOrdered (documentAgent graph17) := by
  intro i p parent
  by_cases bound : i < 2
  · have cases : i = 0 ∨ i = 1 := by omega
    rcases cases with rfl | rfl <;> simp [documentAgent, graph17] at parent
    all_goals subst p; decide
  · have outside : 2 ≤ i := by omega
    simp only [documentAgent, graph17] at parent
    rw [List.getD_eq_getElem?_getD, List.getElem?_eq_none (by simpa using outside)] at parent
    simp at parent
theorem bounded17 : DepthBounded (documentAgent graph17) := by
  intro i bound
  have small : i < 2 := bound
  have checked : ∀ i : Fin 2, (documentAgent graph17).depth i.val < (documentAgent graph17).size := by decide
  exact checked ⟨i, small⟩
theorem parents17 : AgentParentBounded graph17 := by
  intro i p bound parent
  have small : i < 2 := bound
  have cases : i = 0 ∨ i = 1 := by omega
  rcases cases with rfl | rfl <;> simp [graph17] at parent
  all_goals subst p; decide
def patch17 : Nat → ComponentPatch Nat Nat := (fun i => [⟨none, none⟩, ⟨none, none⟩].getD i (⟨none, none⟩))
def registry17 : Nat → Nat := (fun i => [6, 6, 6, 2, 6].getD i (6))
def receipts17 : RegistryReceipts := {
  size := 2
  owner := (fun i => [0, 1].getD i (2))
  registry := (fun i => [2, 2].getD i (6))
  chain := (fun i => [true, true, true, false, false, false].getD i (false))
  accepted := fun _ => true
}
abbrev anchors17 := componentAnchors graph17 patch17 registry17 3 receipts17
abbrev model17 := componentEvents graph17 anchors17
def positions17 : Nat → List Nat := (fun i => [[1, 1, 0], [45, 0, 0]].getD i ([]))
theorem ranks17 : RegistryCidRanks (componentRegistry graph17 patch17 registry17 3) receipts17 positions17 := by
  intro x y xv yv same
  have xb : x < 2 := eligible_lt _ _ _ xv
  have yb : y < 2 := eligible_lt _ _ _ yv
  have checked : ∀ x y : Fin 2,
      eligible (registryAnchors (componentRegistry graph17 patch17 registry17 3) receipts17) (receipts17.owner x.val) x.val = true →
      eligible (registryAnchors (componentRegistry graph17 patch17 registry17 3) receipts17) (receipts17.owner y.val) y.val = true →
      receipts17.registry x.val = receipts17.registry y.val →
      (x.val < y.val ↔ compare (positions17 x.val) (positions17 y.val) = .lt ∨
        (compare (positions17 x.val) (positions17 y.val) = .eq ∧ receipts17.owner x.val < receipts17.owner y.val)) := by decide
  exact checked ⟨x, xb⟩ ⟨y, yb⟩ xv yv same
def operationTime17 : Nat → Int := (fun i => [1788998460000, 1789001100000].getD i (0))
def chainFacts17 : Nat → ChainReceiptView := (fun i => [⟨2, [1, 1, 0], 1788998460000, true⟩, ⟨2, [45, 0, 0], 1789001100000, true⟩].getD i (⟨0, [], 0, false⟩))
def atoms18 : Nat → String := (fun i => ["{\"@context\":[\"https://www.w3.org/ns/did/v1\"],\"id\":\"did:cid:bagaaieraqba7t2exnqbyu3tux4hteewttfkii4xak544z2igzf2hkfyigr5q\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaieraqba7t2exnqbyu3tux4hteewttfkii4xak544z2igzf2hkfyigr5q\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"azJ09248a2vKqs80FWCLG3Xw5xc9UF4sd_DImBsaxDw\",\"y\":\"215hdHiCRD7Q-DyAt5zcT4YLjdXFhm6y8bAbbia4Ne4\"}}],\"authentication\":[\"#key-1\"],\"assertionMethod\":[\"#key-1\"],\"capabilityInvocation\":[\"#key-1\"]}", "{\"id\":\"did:cid:bagaaieraqba7t2exnqbyu3tux4hteewttfkii4xak544z2igzf2hkfyigr5q\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaieraqba7t2exnqbyu3tux4hteewttfkii4xak544z2igzf2hkfyigr5q\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"7c8q6jrR_99AQxXwI0id7tkVCZwTRPf9g4S1Y329QGk\",\"y\":\"8by6qVswtkb9OzuzZqAMBsVV-9Nh4Oci2VAxcqKFaQY\"}}]}", "{\"id\":\"did:cid:bagaaieraqba7t2exnqbyu3tux4hteewttfkii4xak544z2igzf2hkfyigr5q\"}", "{\"version\":1,\"type\":\"agent\",\"registry\":\"local\"}", "{}"].getD i (""))
def methods18 : Nat → List VerificationMethod := (fun i => [[⟨0, 0⟩], [⟨0, 1⟩], [], [], []].getD i ([]))
def documents18 : Nat → Nat := (fun i => [1, 4, 0].getD i (4))
def graph18 : DocumentGraph := {
  size := 3
  root := 2
  initialDocument := 2
  parent := (fun i => [some 2, some 0, none].getD i (none))
  depth := (fun i => [1, 2, 0].getD i (0))
  action := (fun i => [AgentAction.rotate 0, AgentAction.deactivate, AgentAction.keep].getD i (AgentAction.keep))
  documents := (fun i => [[⟨0, 1⟩], [], [⟨0, 0⟩]].getD i ([]))
  named := (fun i => [0, 0, 0].getD i (0))
  signatureValid := fun i k => ((fun i => [[true, false, false, false], [false, true, false, false], [true, false, false, false]].getD i ([]))) i |>.getD k false
}
theorem methods_agree18 : ∀ i, methods18 (documents18 i) = graph18.documents i := by
  intro i
  cases i with
  | zero => rfl
  | succ i =>
    cases i with
    | zero => rfl
    | succ i =>
      cases i with
      | zero => rfl
      | succ i =>
        rfl
theorem ordered18 : AncestryOrdered (documentAgent graph18) := by
  intro i p parent
  by_cases bound : i < 3
  · have cases : i = 0 ∨ i = 1 ∨ i = 2 := by omega
    rcases cases with rfl | rfl | rfl <;> simp [documentAgent, graph18] at parent
    all_goals subst p; decide
  · have outside : 3 ≤ i := by omega
    simp only [documentAgent, graph18] at parent
    rw [List.getD_eq_getElem?_getD, List.getElem?_eq_none (by simpa using outside)] at parent
    simp at parent
theorem bounded18 : DepthBounded (documentAgent graph18) := by
  intro i bound
  have small : i < 3 := bound
  have checked : ∀ i : Fin 3, (documentAgent graph18).depth i.val < (documentAgent graph18).size := by decide
  exact checked ⟨i, small⟩
theorem parents18 : AgentParentBounded graph18 := by
  intro i p bound parent
  have small : i < 3 := bound
  have cases : i = 0 ∨ i = 1 ∨ i = 2 := by omega
  rcases cases with rfl | rfl | rfl <;> simp [graph18] at parent
  all_goals subst p; decide
def patch18 : Nat → ComponentPatch Nat Nat := (fun i => [⟨none, none⟩, ⟨none, none⟩, ⟨none, none⟩].getD i (⟨none, none⟩))
def registry18 : Nat → Nat := (fun i => [6, 6, 6, 4, 6].getD i (6))
def receipts18 : RegistryReceipts := {
  size := 0
  owner := (fun i => [].getD i (3))
  registry := (fun i => [].getD i (6))
  chain := (fun i => [true, true, true, false, false, false].getD i (false))
  accepted := fun _ => true
}
abbrev anchors18 := componentAnchors graph18 patch18 registry18 3 receipts18
abbrev model18 := componentEvents graph18 anchors18
def positions18 : Nat → List Nat := (fun i => [].getD i ([]))
theorem ranks18 : RegistryCidRanks (componentRegistry graph18 patch18 registry18 3) receipts18 positions18 := by
  intro x y xv yv same
  have xb : x < 0 := eligible_lt _ _ _ xv
  have yb : y < 0 := eligible_lt _ _ _ yv
  have checked : ∀ x y : Fin 0,
      eligible (registryAnchors (componentRegistry graph18 patch18 registry18 3) receipts18) (receipts18.owner x.val) x.val = true →
      eligible (registryAnchors (componentRegistry graph18 patch18 registry18 3) receipts18) (receipts18.owner y.val) y.val = true →
      receipts18.registry x.val = receipts18.registry y.val →
      (x.val < y.val ↔ compare (positions18 x.val) (positions18 y.val) = .lt ∨
        (compare (positions18 x.val) (positions18 y.val) = .eq ∧ receipts18.owner x.val < receipts18.owner y.val)) := by decide
  exact checked ⟨x, xb⟩ ⟨y, yb⟩ xv yv same
def operationTime18 : Nat → Int := (fun i => [1788999600000, 1788999900000, 1788998460000].getD i (0))
def chainFacts18 : Nat → ChainReceiptView := (fun i => [].getD i (⟨0, [], 0, false⟩))
def atoms19 : Nat → String := (fun i => ["{\"@context\":[\"https://www.w3.org/ns/did/v1\"],\"id\":\"did:cid:bagaaierajlnepjtoweq2u53vl3ytk2wutkjjwtshujrd4lq2l3n7ubyfvd7q\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaierajlnepjtoweq2u53vl3ytk2wutkjjwtshujrd4lq2l3n7ubyfvd7q\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"MAemGeO4kBa-f3jOK_Hb21lXKC6jN4jeuIuyMumLmlA\",\"y\":\"iWcPPQGrI3j02b0_ocPHCHj6OptQ9kGWskmn6StCooo\"}}],\"authentication\":[\"#key-1\"],\"assertionMethod\":[\"#key-1\"],\"capabilityInvocation\":[\"#key-1\"]}", "{\"id\":\"did:cid:bagaaierajlnepjtoweq2u53vl3ytk2wutkjjwtshujrd4lq2l3n7ubyfvd7q\",\"verificationMethod\":[{\"id\":\"#key-1\",\"controller\":\"did:cid:bagaaierajlnepjtoweq2u53vl3ytk2wutkjjwtshujrd4lq2l3n7ubyfvd7q\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"uVwknYT0F-PjlaEnQlQotUBnHMFYgeuCjBe3IqU_xZk\",\"y\":\"4hyl5WyQ80CYjTkzrMdr64Mv1kyrB43fPOcykjAx0ag\"}},{\"id\":\"#key-2\",\"controller\":\"did:cid:bagaaierajlnepjtoweq2u53vl3ytk2wutkjjwtshujrd4lq2l3n7ubyfvd7q\",\"type\":\"EcdsaSecp256k1VerificationKey2019\",\"publicKeyJwk\":{\"kty\":\"EC\",\"crv\":\"secp256k1\",\"x\":\"MAemGeO4kBa-f3jOK_Hb21lXKC6jN4jeuIuyMumLmlA\",\"y\":\"iWcPPQGrI3j02b0_ocPHCHj6OptQ9kGWskmn6StCooo\"}}]}", "{\"id\":\"did:cid:bagaaierajlnepjtoweq2u53vl3ytk2wutkjjwtshujrd4lq2l3n7ubyfvd7q\"}", "{\"version\":1,\"type\":\"agent\",\"registry\":\"local\"}", "{}"].getD i (""))
def methods19 : Nat → List VerificationMethod := (fun i => [[⟨0, 2⟩], [⟨0, 3⟩, ⟨1, 2⟩], [], [], []].getD i ([]))
def documents19 : Nat → Nat := (fun i => [1, 0].getD i (4))
def graph19 : DocumentGraph := {
  size := 2
  root := 1
  initialDocument := 1
  parent := (fun i => [some 1, none].getD i (none))
  depth := (fun i => [1, 0].getD i (0))
  action := (fun i => [AgentAction.rotate 0, AgentAction.keep].getD i (AgentAction.keep))
  documents := (fun i => [[⟨0, 3⟩, ⟨1, 2⟩], [⟨0, 2⟩]].getD i ([]))
  named := (fun i => [0, 0].getD i (0))
  signatureValid := fun i k => ((fun i => [[false, false, true, false], [false, false, true, false]].getD i ([]))) i |>.getD k false
}
theorem methods_agree19 : ∀ i, methods19 (documents19 i) = graph19.documents i := by
  intro i
  cases i with
  | zero => rfl
  | succ i =>
    cases i with
    | zero => rfl
    | succ i =>
      rfl
theorem ordered19 : AncestryOrdered (documentAgent graph19) := by
  intro i p parent
  by_cases bound : i < 2
  · have cases : i = 0 ∨ i = 1 := by omega
    rcases cases with rfl | rfl <;> simp [documentAgent, graph19] at parent
    all_goals subst p; decide
  · have outside : 2 ≤ i := by omega
    simp only [documentAgent, graph19] at parent
    rw [List.getD_eq_getElem?_getD, List.getElem?_eq_none (by simpa using outside)] at parent
    simp at parent
theorem bounded19 : DepthBounded (documentAgent graph19) := by
  intro i bound
  have small : i < 2 := bound
  have checked : ∀ i : Fin 2, (documentAgent graph19).depth i.val < (documentAgent graph19).size := by decide
  exact checked ⟨i, small⟩
theorem parents19 : AgentParentBounded graph19 := by
  intro i p bound parent
  have small : i < 2 := bound
  have cases : i = 0 ∨ i = 1 := by omega
  rcases cases with rfl | rfl <;> simp [graph19] at parent
  all_goals subst p; decide
def patch19 : Nat → ComponentPatch Nat Nat := (fun i => [⟨none, none⟩, ⟨none, none⟩].getD i (⟨none, none⟩))
def registry19 : Nat → Nat := (fun i => [6, 6, 6, 4, 6].getD i (6))
def receipts19 : RegistryReceipts := {
  size := 0
  owner := (fun i => [].getD i (2))
  registry := (fun i => [].getD i (6))
  chain := (fun i => [true, true, true, false, false, false].getD i (false))
  accepted := fun _ => true
}
abbrev anchors19 := componentAnchors graph19 patch19 registry19 3 receipts19
abbrev model19 := componentEvents graph19 anchors19
def positions19 : Nat → List Nat := (fun i => [].getD i ([]))
theorem ranks19 : RegistryCidRanks (componentRegistry graph19 patch19 registry19 3) receipts19 positions19 := by
  intro x y xv yv same
  have xb : x < 0 := eligible_lt _ _ _ xv
  have yb : y < 0 := eligible_lt _ _ _ yv
  have checked : ∀ x y : Fin 0,
      eligible (registryAnchors (componentRegistry graph19 patch19 registry19 3) receipts19) (receipts19.owner x.val) x.val = true →
      eligible (registryAnchors (componentRegistry graph19 patch19 registry19 3) receipts19) (receipts19.owner y.val) y.val = true →
      receipts19.registry x.val = receipts19.registry y.val →
      (x.val < y.val ↔ compare (positions19 x.val) (positions19 y.val) = .lt ∨
        (compare (positions19 x.val) (positions19 y.val) = .eq ∧ receipts19.owner x.val < receipts19.owner y.val)) := by decide
  exact checked ⟨x, xb⟩ ⟨y, yb⟩ xv yv same
def operationTime19 : Nat → Int := (fun i => [1789001100000, 1788998460000].getD i (0))
def chainFacts19 : Nat → ChainReceiptView := (fun i => [].getD i (⟨0, [], 0, false⟩))
end Archon.AssetControllerFixtures
