-- Generated by generate-chain-successor-fixtures.mjs; do not edit.
import ChainSuccessors
set_option warningAsError true
namespace Archon.ChainSuccessorFixtures
def ops0 : Model := ⟨5, (fun i => [some 2, none, some 1, some 1, some 3].getD i (none)), fun _ => true, (fun i => [0, 2, 1, 1, 0].getD i (0))⟩
def anchors0 : AnchorModel := ⟨1, (fun i => [some 1].getD i (none)), fun _ => true, fun _ => 0⟩
abbrev graph0 := chainGraph ops0 anchors0 [0]
theorem acyclic0 : WellFoundedEdges graph0 := by
  intro p i h
  have bound : i < 6 := eligible_lt _ _ _ h
  have cases : i = 0 ∨ i = 1 ∨ i = 2 ∨ i = 3 ∨ i = 4 ∨ i = 5 := by omega
  rcases cases with rfl | rfl | rfl | rfl | rfl | rfl <;> simp [eligible, graph0, chainGraph, ops0, anchors0, chainOwner, chainPriority, anchorScan, anchorStep, List.foldl] at h
  all_goals subst p; decide
theorem settled0 : chainReplay ops0 anchors0 [0] 1 [0, 1, 2, 3, 4] = some [1, 2, 0] := by
  rw [chain_replay_converges ops0 anchors0 [0] 1 [0, 1, 2, 3, 4] acyclic0 (by decide) (by decide)]
  decide
example : chainReplay ops0 anchors0 [0] 1 [1, 2, 3, 0, 4, 1] = some [1, 2, 0] := by
  rw [← chain_successors_same_evidence ops0 anchors0 [0] [0] [0, 1, 2, 3, 4] [1, 2, 3, 0, 4, 1] 1 (bounded_membership_agrees 1 _ _ (by decide) (by decide) (by decide)) (bounded_membership_agrees 5 _ _ (by decide) (by decide) (by decide)) acyclic0 (by decide) (by decide)]
  exact settled0
example : chainReplay ops0 anchors0 [0] 1 [1, 4, 0, 3, 2, 1] = some [1, 2, 0] := by
  rw [← chain_successors_same_evidence ops0 anchors0 [0] [0] [0, 1, 2, 3, 4] [1, 4, 0, 3, 2, 1] 1 (bounded_membership_agrees 1 _ _ (by decide) (by decide) (by decide)) (bounded_membership_agrees 5 _ _ (by decide) (by decide) (by decide)) acyclic0 (by decide) (by decide)]
  exact settled0
example : chainReplay ops0 anchors0 [0] 1 [4, 0, 3, 2, 1, 1] = some [1, 2, 0] := by
  rw [← chain_successors_same_evidence ops0 anchors0 [0] [0] [0, 1, 2, 3, 4] [4, 0, 3, 2, 1, 1] 1 (bounded_membership_agrees 1 _ _ (by decide) (by decide) (by decide)) (bounded_membership_agrees 5 _ _ (by decide) (by decide) (by decide)) acyclic0 (by decide) (by decide)]
  exact settled0
example : chainReplay ops0 anchors0 [0] 1 [1, 0, 2, 4, 3, 1] = some [1, 2, 0] := by
  rw [← chain_successors_same_evidence ops0 anchors0 [0] [0] [0, 1, 2, 3, 4] [1, 0, 2, 4, 3, 1] 1 (bounded_membership_agrees 1 _ _ (by decide) (by decide) (by decide)) (bounded_membership_agrees 5 _ _ (by decide) (by decide) (by decide)) acyclic0 (by decide) (by decide)]
  exact settled0
example : chainReplay ops0 anchors0 [0] 1 [3, 4, 1, 2, 0, 1] = some [1, 2, 0] := by
  rw [← chain_successors_same_evidence ops0 anchors0 [0] [0] [0, 1, 2, 3, 4] [3, 4, 1, 2, 0, 1] 1 (bounded_membership_agrees 1 _ _ (by decide) (by decide) (by decide)) (bounded_membership_agrees 5 _ _ (by decide) (by decide) (by decide)) acyclic0 (by decide) (by decide)]
  exact settled0
example : chainReplay ops0 anchors0 [0] 1 [2, 0, 1, 3, 4, 1] = some [1, 2, 0] := by
  rw [← chain_successors_same_evidence ops0 anchors0 [0] [0] [0, 1, 2, 3, 4] [2, 0, 1, 3, 4, 1] 1 (bounded_membership_agrees 1 _ _ (by decide) (by decide) (by decide)) (bounded_membership_agrees 5 _ _ (by decide) (by decide) (by decide)) acyclic0 (by decide) (by decide)]
  exact settled0
def ops1 : Model := ⟨5, (fun i => [some 2, none, some 1, some 1, some 3].getD i (none)), fun _ => true, (fun i => [0, 2, 1, 1, 0].getD i (0))⟩
def anchors1 : AnchorModel := ⟨3, (fun i => [some 3, some 1, some 2].getD i (none)), fun _ => true, fun _ => 0⟩
abbrev graph1 := chainGraph ops1 anchors1 [0, 1, 2]
theorem acyclic1 : WellFoundedEdges graph1 := by
  intro p i h
  have bound : i < 8 := eligible_lt _ _ _ h
  have cases : i = 0 ∨ i = 1 ∨ i = 2 ∨ i = 3 ∨ i = 4 ∨ i = 5 ∨ i = 6 ∨ i = 7 := by omega
  rcases cases with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl <;> simp [eligible, graph1, chainGraph, ops1, anchors1, chainOwner, chainPriority, anchorScan, anchorStep, List.foldl] at h
  all_goals subst p; decide
theorem settled1 : chainReplay ops1 anchors1 [0, 1, 2] 1 [0, 1, 2, 3, 4] = some [1, 3, 4] := by
  rw [chain_replay_converges ops1 anchors1 [0, 1, 2] 1 [0, 1, 2, 3, 4] acyclic1 (by decide) (by decide)]
  decide
example : chainReplay ops1 anchors1 [1, 2, 0] 1 [1, 2, 3, 0, 4, 1, 2, 3] = some [1, 3, 4] := by
  rw [← chain_successors_same_evidence ops1 anchors1 [0, 1, 2] [1, 2, 0] [0, 1, 2, 3, 4] [1, 2, 3, 0, 4, 1, 2, 3] 1 (bounded_membership_agrees 3 _ _ (by decide) (by decide) (by decide)) (bounded_membership_agrees 5 _ _ (by decide) (by decide) (by decide)) acyclic1 (by decide) (by decide)]
  exact settled1
example : chainReplay ops1 anchors1 [0, 2, 1] 1 [3, 2, 1, 4, 0, 3, 2, 1] = some [1, 3, 4] := by
  rw [← chain_successors_same_evidence ops1 anchors1 [0, 1, 2] [0, 2, 1] [0, 1, 2, 3, 4] [3, 2, 1, 4, 0, 3, 2, 1] 1 (bounded_membership_agrees 3 _ _ (by decide) (by decide) (by decide)) (bounded_membership_agrees 5 _ _ (by decide) (by decide) (by decide)) acyclic1 (by decide) (by decide)]
  exact settled1
example : chainReplay ops1 anchors1 [1, 2, 0] 1 [4, 0, 3, 2, 1, 1, 2, 3] = some [1, 3, 4] := by
  rw [← chain_successors_same_evidence ops1 anchors1 [0, 1, 2] [1, 2, 0] [0, 1, 2, 3, 4] [4, 0, 3, 2, 1, 1, 2, 3] 1 (bounded_membership_agrees 3 _ _ (by decide) (by decide) (by decide)) (bounded_membership_agrees 5 _ _ (by decide) (by decide) (by decide)) acyclic1 (by decide) (by decide)]
  exact settled1
example : chainReplay ops1 anchors1 [1, 2, 0] 1 [1, 2, 3, 0, 2, 4, 3, 1] = some [1, 3, 4] := by
  rw [← chain_successors_same_evidence ops1 anchors1 [0, 1, 2] [1, 2, 0] [0, 1, 2, 3, 4] [1, 2, 3, 0, 2, 4, 3, 1] 1 (bounded_membership_agrees 3 _ _ (by decide) (by decide) (by decide)) (bounded_membership_agrees 5 _ _ (by decide) (by decide) (by decide)) acyclic1 (by decide) (by decide)]
  exact settled1
example : chainReplay ops1 anchors1 [0, 2, 1] 1 [3, 4, 1, 2, 0, 3, 2, 1] = some [1, 3, 4] := by
  rw [← chain_successors_same_evidence ops1 anchors1 [0, 1, 2] [0, 2, 1] [0, 1, 2, 3, 4] [3, 4, 1, 2, 0, 3, 2, 1] 1 (bounded_membership_agrees 3 _ _ (by decide) (by decide) (by decide)) (bounded_membership_agrees 5 _ _ (by decide) (by decide) (by decide)) acyclic1 (by decide) (by decide)]
  exact settled1
example : chainReplay ops1 anchors1 [1, 2, 0] 1 [2, 0, 1, 3, 4, 1, 2, 3] = some [1, 3, 4] := by
  rw [← chain_successors_same_evidence ops1 anchors1 [0, 1, 2] [1, 2, 0] [0, 1, 2, 3, 4] [2, 0, 1, 3, 4, 1, 2, 3] 1 (bounded_membership_agrees 3 _ _ (by decide) (by decide) (by decide)) (bounded_membership_agrees 5 _ _ (by decide) (by decide) (by decide)) acyclic1 (by decide) (by decide)]
  exact settled1
def ops2 : Model := ⟨5, (fun i => [some 2, none, some 1, some 1, some 3].getD i (none)), fun _ => true, (fun i => [0, 2, 1, 1, 0].getD i (0))⟩
def anchors2 : AnchorModel := ⟨4, (fun i => [some 2, some 3, some 1, some 2].getD i (none)), fun _ => true, fun _ => 0⟩
abbrev graph2 := chainGraph ops2 anchors2 [0, 1, 2, 3]
theorem acyclic2 : WellFoundedEdges graph2 := by
  intro p i h
  have bound : i < 9 := eligible_lt _ _ _ h
  have cases : i = 0 ∨ i = 1 ∨ i = 2 ∨ i = 3 ∨ i = 4 ∨ i = 5 ∨ i = 6 ∨ i = 7 ∨ i = 8 := by omega
  rcases cases with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl <;> simp [eligible, graph2, chainGraph, ops2, anchors2, chainOwner, chainPriority, anchorScan, anchorStep, List.foldl] at h
  all_goals subst p; decide
theorem settled2 : chainReplay ops2 anchors2 [0, 1, 2, 3] 1 [0, 1, 2, 3, 4] = some [1, 2, 0] := by
  rw [chain_replay_converges ops2 anchors2 [0, 1, 2, 3] 1 [0, 1, 2, 3, 4] acyclic2 (by decide) (by decide)]
  decide
example : chainReplay ops2 anchors2 [2, 3, 1, 0] 1 [1, 2, 3, 0, 4, 1, 2, 3, 2] = some [1, 2, 0] := by
  rw [← chain_successors_same_evidence ops2 anchors2 [0, 1, 2, 3] [2, 3, 1, 0] [0, 1, 2, 3, 4] [1, 2, 3, 0, 4, 1, 2, 3, 2] 1 (bounded_membership_agrees 4 _ _ (by decide) (by decide) (by decide)) (bounded_membership_agrees 5 _ _ (by decide) (by decide) (by decide)) acyclic2 (by decide) (by decide)]
  exact settled2
example : chainReplay ops2 anchors2 [0, 1, 3, 2] 1 [2, 3, 2, 1, 4, 0, 3, 2, 1] = some [1, 2, 0] := by
  rw [← chain_successors_same_evidence ops2 anchors2 [0, 1, 2, 3] [0, 1, 3, 2] [0, 1, 2, 3, 4] [2, 3, 2, 1, 4, 0, 3, 2, 1] 1 (bounded_membership_agrees 4 _ _ (by decide) (by decide) (by decide)) (bounded_membership_agrees 5 _ _ (by decide) (by decide) (by decide)) acyclic2 (by decide) (by decide)]
  exact settled2
example : chainReplay ops2 anchors2 [2, 3, 1, 0] 1 [4, 0, 3, 2, 1, 1, 2, 3, 2] = some [1, 2, 0] := by
  rw [← chain_successors_same_evidence ops2 anchors2 [0, 1, 2, 3] [2, 3, 1, 0] [0, 1, 2, 3, 4] [4, 0, 3, 2, 1, 1, 2, 3, 2] 1 (bounded_membership_agrees 4 _ _ (by decide) (by decide) (by decide)) (bounded_membership_agrees 5 _ _ (by decide) (by decide) (by decide)) acyclic2 (by decide) (by decide)]
  exact settled2
example : chainReplay ops2 anchors2 [2, 3, 1, 0] 1 [1, 2, 3, 2, 0, 2, 4, 3, 1] = some [1, 2, 0] := by
  rw [← chain_successors_same_evidence ops2 anchors2 [0, 1, 2, 3] [2, 3, 1, 0] [0, 1, 2, 3, 4] [1, 2, 3, 2, 0, 2, 4, 3, 1] 1 (bounded_membership_agrees 4 _ _ (by decide) (by decide) (by decide)) (bounded_membership_agrees 5 _ _ (by decide) (by decide) (by decide)) acyclic2 (by decide) (by decide)]
  exact settled2
example : chainReplay ops2 anchors2 [0, 1, 3, 2] 1 [3, 4, 1, 2, 0, 2, 3, 2, 1] = some [1, 2, 0] := by
  rw [← chain_successors_same_evidence ops2 anchors2 [0, 1, 2, 3] [0, 1, 3, 2] [0, 1, 2, 3, 4] [3, 4, 1, 2, 0, 2, 3, 2, 1] 1 (bounded_membership_agrees 4 _ _ (by decide) (by decide) (by decide)) (bounded_membership_agrees 5 _ _ (by decide) (by decide) (by decide)) acyclic2 (by decide) (by decide)]
  exact settled2
example : chainReplay ops2 anchors2 [2, 3, 1, 0] 1 [2, 0, 1, 3, 4, 1, 2, 3, 2] = some [1, 2, 0] := by
  rw [← chain_successors_same_evidence ops2 anchors2 [0, 1, 2, 3] [2, 3, 1, 0] [0, 1, 2, 3, 4] [2, 0, 1, 3, 4, 1, 2, 3, 2] 1 (bounded_membership_agrees 4 _ _ (by decide) (by decide) (by decide)) (bounded_membership_agrees 5 _ _ (by decide) (by decide) (by decide)) acyclic2 (by decide) (by decide)]
  exact settled2
def ops3 : Model := ⟨5, (fun i => [some 1, some 4, some 3, some 4, none].getD i (none)), fun _ => true, (fun i => [0, 1, 0, 1, 2].getD i (0))⟩
def anchors3 : AnchorModel := ⟨1, (fun i => [some 4].getD i (none)), fun _ => true, fun _ => 0⟩
abbrev graph3 := chainGraph ops3 anchors3 [0]
theorem acyclic3 : WellFoundedEdges graph3 := by
  intro p i h
  have bound : i < 6 := eligible_lt _ _ _ h
  have cases : i = 0 ∨ i = 1 ∨ i = 2 ∨ i = 3 ∨ i = 4 ∨ i = 5 := by omega
  rcases cases with rfl | rfl | rfl | rfl | rfl | rfl <;> simp [eligible, graph3, chainGraph, ops3, anchors3, chainOwner, chainPriority, anchorScan, anchorStep, List.foldl] at h
  all_goals subst p; decide
theorem settled3 : chainReplay ops3 anchors3 [0] 4 [0, 1, 2, 3, 4] = some [4, 1, 0] := by
  rw [chain_replay_converges ops3 anchors3 [0] 4 [0, 1, 2, 3, 4] acyclic3 (by decide) (by decide)]
  decide
example : chainReplay ops3 anchors3 [0] 4 [4, 1, 3, 0, 2, 4] = some [4, 1, 0] := by
  rw [← chain_successors_same_evidence ops3 anchors3 [0] [0] [0, 1, 2, 3, 4] [4, 1, 3, 0, 2, 4] 4 (bounded_membership_agrees 1 _ _ (by decide) (by decide) (by decide)) (bounded_membership_agrees 5 _ _ (by decide) (by decide) (by decide)) acyclic3 (by decide) (by decide)]
  exact settled3
example : chainReplay ops3 anchors3 [0] 4 [4, 2, 0, 3, 1, 4] = some [4, 1, 0] := by
  rw [← chain_successors_same_evidence ops3 anchors3 [0] [0] [0, 1, 2, 3, 4] [4, 2, 0, 3, 1, 4] 4 (bounded_membership_agrees 1 _ _ (by decide) (by decide) (by decide)) (bounded_membership_agrees 5 _ _ (by decide) (by decide) (by decide)) acyclic3 (by decide) (by decide)]
  exact settled3
example : chainReplay ops3 anchors3 [0] 4 [2, 0, 3, 1, 4, 4] = some [4, 1, 0] := by
  rw [← chain_successors_same_evidence ops3 anchors3 [0] [0] [0, 1, 2, 3, 4] [2, 0, 3, 1, 4, 4] 4 (bounded_membership_agrees 1 _ _ (by decide) (by decide) (by decide)) (bounded_membership_agrees 5 _ _ (by decide) (by decide) (by decide)) acyclic3 (by decide) (by decide)]
  exact settled3
example : chainReplay ops3 anchors3 [0] 4 [4, 0, 1, 2, 3, 4] = some [4, 1, 0] := by
  rw [← chain_successors_same_evidence ops3 anchors3 [0] [0] [0, 1, 2, 3, 4] [4, 0, 1, 2, 3, 4] 4 (bounded_membership_agrees 1 _ _ (by decide) (by decide) (by decide)) (bounded_membership_agrees 5 _ _ (by decide) (by decide) (by decide)) acyclic3 (by decide) (by decide)]
  exact settled3
example : chainReplay ops3 anchors3 [0] 4 [3, 2, 4, 1, 0, 4] = some [4, 1, 0] := by
  rw [← chain_successors_same_evidence ops3 anchors3 [0] [0] [0, 1, 2, 3, 4] [3, 2, 4, 1, 0, 4] 4 (bounded_membership_agrees 1 _ _ (by decide) (by decide) (by decide)) (bounded_membership_agrees 5 _ _ (by decide) (by decide) (by decide)) acyclic3 (by decide) (by decide)]
  exact settled3
example : chainReplay ops3 anchors3 [0] 4 [1, 0, 4, 3, 2, 4] = some [4, 1, 0] := by
  rw [← chain_successors_same_evidence ops3 anchors3 [0] [0] [0, 1, 2, 3, 4] [1, 0, 4, 3, 2, 4] 4 (bounded_membership_agrees 1 _ _ (by decide) (by decide) (by decide)) (bounded_membership_agrees 5 _ _ (by decide) (by decide) (by decide)) acyclic3 (by decide) (by decide)]
  exact settled3
def ops4 : Model := ⟨5, (fun i => [some 1, some 4, some 3, some 4, none].getD i (none)), fun _ => true, (fun i => [0, 1, 0, 1, 2].getD i (0))⟩
def anchors4 : AnchorModel := ⟨3, (fun i => [some 3, some 4, some 1].getD i (none)), fun _ => true, fun _ => 0⟩
abbrev graph4 := chainGraph ops4 anchors4 [0, 1, 2]
theorem acyclic4 : WellFoundedEdges graph4 := by
  intro p i h
  have bound : i < 8 := eligible_lt _ _ _ h
  have cases : i = 0 ∨ i = 1 ∨ i = 2 ∨ i = 3 ∨ i = 4 ∨ i = 5 ∨ i = 6 ∨ i = 7 := by omega
  rcases cases with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl <;> simp [eligible, graph4, chainGraph, ops4, anchors4, chainOwner, chainPriority, anchorScan, anchorStep, List.foldl] at h
  all_goals subst p; decide
theorem settled4 : chainReplay ops4 anchors4 [0, 1, 2] 4 [0, 1, 2, 3, 4] = some [4, 3, 2] := by
  rw [chain_replay_converges ops4 anchors4 [0, 1, 2] 4 [0, 1, 2, 3, 4] acyclic4 (by decide) (by decide)]
  decide
example : chainReplay ops4 anchors4 [1, 2, 0] 4 [4, 1, 3, 0, 2, 4, 1, 3] = some [4, 3, 2] := by
  rw [← chain_successors_same_evidence ops4 anchors4 [0, 1, 2] [1, 2, 0] [0, 1, 2, 3, 4] [4, 1, 3, 0, 2, 4, 1, 3] 4 (bounded_membership_agrees 3 _ _ (by decide) (by decide) (by decide)) (bounded_membership_agrees 5 _ _ (by decide) (by decide) (by decide)) acyclic4 (by decide) (by decide)]
  exact settled4
example : chainReplay ops4 anchors4 [0, 2, 1] 4 [3, 1, 4, 2, 0, 3, 1, 4] = some [4, 3, 2] := by
  rw [← chain_successors_same_evidence ops4 anchors4 [0, 1, 2] [0, 2, 1] [0, 1, 2, 3, 4] [3, 1, 4, 2, 0, 3, 1, 4] 4 (bounded_membership_agrees 3 _ _ (by decide) (by decide) (by decide)) (bounded_membership_agrees 5 _ _ (by decide) (by decide) (by decide)) acyclic4 (by decide) (by decide)]
  exact settled4
example : chainReplay ops4 anchors4 [1, 2, 0] 4 [2, 0, 3, 1, 4, 4, 1, 3] = some [4, 3, 2] := by
  rw [← chain_successors_same_evidence ops4 anchors4 [0, 1, 2] [1, 2, 0] [0, 1, 2, 3, 4] [2, 0, 3, 1, 4, 4, 1, 3] 4 (bounded_membership_agrees 3 _ _ (by decide) (by decide) (by decide)) (bounded_membership_agrees 5 _ _ (by decide) (by decide) (by decide)) acyclic4 (by decide) (by decide)]
  exact settled4
example : chainReplay ops4 anchors4 [1, 2, 0] 4 [4, 1, 3, 0, 1, 2, 3, 4] = some [4, 3, 2] := by
  rw [← chain_successors_same_evidence ops4 anchors4 [0, 1, 2] [1, 2, 0] [0, 1, 2, 3, 4] [4, 1, 3, 0, 1, 2, 3, 4] 4 (bounded_membership_agrees 3 _ _ (by decide) (by decide) (by decide)) (bounded_membership_agrees 5 _ _ (by decide) (by decide) (by decide)) acyclic4 (by decide) (by decide)]
  exact settled4
example : chainReplay ops4 anchors4 [0, 2, 1] 4 [3, 2, 4, 1, 0, 3, 1, 4] = some [4, 3, 2] := by
  rw [← chain_successors_same_evidence ops4 anchors4 [0, 1, 2] [0, 2, 1] [0, 1, 2, 3, 4] [3, 2, 4, 1, 0, 3, 1, 4] 4 (bounded_membership_agrees 3 _ _ (by decide) (by decide) (by decide)) (bounded_membership_agrees 5 _ _ (by decide) (by decide) (by decide)) acyclic4 (by decide) (by decide)]
  exact settled4
example : chainReplay ops4 anchors4 [1, 2, 0] 4 [1, 0, 4, 3, 2, 4, 1, 3] = some [4, 3, 2] := by
  rw [← chain_successors_same_evidence ops4 anchors4 [0, 1, 2] [1, 2, 0] [0, 1, 2, 3, 4] [1, 0, 4, 3, 2, 4, 1, 3] 4 (bounded_membership_agrees 3 _ _ (by decide) (by decide) (by decide)) (bounded_membership_agrees 5 _ _ (by decide) (by decide) (by decide)) acyclic4 (by decide) (by decide)]
  exact settled4
def ops5 : Model := ⟨5, (fun i => [some 1, some 4, some 3, some 4, none].getD i (none)), fun _ => true, (fun i => [0, 1, 0, 1, 2].getD i (0))⟩
def anchors5 : AnchorModel := ⟨4, (fun i => [some 1, some 3, some 4, some 1].getD i (none)), fun _ => true, fun _ => 0⟩
abbrev graph5 := chainGraph ops5 anchors5 [0, 1, 2, 3]
theorem acyclic5 : WellFoundedEdges graph5 := by
  intro p i h
  have bound : i < 9 := eligible_lt _ _ _ h
  have cases : i = 0 ∨ i = 1 ∨ i = 2 ∨ i = 3 ∨ i = 4 ∨ i = 5 ∨ i = 6 ∨ i = 7 ∨ i = 8 := by omega
  rcases cases with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl <;> simp [eligible, graph5, chainGraph, ops5, anchors5, chainOwner, chainPriority, anchorScan, anchorStep, List.foldl] at h
  all_goals subst p; decide
theorem settled5 : chainReplay ops5 anchors5 [0, 1, 2, 3] 4 [0, 1, 2, 3, 4] = some [4, 1, 0] := by
  rw [chain_replay_converges ops5 anchors5 [0, 1, 2, 3] 4 [0, 1, 2, 3, 4] acyclic5 (by decide) (by decide)]
  decide
example : chainReplay ops5 anchors5 [2, 3, 1, 0] 4 [4, 1, 3, 0, 2, 4, 1, 3, 1] = some [4, 1, 0] := by
  rw [← chain_successors_same_evidence ops5 anchors5 [0, 1, 2, 3] [2, 3, 1, 0] [0, 1, 2, 3, 4] [4, 1, 3, 0, 2, 4, 1, 3, 1] 4 (bounded_membership_agrees 4 _ _ (by decide) (by decide) (by decide)) (bounded_membership_agrees 5 _ _ (by decide) (by decide) (by decide)) acyclic5 (by decide) (by decide)]
  exact settled5
example : chainReplay ops5 anchors5 [0, 1, 3, 2] 4 [1, 3, 1, 4, 2, 0, 3, 1, 4] = some [4, 1, 0] := by
  rw [← chain_successors_same_evidence ops5 anchors5 [0, 1, 2, 3] [0, 1, 3, 2] [0, 1, 2, 3, 4] [1, 3, 1, 4, 2, 0, 3, 1, 4] 4 (bounded_membership_agrees 4 _ _ (by decide) (by decide) (by decide)) (bounded_membership_agrees 5 _ _ (by decide) (by decide) (by decide)) acyclic5 (by decide) (by decide)]
  exact settled5
example : chainReplay ops5 anchors5 [2, 3, 1, 0] 4 [2, 0, 3, 1, 4, 4, 1, 3, 1] = some [4, 1, 0] := by
  rw [← chain_successors_same_evidence ops5 anchors5 [0, 1, 2, 3] [2, 3, 1, 0] [0, 1, 2, 3, 4] [2, 0, 3, 1, 4, 4, 1, 3, 1] 4 (bounded_membership_agrees 4 _ _ (by decide) (by decide) (by decide)) (bounded_membership_agrees 5 _ _ (by decide) (by decide) (by decide)) acyclic5 (by decide) (by decide)]
  exact settled5
example : chainReplay ops5 anchors5 [2, 3, 1, 0] 4 [4, 1, 3, 1, 0, 1, 2, 3, 4] = some [4, 1, 0] := by
  rw [← chain_successors_same_evidence ops5 anchors5 [0, 1, 2, 3] [2, 3, 1, 0] [0, 1, 2, 3, 4] [4, 1, 3, 1, 0, 1, 2, 3, 4] 4 (bounded_membership_agrees 4 _ _ (by decide) (by decide) (by decide)) (bounded_membership_agrees 5 _ _ (by decide) (by decide) (by decide)) acyclic5 (by decide) (by decide)]
  exact settled5
example : chainReplay ops5 anchors5 [0, 1, 3, 2] 4 [3, 2, 4, 1, 0, 1, 3, 1, 4] = some [4, 1, 0] := by
  rw [← chain_successors_same_evidence ops5 anchors5 [0, 1, 2, 3] [0, 1, 3, 2] [0, 1, 2, 3, 4] [3, 2, 4, 1, 0, 1, 3, 1, 4] 4 (bounded_membership_agrees 4 _ _ (by decide) (by decide) (by decide)) (bounded_membership_agrees 5 _ _ (by decide) (by decide) (by decide)) acyclic5 (by decide) (by decide)]
  exact settled5
example : chainReplay ops5 anchors5 [2, 3, 1, 0] 4 [1, 0, 4, 3, 2, 4, 1, 3, 1] = some [4, 1, 0] := by
  rw [← chain_successors_same_evidence ops5 anchors5 [0, 1, 2, 3] [2, 3, 1, 0] [0, 1, 2, 3, 4] [1, 0, 4, 3, 2, 4, 1, 3, 1] 4 (bounded_membership_agrees 4 _ _ (by decide) (by decide) (by decide)) (bounded_membership_agrees 5 _ _ (by decide) (by decide) (by decide)) acyclic5 (by decide) (by decide)]
  exact settled5
end Archon.ChainSuccessorFixtures
