-- Generated by generate-chain-anchor-fixtures.mjs; do not edit.
import ChainAnchors

set_option warningAsError true

namespace Archon.ChainAnchorFixtures

-- Rank -> chain ordinal: [[100,10,0],[100,30,0],[100,40,0],[100,50,0]]
def model0 : AnchorModel where
  size := 4
  parent := fun rank => match rank with
    | 0 => some 2
    | 1 => some 0
    | 2 => some 1
    | 3 => some 2
    | _ => none
  authorized := fun _ => true
  level := fun _ => 0

example : anchorScan model0 0 [0, 1, 2, 3] 4 = 1 := by
  change anchorScan model0 0 [0, 1, 2, 3] model0.size = 1
  rw [anchor_scan_cold]
  decide
example : anchorScan model0 0 [0, 1, 2, 3] 1 = 1 := by
  rw [anchor_scan_from_retained model0 0 [0, 1, 2, 3] 1 (by decide) (by decide)]
  decide
example : anchorScan model0 1 [0, 1, 2, 3] 4 = 2 := by
  change anchorScan model0 1 [0, 1, 2, 3] model0.size = 2
  rw [anchor_scan_cold]
  decide
example : anchorScan model0 1 [0, 1, 2, 3] 2 = 2 := by
  rw [anchor_scan_from_retained model0 1 [0, 1, 2, 3] 2 (by decide) (by decide)]
  decide
example : anchorScan model0 2 [0, 1, 2, 3] 4 = 0 := by
  change anchorScan model0 2 [0, 1, 2, 3] model0.size = 0
  rw [anchor_scan_cold]
  decide
example : anchorScan model0 2 [0, 1, 2, 3] 0 = 0 := by
  rw [anchor_scan_from_retained model0 2 [0, 1, 2, 3] 0 (by decide) (by decide)]
  decide
example : anchorScan model0 2 [0, 1, 2, 3] 3 = 0 := by
  rw [anchor_scan_from_retained model0 2 [0, 1, 2, 3] 3 (by decide) (by decide)]
  decide
example : anchorScan model0 0 [0, 1, 2, 3] 4 = 1 := by
  change anchorScan model0 0 [0, 1, 2, 3] model0.size = 1
  rw [anchor_scan_cold]
  decide
example : anchorScan model0 0 [0, 1, 2, 3] 1 = 1 := by
  rw [anchor_scan_from_retained model0 0 [0, 1, 2, 3] 1 (by decide) (by decide)]
  decide
example : anchorScan model0 1 [0, 1, 2, 3] 4 = 2 := by
  change anchorScan model0 1 [0, 1, 2, 3] model0.size = 2
  rw [anchor_scan_cold]
  decide
example : anchorScan model0 1 [0, 1, 2, 3] 2 = 2 := by
  rw [anchor_scan_from_retained model0 1 [0, 1, 2, 3] 2 (by decide) (by decide)]
  decide
example : anchorScan model0 2 [0, 1, 2, 3] 4 = 0 := by
  change anchorScan model0 2 [0, 1, 2, 3] model0.size = 0
  rw [anchor_scan_cold]
  decide
example : anchorScan model0 2 [0, 1, 2, 3] 0 = 0 := by
  rw [anchor_scan_from_retained model0 2 [0, 1, 2, 3] 0 (by decide) (by decide)]
  decide
example : anchorScan model0 2 [0, 1, 2, 3] 3 = 0 := by
  rw [anchor_scan_from_retained model0 2 [0, 1, 2, 3] 3 (by decide) (by decide)]
  decide
example : anchorScan model0 0 [3, 2, 1, 0] 4 = 1 := by
  change anchorScan model0 0 [3, 2, 1, 0] model0.size = 1
  rw [anchor_scan_cold]
  decide
example : anchorScan model0 0 [3, 2, 1, 0] 1 = 1 := by
  rw [anchor_scan_from_retained model0 0 [3, 2, 1, 0] 1 (by decide) (by decide)]
  decide
example : anchorScan model0 1 [3, 2, 1, 0] 4 = 2 := by
  change anchorScan model0 1 [3, 2, 1, 0] model0.size = 2
  rw [anchor_scan_cold]
  decide
example : anchorScan model0 1 [3, 2, 1, 0] 2 = 2 := by
  rw [anchor_scan_from_retained model0 1 [3, 2, 1, 0] 2 (by decide) (by decide)]
  decide
example : anchorScan model0 2 [3, 2, 1, 0] 4 = 0 := by
  change anchorScan model0 2 [3, 2, 1, 0] model0.size = 0
  rw [anchor_scan_cold]
  decide
example : anchorScan model0 2 [3, 2, 1, 0] 0 = 0 := by
  rw [anchor_scan_from_retained model0 2 [3, 2, 1, 0] 0 (by decide) (by decide)]
  decide
example : anchorScan model0 2 [3, 2, 1, 0] 3 = 0 := by
  rw [anchor_scan_from_retained model0 2 [3, 2, 1, 0] 3 (by decide) (by decide)]
  decide
example : anchorScan model0 0 [0, 3, 2, 1] 4 = 1 := by
  change anchorScan model0 0 [0, 3, 2, 1] model0.size = 1
  rw [anchor_scan_cold]
  decide
example : anchorScan model0 0 [0, 3, 2, 1] 1 = 1 := by
  rw [anchor_scan_from_retained model0 0 [0, 3, 2, 1] 1 (by decide) (by decide)]
  decide
example : anchorScan model0 1 [0, 3, 2, 1] 4 = 2 := by
  change anchorScan model0 1 [0, 3, 2, 1] model0.size = 2
  rw [anchor_scan_cold]
  decide
example : anchorScan model0 1 [0, 3, 2, 1] 2 = 2 := by
  rw [anchor_scan_from_retained model0 1 [0, 3, 2, 1] 2 (by decide) (by decide)]
  decide
example : anchorScan model0 2 [0, 3, 2, 1] 4 = 0 := by
  change anchorScan model0 2 [0, 3, 2, 1] model0.size = 0
  rw [anchor_scan_cold]
  decide
example : anchorScan model0 2 [0, 3, 2, 1] 0 = 0 := by
  rw [anchor_scan_from_retained model0 2 [0, 3, 2, 1] 0 (by decide) (by decide)]
  decide
example : anchorScan model0 2 [0, 3, 2, 1] 3 = 0 := by
  rw [anchor_scan_from_retained model0 2 [0, 3, 2, 1] 3 (by decide) (by decide)]
  decide
example : anchorScan model0 0 [1, 2, 3, 0] 4 = 1 := by
  change anchorScan model0 0 [1, 2, 3, 0] model0.size = 1
  rw [anchor_scan_cold]
  decide
example : anchorScan model0 0 [1, 2, 3, 0] 1 = 1 := by
  rw [anchor_scan_from_retained model0 0 [1, 2, 3, 0] 1 (by decide) (by decide)]
  decide
example : anchorScan model0 1 [1, 2, 3, 0] 4 = 2 := by
  change anchorScan model0 1 [1, 2, 3, 0] model0.size = 2
  rw [anchor_scan_cold]
  decide
example : anchorScan model0 1 [1, 2, 3, 0] 2 = 2 := by
  rw [anchor_scan_from_retained model0 1 [1, 2, 3, 0] 2 (by decide) (by decide)]
  decide
example : anchorScan model0 2 [1, 2, 3, 0] 4 = 0 := by
  change anchorScan model0 2 [1, 2, 3, 0] model0.size = 0
  rw [anchor_scan_cold]
  decide
example : anchorScan model0 2 [1, 2, 3, 0] 0 = 0 := by
  rw [anchor_scan_from_retained model0 2 [1, 2, 3, 0] 0 (by decide) (by decide)]
  decide
example : anchorScan model0 2 [1, 2, 3, 0] 3 = 0 := by
  rw [anchor_scan_from_retained model0 2 [1, 2, 3, 0] 3 (by decide) (by decide)]
  decide
example : anchorScan model0 0 [3, 2, 1, 0] 4 = 1 := by
  change anchorScan model0 0 [3, 2, 1, 0] model0.size = 1
  rw [anchor_scan_cold]
  decide
example : anchorScan model0 0 [3, 2, 1, 0] 1 = 1 := by
  rw [anchor_scan_from_retained model0 0 [3, 2, 1, 0] 1 (by decide) (by decide)]
  decide
example : anchorScan model0 1 [3, 2, 1, 0] 4 = 2 := by
  change anchorScan model0 1 [3, 2, 1, 0] model0.size = 2
  rw [anchor_scan_cold]
  decide
example : anchorScan model0 1 [3, 2, 1, 0] 2 = 2 := by
  rw [anchor_scan_from_retained model0 1 [3, 2, 1, 0] 2 (by decide) (by decide)]
  decide
example : anchorScan model0 2 [3, 2, 1, 0] 4 = 0 := by
  change anchorScan model0 2 [3, 2, 1, 0] model0.size = 0
  rw [anchor_scan_cold]
  decide
example : anchorScan model0 2 [3, 2, 1, 0] 0 = 0 := by
  rw [anchor_scan_from_retained model0 2 [3, 2, 1, 0] 0 (by decide) (by decide)]
  decide
example : anchorScan model0 2 [3, 2, 1, 0] 3 = 0 := by
  rw [anchor_scan_from_retained model0 2 [3, 2, 1, 0] 3 (by decide) (by decide)]
  decide
-- Rank -> chain ordinal: [[100,10,0],[100,30,0],[100,40,0],[100,50,0]]
def model1 : AnchorModel where
  size := 4
  parent := fun rank => match rank with
    | 0 => some 2
    | 1 => some 0
    | 2 => some 1
    | 3 => some 2
    | _ => none
  authorized := fun _ => true
  level := fun _ => 0

example : anchorScan model1 0 [0, 1, 2, 3] 4 = 1 := by
  change anchorScan model1 0 [0, 1, 2, 3] model1.size = 1
  rw [anchor_scan_cold]
  decide
example : anchorScan model1 0 [0, 1, 2, 3] 1 = 1 := by
  rw [anchor_scan_from_retained model1 0 [0, 1, 2, 3] 1 (by decide) (by decide)]
  decide
example : anchorScan model1 1 [0, 1, 2, 3] 4 = 2 := by
  change anchorScan model1 1 [0, 1, 2, 3] model1.size = 2
  rw [anchor_scan_cold]
  decide
example : anchorScan model1 1 [0, 1, 2, 3] 2 = 2 := by
  rw [anchor_scan_from_retained model1 1 [0, 1, 2, 3] 2 (by decide) (by decide)]
  decide
example : anchorScan model1 2 [0, 1, 2, 3] 4 = 0 := by
  change anchorScan model1 2 [0, 1, 2, 3] model1.size = 0
  rw [anchor_scan_cold]
  decide
example : anchorScan model1 2 [0, 1, 2, 3] 0 = 0 := by
  rw [anchor_scan_from_retained model1 2 [0, 1, 2, 3] 0 (by decide) (by decide)]
  decide
example : anchorScan model1 2 [0, 1, 2, 3] 3 = 0 := by
  rw [anchor_scan_from_retained model1 2 [0, 1, 2, 3] 3 (by decide) (by decide)]
  decide
example : anchorScan model1 0 [0, 1, 2, 3] 4 = 1 := by
  change anchorScan model1 0 [0, 1, 2, 3] model1.size = 1
  rw [anchor_scan_cold]
  decide
example : anchorScan model1 0 [0, 1, 2, 3] 1 = 1 := by
  rw [anchor_scan_from_retained model1 0 [0, 1, 2, 3] 1 (by decide) (by decide)]
  decide
example : anchorScan model1 1 [0, 1, 2, 3] 4 = 2 := by
  change anchorScan model1 1 [0, 1, 2, 3] model1.size = 2
  rw [anchor_scan_cold]
  decide
example : anchorScan model1 1 [0, 1, 2, 3] 2 = 2 := by
  rw [anchor_scan_from_retained model1 1 [0, 1, 2, 3] 2 (by decide) (by decide)]
  decide
example : anchorScan model1 2 [0, 1, 2, 3] 4 = 0 := by
  change anchorScan model1 2 [0, 1, 2, 3] model1.size = 0
  rw [anchor_scan_cold]
  decide
example : anchorScan model1 2 [0, 1, 2, 3] 0 = 0 := by
  rw [anchor_scan_from_retained model1 2 [0, 1, 2, 3] 0 (by decide) (by decide)]
  decide
example : anchorScan model1 2 [0, 1, 2, 3] 3 = 0 := by
  rw [anchor_scan_from_retained model1 2 [0, 1, 2, 3] 3 (by decide) (by decide)]
  decide
example : anchorScan model1 0 [3, 2, 1, 0] 4 = 1 := by
  change anchorScan model1 0 [3, 2, 1, 0] model1.size = 1
  rw [anchor_scan_cold]
  decide
example : anchorScan model1 0 [3, 2, 1, 0] 1 = 1 := by
  rw [anchor_scan_from_retained model1 0 [3, 2, 1, 0] 1 (by decide) (by decide)]
  decide
example : anchorScan model1 1 [3, 2, 1, 0] 4 = 2 := by
  change anchorScan model1 1 [3, 2, 1, 0] model1.size = 2
  rw [anchor_scan_cold]
  decide
example : anchorScan model1 1 [3, 2, 1, 0] 2 = 2 := by
  rw [anchor_scan_from_retained model1 1 [3, 2, 1, 0] 2 (by decide) (by decide)]
  decide
example : anchorScan model1 2 [3, 2, 1, 0] 4 = 0 := by
  change anchorScan model1 2 [3, 2, 1, 0] model1.size = 0
  rw [anchor_scan_cold]
  decide
example : anchorScan model1 2 [3, 2, 1, 0] 0 = 0 := by
  rw [anchor_scan_from_retained model1 2 [3, 2, 1, 0] 0 (by decide) (by decide)]
  decide
example : anchorScan model1 2 [3, 2, 1, 0] 3 = 0 := by
  rw [anchor_scan_from_retained model1 2 [3, 2, 1, 0] 3 (by decide) (by decide)]
  decide
example : anchorScan model1 0 [0, 3, 2, 1] 4 = 1 := by
  change anchorScan model1 0 [0, 3, 2, 1] model1.size = 1
  rw [anchor_scan_cold]
  decide
example : anchorScan model1 0 [0, 3, 2, 1] 1 = 1 := by
  rw [anchor_scan_from_retained model1 0 [0, 3, 2, 1] 1 (by decide) (by decide)]
  decide
example : anchorScan model1 1 [0, 3, 2, 1] 4 = 2 := by
  change anchorScan model1 1 [0, 3, 2, 1] model1.size = 2
  rw [anchor_scan_cold]
  decide
example : anchorScan model1 1 [0, 3, 2, 1] 2 = 2 := by
  rw [anchor_scan_from_retained model1 1 [0, 3, 2, 1] 2 (by decide) (by decide)]
  decide
example : anchorScan model1 2 [0, 3, 2, 1] 4 = 0 := by
  change anchorScan model1 2 [0, 3, 2, 1] model1.size = 0
  rw [anchor_scan_cold]
  decide
example : anchorScan model1 2 [0, 3, 2, 1] 0 = 0 := by
  rw [anchor_scan_from_retained model1 2 [0, 3, 2, 1] 0 (by decide) (by decide)]
  decide
example : anchorScan model1 2 [0, 3, 2, 1] 3 = 0 := by
  rw [anchor_scan_from_retained model1 2 [0, 3, 2, 1] 3 (by decide) (by decide)]
  decide
example : anchorScan model1 0 [1, 2, 3, 0] 4 = 1 := by
  change anchorScan model1 0 [1, 2, 3, 0] model1.size = 1
  rw [anchor_scan_cold]
  decide
example : anchorScan model1 0 [1, 2, 3, 0] 1 = 1 := by
  rw [anchor_scan_from_retained model1 0 [1, 2, 3, 0] 1 (by decide) (by decide)]
  decide
example : anchorScan model1 1 [1, 2, 3, 0] 4 = 2 := by
  change anchorScan model1 1 [1, 2, 3, 0] model1.size = 2
  rw [anchor_scan_cold]
  decide
example : anchorScan model1 1 [1, 2, 3, 0] 2 = 2 := by
  rw [anchor_scan_from_retained model1 1 [1, 2, 3, 0] 2 (by decide) (by decide)]
  decide
example : anchorScan model1 2 [1, 2, 3, 0] 4 = 0 := by
  change anchorScan model1 2 [1, 2, 3, 0] model1.size = 0
  rw [anchor_scan_cold]
  decide
example : anchorScan model1 2 [1, 2, 3, 0] 0 = 0 := by
  rw [anchor_scan_from_retained model1 2 [1, 2, 3, 0] 0 (by decide) (by decide)]
  decide
example : anchorScan model1 2 [1, 2, 3, 0] 3 = 0 := by
  rw [anchor_scan_from_retained model1 2 [1, 2, 3, 0] 3 (by decide) (by decide)]
  decide
example : anchorScan model1 0 [3, 2, 1, 0] 4 = 1 := by
  change anchorScan model1 0 [3, 2, 1, 0] model1.size = 1
  rw [anchor_scan_cold]
  decide
example : anchorScan model1 0 [3, 2, 1, 0] 1 = 1 := by
  rw [anchor_scan_from_retained model1 0 [3, 2, 1, 0] 1 (by decide) (by decide)]
  decide
example : anchorScan model1 1 [3, 2, 1, 0] 4 = 2 := by
  change anchorScan model1 1 [3, 2, 1, 0] model1.size = 2
  rw [anchor_scan_cold]
  decide
example : anchorScan model1 1 [3, 2, 1, 0] 2 = 2 := by
  rw [anchor_scan_from_retained model1 1 [3, 2, 1, 0] 2 (by decide) (by decide)]
  decide
example : anchorScan model1 2 [3, 2, 1, 0] 4 = 0 := by
  change anchorScan model1 2 [3, 2, 1, 0] model1.size = 0
  rw [anchor_scan_cold]
  decide
example : anchorScan model1 2 [3, 2, 1, 0] 0 = 0 := by
  rw [anchor_scan_from_retained model1 2 [3, 2, 1, 0] 0 (by decide) (by decide)]
  decide
example : anchorScan model1 2 [3, 2, 1, 0] 3 = 0 := by
  rw [anchor_scan_from_retained model1 2 [3, 2, 1, 0] 3 (by decide) (by decide)]
  decide

end Archon.ChainAnchorFixtures
