-- Generated by generate-fixtures.mjs; do not edit.
import AgentConvergence

set_option warningAsError true

namespace Archon.Fixtures

-- hyperswarm: finite, fixed-authorization data-only graph.
def model0 : Model := {
  size := 4
  parent := fun i => ([none, some 0, some 0, some 2] : List (Option Nat))[i]?.getD none
  authorized := fun _ => true
  level := fun i => ([2, 0, 1, 0] : List Nat)[i]?.getD 0
}

theorem model0_acyclic : WellFoundedEdges model0 := by
  intro p i h
  have bound : i < 4 := by
    simp only [eligible, Bool.and_eq_true, decide_eq_true_eq] at h
    exact h.1.1
  have cases : i = 0 ∨ i = 1 ∨ i = 2 ∨ i = 3 := by omega
  rcases cases with rfl | rfl | rfl | rfl <;> simp [eligible, model0] at h
  all_goals subst p; decide

-- hyperswarm/hyperswarm/fresh/linear
example : history model0 0 [0, 2, 3] = [0, 2, 3] := by decide
example : history model0 0 [0, 3, 2] = [0, 2, 3] := by decide
example : history model0 0 [2, 0, 3] = [0, 2, 3] := by decide
example : history model0 0 [2, 3, 0] = [0, 2, 3] := by decide
example : history model0 0 [3, 0, 2] = [0, 2, 3] := by decide
example : history model0 0 [3, 2, 0] = [0, 2, 3] := by decide

-- hyperswarm/hyperswarm/fresh/fork
example : history model0 0 [0, 2, 1, 3] = [0, 1] := by decide
example : history model0 0 [0, 2, 3, 1] = [0, 1] := by decide
example : history model0 0 [0, 1, 2, 3] = [0, 1] := by decide
example : history model0 0 [0, 1, 3, 2] = [0, 1] := by decide
example : history model0 0 [0, 3, 2, 1] = [0, 1] := by decide
example : history model0 0 [0, 3, 1, 2] = [0, 1] := by decide
example : history model0 0 [2, 0, 1, 3] = [0, 1] := by decide
example : history model0 0 [2, 0, 3, 1] = [0, 1] := by decide
example : history model0 0 [2, 1, 0, 3] = [0, 1] := by decide
example : history model0 0 [2, 1, 3, 0] = [0, 1] := by decide
example : history model0 0 [2, 3, 0, 1] = [0, 1] := by decide
example : history model0 0 [2, 3, 1, 0] = [0, 1] := by decide
example : history model0 0 [1, 0, 2, 3] = [0, 1] := by decide
example : history model0 0 [1, 0, 3, 2] = [0, 1] := by decide
example : history model0 0 [1, 2, 0, 3] = [0, 1] := by decide
example : history model0 0 [1, 2, 3, 0] = [0, 1] := by decide
example : history model0 0 [1, 3, 0, 2] = [0, 1] := by decide
example : history model0 0 [1, 3, 2, 0] = [0, 1] := by decide
example : history model0 0 [3, 0, 2, 1] = [0, 1] := by decide
example : history model0 0 [3, 0, 1, 2] = [0, 1] := by decide
example : history model0 0 [3, 2, 0, 1] = [0, 1] := by decide
example : history model0 0 [3, 2, 1, 0] = [0, 1] := by decide
example : history model0 0 [3, 1, 0, 2] = [0, 1] := by decide
example : history model0 0 [3, 1, 2, 0] = [0, 1] := by decide

-- hyperswarm/hyperswarm/tied/linear
example : history model0 0 [0, 2, 3] = [0, 2, 3] := by decide
example : history model0 0 [0, 3, 2] = [0, 2, 3] := by decide
example : history model0 0 [2, 0, 3] = [0, 2, 3] := by decide
example : history model0 0 [2, 3, 0] = [0, 2, 3] := by decide
example : history model0 0 [3, 0, 2] = [0, 2, 3] := by decide
example : history model0 0 [3, 2, 0] = [0, 2, 3] := by decide

-- hyperswarm/hyperswarm/tied/fork
example : history model0 0 [0, 2, 1, 3] = [0, 1] := by decide
example : history model0 0 [0, 2, 3, 1] = [0, 1] := by decide
example : history model0 0 [0, 1, 2, 3] = [0, 1] := by decide
example : history model0 0 [0, 1, 3, 2] = [0, 1] := by decide
example : history model0 0 [0, 3, 2, 1] = [0, 1] := by decide
example : history model0 0 [0, 3, 1, 2] = [0, 1] := by decide
example : history model0 0 [2, 0, 1, 3] = [0, 1] := by decide
example : history model0 0 [2, 0, 3, 1] = [0, 1] := by decide
example : history model0 0 [2, 1, 0, 3] = [0, 1] := by decide
example : history model0 0 [2, 1, 3, 0] = [0, 1] := by decide
example : history model0 0 [2, 3, 0, 1] = [0, 1] := by decide
example : history model0 0 [2, 3, 1, 0] = [0, 1] := by decide
example : history model0 0 [1, 0, 2, 3] = [0, 1] := by decide
example : history model0 0 [1, 0, 3, 2] = [0, 1] := by decide
example : history model0 0 [1, 2, 0, 3] = [0, 1] := by decide
example : history model0 0 [1, 2, 3, 0] = [0, 1] := by decide
example : history model0 0 [1, 3, 0, 2] = [0, 1] := by decide
example : history model0 0 [1, 3, 2, 0] = [0, 1] := by decide
example : history model0 0 [3, 0, 2, 1] = [0, 1] := by decide
example : history model0 0 [3, 0, 1, 2] = [0, 1] := by decide
example : history model0 0 [3, 2, 0, 1] = [0, 1] := by decide
example : history model0 0 [3, 2, 1, 0] = [0, 1] := by decide
example : history model0 0 [3, 1, 0, 2] = [0, 1] := by decide
example : history model0 0 [3, 1, 2, 0] = [0, 1] := by decide

-- hyperswarm/mixed/fresh/linear
example : history model0 0 [0, 2, 3] = [0, 2, 3] := by decide
example : history model0 0 [0, 3, 2] = [0, 2, 3] := by decide
example : history model0 0 [2, 0, 3] = [0, 2, 3] := by decide
example : history model0 0 [2, 3, 0] = [0, 2, 3] := by decide
example : history model0 0 [3, 0, 2] = [0, 2, 3] := by decide
example : history model0 0 [3, 2, 0] = [0, 2, 3] := by decide

-- hyperswarm/mixed/fresh/fork
example : history model0 0 [0, 2, 1, 3] = [0, 1] := by decide
example : history model0 0 [0, 2, 3, 1] = [0, 1] := by decide
example : history model0 0 [0, 1, 2, 3] = [0, 1] := by decide
example : history model0 0 [0, 1, 3, 2] = [0, 1] := by decide
example : history model0 0 [0, 3, 2, 1] = [0, 1] := by decide
example : history model0 0 [0, 3, 1, 2] = [0, 1] := by decide
example : history model0 0 [2, 0, 1, 3] = [0, 1] := by decide
example : history model0 0 [2, 0, 3, 1] = [0, 1] := by decide
example : history model0 0 [2, 1, 0, 3] = [0, 1] := by decide
example : history model0 0 [2, 1, 3, 0] = [0, 1] := by decide
example : history model0 0 [2, 3, 0, 1] = [0, 1] := by decide
example : history model0 0 [2, 3, 1, 0] = [0, 1] := by decide
example : history model0 0 [1, 0, 2, 3] = [0, 1] := by decide
example : history model0 0 [1, 0, 3, 2] = [0, 1] := by decide
example : history model0 0 [1, 2, 0, 3] = [0, 1] := by decide
example : history model0 0 [1, 2, 3, 0] = [0, 1] := by decide
example : history model0 0 [1, 3, 0, 2] = [0, 1] := by decide
example : history model0 0 [1, 3, 2, 0] = [0, 1] := by decide
example : history model0 0 [3, 0, 2, 1] = [0, 1] := by decide
example : history model0 0 [3, 0, 1, 2] = [0, 1] := by decide
example : history model0 0 [3, 2, 0, 1] = [0, 1] := by decide
example : history model0 0 [3, 2, 1, 0] = [0, 1] := by decide
example : history model0 0 [3, 1, 0, 2] = [0, 1] := by decide
example : history model0 0 [3, 1, 2, 0] = [0, 1] := by decide

-- hyperswarm/mixed/tied/linear
example : history model0 0 [0, 2, 3] = [0, 2, 3] := by decide
example : history model0 0 [0, 3, 2] = [0, 2, 3] := by decide
example : history model0 0 [2, 0, 3] = [0, 2, 3] := by decide
example : history model0 0 [2, 3, 0] = [0, 2, 3] := by decide
example : history model0 0 [3, 0, 2] = [0, 2, 3] := by decide
example : history model0 0 [3, 2, 0] = [0, 2, 3] := by decide

-- hyperswarm/mixed/tied/fork
example : history model0 0 [0, 2, 1, 3] = [0, 1] := by decide
example : history model0 0 [0, 2, 3, 1] = [0, 1] := by decide
example : history model0 0 [0, 1, 2, 3] = [0, 1] := by decide
example : history model0 0 [0, 1, 3, 2] = [0, 1] := by decide
example : history model0 0 [0, 3, 2, 1] = [0, 1] := by decide
example : history model0 0 [0, 3, 1, 2] = [0, 1] := by decide
example : history model0 0 [2, 0, 1, 3] = [0, 1] := by decide
example : history model0 0 [2, 0, 3, 1] = [0, 1] := by decide
example : history model0 0 [2, 1, 0, 3] = [0, 1] := by decide
example : history model0 0 [2, 1, 3, 0] = [0, 1] := by decide
example : history model0 0 [2, 3, 0, 1] = [0, 1] := by decide
example : history model0 0 [2, 3, 1, 0] = [0, 1] := by decide
example : history model0 0 [1, 0, 2, 3] = [0, 1] := by decide
example : history model0 0 [1, 0, 3, 2] = [0, 1] := by decide
example : history model0 0 [1, 2, 0, 3] = [0, 1] := by decide
example : history model0 0 [1, 2, 3, 0] = [0, 1] := by decide
example : history model0 0 [1, 3, 0, 2] = [0, 1] := by decide
example : history model0 0 [1, 3, 2, 0] = [0, 1] := by decide
example : history model0 0 [3, 0, 2, 1] = [0, 1] := by decide
example : history model0 0 [3, 0, 1, 2] = [0, 1] := by decide
example : history model0 0 [3, 2, 0, 1] = [0, 1] := by decide
example : history model0 0 [3, 2, 1, 0] = [0, 1] := by decide
example : history model0 0 [3, 1, 0, 2] = [0, 1] := by decide
example : history model0 0 [3, 1, 2, 0] = [0, 1] := by decide

-- local: finite, fixed-authorization data-only graph.
def model1 : Model := {
  size := 4
  parent := fun i => ([some 3, none, some 1, some 1] : List (Option Nat))[i]?.getD none
  authorized := fun _ => true
  level := fun i => ([0, 2, 0, 1] : List Nat)[i]?.getD 0
}

theorem model1_acyclic : WellFoundedEdges model1 := by
  intro p i h
  have bound : i < 4 := by
    simp only [eligible, Bool.and_eq_true, decide_eq_true_eq] at h
    exact h.1.1
  have cases : i = 0 ∨ i = 1 ∨ i = 2 ∨ i = 3 := by omega
  rcases cases with rfl | rfl | rfl | rfl <;> simp [eligible, model1] at h
  all_goals subst p; decide

-- local/local/fresh/linear
example : history model1 1 [1, 3, 0] = [1, 3, 0] := by decide
example : history model1 1 [1, 0, 3] = [1, 3, 0] := by decide
example : history model1 1 [3, 1, 0] = [1, 3, 0] := by decide
example : history model1 1 [3, 0, 1] = [1, 3, 0] := by decide
example : history model1 1 [0, 1, 3] = [1, 3, 0] := by decide
example : history model1 1 [0, 3, 1] = [1, 3, 0] := by decide

-- local/local/fresh/fork
example : history model1 1 [1, 3, 2, 0] = [1, 2] := by decide
example : history model1 1 [1, 3, 0, 2] = [1, 2] := by decide
example : history model1 1 [1, 2, 3, 0] = [1, 2] := by decide
example : history model1 1 [1, 2, 0, 3] = [1, 2] := by decide
example : history model1 1 [1, 0, 3, 2] = [1, 2] := by decide
example : history model1 1 [1, 0, 2, 3] = [1, 2] := by decide
example : history model1 1 [3, 1, 2, 0] = [1, 2] := by decide
example : history model1 1 [3, 1, 0, 2] = [1, 2] := by decide
example : history model1 1 [3, 2, 1, 0] = [1, 2] := by decide
example : history model1 1 [3, 2, 0, 1] = [1, 2] := by decide
example : history model1 1 [3, 0, 1, 2] = [1, 2] := by decide
example : history model1 1 [3, 0, 2, 1] = [1, 2] := by decide
example : history model1 1 [2, 1, 3, 0] = [1, 2] := by decide
example : history model1 1 [2, 1, 0, 3] = [1, 2] := by decide
example : history model1 1 [2, 3, 1, 0] = [1, 2] := by decide
example : history model1 1 [2, 3, 0, 1] = [1, 2] := by decide
example : history model1 1 [2, 0, 1, 3] = [1, 2] := by decide
example : history model1 1 [2, 0, 3, 1] = [1, 2] := by decide
example : history model1 1 [0, 1, 3, 2] = [1, 2] := by decide
example : history model1 1 [0, 1, 2, 3] = [1, 2] := by decide
example : history model1 1 [0, 3, 1, 2] = [1, 2] := by decide
example : history model1 1 [0, 3, 2, 1] = [1, 2] := by decide
example : history model1 1 [0, 2, 1, 3] = [1, 2] := by decide
example : history model1 1 [0, 2, 3, 1] = [1, 2] := by decide

-- local/local/tied/linear
example : history model1 1 [1, 3, 0] = [1, 3, 0] := by decide
example : history model1 1 [1, 0, 3] = [1, 3, 0] := by decide
example : history model1 1 [3, 1, 0] = [1, 3, 0] := by decide
example : history model1 1 [3, 0, 1] = [1, 3, 0] := by decide
example : history model1 1 [0, 1, 3] = [1, 3, 0] := by decide
example : history model1 1 [0, 3, 1] = [1, 3, 0] := by decide

-- local/local/tied/fork
example : history model1 1 [1, 3, 2, 0] = [1, 2] := by decide
example : history model1 1 [1, 3, 0, 2] = [1, 2] := by decide
example : history model1 1 [1, 2, 3, 0] = [1, 2] := by decide
example : history model1 1 [1, 2, 0, 3] = [1, 2] := by decide
example : history model1 1 [1, 0, 3, 2] = [1, 2] := by decide
example : history model1 1 [1, 0, 2, 3] = [1, 2] := by decide
example : history model1 1 [3, 1, 2, 0] = [1, 2] := by decide
example : history model1 1 [3, 1, 0, 2] = [1, 2] := by decide
example : history model1 1 [3, 2, 1, 0] = [1, 2] := by decide
example : history model1 1 [3, 2, 0, 1] = [1, 2] := by decide
example : history model1 1 [3, 0, 1, 2] = [1, 2] := by decide
example : history model1 1 [3, 0, 2, 1] = [1, 2] := by decide
example : history model1 1 [2, 1, 3, 0] = [1, 2] := by decide
example : history model1 1 [2, 1, 0, 3] = [1, 2] := by decide
example : history model1 1 [2, 3, 1, 0] = [1, 2] := by decide
example : history model1 1 [2, 3, 0, 1] = [1, 2] := by decide
example : history model1 1 [2, 0, 1, 3] = [1, 2] := by decide
example : history model1 1 [2, 0, 3, 1] = [1, 2] := by decide
example : history model1 1 [0, 1, 3, 2] = [1, 2] := by decide
example : history model1 1 [0, 1, 2, 3] = [1, 2] := by decide
example : history model1 1 [0, 3, 1, 2] = [1, 2] := by decide
example : history model1 1 [0, 3, 2, 1] = [1, 2] := by decide
example : history model1 1 [0, 2, 1, 3] = [1, 2] := by decide
example : history model1 1 [0, 2, 3, 1] = [1, 2] := by decide

-- pin: finite, fixed-authorization data-only graph.
def model2 : Model := {
  size := 4
  parent := fun i => ([some 2, some 3, some 3, none] : List (Option Nat))[i]?.getD none
  authorized := fun _ => true
  level := fun i => ([0, 0, 1, 2] : List Nat)[i]?.getD 0
}

theorem model2_acyclic : WellFoundedEdges model2 := by
  intro p i h
  have bound : i < 4 := by
    simp only [eligible, Bool.and_eq_true, decide_eq_true_eq] at h
    exact h.1.1
  have cases : i = 0 ∨ i = 1 ∨ i = 2 ∨ i = 3 := by omega
  rcases cases with rfl | rfl | rfl | rfl <;> simp [eligible, model2] at h
  all_goals subst p; decide

-- pin/pin/fresh/linear
example : history model2 3 [3, 2, 0] = [3, 2, 0] := by decide
example : history model2 3 [3, 0, 2] = [3, 2, 0] := by decide
example : history model2 3 [2, 3, 0] = [3, 2, 0] := by decide
example : history model2 3 [2, 0, 3] = [3, 2, 0] := by decide
example : history model2 3 [0, 3, 2] = [3, 2, 0] := by decide
example : history model2 3 [0, 2, 3] = [3, 2, 0] := by decide

-- pin/pin/fresh/fork
example : history model2 3 [3, 2, 1, 0] = [3, 1] := by decide
example : history model2 3 [3, 2, 0, 1] = [3, 1] := by decide
example : history model2 3 [3, 1, 2, 0] = [3, 1] := by decide
example : history model2 3 [3, 1, 0, 2] = [3, 1] := by decide
example : history model2 3 [3, 0, 2, 1] = [3, 1] := by decide
example : history model2 3 [3, 0, 1, 2] = [3, 1] := by decide
example : history model2 3 [2, 3, 1, 0] = [3, 1] := by decide
example : history model2 3 [2, 3, 0, 1] = [3, 1] := by decide
example : history model2 3 [2, 1, 3, 0] = [3, 1] := by decide
example : history model2 3 [2, 1, 0, 3] = [3, 1] := by decide
example : history model2 3 [2, 0, 3, 1] = [3, 1] := by decide
example : history model2 3 [2, 0, 1, 3] = [3, 1] := by decide
example : history model2 3 [1, 3, 2, 0] = [3, 1] := by decide
example : history model2 3 [1, 3, 0, 2] = [3, 1] := by decide
example : history model2 3 [1, 2, 3, 0] = [3, 1] := by decide
example : history model2 3 [1, 2, 0, 3] = [3, 1] := by decide
example : history model2 3 [1, 0, 3, 2] = [3, 1] := by decide
example : history model2 3 [1, 0, 2, 3] = [3, 1] := by decide
example : history model2 3 [0, 3, 2, 1] = [3, 1] := by decide
example : history model2 3 [0, 3, 1, 2] = [3, 1] := by decide
example : history model2 3 [0, 2, 3, 1] = [3, 1] := by decide
example : history model2 3 [0, 2, 1, 3] = [3, 1] := by decide
example : history model2 3 [0, 1, 3, 2] = [3, 1] := by decide
example : history model2 3 [0, 1, 2, 3] = [3, 1] := by decide

-- pin/pin/tied/linear
example : history model2 3 [3, 2, 0] = [3, 2, 0] := by decide
example : history model2 3 [3, 0, 2] = [3, 2, 0] := by decide
example : history model2 3 [2, 3, 0] = [3, 2, 0] := by decide
example : history model2 3 [2, 0, 3] = [3, 2, 0] := by decide
example : history model2 3 [0, 3, 2] = [3, 2, 0] := by decide
example : history model2 3 [0, 2, 3] = [3, 2, 0] := by decide

-- pin/pin/tied/fork
example : history model2 3 [3, 2, 1, 0] = [3, 1] := by decide
example : history model2 3 [3, 2, 0, 1] = [3, 1] := by decide
example : history model2 3 [3, 1, 2, 0] = [3, 1] := by decide
example : history model2 3 [3, 1, 0, 2] = [3, 1] := by decide
example : history model2 3 [3, 0, 2, 1] = [3, 1] := by decide
example : history model2 3 [3, 0, 1, 2] = [3, 1] := by decide
example : history model2 3 [2, 3, 1, 0] = [3, 1] := by decide
example : history model2 3 [2, 3, 0, 1] = [3, 1] := by decide
example : history model2 3 [2, 1, 3, 0] = [3, 1] := by decide
example : history model2 3 [2, 1, 0, 3] = [3, 1] := by decide
example : history model2 3 [2, 0, 3, 1] = [3, 1] := by decide
example : history model2 3 [2, 0, 1, 3] = [3, 1] := by decide
example : history model2 3 [1, 3, 2, 0] = [3, 1] := by decide
example : history model2 3 [1, 3, 0, 2] = [3, 1] := by decide
example : history model2 3 [1, 2, 3, 0] = [3, 1] := by decide
example : history model2 3 [1, 2, 0, 3] = [3, 1] := by decide
example : history model2 3 [1, 0, 3, 2] = [3, 1] := by decide
example : history model2 3 [1, 0, 2, 3] = [3, 1] := by decide
example : history model2 3 [0, 3, 2, 1] = [3, 1] := by decide
example : history model2 3 [0, 3, 1, 2] = [3, 1] := by decide
example : history model2 3 [0, 2, 3, 1] = [3, 1] := by decide
example : history model2 3 [0, 2, 1, 3] = [3, 1] := by decide
example : history model2 3 [0, 1, 3, 2] = [3, 1] := by decide
example : history model2 3 [0, 1, 2, 3] = [3, 1] := by decide

-- pin/pin-mixed/fresh/linear
example : history model2 3 [3, 2, 0] = [3, 2, 0] := by decide
example : history model2 3 [3, 0, 2] = [3, 2, 0] := by decide
example : history model2 3 [2, 3, 0] = [3, 2, 0] := by decide
example : history model2 3 [2, 0, 3] = [3, 2, 0] := by decide
example : history model2 3 [0, 3, 2] = [3, 2, 0] := by decide
example : history model2 3 [0, 2, 3] = [3, 2, 0] := by decide

-- pin/pin-mixed/fresh/fork
example : history model2 3 [3, 2, 1, 0] = [3, 1] := by decide
example : history model2 3 [3, 2, 0, 1] = [3, 1] := by decide
example : history model2 3 [3, 1, 2, 0] = [3, 1] := by decide
example : history model2 3 [3, 1, 0, 2] = [3, 1] := by decide
example : history model2 3 [3, 0, 2, 1] = [3, 1] := by decide
example : history model2 3 [3, 0, 1, 2] = [3, 1] := by decide
example : history model2 3 [2, 3, 1, 0] = [3, 1] := by decide
example : history model2 3 [2, 3, 0, 1] = [3, 1] := by decide
example : history model2 3 [2, 1, 3, 0] = [3, 1] := by decide
example : history model2 3 [2, 1, 0, 3] = [3, 1] := by decide
example : history model2 3 [2, 0, 3, 1] = [3, 1] := by decide
example : history model2 3 [2, 0, 1, 3] = [3, 1] := by decide
example : history model2 3 [1, 3, 2, 0] = [3, 1] := by decide
example : history model2 3 [1, 3, 0, 2] = [3, 1] := by decide
example : history model2 3 [1, 2, 3, 0] = [3, 1] := by decide
example : history model2 3 [1, 2, 0, 3] = [3, 1] := by decide
example : history model2 3 [1, 0, 3, 2] = [3, 1] := by decide
example : history model2 3 [1, 0, 2, 3] = [3, 1] := by decide
example : history model2 3 [0, 3, 2, 1] = [3, 1] := by decide
example : history model2 3 [0, 3, 1, 2] = [3, 1] := by decide
example : history model2 3 [0, 2, 3, 1] = [3, 1] := by decide
example : history model2 3 [0, 2, 1, 3] = [3, 1] := by decide
example : history model2 3 [0, 1, 3, 2] = [3, 1] := by decide
example : history model2 3 [0, 1, 2, 3] = [3, 1] := by decide

-- pin/pin-mixed/tied/linear
example : history model2 3 [3, 2, 0] = [3, 2, 0] := by decide
example : history model2 3 [3, 0, 2] = [3, 2, 0] := by decide
example : history model2 3 [2, 3, 0] = [3, 2, 0] := by decide
example : history model2 3 [2, 0, 3] = [3, 2, 0] := by decide
example : history model2 3 [0, 3, 2] = [3, 2, 0] := by decide
example : history model2 3 [0, 2, 3] = [3, 2, 0] := by decide

-- pin/pin-mixed/tied/fork
example : history model2 3 [3, 2, 1, 0] = [3, 1] := by decide
example : history model2 3 [3, 2, 0, 1] = [3, 1] := by decide
example : history model2 3 [3, 1, 2, 0] = [3, 1] := by decide
example : history model2 3 [3, 1, 0, 2] = [3, 1] := by decide
example : history model2 3 [3, 0, 2, 1] = [3, 1] := by decide
example : history model2 3 [3, 0, 1, 2] = [3, 1] := by decide
example : history model2 3 [2, 3, 1, 0] = [3, 1] := by decide
example : history model2 3 [2, 3, 0, 1] = [3, 1] := by decide
example : history model2 3 [2, 1, 3, 0] = [3, 1] := by decide
example : history model2 3 [2, 1, 0, 3] = [3, 1] := by decide
example : history model2 3 [2, 0, 3, 1] = [3, 1] := by decide
example : history model2 3 [2, 0, 1, 3] = [3, 1] := by decide
example : history model2 3 [1, 3, 2, 0] = [3, 1] := by decide
example : history model2 3 [1, 3, 0, 2] = [3, 1] := by decide
example : history model2 3 [1, 2, 3, 0] = [3, 1] := by decide
example : history model2 3 [1, 2, 0, 3] = [3, 1] := by decide
example : history model2 3 [1, 0, 3, 2] = [3, 1] := by decide
example : history model2 3 [1, 0, 2, 3] = [3, 1] := by decide
example : history model2 3 [0, 3, 2, 1] = [3, 1] := by decide
example : history model2 3 [0, 3, 1, 2] = [3, 1] := by decide
example : history model2 3 [0, 2, 3, 1] = [3, 1] := by decide
example : history model2 3 [0, 2, 1, 3] = [3, 1] := by decide
example : history model2 3 [0, 1, 3, 2] = [3, 1] := by decide
example : history model2 3 [0, 1, 2, 3] = [3, 1] := by decide

-- BTC:signet: finite, fixed-authorization data-only graph.
def model3 : Model := {
  size := 4
  parent := fun i => ([none, some 0, some 1, some 0] : List (Option Nat))[i]?.getD none
  authorized := fun _ => true
  level := fun i => ([2, 1, 0, 0] : List Nat)[i]?.getD 0
}

theorem model3_acyclic : WellFoundedEdges model3 := by
  intro p i h
  have bound : i < 4 := by
    simp only [eligible, Bool.and_eq_true, decide_eq_true_eq] at h
    exact h.1.1
  have cases : i = 0 ∨ i = 1 ∨ i = 2 ∨ i = 3 := by omega
  rcases cases with rfl | rfl | rfl | rfl <;> simp [eligible, model3] at h
  all_goals subst p; decide

-- BTC:signet/hyperswarm/fresh/linear
example : history model3 0 [0, 1, 2] = [0, 1, 2] := by decide
example : history model3 0 [0, 2, 1] = [0, 1, 2] := by decide
example : history model3 0 [1, 0, 2] = [0, 1, 2] := by decide
example : history model3 0 [1, 2, 0] = [0, 1, 2] := by decide
example : history model3 0 [2, 0, 1] = [0, 1, 2] := by decide
example : history model3 0 [2, 1, 0] = [0, 1, 2] := by decide

-- BTC:signet/hyperswarm/fresh/fork
example : history model3 0 [0, 1, 3, 2] = [0, 1, 2] := by decide
example : history model3 0 [0, 1, 2, 3] = [0, 1, 2] := by decide
example : history model3 0 [0, 3, 1, 2] = [0, 1, 2] := by decide
example : history model3 0 [0, 3, 2, 1] = [0, 1, 2] := by decide
example : history model3 0 [0, 2, 1, 3] = [0, 1, 2] := by decide
example : history model3 0 [0, 2, 3, 1] = [0, 1, 2] := by decide
example : history model3 0 [1, 0, 3, 2] = [0, 1, 2] := by decide
example : history model3 0 [1, 0, 2, 3] = [0, 1, 2] := by decide
example : history model3 0 [1, 3, 0, 2] = [0, 1, 2] := by decide
example : history model3 0 [1, 3, 2, 0] = [0, 1, 2] := by decide
example : history model3 0 [1, 2, 0, 3] = [0, 1, 2] := by decide
example : history model3 0 [1, 2, 3, 0] = [0, 1, 2] := by decide
example : history model3 0 [3, 0, 1, 2] = [0, 1, 2] := by decide
example : history model3 0 [3, 0, 2, 1] = [0, 1, 2] := by decide
example : history model3 0 [3, 1, 0, 2] = [0, 1, 2] := by decide
example : history model3 0 [3, 1, 2, 0] = [0, 1, 2] := by decide
example : history model3 0 [3, 2, 0, 1] = [0, 1, 2] := by decide
example : history model3 0 [3, 2, 1, 0] = [0, 1, 2] := by decide
example : history model3 0 [2, 0, 1, 3] = [0, 1, 2] := by decide
example : history model3 0 [2, 0, 3, 1] = [0, 1, 2] := by decide
example : history model3 0 [2, 1, 0, 3] = [0, 1, 2] := by decide
example : history model3 0 [2, 1, 3, 0] = [0, 1, 2] := by decide
example : history model3 0 [2, 3, 0, 1] = [0, 1, 2] := by decide
example : history model3 0 [2, 3, 1, 0] = [0, 1, 2] := by decide

-- BTC:signet/hyperswarm/tied/linear
example : history model3 0 [0, 1, 2] = [0, 1, 2] := by decide
example : history model3 0 [0, 2, 1] = [0, 1, 2] := by decide
example : history model3 0 [1, 0, 2] = [0, 1, 2] := by decide
example : history model3 0 [1, 2, 0] = [0, 1, 2] := by decide
example : history model3 0 [2, 0, 1] = [0, 1, 2] := by decide
example : history model3 0 [2, 1, 0] = [0, 1, 2] := by decide

-- BTC:signet/hyperswarm/tied/fork
example : history model3 0 [0, 1, 3, 2] = [0, 1, 2] := by decide
example : history model3 0 [0, 1, 2, 3] = [0, 1, 2] := by decide
example : history model3 0 [0, 3, 1, 2] = [0, 1, 2] := by decide
example : history model3 0 [0, 3, 2, 1] = [0, 1, 2] := by decide
example : history model3 0 [0, 2, 1, 3] = [0, 1, 2] := by decide
example : history model3 0 [0, 2, 3, 1] = [0, 1, 2] := by decide
example : history model3 0 [1, 0, 3, 2] = [0, 1, 2] := by decide
example : history model3 0 [1, 0, 2, 3] = [0, 1, 2] := by decide
example : history model3 0 [1, 3, 0, 2] = [0, 1, 2] := by decide
example : history model3 0 [1, 3, 2, 0] = [0, 1, 2] := by decide
example : history model3 0 [1, 2, 0, 3] = [0, 1, 2] := by decide
example : history model3 0 [1, 2, 3, 0] = [0, 1, 2] := by decide
example : history model3 0 [3, 0, 1, 2] = [0, 1, 2] := by decide
example : history model3 0 [3, 0, 2, 1] = [0, 1, 2] := by decide
example : history model3 0 [3, 1, 0, 2] = [0, 1, 2] := by decide
example : history model3 0 [3, 1, 2, 0] = [0, 1, 2] := by decide
example : history model3 0 [3, 2, 0, 1] = [0, 1, 2] := by decide
example : history model3 0 [3, 2, 1, 0] = [0, 1, 2] := by decide
example : history model3 0 [2, 0, 1, 3] = [0, 1, 2] := by decide
example : history model3 0 [2, 0, 3, 1] = [0, 1, 2] := by decide
example : history model3 0 [2, 1, 0, 3] = [0, 1, 2] := by decide
example : history model3 0 [2, 1, 3, 0] = [0, 1, 2] := by decide
example : history model3 0 [2, 3, 0, 1] = [0, 1, 2] := by decide
example : history model3 0 [2, 3, 1, 0] = [0, 1, 2] := by decide

-- BTC:signet/mixed/fresh/linear
example : history model3 0 [0, 1, 2] = [0, 1, 2] := by decide
example : history model3 0 [0, 2, 1] = [0, 1, 2] := by decide
example : history model3 0 [1, 0, 2] = [0, 1, 2] := by decide
example : history model3 0 [1, 2, 0] = [0, 1, 2] := by decide
example : history model3 0 [2, 0, 1] = [0, 1, 2] := by decide
example : history model3 0 [2, 1, 0] = [0, 1, 2] := by decide

-- BTC:signet/mixed/fresh/fork
example : history model3 0 [0, 1, 3, 2] = [0, 1, 2] := by decide
example : history model3 0 [0, 1, 2, 3] = [0, 1, 2] := by decide
example : history model3 0 [0, 3, 1, 2] = [0, 1, 2] := by decide
example : history model3 0 [0, 3, 2, 1] = [0, 1, 2] := by decide
example : history model3 0 [0, 2, 1, 3] = [0, 1, 2] := by decide
example : history model3 0 [0, 2, 3, 1] = [0, 1, 2] := by decide
example : history model3 0 [1, 0, 3, 2] = [0, 1, 2] := by decide
example : history model3 0 [1, 0, 2, 3] = [0, 1, 2] := by decide
example : history model3 0 [1, 3, 0, 2] = [0, 1, 2] := by decide
example : history model3 0 [1, 3, 2, 0] = [0, 1, 2] := by decide
example : history model3 0 [1, 2, 0, 3] = [0, 1, 2] := by decide
example : history model3 0 [1, 2, 3, 0] = [0, 1, 2] := by decide
example : history model3 0 [3, 0, 1, 2] = [0, 1, 2] := by decide
example : history model3 0 [3, 0, 2, 1] = [0, 1, 2] := by decide
example : history model3 0 [3, 1, 0, 2] = [0, 1, 2] := by decide
example : history model3 0 [3, 1, 2, 0] = [0, 1, 2] := by decide
example : history model3 0 [3, 2, 0, 1] = [0, 1, 2] := by decide
example : history model3 0 [3, 2, 1, 0] = [0, 1, 2] := by decide
example : history model3 0 [2, 0, 1, 3] = [0, 1, 2] := by decide
example : history model3 0 [2, 0, 3, 1] = [0, 1, 2] := by decide
example : history model3 0 [2, 1, 0, 3] = [0, 1, 2] := by decide
example : history model3 0 [2, 1, 3, 0] = [0, 1, 2] := by decide
example : history model3 0 [2, 3, 0, 1] = [0, 1, 2] := by decide
example : history model3 0 [2, 3, 1, 0] = [0, 1, 2] := by decide

-- BTC:signet/mixed/tied/linear
example : history model3 0 [0, 1, 2] = [0, 1, 2] := by decide
example : history model3 0 [0, 2, 1] = [0, 1, 2] := by decide
example : history model3 0 [1, 0, 2] = [0, 1, 2] := by decide
example : history model3 0 [1, 2, 0] = [0, 1, 2] := by decide
example : history model3 0 [2, 0, 1] = [0, 1, 2] := by decide
example : history model3 0 [2, 1, 0] = [0, 1, 2] := by decide

-- BTC:signet/mixed/tied/fork
example : history model3 0 [0, 1, 3, 2] = [0, 1, 2] := by decide
example : history model3 0 [0, 1, 2, 3] = [0, 1, 2] := by decide
example : history model3 0 [0, 3, 1, 2] = [0, 1, 2] := by decide
example : history model3 0 [0, 3, 2, 1] = [0, 1, 2] := by decide
example : history model3 0 [0, 2, 1, 3] = [0, 1, 2] := by decide
example : history model3 0 [0, 2, 3, 1] = [0, 1, 2] := by decide
example : history model3 0 [1, 0, 3, 2] = [0, 1, 2] := by decide
example : history model3 0 [1, 0, 2, 3] = [0, 1, 2] := by decide
example : history model3 0 [1, 3, 0, 2] = [0, 1, 2] := by decide
example : history model3 0 [1, 3, 2, 0] = [0, 1, 2] := by decide
example : history model3 0 [1, 2, 0, 3] = [0, 1, 2] := by decide
example : history model3 0 [1, 2, 3, 0] = [0, 1, 2] := by decide
example : history model3 0 [3, 0, 1, 2] = [0, 1, 2] := by decide
example : history model3 0 [3, 0, 2, 1] = [0, 1, 2] := by decide
example : history model3 0 [3, 1, 0, 2] = [0, 1, 2] := by decide
example : history model3 0 [3, 1, 2, 0] = [0, 1, 2] := by decide
example : history model3 0 [3, 2, 0, 1] = [0, 1, 2] := by decide
example : history model3 0 [3, 2, 1, 0] = [0, 1, 2] := by decide
example : history model3 0 [2, 0, 1, 3] = [0, 1, 2] := by decide
example : history model3 0 [2, 0, 3, 1] = [0, 1, 2] := by decide
example : history model3 0 [2, 1, 0, 3] = [0, 1, 2] := by decide
example : history model3 0 [2, 1, 3, 0] = [0, 1, 2] := by decide
example : history model3 0 [2, 3, 0, 1] = [0, 1, 2] := by decide
example : history model3 0 [2, 3, 1, 0] = [0, 1, 2] := by decide

end Archon.Fixtures
