-- Generated by generate-interleaved-fixtures.mjs; do not edit.
import InterleavedReplay
set_option warningAsError true
namespace Archon.InterleavedFixtures
def model0 : Model := ⟨6, (fun i => [some 5, some 2, some 5, some 1, some 1, some 3].getD i none), fun _ => true, fun _ => 0⟩
def owner0 : Nat → Nat := (fun i => [1, 0, 1, 2, 3, 4].getD i 0)
example : interleavedInsert model0 owner0 5 2 [] = [2] := by decide
example : interleavedInsert model0 owner0 5 3 [2] = [2, 3] := by decide
example : interleavedInsert model0 owner0 5 4 [2, 3] = [2, 3] := by decide
example : interleavedInsert model0 owner0 5 1 [2, 3] = [2, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 5 [2, 3, 1] = [2, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 0 [2, 3, 1] = [0, 3, 1] := by decide
example : interleavedPass model0 owner0 5 [2, 3, 4, 1, 5, 0] [] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 2 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 3 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 4 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 1 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 5 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 0 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedPass model0 owner0 5 [2, 3, 4, 1, 5, 0] [0, 3, 1] = [0, 3, 1] := by decide
example : (interleavedPass model0 owner0 5 [2, 3, 4, 1, 5, 0] [0, 3, 1]).headD model0.size = winner model0 5 [2, 3, 4, 1, 5, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : (interleavedPass model0 owner0 5 [2, 3, 4, 1, 5, 0] []).headD model0.size = winner model0 5 [2, 3, 4, 1, 5, 0] := interleaved_empty_head _ _ _ _
example : interleavedInsert model0 owner0 5 0 [] = [0] := by decide
example : interleavedInsert model0 owner0 5 5 [0] = [0] := by decide
example : interleavedInsert model0 owner0 5 1 [0] = [0] := by decide
example : interleavedInsert model0 owner0 5 4 [0] = [0, 4] := by decide
example : interleavedInsert model0 owner0 5 3 [0, 4] = [0, 3] := by decide
example : interleavedInsert model0 owner0 5 2 [0, 3] = [0, 3] := by decide
example : interleavedPass model0 owner0 5 [0, 5, 1, 4, 3, 2] [] = [0, 3] := by decide
example : interleavedInsert model0 owner0 5 0 [0, 3] = [0, 3] := by decide
example : interleavedInsert model0 owner0 5 5 [0, 3] = [0, 3] := by decide
example : interleavedInsert model0 owner0 5 1 [0, 3] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 4 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 3 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 2 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedPass model0 owner0 5 [0, 5, 1, 4, 3, 2] [0, 3] = [0, 3, 1] := by decide
example : (interleavedPass model0 owner0 5 [0, 5, 1, 4, 3, 2] [0, 3]).headD model0.size = winner model0 5 [0, 5, 1, 4, 3, 2] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : interleavedInsert model0 owner0 5 0 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 5 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 1 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 4 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 3 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 2 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedPass model0 owner0 5 [0, 5, 1, 4, 3, 2] [0, 3, 1] = [0, 3, 1] := by decide
example : (interleavedPass model0 owner0 5 [0, 5, 1, 4, 3, 2] [0, 3, 1]).headD model0.size = winner model0 5 [0, 5, 1, 4, 3, 2] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : (interleavedPass model0 owner0 5 [0, 5, 1, 4, 3, 2] []).headD model0.size = winner model0 5 [0, 5, 1, 4, 3, 2] := interleaved_empty_head _ _ _ _
example : interleavedInsert model0 owner0 5 5 [] = [] := by decide
example : interleavedInsert model0 owner0 5 1 [] = [] := by decide
example : interleavedInsert model0 owner0 5 4 [] = [] := by decide
example : interleavedInsert model0 owner0 5 3 [] = [] := by decide
example : interleavedInsert model0 owner0 5 2 [] = [2] := by decide
example : interleavedInsert model0 owner0 5 0 [2] = [0] := by decide
example : interleavedPass model0 owner0 5 [5, 1, 4, 3, 2, 0] [] = [0] := by decide
example : interleavedInsert model0 owner0 5 5 [0] = [0] := by decide
example : interleavedInsert model0 owner0 5 1 [0] = [0] := by decide
example : interleavedInsert model0 owner0 5 4 [0] = [0, 4] := by decide
example : interleavedInsert model0 owner0 5 3 [0, 4] = [0, 3] := by decide
example : interleavedInsert model0 owner0 5 2 [0, 3] = [0, 3] := by decide
example : interleavedInsert model0 owner0 5 0 [0, 3] = [0, 3] := by decide
example : interleavedPass model0 owner0 5 [5, 1, 4, 3, 2, 0] [0] = [0, 3] := by decide
example : (interleavedPass model0 owner0 5 [5, 1, 4, 3, 2, 0] [0]).headD model0.size = winner model0 5 [5, 1, 4, 3, 2, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : interleavedInsert model0 owner0 5 5 [0, 3] = [0, 3] := by decide
example : interleavedInsert model0 owner0 5 1 [0, 3] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 4 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 3 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 2 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 0 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedPass model0 owner0 5 [5, 1, 4, 3, 2, 0] [0, 3] = [0, 3, 1] := by decide
example : (interleavedPass model0 owner0 5 [5, 1, 4, 3, 2, 0] [0, 3]).headD model0.size = winner model0 5 [5, 1, 4, 3, 2, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : interleavedInsert model0 owner0 5 5 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 1 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 4 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 3 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 2 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 0 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedPass model0 owner0 5 [5, 1, 4, 3, 2, 0] [0, 3, 1] = [0, 3, 1] := by decide
example : (interleavedPass model0 owner0 5 [5, 1, 4, 3, 2, 0] [0, 3, 1]).headD model0.size = winner model0 5 [5, 1, 4, 3, 2, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : (interleavedPass model0 owner0 5 [5, 1, 4, 3, 2, 0] []).headD model0.size = winner model0 5 [5, 1, 4, 3, 2, 0] := interleaved_empty_head _ _ _ _
example : interleavedInsert model0 owner0 5 0 [] = [0] := by decide
example : interleavedInsert model0 owner0 5 1 [0] = [0] := by decide
example : interleavedInsert model0 owner0 5 3 [0] = [0, 3] := by decide
example : interleavedInsert model0 owner0 5 5 [0, 3] = [0, 3] := by decide
example : interleavedInsert model0 owner0 5 4 [0, 3] = [0, 3] := by decide
example : interleavedInsert model0 owner0 5 2 [0, 3] = [0, 3] := by decide
example : interleavedPass model0 owner0 5 [0, 1, 3, 5, 4, 2] [] = [0, 3] := by decide
example : interleavedInsert model0 owner0 5 0 [0, 3] = [0, 3] := by decide
example : interleavedInsert model0 owner0 5 1 [0, 3] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 3 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 5 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 4 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 2 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedPass model0 owner0 5 [0, 1, 3, 5, 4, 2] [0, 3] = [0, 3, 1] := by decide
example : (interleavedPass model0 owner0 5 [0, 1, 3, 5, 4, 2] [0, 3]).headD model0.size = winner model0 5 [0, 1, 3, 5, 4, 2] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : interleavedInsert model0 owner0 5 0 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 1 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 3 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 5 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 4 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 2 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedPass model0 owner0 5 [0, 1, 3, 5, 4, 2] [0, 3, 1] = [0, 3, 1] := by decide
example : (interleavedPass model0 owner0 5 [0, 1, 3, 5, 4, 2] [0, 3, 1]).headD model0.size = winner model0 5 [0, 1, 3, 5, 4, 2] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : (interleavedPass model0 owner0 5 [0, 1, 3, 5, 4, 2] []).headD model0.size = winner model0 5 [0, 1, 3, 5, 4, 2] := interleaved_empty_head _ _ _ _
example : interleavedInsert model0 owner0 5 4 [] = [] := by decide
example : interleavedInsert model0 owner0 5 5 [] = [] := by decide
example : interleavedInsert model0 owner0 5 2 [] = [2] := by decide
example : interleavedInsert model0 owner0 5 3 [2] = [2, 3] := by decide
example : interleavedInsert model0 owner0 5 1 [2, 3] = [2, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 0 [2, 3, 1] = [0, 3, 1] := by decide
example : interleavedPass model0 owner0 5 [4, 5, 2, 3, 1, 0] [] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 4 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 5 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 2 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 3 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 1 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 0 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedPass model0 owner0 5 [4, 5, 2, 3, 1, 0] [0, 3, 1] = [0, 3, 1] := by decide
example : (interleavedPass model0 owner0 5 [4, 5, 2, 3, 1, 0] [0, 3, 1]).headD model0.size = winner model0 5 [4, 5, 2, 3, 1, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : (interleavedPass model0 owner0 5 [4, 5, 2, 3, 1, 0] []).headD model0.size = winner model0 5 [4, 5, 2, 3, 1, 0] := interleaved_empty_head _ _ _ _
example : interleavedInsert model0 owner0 5 3 [] = [] := by decide
example : interleavedInsert model0 owner0 5 1 [] = [] := by decide
example : interleavedInsert model0 owner0 5 2 [] = [2] := by decide
example : interleavedInsert model0 owner0 5 4 [2] = [2, 4] := by decide
example : interleavedInsert model0 owner0 5 5 [2, 4] = [2, 4, 5] := by decide
example : interleavedInsert model0 owner0 5 0 [2, 4, 5] = [0, 4, 5] := by decide
example : interleavedPass model0 owner0 5 [3, 1, 2, 4, 5, 0] [] = [0, 4, 5] := by decide
example : interleavedInsert model0 owner0 5 3 [0, 4, 5] = [0, 3] := by decide
example : interleavedInsert model0 owner0 5 1 [0, 3] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 2 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 4 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 5 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 0 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedPass model0 owner0 5 [3, 1, 2, 4, 5, 0] [0, 4, 5] = [0, 3, 1] := by decide
example : (interleavedPass model0 owner0 5 [3, 1, 2, 4, 5, 0] [0, 4, 5]).headD model0.size = winner model0 5 [3, 1, 2, 4, 5, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : interleavedInsert model0 owner0 5 3 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 1 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 2 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 4 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 5 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedInsert model0 owner0 5 0 [0, 3, 1] = [0, 3, 1] := by decide
example : interleavedPass model0 owner0 5 [3, 1, 2, 4, 5, 0] [0, 3, 1] = [0, 3, 1] := by decide
example : (interleavedPass model0 owner0 5 [3, 1, 2, 4, 5, 0] [0, 3, 1]).headD model0.size = winner model0 5 [3, 1, 2, 4, 5, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : (interleavedPass model0 owner0 5 [3, 1, 2, 4, 5, 0] []).headD model0.size = winner model0 5 [3, 1, 2, 4, 5, 0] := interleaved_empty_head _ _ _ _
def model1 : Model := ⟨8, (fun i => [some 1, some 5, some 1, some 2, some 5, some 1, some 1, some 3].getD i none), fun _ => true, fun _ => 0⟩
def owner1 : Nat → Nat := (fun i => [3, 1, 2, 0, 1, 2, 3, 4].getD i 0)
example : interleavedInsert model1 owner1 5 4 [] = [4] := by decide
example : interleavedInsert model1 owner1 5 5 [4] = [4, 5] := by decide
example : interleavedInsert model1 owner1 5 6 [4, 5] = [4, 5] := by decide
example : interleavedInsert model1 owner1 5 3 [4, 5] = [4, 5, 3] := by decide
example : interleavedInsert model1 owner1 5 7 [4, 5, 3] = [4, 5, 3] := by decide
example : interleavedInsert model1 owner1 5 1 [4, 5, 3] = [1, 5, 3] := by decide
example : interleavedInsert model1 owner1 5 2 [1, 5, 3] = [1, 2, 3] := by decide
example : interleavedInsert model1 owner1 5 0 [1, 2, 3] = [1, 0] := by decide
example : interleavedPass model1 owner1 5 [4, 5, 6, 3, 7, 1, 2, 0] [] = [1, 0] := by decide
example : interleavedInsert model1 owner1 5 4 [1, 0] = [1, 0] := by decide
example : interleavedInsert model1 owner1 5 5 [1, 0] = [1, 0] := by decide
example : interleavedInsert model1 owner1 5 6 [1, 0] = [1, 0] := by decide
example : interleavedInsert model1 owner1 5 3 [1, 0] = [1, 0] := by decide
example : interleavedInsert model1 owner1 5 7 [1, 0] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 1 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 2 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 0 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedPass model1 owner1 5 [4, 5, 6, 3, 7, 1, 2, 0] [1, 0] = [1, 0, 7] := by decide
example : (interleavedPass model1 owner1 5 [4, 5, 6, 3, 7, 1, 2, 0] [1, 0]).headD model1.size = winner model1 5 [4, 5, 6, 3, 7, 1, 2, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : interleavedInsert model1 owner1 5 4 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 5 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 6 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 3 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 7 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 1 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 2 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 0 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedPass model1 owner1 5 [4, 5, 6, 3, 7, 1, 2, 0] [1, 0, 7] = [1, 0, 7] := by decide
example : (interleavedPass model1 owner1 5 [4, 5, 6, 3, 7, 1, 2, 0] [1, 0, 7]).headD model1.size = winner model1 5 [4, 5, 6, 3, 7, 1, 2, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : (interleavedPass model1 owner1 5 [4, 5, 6, 3, 7, 1, 2, 0] []).headD model1.size = winner model1 5 [4, 5, 6, 3, 7, 1, 2, 0] := interleaved_empty_head _ _ _ _
example : interleavedInsert model1 owner1 5 0 [] = [] := by decide
example : interleavedInsert model1 owner1 5 2 [] = [] := by decide
example : interleavedInsert model1 owner1 5 1 [] = [1] := by decide
example : interleavedInsert model1 owner1 5 7 [1] = [1] := by decide
example : interleavedInsert model1 owner1 5 3 [1] = [1] := by decide
example : interleavedInsert model1 owner1 5 6 [1] = [1, 6] := by decide
example : interleavedInsert model1 owner1 5 5 [1, 6] = [1, 5] := by decide
example : interleavedInsert model1 owner1 5 4 [1, 5] = [1, 5] := by decide
example : interleavedPass model1 owner1 5 [0, 2, 1, 7, 3, 6, 5, 4] [] = [1, 5] := by decide
example : interleavedInsert model1 owner1 5 0 [1, 5] = [1, 0] := by decide
example : interleavedInsert model1 owner1 5 2 [1, 0] = [1, 0] := by decide
example : interleavedInsert model1 owner1 5 1 [1, 0] = [1, 0] := by decide
example : interleavedInsert model1 owner1 5 7 [1, 0] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 3 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 6 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 5 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 4 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedPass model1 owner1 5 [0, 2, 1, 7, 3, 6, 5, 4] [1, 5] = [1, 0, 7] := by decide
example : (interleavedPass model1 owner1 5 [0, 2, 1, 7, 3, 6, 5, 4] [1, 5]).headD model1.size = winner model1 5 [0, 2, 1, 7, 3, 6, 5, 4] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : interleavedInsert model1 owner1 5 0 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 2 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 1 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 7 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 3 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 6 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 5 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 4 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedPass model1 owner1 5 [0, 2, 1, 7, 3, 6, 5, 4] [1, 0, 7] = [1, 0, 7] := by decide
example : (interleavedPass model1 owner1 5 [0, 2, 1, 7, 3, 6, 5, 4] [1, 0, 7]).headD model1.size = winner model1 5 [0, 2, 1, 7, 3, 6, 5, 4] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : (interleavedPass model1 owner1 5 [0, 2, 1, 7, 3, 6, 5, 4] []).headD model1.size = winner model1 5 [0, 2, 1, 7, 3, 6, 5, 4] := interleaved_empty_head _ _ _ _
example : interleavedInsert model1 owner1 5 7 [] = [] := by decide
example : interleavedInsert model1 owner1 5 3 [] = [] := by decide
example : interleavedInsert model1 owner1 5 6 [] = [] := by decide
example : interleavedInsert model1 owner1 5 5 [] = [] := by decide
example : interleavedInsert model1 owner1 5 4 [] = [4] := by decide
example : interleavedInsert model1 owner1 5 1 [4] = [1] := by decide
example : interleavedInsert model1 owner1 5 2 [1] = [1, 2] := by decide
example : interleavedInsert model1 owner1 5 0 [1, 2] = [1, 0] := by decide
example : interleavedPass model1 owner1 5 [7, 3, 6, 5, 4, 1, 2, 0] [] = [1, 0] := by decide
example : interleavedInsert model1 owner1 5 7 [1, 0] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 3 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 6 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 5 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 4 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 1 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 2 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 0 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedPass model1 owner1 5 [7, 3, 6, 5, 4, 1, 2, 0] [1, 0] = [1, 0, 7] := by decide
example : (interleavedPass model1 owner1 5 [7, 3, 6, 5, 4, 1, 2, 0] [1, 0]).headD model1.size = winner model1 5 [7, 3, 6, 5, 4, 1, 2, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : interleavedInsert model1 owner1 5 7 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 3 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 6 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 5 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 4 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 1 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 2 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 0 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedPass model1 owner1 5 [7, 3, 6, 5, 4, 1, 2, 0] [1, 0, 7] = [1, 0, 7] := by decide
example : (interleavedPass model1 owner1 5 [7, 3, 6, 5, 4, 1, 2, 0] [1, 0, 7]).headD model1.size = winner model1 5 [7, 3, 6, 5, 4, 1, 2, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : (interleavedPass model1 owner1 5 [7, 3, 6, 5, 4, 1, 2, 0] []).headD model1.size = winner model1 5 [7, 3, 6, 5, 4, 1, 2, 0] := interleaved_empty_head _ _ _ _
example : interleavedInsert model1 owner1 5 1 [] = [1] := by decide
example : interleavedInsert model1 owner1 5 2 [1] = [1, 2] := by decide
example : interleavedInsert model1 owner1 5 0 [1, 2] = [1, 0] := by decide
example : interleavedInsert model1 owner1 5 3 [1, 0] = [1, 0] := by decide
example : interleavedInsert model1 owner1 5 5 [1, 0] = [1, 0] := by decide
example : interleavedInsert model1 owner1 5 7 [1, 0] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 6 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 4 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedPass model1 owner1 5 [1, 2, 0, 3, 5, 7, 6, 4] [] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 1 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 2 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 0 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 3 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 5 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 7 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 6 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 4 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedPass model1 owner1 5 [1, 2, 0, 3, 5, 7, 6, 4] [1, 0, 7] = [1, 0, 7] := by decide
example : (interleavedPass model1 owner1 5 [1, 2, 0, 3, 5, 7, 6, 4] [1, 0, 7]).headD model1.size = winner model1 5 [1, 2, 0, 3, 5, 7, 6, 4] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : (interleavedPass model1 owner1 5 [1, 2, 0, 3, 5, 7, 6, 4] []).headD model1.size = winner model1 5 [1, 2, 0, 3, 5, 7, 6, 4] := interleaved_empty_head _ _ _ _
example : interleavedInsert model1 owner1 5 6 [] = [] := by decide
example : interleavedInsert model1 owner1 5 7 [] = [] := by decide
example : interleavedInsert model1 owner1 5 4 [] = [4] := by decide
example : interleavedInsert model1 owner1 5 5 [4] = [4, 5] := by decide
example : interleavedInsert model1 owner1 5 3 [4, 5] = [4, 5, 3] := by decide
example : interleavedInsert model1 owner1 5 0 [4, 5, 3] = [4, 0] := by decide
example : interleavedInsert model1 owner1 5 2 [4, 0] = [4, 0] := by decide
example : interleavedInsert model1 owner1 5 1 [4, 0] = [1, 0] := by decide
example : interleavedPass model1 owner1 5 [6, 7, 4, 5, 3, 0, 2, 1] [] = [1, 0] := by decide
example : interleavedInsert model1 owner1 5 6 [1, 0] = [1, 0] := by decide
example : interleavedInsert model1 owner1 5 7 [1, 0] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 4 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 5 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 3 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 0 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 2 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 1 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedPass model1 owner1 5 [6, 7, 4, 5, 3, 0, 2, 1] [1, 0] = [1, 0, 7] := by decide
example : (interleavedPass model1 owner1 5 [6, 7, 4, 5, 3, 0, 2, 1] [1, 0]).headD model1.size = winner model1 5 [6, 7, 4, 5, 3, 0, 2, 1] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : interleavedInsert model1 owner1 5 6 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 7 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 4 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 5 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 3 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 0 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 2 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 1 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedPass model1 owner1 5 [6, 7, 4, 5, 3, 0, 2, 1] [1, 0, 7] = [1, 0, 7] := by decide
example : (interleavedPass model1 owner1 5 [6, 7, 4, 5, 3, 0, 2, 1] [1, 0, 7]).headD model1.size = winner model1 5 [6, 7, 4, 5, 3, 0, 2, 1] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : (interleavedPass model1 owner1 5 [6, 7, 4, 5, 3, 0, 2, 1] []).headD model1.size = winner model1 5 [6, 7, 4, 5, 3, 0, 2, 1] := interleaved_empty_head _ _ _ _
example : interleavedInsert model1 owner1 5 5 [] = [] := by decide
example : interleavedInsert model1 owner1 5 3 [] = [] := by decide
example : interleavedInsert model1 owner1 5 4 [] = [4] := by decide
example : interleavedInsert model1 owner1 5 6 [4] = [4, 6] := by decide
example : interleavedInsert model1 owner1 5 7 [4, 6] = [4, 6, 7] := by decide
example : interleavedInsert model1 owner1 5 1 [4, 6, 7] = [1, 6, 7] := by decide
example : interleavedInsert model1 owner1 5 2 [1, 6, 7] = [1, 2] := by decide
example : interleavedInsert model1 owner1 5 0 [1, 2] = [1, 0] := by decide
example : interleavedPass model1 owner1 5 [5, 3, 4, 6, 7, 1, 2, 0] [] = [1, 0] := by decide
example : interleavedInsert model1 owner1 5 5 [1, 0] = [1, 0] := by decide
example : interleavedInsert model1 owner1 5 3 [1, 0] = [1, 0] := by decide
example : interleavedInsert model1 owner1 5 4 [1, 0] = [1, 0] := by decide
example : interleavedInsert model1 owner1 5 6 [1, 0] = [1, 0] := by decide
example : interleavedInsert model1 owner1 5 7 [1, 0] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 1 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 2 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 0 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedPass model1 owner1 5 [5, 3, 4, 6, 7, 1, 2, 0] [1, 0] = [1, 0, 7] := by decide
example : (interleavedPass model1 owner1 5 [5, 3, 4, 6, 7, 1, 2, 0] [1, 0]).headD model1.size = winner model1 5 [5, 3, 4, 6, 7, 1, 2, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : interleavedInsert model1 owner1 5 5 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 3 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 4 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 6 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 7 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 1 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 2 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedInsert model1 owner1 5 0 [1, 0, 7] = [1, 0, 7] := by decide
example : interleavedPass model1 owner1 5 [5, 3, 4, 6, 7, 1, 2, 0] [1, 0, 7] = [1, 0, 7] := by decide
example : (interleavedPass model1 owner1 5 [5, 3, 4, 6, 7, 1, 2, 0] [1, 0, 7]).headD model1.size = winner model1 5 [5, 3, 4, 6, 7, 1, 2, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : (interleavedPass model1 owner1 5 [5, 3, 4, 6, 7, 1, 2, 0] []).headD model1.size = winner model1 5 [5, 3, 4, 6, 7, 1, 2, 0] := interleaved_empty_head _ _ _ _
def model2 : Model := ⟨9, (fun i => [some 1, some 1, some 5, some 1, some 2, some 5, some 1, some 1, some 3].getD i none), fun _ => true, fun _ => 0⟩
def owner2 : Nat → Nat := (fun i => [2, 3, 1, 2, 0, 1, 2, 3, 4].getD i 0)
example : interleavedInsert model2 owner2 5 5 [] = [5] := by decide
example : interleavedInsert model2 owner2 5 6 [5] = [5, 6] := by decide
example : interleavedInsert model2 owner2 5 7 [5, 6] = [5, 6] := by decide
example : interleavedInsert model2 owner2 5 4 [5, 6] = [5, 6, 4] := by decide
example : interleavedInsert model2 owner2 5 8 [5, 6, 4] = [5, 6, 4] := by decide
example : interleavedInsert model2 owner2 5 2 [5, 6, 4] = [2, 6, 4] := by decide
example : interleavedInsert model2 owner2 5 3 [2, 6, 4] = [2, 3, 4] := by decide
example : interleavedInsert model2 owner2 5 1 [2, 3, 4] = [2, 1] := by decide
example : interleavedInsert model2 owner2 5 0 [2, 1] = [2, 0] := by decide
example : interleavedPass model2 owner2 5 [5, 6, 7, 4, 8, 2, 3, 1, 0] [] = [2, 0] := by decide
example : interleavedInsert model2 owner2 5 5 [2, 0] = [2, 0] := by decide
example : interleavedInsert model2 owner2 5 6 [2, 0] = [2, 0] := by decide
example : interleavedInsert model2 owner2 5 7 [2, 0] = [2, 0] := by decide
example : interleavedInsert model2 owner2 5 4 [2, 0] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 8 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 2 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 3 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 1 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 0 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedPass model2 owner2 5 [5, 6, 7, 4, 8, 2, 3, 1, 0] [2, 0] = [2, 0, 4] := by decide
example : (interleavedPass model2 owner2 5 [5, 6, 7, 4, 8, 2, 3, 1, 0] [2, 0]).headD model2.size = winner model2 5 [5, 6, 7, 4, 8, 2, 3, 1, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : interleavedInsert model2 owner2 5 5 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 6 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 7 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 4 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 8 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 2 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 3 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 1 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 0 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedPass model2 owner2 5 [5, 6, 7, 4, 8, 2, 3, 1, 0] [2, 0, 4] = [2, 0, 4] := by decide
example : (interleavedPass model2 owner2 5 [5, 6, 7, 4, 8, 2, 3, 1, 0] [2, 0, 4]).headD model2.size = winner model2 5 [5, 6, 7, 4, 8, 2, 3, 1, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : (interleavedPass model2 owner2 5 [5, 6, 7, 4, 8, 2, 3, 1, 0] []).headD model2.size = winner model2 5 [5, 6, 7, 4, 8, 2, 3, 1, 0] := interleaved_empty_head _ _ _ _
example : interleavedInsert model2 owner2 5 0 [] = [] := by decide
example : interleavedInsert model2 owner2 5 1 [] = [] := by decide
example : interleavedInsert model2 owner2 5 3 [] = [] := by decide
example : interleavedInsert model2 owner2 5 2 [] = [2] := by decide
example : interleavedInsert model2 owner2 5 8 [2] = [2] := by decide
example : interleavedInsert model2 owner2 5 4 [2] = [2] := by decide
example : interleavedInsert model2 owner2 5 7 [2] = [2, 7] := by decide
example : interleavedInsert model2 owner2 5 6 [2, 7] = [2, 6] := by decide
example : interleavedInsert model2 owner2 5 5 [2, 6] = [2, 6] := by decide
example : interleavedPass model2 owner2 5 [0, 1, 3, 2, 8, 4, 7, 6, 5] [] = [2, 6] := by decide
example : interleavedInsert model2 owner2 5 0 [2, 6] = [2, 0] := by decide
example : interleavedInsert model2 owner2 5 1 [2, 0] = [2, 0] := by decide
example : interleavedInsert model2 owner2 5 3 [2, 0] = [2, 0] := by decide
example : interleavedInsert model2 owner2 5 2 [2, 0] = [2, 0] := by decide
example : interleavedInsert model2 owner2 5 8 [2, 0] = [2, 0] := by decide
example : interleavedInsert model2 owner2 5 4 [2, 0] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 7 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 6 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 5 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedPass model2 owner2 5 [0, 1, 3, 2, 8, 4, 7, 6, 5] [2, 6] = [2, 0, 4] := by decide
example : (interleavedPass model2 owner2 5 [0, 1, 3, 2, 8, 4, 7, 6, 5] [2, 6]).headD model2.size = winner model2 5 [0, 1, 3, 2, 8, 4, 7, 6, 5] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : interleavedInsert model2 owner2 5 0 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 1 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 3 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 2 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 8 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 4 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 7 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 6 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 5 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedPass model2 owner2 5 [0, 1, 3, 2, 8, 4, 7, 6, 5] [2, 0, 4] = [2, 0, 4] := by decide
example : (interleavedPass model2 owner2 5 [0, 1, 3, 2, 8, 4, 7, 6, 5] [2, 0, 4]).headD model2.size = winner model2 5 [0, 1, 3, 2, 8, 4, 7, 6, 5] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : (interleavedPass model2 owner2 5 [0, 1, 3, 2, 8, 4, 7, 6, 5] []).headD model2.size = winner model2 5 [0, 1, 3, 2, 8, 4, 7, 6, 5] := interleaved_empty_head _ _ _ _
example : interleavedInsert model2 owner2 5 8 [] = [] := by decide
example : interleavedInsert model2 owner2 5 4 [] = [] := by decide
example : interleavedInsert model2 owner2 5 7 [] = [] := by decide
example : interleavedInsert model2 owner2 5 6 [] = [] := by decide
example : interleavedInsert model2 owner2 5 5 [] = [5] := by decide
example : interleavedInsert model2 owner2 5 2 [5] = [2] := by decide
example : interleavedInsert model2 owner2 5 3 [2] = [2, 3] := by decide
example : interleavedInsert model2 owner2 5 1 [2, 3] = [2, 1] := by decide
example : interleavedInsert model2 owner2 5 0 [2, 1] = [2, 0] := by decide
example : interleavedPass model2 owner2 5 [8, 4, 7, 6, 5, 2, 3, 1, 0] [] = [2, 0] := by decide
example : interleavedInsert model2 owner2 5 8 [2, 0] = [2, 0] := by decide
example : interleavedInsert model2 owner2 5 4 [2, 0] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 7 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 6 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 5 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 2 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 3 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 1 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 0 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedPass model2 owner2 5 [8, 4, 7, 6, 5, 2, 3, 1, 0] [2, 0] = [2, 0, 4] := by decide
example : (interleavedPass model2 owner2 5 [8, 4, 7, 6, 5, 2, 3, 1, 0] [2, 0]).headD model2.size = winner model2 5 [8, 4, 7, 6, 5, 2, 3, 1, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : interleavedInsert model2 owner2 5 8 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 4 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 7 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 6 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 5 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 2 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 3 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 1 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 0 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedPass model2 owner2 5 [8, 4, 7, 6, 5, 2, 3, 1, 0] [2, 0, 4] = [2, 0, 4] := by decide
example : (interleavedPass model2 owner2 5 [8, 4, 7, 6, 5, 2, 3, 1, 0] [2, 0, 4]).headD model2.size = winner model2 5 [8, 4, 7, 6, 5, 2, 3, 1, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : (interleavedPass model2 owner2 5 [8, 4, 7, 6, 5, 2, 3, 1, 0] []).headD model2.size = winner model2 5 [8, 4, 7, 6, 5, 2, 3, 1, 0] := interleaved_empty_head _ _ _ _
example : interleavedInsert model2 owner2 5 2 [] = [2] := by decide
example : interleavedInsert model2 owner2 5 3 [2] = [2, 3] := by decide
example : interleavedInsert model2 owner2 5 1 [2, 3] = [2, 1] := by decide
example : interleavedInsert model2 owner2 5 0 [2, 1] = [2, 0] := by decide
example : interleavedInsert model2 owner2 5 4 [2, 0] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 6 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 8 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 7 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 5 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedPass model2 owner2 5 [2, 3, 1, 0, 4, 6, 8, 7, 5] [] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 2 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 3 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 1 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 0 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 4 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 6 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 8 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 7 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 5 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedPass model2 owner2 5 [2, 3, 1, 0, 4, 6, 8, 7, 5] [2, 0, 4] = [2, 0, 4] := by decide
example : (interleavedPass model2 owner2 5 [2, 3, 1, 0, 4, 6, 8, 7, 5] [2, 0, 4]).headD model2.size = winner model2 5 [2, 3, 1, 0, 4, 6, 8, 7, 5] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : (interleavedPass model2 owner2 5 [2, 3, 1, 0, 4, 6, 8, 7, 5] []).headD model2.size = winner model2 5 [2, 3, 1, 0, 4, 6, 8, 7, 5] := interleaved_empty_head _ _ _ _
example : interleavedInsert model2 owner2 5 7 [] = [] := by decide
example : interleavedInsert model2 owner2 5 8 [] = [] := by decide
example : interleavedInsert model2 owner2 5 5 [] = [5] := by decide
example : interleavedInsert model2 owner2 5 6 [5] = [5, 6] := by decide
example : interleavedInsert model2 owner2 5 4 [5, 6] = [5, 6, 4] := by decide
example : interleavedInsert model2 owner2 5 0 [5, 6, 4] = [5, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 1 [5, 0, 4] = [5, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 3 [5, 0, 4] = [5, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 2 [5, 0, 4] = [2, 0, 4] := by decide
example : interleavedPass model2 owner2 5 [7, 8, 5, 6, 4, 0, 1, 3, 2] [] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 7 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 8 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 5 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 6 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 4 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 0 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 1 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 3 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 2 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedPass model2 owner2 5 [7, 8, 5, 6, 4, 0, 1, 3, 2] [2, 0, 4] = [2, 0, 4] := by decide
example : (interleavedPass model2 owner2 5 [7, 8, 5, 6, 4, 0, 1, 3, 2] [2, 0, 4]).headD model2.size = winner model2 5 [7, 8, 5, 6, 4, 0, 1, 3, 2] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : (interleavedPass model2 owner2 5 [7, 8, 5, 6, 4, 0, 1, 3, 2] []).headD model2.size = winner model2 5 [7, 8, 5, 6, 4, 0, 1, 3, 2] := interleaved_empty_head _ _ _ _
example : interleavedInsert model2 owner2 5 6 [] = [] := by decide
example : interleavedInsert model2 owner2 5 4 [] = [] := by decide
example : interleavedInsert model2 owner2 5 5 [] = [5] := by decide
example : interleavedInsert model2 owner2 5 7 [5] = [5, 7] := by decide
example : interleavedInsert model2 owner2 5 8 [5, 7] = [5, 7, 8] := by decide
example : interleavedInsert model2 owner2 5 2 [5, 7, 8] = [2, 7, 8] := by decide
example : interleavedInsert model2 owner2 5 3 [2, 7, 8] = [2, 3] := by decide
example : interleavedInsert model2 owner2 5 1 [2, 3] = [2, 1] := by decide
example : interleavedInsert model2 owner2 5 0 [2, 1] = [2, 0] := by decide
example : interleavedPass model2 owner2 5 [6, 4, 5, 7, 8, 2, 3, 1, 0] [] = [2, 0] := by decide
example : interleavedInsert model2 owner2 5 6 [2, 0] = [2, 0] := by decide
example : interleavedInsert model2 owner2 5 4 [2, 0] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 5 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 7 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 8 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 2 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 3 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 1 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 0 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedPass model2 owner2 5 [6, 4, 5, 7, 8, 2, 3, 1, 0] [2, 0] = [2, 0, 4] := by decide
example : (interleavedPass model2 owner2 5 [6, 4, 5, 7, 8, 2, 3, 1, 0] [2, 0]).headD model2.size = winner model2 5 [6, 4, 5, 7, 8, 2, 3, 1, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : interleavedInsert model2 owner2 5 6 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 4 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 5 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 7 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 8 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 2 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 3 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 1 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model2 owner2 5 0 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedPass model2 owner2 5 [6, 4, 5, 7, 8, 2, 3, 1, 0] [2, 0, 4] = [2, 0, 4] := by decide
example : (interleavedPass model2 owner2 5 [6, 4, 5, 7, 8, 2, 3, 1, 0] [2, 0, 4]).headD model2.size = winner model2 5 [6, 4, 5, 7, 8, 2, 3, 1, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : (interleavedPass model2 owner2 5 [6, 4, 5, 7, 8, 2, 3, 1, 0] []).headD model2.size = winner model2 5 [6, 4, 5, 7, 8, 2, 3, 1, 0] := interleaved_empty_head _ _ _ _
def model3 : Model := ⟨6, (fun i => [some 5, some 1, some 4, some 3, some 4, some 5].getD i none), fun _ => true, fun _ => 0⟩
def owner3 : Nat → Nat := (fun i => [4, 0, 1, 2, 3, 4].getD i 0)
example : interleavedInsert model3 owner3 5 5 [] = [5] := by decide
example : interleavedInsert model3 owner3 5 2 [5] = [5, 2] := by decide
example : interleavedInsert model3 owner3 5 4 [5, 2] = [5, 2] := by decide
example : interleavedInsert model3 owner3 5 1 [5, 2] = [5, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 3 [5, 2, 1] = [5, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 0 [5, 2, 1] = [0, 2, 1] := by decide
example : interleavedPass model3 owner3 5 [5, 2, 4, 1, 3, 0] [] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 5 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 2 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 4 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 1 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 3 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 0 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedPass model3 owner3 5 [5, 2, 4, 1, 3, 0] [0, 2, 1] = [0, 2, 1] := by decide
example : (interleavedPass model3 owner3 5 [5, 2, 4, 1, 3, 0] [0, 2, 1]).headD model3.size = winner model3 5 [5, 2, 4, 1, 3, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : (interleavedPass model3 owner3 5 [5, 2, 4, 1, 3, 0] []).headD model3.size = winner model3 5 [5, 2, 4, 1, 3, 0] := interleaved_empty_head _ _ _ _
example : interleavedInsert model3 owner3 5 0 [] = [0] := by decide
example : interleavedInsert model3 owner3 5 3 [0] = [0] := by decide
example : interleavedInsert model3 owner3 5 1 [0] = [0] := by decide
example : interleavedInsert model3 owner3 5 4 [0] = [0, 4] := by decide
example : interleavedInsert model3 owner3 5 2 [0, 4] = [0, 2] := by decide
example : interleavedInsert model3 owner3 5 5 [0, 2] = [0, 2] := by decide
example : interleavedPass model3 owner3 5 [0, 3, 1, 4, 2, 5] [] = [0, 2] := by decide
example : interleavedInsert model3 owner3 5 0 [0, 2] = [0, 2] := by decide
example : interleavedInsert model3 owner3 5 3 [0, 2] = [0, 2] := by decide
example : interleavedInsert model3 owner3 5 1 [0, 2] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 4 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 2 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 5 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedPass model3 owner3 5 [0, 3, 1, 4, 2, 5] [0, 2] = [0, 2, 1] := by decide
example : (interleavedPass model3 owner3 5 [0, 3, 1, 4, 2, 5] [0, 2]).headD model3.size = winner model3 5 [0, 3, 1, 4, 2, 5] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : interleavedInsert model3 owner3 5 0 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 3 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 1 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 4 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 2 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 5 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedPass model3 owner3 5 [0, 3, 1, 4, 2, 5] [0, 2, 1] = [0, 2, 1] := by decide
example : (interleavedPass model3 owner3 5 [0, 3, 1, 4, 2, 5] [0, 2, 1]).headD model3.size = winner model3 5 [0, 3, 1, 4, 2, 5] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : (interleavedPass model3 owner3 5 [0, 3, 1, 4, 2, 5] []).headD model3.size = winner model3 5 [0, 3, 1, 4, 2, 5] := interleaved_empty_head _ _ _ _
example : interleavedInsert model3 owner3 5 3 [] = [] := by decide
example : interleavedInsert model3 owner3 5 1 [] = [] := by decide
example : interleavedInsert model3 owner3 5 4 [] = [] := by decide
example : interleavedInsert model3 owner3 5 2 [] = [] := by decide
example : interleavedInsert model3 owner3 5 5 [] = [5] := by decide
example : interleavedInsert model3 owner3 5 0 [5] = [0] := by decide
example : interleavedPass model3 owner3 5 [3, 1, 4, 2, 5, 0] [] = [0] := by decide
example : interleavedInsert model3 owner3 5 3 [0] = [0] := by decide
example : interleavedInsert model3 owner3 5 1 [0] = [0] := by decide
example : interleavedInsert model3 owner3 5 4 [0] = [0, 4] := by decide
example : interleavedInsert model3 owner3 5 2 [0, 4] = [0, 2] := by decide
example : interleavedInsert model3 owner3 5 5 [0, 2] = [0, 2] := by decide
example : interleavedInsert model3 owner3 5 0 [0, 2] = [0, 2] := by decide
example : interleavedPass model3 owner3 5 [3, 1, 4, 2, 5, 0] [0] = [0, 2] := by decide
example : (interleavedPass model3 owner3 5 [3, 1, 4, 2, 5, 0] [0]).headD model3.size = winner model3 5 [3, 1, 4, 2, 5, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : interleavedInsert model3 owner3 5 3 [0, 2] = [0, 2] := by decide
example : interleavedInsert model3 owner3 5 1 [0, 2] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 4 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 2 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 5 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 0 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedPass model3 owner3 5 [3, 1, 4, 2, 5, 0] [0, 2] = [0, 2, 1] := by decide
example : (interleavedPass model3 owner3 5 [3, 1, 4, 2, 5, 0] [0, 2]).headD model3.size = winner model3 5 [3, 1, 4, 2, 5, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : interleavedInsert model3 owner3 5 3 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 1 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 4 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 2 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 5 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 0 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedPass model3 owner3 5 [3, 1, 4, 2, 5, 0] [0, 2, 1] = [0, 2, 1] := by decide
example : (interleavedPass model3 owner3 5 [3, 1, 4, 2, 5, 0] [0, 2, 1]).headD model3.size = winner model3 5 [3, 1, 4, 2, 5, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : (interleavedPass model3 owner3 5 [3, 1, 4, 2, 5, 0] []).headD model3.size = winner model3 5 [3, 1, 4, 2, 5, 0] := interleaved_empty_head _ _ _ _
example : interleavedInsert model3 owner3 5 0 [] = [0] := by decide
example : interleavedInsert model3 owner3 5 1 [0] = [0] := by decide
example : interleavedInsert model3 owner3 5 2 [0] = [0, 2] := by decide
example : interleavedInsert model3 owner3 5 3 [0, 2] = [0, 2] := by decide
example : interleavedInsert model3 owner3 5 4 [0, 2] = [0, 2] := by decide
example : interleavedInsert model3 owner3 5 5 [0, 2] = [0, 2] := by decide
example : interleavedPass model3 owner3 5 [0, 1, 2, 3, 4, 5] [] = [0, 2] := by decide
example : interleavedInsert model3 owner3 5 0 [0, 2] = [0, 2] := by decide
example : interleavedInsert model3 owner3 5 1 [0, 2] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 2 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 3 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 4 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 5 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedPass model3 owner3 5 [0, 1, 2, 3, 4, 5] [0, 2] = [0, 2, 1] := by decide
example : (interleavedPass model3 owner3 5 [0, 1, 2, 3, 4, 5] [0, 2]).headD model3.size = winner model3 5 [0, 1, 2, 3, 4, 5] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : interleavedInsert model3 owner3 5 0 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 1 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 2 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 3 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 4 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 5 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedPass model3 owner3 5 [0, 1, 2, 3, 4, 5] [0, 2, 1] = [0, 2, 1] := by decide
example : (interleavedPass model3 owner3 5 [0, 1, 2, 3, 4, 5] [0, 2, 1]).headD model3.size = winner model3 5 [0, 1, 2, 3, 4, 5] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : (interleavedPass model3 owner3 5 [0, 1, 2, 3, 4, 5] []).headD model3.size = winner model3 5 [0, 1, 2, 3, 4, 5] := interleaved_empty_head _ _ _ _
example : interleavedInsert model3 owner3 5 4 [] = [] := by decide
example : interleavedInsert model3 owner3 5 3 [] = [] := by decide
example : interleavedInsert model3 owner3 5 5 [] = [5] := by decide
example : interleavedInsert model3 owner3 5 2 [5] = [5, 2] := by decide
example : interleavedInsert model3 owner3 5 1 [5, 2] = [5, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 0 [5, 2, 1] = [0, 2, 1] := by decide
example : interleavedPass model3 owner3 5 [4, 3, 5, 2, 1, 0] [] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 4 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 3 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 5 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 2 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 1 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 0 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedPass model3 owner3 5 [4, 3, 5, 2, 1, 0] [0, 2, 1] = [0, 2, 1] := by decide
example : (interleavedPass model3 owner3 5 [4, 3, 5, 2, 1, 0] [0, 2, 1]).headD model3.size = winner model3 5 [4, 3, 5, 2, 1, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : (interleavedPass model3 owner3 5 [4, 3, 5, 2, 1, 0] []).headD model3.size = winner model3 5 [4, 3, 5, 2, 1, 0] := interleaved_empty_head _ _ _ _
example : interleavedInsert model3 owner3 5 2 [] = [] := by decide
example : interleavedInsert model3 owner3 5 1 [] = [] := by decide
example : interleavedInsert model3 owner3 5 5 [] = [5] := by decide
example : interleavedInsert model3 owner3 5 4 [5] = [5, 4] := by decide
example : interleavedInsert model3 owner3 5 3 [5, 4] = [5, 4, 3] := by decide
example : interleavedInsert model3 owner3 5 0 [5, 4, 3] = [0, 4, 3] := by decide
example : interleavedPass model3 owner3 5 [2, 1, 5, 4, 3, 0] [] = [0, 4, 3] := by decide
example : interleavedInsert model3 owner3 5 2 [0, 4, 3] = [0, 2] := by decide
example : interleavedInsert model3 owner3 5 1 [0, 2] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 5 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 4 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 3 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 0 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedPass model3 owner3 5 [2, 1, 5, 4, 3, 0] [0, 4, 3] = [0, 2, 1] := by decide
example : (interleavedPass model3 owner3 5 [2, 1, 5, 4, 3, 0] [0, 4, 3]).headD model3.size = winner model3 5 [2, 1, 5, 4, 3, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : interleavedInsert model3 owner3 5 2 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 1 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 5 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 4 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 3 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedInsert model3 owner3 5 0 [0, 2, 1] = [0, 2, 1] := by decide
example : interleavedPass model3 owner3 5 [2, 1, 5, 4, 3, 0] [0, 2, 1] = [0, 2, 1] := by decide
example : (interleavedPass model3 owner3 5 [2, 1, 5, 4, 3, 0] [0, 2, 1]).headD model3.size = winner model3 5 [2, 1, 5, 4, 3, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : (interleavedPass model3 owner3 5 [2, 1, 5, 4, 3, 0] []).headD model3.size = winner model3 5 [2, 1, 5, 4, 3, 0] := interleaved_empty_head _ _ _ _
def model4 : Model := ⟨8, (fun i => [some 4, some 5, some 4, some 1, some 4, some 3, some 4, some 5].getD i none), fun _ => true, fun _ => 0⟩
def owner4 : Nat → Nat := (fun i => [3, 4, 1, 0, 1, 2, 3, 4].getD i 0)
example : interleavedInsert model4 owner4 5 7 [] = [7] := by decide
example : interleavedInsert model4 owner4 5 4 [7] = [7, 4] := by decide
example : interleavedInsert model4 owner4 5 6 [7, 4] = [7, 4] := by decide
example : interleavedInsert model4 owner4 5 3 [7, 4] = [7, 4, 3] := by decide
example : interleavedInsert model4 owner4 5 5 [7, 4, 3] = [7, 4, 3] := by decide
example : interleavedInsert model4 owner4 5 1 [7, 4, 3] = [1, 4, 3] := by decide
example : interleavedInsert model4 owner4 5 2 [1, 4, 3] = [1, 2, 3] := by decide
example : interleavedInsert model4 owner4 5 0 [1, 2, 3] = [1, 0] := by decide
example : interleavedPass model4 owner4 5 [7, 4, 6, 3, 5, 1, 2, 0] [] = [1, 0] := by decide
example : interleavedInsert model4 owner4 5 7 [1, 0] = [1, 0] := by decide
example : interleavedInsert model4 owner4 5 4 [1, 0] = [1, 0] := by decide
example : interleavedInsert model4 owner4 5 6 [1, 0] = [1, 0] := by decide
example : interleavedInsert model4 owner4 5 3 [1, 0] = [1, 0] := by decide
example : interleavedInsert model4 owner4 5 5 [1, 0] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 1 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 2 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 0 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedPass model4 owner4 5 [7, 4, 6, 3, 5, 1, 2, 0] [1, 0] = [1, 0, 5] := by decide
example : (interleavedPass model4 owner4 5 [7, 4, 6, 3, 5, 1, 2, 0] [1, 0]).headD model4.size = winner model4 5 [7, 4, 6, 3, 5, 1, 2, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : interleavedInsert model4 owner4 5 7 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 4 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 6 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 3 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 5 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 1 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 2 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 0 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedPass model4 owner4 5 [7, 4, 6, 3, 5, 1, 2, 0] [1, 0, 5] = [1, 0, 5] := by decide
example : (interleavedPass model4 owner4 5 [7, 4, 6, 3, 5, 1, 2, 0] [1, 0, 5]).headD model4.size = winner model4 5 [7, 4, 6, 3, 5, 1, 2, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : (interleavedPass model4 owner4 5 [7, 4, 6, 3, 5, 1, 2, 0] []).headD model4.size = winner model4 5 [7, 4, 6, 3, 5, 1, 2, 0] := interleaved_empty_head _ _ _ _
example : interleavedInsert model4 owner4 5 0 [] = [] := by decide
example : interleavedInsert model4 owner4 5 2 [] = [] := by decide
example : interleavedInsert model4 owner4 5 1 [] = [1] := by decide
example : interleavedInsert model4 owner4 5 5 [1] = [1] := by decide
example : interleavedInsert model4 owner4 5 3 [1] = [1] := by decide
example : interleavedInsert model4 owner4 5 6 [1] = [1, 6] := by decide
example : interleavedInsert model4 owner4 5 4 [1, 6] = [1, 4] := by decide
example : interleavedInsert model4 owner4 5 7 [1, 4] = [1, 4] := by decide
example : interleavedPass model4 owner4 5 [0, 2, 1, 5, 3, 6, 4, 7] [] = [1, 4] := by decide
example : interleavedInsert model4 owner4 5 0 [1, 4] = [1, 0] := by decide
example : interleavedInsert model4 owner4 5 2 [1, 0] = [1, 0] := by decide
example : interleavedInsert model4 owner4 5 1 [1, 0] = [1, 0] := by decide
example : interleavedInsert model4 owner4 5 5 [1, 0] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 3 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 6 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 4 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 7 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedPass model4 owner4 5 [0, 2, 1, 5, 3, 6, 4, 7] [1, 4] = [1, 0, 5] := by decide
example : (interleavedPass model4 owner4 5 [0, 2, 1, 5, 3, 6, 4, 7] [1, 4]).headD model4.size = winner model4 5 [0, 2, 1, 5, 3, 6, 4, 7] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : interleavedInsert model4 owner4 5 0 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 2 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 1 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 5 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 3 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 6 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 4 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 7 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedPass model4 owner4 5 [0, 2, 1, 5, 3, 6, 4, 7] [1, 0, 5] = [1, 0, 5] := by decide
example : (interleavedPass model4 owner4 5 [0, 2, 1, 5, 3, 6, 4, 7] [1, 0, 5]).headD model4.size = winner model4 5 [0, 2, 1, 5, 3, 6, 4, 7] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : (interleavedPass model4 owner4 5 [0, 2, 1, 5, 3, 6, 4, 7] []).headD model4.size = winner model4 5 [0, 2, 1, 5, 3, 6, 4, 7] := interleaved_empty_head _ _ _ _
example : interleavedInsert model4 owner4 5 5 [] = [] := by decide
example : interleavedInsert model4 owner4 5 3 [] = [] := by decide
example : interleavedInsert model4 owner4 5 6 [] = [] := by decide
example : interleavedInsert model4 owner4 5 4 [] = [] := by decide
example : interleavedInsert model4 owner4 5 7 [] = [7] := by decide
example : interleavedInsert model4 owner4 5 1 [7] = [1] := by decide
example : interleavedInsert model4 owner4 5 2 [1] = [1, 2] := by decide
example : interleavedInsert model4 owner4 5 0 [1, 2] = [1, 0] := by decide
example : interleavedPass model4 owner4 5 [5, 3, 6, 4, 7, 1, 2, 0] [] = [1, 0] := by decide
example : interleavedInsert model4 owner4 5 5 [1, 0] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 3 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 6 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 4 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 7 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 1 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 2 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 0 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedPass model4 owner4 5 [5, 3, 6, 4, 7, 1, 2, 0] [1, 0] = [1, 0, 5] := by decide
example : (interleavedPass model4 owner4 5 [5, 3, 6, 4, 7, 1, 2, 0] [1, 0]).headD model4.size = winner model4 5 [5, 3, 6, 4, 7, 1, 2, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : interleavedInsert model4 owner4 5 5 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 3 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 6 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 4 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 7 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 1 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 2 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 0 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedPass model4 owner4 5 [5, 3, 6, 4, 7, 1, 2, 0] [1, 0, 5] = [1, 0, 5] := by decide
example : (interleavedPass model4 owner4 5 [5, 3, 6, 4, 7, 1, 2, 0] [1, 0, 5]).headD model4.size = winner model4 5 [5, 3, 6, 4, 7, 1, 2, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : (interleavedPass model4 owner4 5 [5, 3, 6, 4, 7, 1, 2, 0] []).headD model4.size = winner model4 5 [5, 3, 6, 4, 7, 1, 2, 0] := interleaved_empty_head _ _ _ _
example : interleavedInsert model4 owner4 5 1 [] = [1] := by decide
example : interleavedInsert model4 owner4 5 2 [1] = [1, 2] := by decide
example : interleavedInsert model4 owner4 5 0 [1, 2] = [1, 0] := by decide
example : interleavedInsert model4 owner4 5 3 [1, 0] = [1, 0] := by decide
example : interleavedInsert model4 owner4 5 4 [1, 0] = [1, 0] := by decide
example : interleavedInsert model4 owner4 5 5 [1, 0] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 6 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 7 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedPass model4 owner4 5 [1, 2, 0, 3, 4, 5, 6, 7] [] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 1 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 2 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 0 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 3 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 4 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 5 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 6 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 7 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedPass model4 owner4 5 [1, 2, 0, 3, 4, 5, 6, 7] [1, 0, 5] = [1, 0, 5] := by decide
example : (interleavedPass model4 owner4 5 [1, 2, 0, 3, 4, 5, 6, 7] [1, 0, 5]).headD model4.size = winner model4 5 [1, 2, 0, 3, 4, 5, 6, 7] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : (interleavedPass model4 owner4 5 [1, 2, 0, 3, 4, 5, 6, 7] []).headD model4.size = winner model4 5 [1, 2, 0, 3, 4, 5, 6, 7] := interleaved_empty_head _ _ _ _
example : interleavedInsert model4 owner4 5 6 [] = [] := by decide
example : interleavedInsert model4 owner4 5 5 [] = [] := by decide
example : interleavedInsert model4 owner4 5 7 [] = [7] := by decide
example : interleavedInsert model4 owner4 5 4 [7] = [7, 4] := by decide
example : interleavedInsert model4 owner4 5 3 [7, 4] = [7, 4, 3] := by decide
example : interleavedInsert model4 owner4 5 0 [7, 4, 3] = [7, 0] := by decide
example : interleavedInsert model4 owner4 5 2 [7, 0] = [7, 0] := by decide
example : interleavedInsert model4 owner4 5 1 [7, 0] = [1, 0] := by decide
example : interleavedPass model4 owner4 5 [6, 5, 7, 4, 3, 0, 2, 1] [] = [1, 0] := by decide
example : interleavedInsert model4 owner4 5 6 [1, 0] = [1, 0] := by decide
example : interleavedInsert model4 owner4 5 5 [1, 0] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 7 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 4 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 3 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 0 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 2 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 1 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedPass model4 owner4 5 [6, 5, 7, 4, 3, 0, 2, 1] [1, 0] = [1, 0, 5] := by decide
example : (interleavedPass model4 owner4 5 [6, 5, 7, 4, 3, 0, 2, 1] [1, 0]).headD model4.size = winner model4 5 [6, 5, 7, 4, 3, 0, 2, 1] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : interleavedInsert model4 owner4 5 6 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 5 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 7 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 4 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 3 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 0 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 2 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 1 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedPass model4 owner4 5 [6, 5, 7, 4, 3, 0, 2, 1] [1, 0, 5] = [1, 0, 5] := by decide
example : (interleavedPass model4 owner4 5 [6, 5, 7, 4, 3, 0, 2, 1] [1, 0, 5]).headD model4.size = winner model4 5 [6, 5, 7, 4, 3, 0, 2, 1] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : (interleavedPass model4 owner4 5 [6, 5, 7, 4, 3, 0, 2, 1] []).headD model4.size = winner model4 5 [6, 5, 7, 4, 3, 0, 2, 1] := interleaved_empty_head _ _ _ _
example : interleavedInsert model4 owner4 5 4 [] = [] := by decide
example : interleavedInsert model4 owner4 5 3 [] = [] := by decide
example : interleavedInsert model4 owner4 5 7 [] = [7] := by decide
example : interleavedInsert model4 owner4 5 6 [7] = [7, 6] := by decide
example : interleavedInsert model4 owner4 5 5 [7, 6] = [7, 6, 5] := by decide
example : interleavedInsert model4 owner4 5 1 [7, 6, 5] = [1, 6, 5] := by decide
example : interleavedInsert model4 owner4 5 2 [1, 6, 5] = [1, 2] := by decide
example : interleavedInsert model4 owner4 5 0 [1, 2] = [1, 0] := by decide
example : interleavedPass model4 owner4 5 [4, 3, 7, 6, 5, 1, 2, 0] [] = [1, 0] := by decide
example : interleavedInsert model4 owner4 5 4 [1, 0] = [1, 0] := by decide
example : interleavedInsert model4 owner4 5 3 [1, 0] = [1, 0] := by decide
example : interleavedInsert model4 owner4 5 7 [1, 0] = [1, 0] := by decide
example : interleavedInsert model4 owner4 5 6 [1, 0] = [1, 0] := by decide
example : interleavedInsert model4 owner4 5 5 [1, 0] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 1 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 2 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 0 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedPass model4 owner4 5 [4, 3, 7, 6, 5, 1, 2, 0] [1, 0] = [1, 0, 5] := by decide
example : (interleavedPass model4 owner4 5 [4, 3, 7, 6, 5, 1, 2, 0] [1, 0]).headD model4.size = winner model4 5 [4, 3, 7, 6, 5, 1, 2, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : interleavedInsert model4 owner4 5 4 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 3 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 7 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 6 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 5 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 1 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 2 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedInsert model4 owner4 5 0 [1, 0, 5] = [1, 0, 5] := by decide
example : interleavedPass model4 owner4 5 [4, 3, 7, 6, 5, 1, 2, 0] [1, 0, 5] = [1, 0, 5] := by decide
example : (interleavedPass model4 owner4 5 [4, 3, 7, 6, 5, 1, 2, 0] [1, 0, 5]).headD model4.size = winner model4 5 [4, 3, 7, 6, 5, 1, 2, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : (interleavedPass model4 owner4 5 [4, 3, 7, 6, 5, 1, 2, 0] []).headD model4.size = winner model4 5 [4, 3, 7, 6, 5, 1, 2, 0] := interleaved_empty_head _ _ _ _
def model5 : Model := ⟨9, (fun i => [some 4, some 4, some 5, some 4, some 1, some 4, some 3, some 4, some 5].getD i none), fun _ => true, fun _ => 0⟩
def owner5 : Nat → Nat := (fun i => [1, 3, 4, 1, 0, 1, 2, 3, 4].getD i 0)
example : interleavedInsert model5 owner5 5 8 [] = [8] := by decide
example : interleavedInsert model5 owner5 5 5 [8] = [8, 5] := by decide
example : interleavedInsert model5 owner5 5 7 [8, 5] = [8, 5] := by decide
example : interleavedInsert model5 owner5 5 4 [8, 5] = [8, 5, 4] := by decide
example : interleavedInsert model5 owner5 5 6 [8, 5, 4] = [8, 5, 4] := by decide
example : interleavedInsert model5 owner5 5 2 [8, 5, 4] = [2, 5, 4] := by decide
example : interleavedInsert model5 owner5 5 3 [2, 5, 4] = [2, 3, 4] := by decide
example : interleavedInsert model5 owner5 5 1 [2, 3, 4] = [2, 1] := by decide
example : interleavedInsert model5 owner5 5 0 [2, 1] = [2, 0] := by decide
example : interleavedPass model5 owner5 5 [8, 5, 7, 4, 6, 2, 3, 1, 0] [] = [2, 0] := by decide
example : interleavedInsert model5 owner5 5 8 [2, 0] = [2, 0] := by decide
example : interleavedInsert model5 owner5 5 5 [2, 0] = [2, 0] := by decide
example : interleavedInsert model5 owner5 5 7 [2, 0] = [2, 0] := by decide
example : interleavedInsert model5 owner5 5 4 [2, 0] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 6 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 2 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 3 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 1 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 0 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedPass model5 owner5 5 [8, 5, 7, 4, 6, 2, 3, 1, 0] [2, 0] = [2, 0, 4] := by decide
example : (interleavedPass model5 owner5 5 [8, 5, 7, 4, 6, 2, 3, 1, 0] [2, 0]).headD model5.size = winner model5 5 [8, 5, 7, 4, 6, 2, 3, 1, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : interleavedInsert model5 owner5 5 8 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 5 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 7 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 4 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 6 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 2 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 3 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 1 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 0 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedPass model5 owner5 5 [8, 5, 7, 4, 6, 2, 3, 1, 0] [2, 0, 4] = [2, 0, 4] := by decide
example : (interleavedPass model5 owner5 5 [8, 5, 7, 4, 6, 2, 3, 1, 0] [2, 0, 4]).headD model5.size = winner model5 5 [8, 5, 7, 4, 6, 2, 3, 1, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : (interleavedPass model5 owner5 5 [8, 5, 7, 4, 6, 2, 3, 1, 0] []).headD model5.size = winner model5 5 [8, 5, 7, 4, 6, 2, 3, 1, 0] := interleaved_empty_head _ _ _ _
example : interleavedInsert model5 owner5 5 0 [] = [] := by decide
example : interleavedInsert model5 owner5 5 1 [] = [] := by decide
example : interleavedInsert model5 owner5 5 3 [] = [] := by decide
example : interleavedInsert model5 owner5 5 2 [] = [2] := by decide
example : interleavedInsert model5 owner5 5 6 [2] = [2] := by decide
example : interleavedInsert model5 owner5 5 4 [2] = [2] := by decide
example : interleavedInsert model5 owner5 5 7 [2] = [2, 7] := by decide
example : interleavedInsert model5 owner5 5 5 [2, 7] = [2, 5] := by decide
example : interleavedInsert model5 owner5 5 8 [2, 5] = [2, 5] := by decide
example : interleavedPass model5 owner5 5 [0, 1, 3, 2, 6, 4, 7, 5, 8] [] = [2, 5] := by decide
example : interleavedInsert model5 owner5 5 0 [2, 5] = [2, 0] := by decide
example : interleavedInsert model5 owner5 5 1 [2, 0] = [2, 0] := by decide
example : interleavedInsert model5 owner5 5 3 [2, 0] = [2, 0] := by decide
example : interleavedInsert model5 owner5 5 2 [2, 0] = [2, 0] := by decide
example : interleavedInsert model5 owner5 5 6 [2, 0] = [2, 0] := by decide
example : interleavedInsert model5 owner5 5 4 [2, 0] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 7 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 5 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 8 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedPass model5 owner5 5 [0, 1, 3, 2, 6, 4, 7, 5, 8] [2, 5] = [2, 0, 4] := by decide
example : (interleavedPass model5 owner5 5 [0, 1, 3, 2, 6, 4, 7, 5, 8] [2, 5]).headD model5.size = winner model5 5 [0, 1, 3, 2, 6, 4, 7, 5, 8] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : interleavedInsert model5 owner5 5 0 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 1 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 3 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 2 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 6 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 4 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 7 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 5 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 8 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedPass model5 owner5 5 [0, 1, 3, 2, 6, 4, 7, 5, 8] [2, 0, 4] = [2, 0, 4] := by decide
example : (interleavedPass model5 owner5 5 [0, 1, 3, 2, 6, 4, 7, 5, 8] [2, 0, 4]).headD model5.size = winner model5 5 [0, 1, 3, 2, 6, 4, 7, 5, 8] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : (interleavedPass model5 owner5 5 [0, 1, 3, 2, 6, 4, 7, 5, 8] []).headD model5.size = winner model5 5 [0, 1, 3, 2, 6, 4, 7, 5, 8] := interleaved_empty_head _ _ _ _
example : interleavedInsert model5 owner5 5 6 [] = [] := by decide
example : interleavedInsert model5 owner5 5 4 [] = [] := by decide
example : interleavedInsert model5 owner5 5 7 [] = [] := by decide
example : interleavedInsert model5 owner5 5 5 [] = [] := by decide
example : interleavedInsert model5 owner5 5 8 [] = [8] := by decide
example : interleavedInsert model5 owner5 5 2 [8] = [2] := by decide
example : interleavedInsert model5 owner5 5 3 [2] = [2, 3] := by decide
example : interleavedInsert model5 owner5 5 1 [2, 3] = [2, 1] := by decide
example : interleavedInsert model5 owner5 5 0 [2, 1] = [2, 0] := by decide
example : interleavedPass model5 owner5 5 [6, 4, 7, 5, 8, 2, 3, 1, 0] [] = [2, 0] := by decide
example : interleavedInsert model5 owner5 5 6 [2, 0] = [2, 0] := by decide
example : interleavedInsert model5 owner5 5 4 [2, 0] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 7 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 5 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 8 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 2 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 3 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 1 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 0 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedPass model5 owner5 5 [6, 4, 7, 5, 8, 2, 3, 1, 0] [2, 0] = [2, 0, 4] := by decide
example : (interleavedPass model5 owner5 5 [6, 4, 7, 5, 8, 2, 3, 1, 0] [2, 0]).headD model5.size = winner model5 5 [6, 4, 7, 5, 8, 2, 3, 1, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : interleavedInsert model5 owner5 5 6 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 4 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 7 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 5 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 8 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 2 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 3 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 1 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 0 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedPass model5 owner5 5 [6, 4, 7, 5, 8, 2, 3, 1, 0] [2, 0, 4] = [2, 0, 4] := by decide
example : (interleavedPass model5 owner5 5 [6, 4, 7, 5, 8, 2, 3, 1, 0] [2, 0, 4]).headD model5.size = winner model5 5 [6, 4, 7, 5, 8, 2, 3, 1, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : (interleavedPass model5 owner5 5 [6, 4, 7, 5, 8, 2, 3, 1, 0] []).headD model5.size = winner model5 5 [6, 4, 7, 5, 8, 2, 3, 1, 0] := interleaved_empty_head _ _ _ _
example : interleavedInsert model5 owner5 5 2 [] = [2] := by decide
example : interleavedInsert model5 owner5 5 3 [2] = [2, 3] := by decide
example : interleavedInsert model5 owner5 5 1 [2, 3] = [2, 1] := by decide
example : interleavedInsert model5 owner5 5 0 [2, 1] = [2, 0] := by decide
example : interleavedInsert model5 owner5 5 4 [2, 0] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 5 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 6 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 7 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 8 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedPass model5 owner5 5 [2, 3, 1, 0, 4, 5, 6, 7, 8] [] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 2 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 3 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 1 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 0 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 4 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 5 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 6 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 7 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 8 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedPass model5 owner5 5 [2, 3, 1, 0, 4, 5, 6, 7, 8] [2, 0, 4] = [2, 0, 4] := by decide
example : (interleavedPass model5 owner5 5 [2, 3, 1, 0, 4, 5, 6, 7, 8] [2, 0, 4]).headD model5.size = winner model5 5 [2, 3, 1, 0, 4, 5, 6, 7, 8] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : (interleavedPass model5 owner5 5 [2, 3, 1, 0, 4, 5, 6, 7, 8] []).headD model5.size = winner model5 5 [2, 3, 1, 0, 4, 5, 6, 7, 8] := interleaved_empty_head _ _ _ _
example : interleavedInsert model5 owner5 5 7 [] = [] := by decide
example : interleavedInsert model5 owner5 5 6 [] = [] := by decide
example : interleavedInsert model5 owner5 5 8 [] = [8] := by decide
example : interleavedInsert model5 owner5 5 5 [8] = [8, 5] := by decide
example : interleavedInsert model5 owner5 5 4 [8, 5] = [8, 5, 4] := by decide
example : interleavedInsert model5 owner5 5 0 [8, 5, 4] = [8, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 1 [8, 0, 4] = [8, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 3 [8, 0, 4] = [8, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 2 [8, 0, 4] = [2, 0, 4] := by decide
example : interleavedPass model5 owner5 5 [7, 6, 8, 5, 4, 0, 1, 3, 2] [] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 7 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 6 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 8 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 5 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 4 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 0 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 1 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 3 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 2 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedPass model5 owner5 5 [7, 6, 8, 5, 4, 0, 1, 3, 2] [2, 0, 4] = [2, 0, 4] := by decide
example : (interleavedPass model5 owner5 5 [7, 6, 8, 5, 4, 0, 1, 3, 2] [2, 0, 4]).headD model5.size = winner model5 5 [7, 6, 8, 5, 4, 0, 1, 3, 2] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : (interleavedPass model5 owner5 5 [7, 6, 8, 5, 4, 0, 1, 3, 2] []).headD model5.size = winner model5 5 [7, 6, 8, 5, 4, 0, 1, 3, 2] := interleaved_empty_head _ _ _ _
example : interleavedInsert model5 owner5 5 5 [] = [] := by decide
example : interleavedInsert model5 owner5 5 4 [] = [] := by decide
example : interleavedInsert model5 owner5 5 8 [] = [8] := by decide
example : interleavedInsert model5 owner5 5 7 [8] = [8, 7] := by decide
example : interleavedInsert model5 owner5 5 6 [8, 7] = [8, 7, 6] := by decide
example : interleavedInsert model5 owner5 5 2 [8, 7, 6] = [2, 7, 6] := by decide
example : interleavedInsert model5 owner5 5 3 [2, 7, 6] = [2, 3] := by decide
example : interleavedInsert model5 owner5 5 1 [2, 3] = [2, 1] := by decide
example : interleavedInsert model5 owner5 5 0 [2, 1] = [2, 0] := by decide
example : interleavedPass model5 owner5 5 [5, 4, 8, 7, 6, 2, 3, 1, 0] [] = [2, 0] := by decide
example : interleavedInsert model5 owner5 5 5 [2, 0] = [2, 0] := by decide
example : interleavedInsert model5 owner5 5 4 [2, 0] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 8 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 7 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 6 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 2 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 3 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 1 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 0 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedPass model5 owner5 5 [5, 4, 8, 7, 6, 2, 3, 1, 0] [2, 0] = [2, 0, 4] := by decide
example : (interleavedPass model5 owner5 5 [5, 4, 8, 7, 6, 2, 3, 1, 0] [2, 0]).headD model5.size = winner model5 5 [5, 4, 8, 7, 6, 2, 3, 1, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : interleavedInsert model5 owner5 5 5 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 4 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 8 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 7 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 6 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 2 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 3 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 1 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedInsert model5 owner5 5 0 [2, 0, 4] = [2, 0, 4] := by decide
example : interleavedPass model5 owner5 5 [5, 4, 8, 7, 6, 2, 3, 1, 0] [2, 0, 4] = [2, 0, 4] := by decide
example : (interleavedPass model5 owner5 5 [5, 4, 8, 7, 6, 2, 3, 1, 0] [2, 0, 4]).headD model5.size = winner model5 5 [5, 4, 8, 7, 6, 2, 3, 1, 0] := interleaved_next_settles _ _ _ _ _ _ (by decide) (by decide)
example : (interleavedPass model5 owner5 5 [5, 4, 8, 7, 6, 2, 3, 1, 0] []).headD model5.size = winner model5 5 [5, 4, 8, 7, 6, 2, 3, 1, 0] := interleaved_empty_head _ _ _ _
end Archon.InterleavedFixtures
