-- Generated by generate-priority-fixtures.mjs; do not edit.
import PriorityProjection
import InterleavedFixtures
import ChainSuccessorFixtures
set_option warningAsError true
namespace Archon.PriorityFixtures
abbrev priority0 := chainPriority ChainSuccessorFixtures.anchors0 [0]
def events0 : List Nat := [0, 1, 2, 3, 4, 5]
def selected0 : List Nat := [0, 1, 2, 3, 4].map priority0
theorem projection0 : PriorityProjection InterleavedFixtures.model0 ChainSuccessorFixtures.graph0 InterleavedFixtures.owner0 priority0 events0 selected0 5 := by
  constructor
  · rfl
  · intro p scope i member valid
    have bound : i < 6 := eligible_lt _ _ _ valid
    have checked : ∀ p : Fin 5, ∀ i : Fin 6, i.val ∈ events0 → eligible InterleavedFixtures.model0 p.val i.val = true → priority0 (InterleavedFixtures.owner0 i.val) ∈ selected0 ∧ eligible ChainSuccessorFixtures.graph0 (priority0 p.val) (priority0 (InterleavedFixtures.owner0 i.val)) = true ∧ priority0 (InterleavedFixtures.owner0 i.val) ≤ i.val := by decide
    exact checked ⟨p, scope⟩ ⟨i, bound⟩ member valid
  · intro p scope i member valid
    have bound : i < 6 := eligible_lt _ _ _ valid
    have checked : ∀ p : Fin 5, ∀ i : Fin 6, i.val ∈ selected0 → eligible ChainSuccessorFixtures.graph0 (priority0 p.val) i.val = true → i.val ∈ events0 ∧ eligible InterleavedFixtures.model0 p.val i.val = true := by decide
    exact checked ⟨p, scope⟩ ⟨i, bound⟩ member valid
  · intro p scope i member valid
    have bound : i < 6 := eligible_lt _ _ _ valid
    have checked : ∀ p : Fin 5, ∀ i : Fin 6, i.val ∈ selected0 → eligible ChainSuccessorFixtures.graph0 (priority0 p.val) i.val = true → i.val = priority0 (InterleavedFixtures.owner0 i.val) ∧ InterleavedFixtures.owner0 i.val < 5 := by decide
    exact checked ⟨p, scope⟩ ⟨i, bound⟩ member valid
theorem agreement0 : interleavedUntilStable InterleavedFixtures.model0 InterleavedFixtures.owner0 5 events0 (InterleavedFixtures.model0.level 5 + 1) [] = replayCold ChainSuccessorFixtures.graph0 (priority0 1) selected0 := by
  exact interleaved_and_priority_replay_agree InterleavedFixtures.model0 ChainSuccessorFixtures.graph0 InterleavedFixtures.owner0 priority0 events0 selected0 5 5 1 [] projection0 (by decide) InterleavedFixtures.descending0 (.nil _) (by decide) (by decide) (by decide) (by decide) ChainSuccessorFixtures.acyclic0 (by decide) (by decide)
example : interleavedUntilStable InterleavedFixtures.model0 InterleavedFixtures.owner0 5 [2, 3, 4, 1, 5, 0] (InterleavedFixtures.model0.level 5 + 1) [] = some [0, 3, 1] := by
  rw [interleaved_replay_same_evidence InterleavedFixtures.model0 InterleavedFixtures.owner0 [2, 3, 4, 1, 5, 0] events0 5 [] [] InterleavedFixtures.descending0 (.nil _) (.nil _) (bounded_membership_agrees 6 _ _ (by decide) (by decide) (by decide))]
  rw [agreement0, cold_replay_converges ChainSuccessorFixtures.graph0 (priority0 1) selected0 ChainSuccessorFixtures.acyclic0 (by decide) (by decide)]
  decide
example : interleavedUntilStable InterleavedFixtures.model0 InterleavedFixtures.owner0 5 [0, 5, 1, 4, 3, 2] (InterleavedFixtures.model0.level 5 + 1) [] = some [0, 3, 1] := by
  rw [interleaved_replay_same_evidence InterleavedFixtures.model0 InterleavedFixtures.owner0 [0, 5, 1, 4, 3, 2] events0 5 [] [] InterleavedFixtures.descending0 (.nil _) (.nil _) (bounded_membership_agrees 6 _ _ (by decide) (by decide) (by decide))]
  rw [agreement0, cold_replay_converges ChainSuccessorFixtures.graph0 (priority0 1) selected0 ChainSuccessorFixtures.acyclic0 (by decide) (by decide)]
  decide
example : interleavedUntilStable InterleavedFixtures.model0 InterleavedFixtures.owner0 5 [5, 1, 4, 3, 2, 0] (InterleavedFixtures.model0.level 5 + 1) [] = some [0, 3, 1] := by
  rw [interleaved_replay_same_evidence InterleavedFixtures.model0 InterleavedFixtures.owner0 [5, 1, 4, 3, 2, 0] events0 5 [] [] InterleavedFixtures.descending0 (.nil _) (.nil _) (bounded_membership_agrees 6 _ _ (by decide) (by decide) (by decide))]
  rw [agreement0, cold_replay_converges ChainSuccessorFixtures.graph0 (priority0 1) selected0 ChainSuccessorFixtures.acyclic0 (by decide) (by decide)]
  decide
example : interleavedUntilStable InterleavedFixtures.model0 InterleavedFixtures.owner0 5 [0, 1, 3, 5, 4, 2] (InterleavedFixtures.model0.level 5 + 1) [] = some [0, 3, 1] := by
  rw [interleaved_replay_same_evidence InterleavedFixtures.model0 InterleavedFixtures.owner0 [0, 1, 3, 5, 4, 2] events0 5 [] [] InterleavedFixtures.descending0 (.nil _) (.nil _) (bounded_membership_agrees 6 _ _ (by decide) (by decide) (by decide))]
  rw [agreement0, cold_replay_converges ChainSuccessorFixtures.graph0 (priority0 1) selected0 ChainSuccessorFixtures.acyclic0 (by decide) (by decide)]
  decide
example : interleavedUntilStable InterleavedFixtures.model0 InterleavedFixtures.owner0 5 [4, 5, 2, 3, 1, 0] (InterleavedFixtures.model0.level 5 + 1) [] = some [0, 3, 1] := by
  rw [interleaved_replay_same_evidence InterleavedFixtures.model0 InterleavedFixtures.owner0 [4, 5, 2, 3, 1, 0] events0 5 [] [] InterleavedFixtures.descending0 (.nil _) (.nil _) (bounded_membership_agrees 6 _ _ (by decide) (by decide) (by decide))]
  rw [agreement0, cold_replay_converges ChainSuccessorFixtures.graph0 (priority0 1) selected0 ChainSuccessorFixtures.acyclic0 (by decide) (by decide)]
  decide
example : interleavedUntilStable InterleavedFixtures.model0 InterleavedFixtures.owner0 5 [3, 1, 2, 4, 5, 0] (InterleavedFixtures.model0.level 5 + 1) [] = some [0, 3, 1] := by
  rw [interleaved_replay_same_evidence InterleavedFixtures.model0 InterleavedFixtures.owner0 [3, 1, 2, 4, 5, 0] events0 5 [] [] InterleavedFixtures.descending0 (.nil _) (.nil _) (bounded_membership_agrees 6 _ _ (by decide) (by decide) (by decide))]
  rw [agreement0, cold_replay_converges ChainSuccessorFixtures.graph0 (priority0 1) selected0 ChainSuccessorFixtures.acyclic0 (by decide) (by decide)]
  decide
abbrev priority1 := chainPriority ChainSuccessorFixtures.anchors1 [0, 1, 2]
def events1 : List Nat := [0, 1, 2, 3, 4, 5, 6, 7]
def selected1 : List Nat := [0, 1, 2, 3, 4].map priority1
theorem projection1 : PriorityProjection InterleavedFixtures.model1 ChainSuccessorFixtures.graph1 InterleavedFixtures.owner1 priority1 events1 selected1 5 := by
  constructor
  · rfl
  · intro p scope i member valid
    have bound : i < 8 := eligible_lt _ _ _ valid
    have checked : ∀ p : Fin 5, ∀ i : Fin 8, i.val ∈ events1 → eligible InterleavedFixtures.model1 p.val i.val = true → priority1 (InterleavedFixtures.owner1 i.val) ∈ selected1 ∧ eligible ChainSuccessorFixtures.graph1 (priority1 p.val) (priority1 (InterleavedFixtures.owner1 i.val)) = true ∧ priority1 (InterleavedFixtures.owner1 i.val) ≤ i.val := by decide
    exact checked ⟨p, scope⟩ ⟨i, bound⟩ member valid
  · intro p scope i member valid
    have bound : i < 8 := eligible_lt _ _ _ valid
    have checked : ∀ p : Fin 5, ∀ i : Fin 8, i.val ∈ selected1 → eligible ChainSuccessorFixtures.graph1 (priority1 p.val) i.val = true → i.val ∈ events1 ∧ eligible InterleavedFixtures.model1 p.val i.val = true := by decide
    exact checked ⟨p, scope⟩ ⟨i, bound⟩ member valid
  · intro p scope i member valid
    have bound : i < 8 := eligible_lt _ _ _ valid
    have checked : ∀ p : Fin 5, ∀ i : Fin 8, i.val ∈ selected1 → eligible ChainSuccessorFixtures.graph1 (priority1 p.val) i.val = true → i.val = priority1 (InterleavedFixtures.owner1 i.val) ∧ InterleavedFixtures.owner1 i.val < 5 := by decide
    exact checked ⟨p, scope⟩ ⟨i, bound⟩ member valid
theorem agreement1 : interleavedUntilStable InterleavedFixtures.model1 InterleavedFixtures.owner1 5 events1 (InterleavedFixtures.model1.level 5 + 1) [] = replayCold ChainSuccessorFixtures.graph1 (priority1 1) selected1 := by
  exact interleaved_and_priority_replay_agree InterleavedFixtures.model1 ChainSuccessorFixtures.graph1 InterleavedFixtures.owner1 priority1 events1 selected1 5 5 1 [] projection1 (by decide) InterleavedFixtures.descending1 (.nil _) (by decide) (by decide) (by decide) (by decide) ChainSuccessorFixtures.acyclic1 (by decide) (by decide)
example : interleavedUntilStable InterleavedFixtures.model1 InterleavedFixtures.owner1 5 [4, 5, 6, 3, 7, 1, 2, 0] (InterleavedFixtures.model1.level 5 + 1) [] = some [1, 0, 7] := by
  rw [interleaved_replay_same_evidence InterleavedFixtures.model1 InterleavedFixtures.owner1 [4, 5, 6, 3, 7, 1, 2, 0] events1 5 [] [] InterleavedFixtures.descending1 (.nil _) (.nil _) (bounded_membership_agrees 8 _ _ (by decide) (by decide) (by decide))]
  rw [agreement1, cold_replay_converges ChainSuccessorFixtures.graph1 (priority1 1) selected1 ChainSuccessorFixtures.acyclic1 (by decide) (by decide)]
  decide
example : interleavedUntilStable InterleavedFixtures.model1 InterleavedFixtures.owner1 5 [0, 2, 1, 7, 3, 6, 5, 4] (InterleavedFixtures.model1.level 5 + 1) [] = some [1, 0, 7] := by
  rw [interleaved_replay_same_evidence InterleavedFixtures.model1 InterleavedFixtures.owner1 [0, 2, 1, 7, 3, 6, 5, 4] events1 5 [] [] InterleavedFixtures.descending1 (.nil _) (.nil _) (bounded_membership_agrees 8 _ _ (by decide) (by decide) (by decide))]
  rw [agreement1, cold_replay_converges ChainSuccessorFixtures.graph1 (priority1 1) selected1 ChainSuccessorFixtures.acyclic1 (by decide) (by decide)]
  decide
example : interleavedUntilStable InterleavedFixtures.model1 InterleavedFixtures.owner1 5 [7, 3, 6, 5, 4, 1, 2, 0] (InterleavedFixtures.model1.level 5 + 1) [] = some [1, 0, 7] := by
  rw [interleaved_replay_same_evidence InterleavedFixtures.model1 InterleavedFixtures.owner1 [7, 3, 6, 5, 4, 1, 2, 0] events1 5 [] [] InterleavedFixtures.descending1 (.nil _) (.nil _) (bounded_membership_agrees 8 _ _ (by decide) (by decide) (by decide))]
  rw [agreement1, cold_replay_converges ChainSuccessorFixtures.graph1 (priority1 1) selected1 ChainSuccessorFixtures.acyclic1 (by decide) (by decide)]
  decide
example : interleavedUntilStable InterleavedFixtures.model1 InterleavedFixtures.owner1 5 [1, 2, 0, 3, 5, 7, 6, 4] (InterleavedFixtures.model1.level 5 + 1) [] = some [1, 0, 7] := by
  rw [interleaved_replay_same_evidence InterleavedFixtures.model1 InterleavedFixtures.owner1 [1, 2, 0, 3, 5, 7, 6, 4] events1 5 [] [] InterleavedFixtures.descending1 (.nil _) (.nil _) (bounded_membership_agrees 8 _ _ (by decide) (by decide) (by decide))]
  rw [agreement1, cold_replay_converges ChainSuccessorFixtures.graph1 (priority1 1) selected1 ChainSuccessorFixtures.acyclic1 (by decide) (by decide)]
  decide
example : interleavedUntilStable InterleavedFixtures.model1 InterleavedFixtures.owner1 5 [6, 7, 4, 5, 3, 0, 2, 1] (InterleavedFixtures.model1.level 5 + 1) [] = some [1, 0, 7] := by
  rw [interleaved_replay_same_evidence InterleavedFixtures.model1 InterleavedFixtures.owner1 [6, 7, 4, 5, 3, 0, 2, 1] events1 5 [] [] InterleavedFixtures.descending1 (.nil _) (.nil _) (bounded_membership_agrees 8 _ _ (by decide) (by decide) (by decide))]
  rw [agreement1, cold_replay_converges ChainSuccessorFixtures.graph1 (priority1 1) selected1 ChainSuccessorFixtures.acyclic1 (by decide) (by decide)]
  decide
example : interleavedUntilStable InterleavedFixtures.model1 InterleavedFixtures.owner1 5 [5, 3, 4, 6, 7, 1, 2, 0] (InterleavedFixtures.model1.level 5 + 1) [] = some [1, 0, 7] := by
  rw [interleaved_replay_same_evidence InterleavedFixtures.model1 InterleavedFixtures.owner1 [5, 3, 4, 6, 7, 1, 2, 0] events1 5 [] [] InterleavedFixtures.descending1 (.nil _) (.nil _) (bounded_membership_agrees 8 _ _ (by decide) (by decide) (by decide))]
  rw [agreement1, cold_replay_converges ChainSuccessorFixtures.graph1 (priority1 1) selected1 ChainSuccessorFixtures.acyclic1 (by decide) (by decide)]
  decide
abbrev priority2 := chainPriority ChainSuccessorFixtures.anchors2 [0, 1, 2, 3]
def events2 : List Nat := [0, 1, 2, 3, 4, 5, 6, 7, 8]
def selected2 : List Nat := [0, 1, 2, 3, 4].map priority2
theorem projection2 : PriorityProjection InterleavedFixtures.model2 ChainSuccessorFixtures.graph2 InterleavedFixtures.owner2 priority2 events2 selected2 5 := by
  constructor
  · rfl
  · intro p scope i member valid
    have bound : i < 9 := eligible_lt _ _ _ valid
    have checked : ∀ p : Fin 5, ∀ i : Fin 9, i.val ∈ events2 → eligible InterleavedFixtures.model2 p.val i.val = true → priority2 (InterleavedFixtures.owner2 i.val) ∈ selected2 ∧ eligible ChainSuccessorFixtures.graph2 (priority2 p.val) (priority2 (InterleavedFixtures.owner2 i.val)) = true ∧ priority2 (InterleavedFixtures.owner2 i.val) ≤ i.val := by decide
    exact checked ⟨p, scope⟩ ⟨i, bound⟩ member valid
  · intro p scope i member valid
    have bound : i < 9 := eligible_lt _ _ _ valid
    have checked : ∀ p : Fin 5, ∀ i : Fin 9, i.val ∈ selected2 → eligible ChainSuccessorFixtures.graph2 (priority2 p.val) i.val = true → i.val ∈ events2 ∧ eligible InterleavedFixtures.model2 p.val i.val = true := by decide
    exact checked ⟨p, scope⟩ ⟨i, bound⟩ member valid
  · intro p scope i member valid
    have bound : i < 9 := eligible_lt _ _ _ valid
    have checked : ∀ p : Fin 5, ∀ i : Fin 9, i.val ∈ selected2 → eligible ChainSuccessorFixtures.graph2 (priority2 p.val) i.val = true → i.val = priority2 (InterleavedFixtures.owner2 i.val) ∧ InterleavedFixtures.owner2 i.val < 5 := by decide
    exact checked ⟨p, scope⟩ ⟨i, bound⟩ member valid
theorem agreement2 : interleavedUntilStable InterleavedFixtures.model2 InterleavedFixtures.owner2 5 events2 (InterleavedFixtures.model2.level 5 + 1) [] = replayCold ChainSuccessorFixtures.graph2 (priority2 1) selected2 := by
  exact interleaved_and_priority_replay_agree InterleavedFixtures.model2 ChainSuccessorFixtures.graph2 InterleavedFixtures.owner2 priority2 events2 selected2 5 5 1 [] projection2 (by decide) InterleavedFixtures.descending2 (.nil _) (by decide) (by decide) (by decide) (by decide) ChainSuccessorFixtures.acyclic2 (by decide) (by decide)
example : interleavedUntilStable InterleavedFixtures.model2 InterleavedFixtures.owner2 5 [5, 6, 7, 4, 8, 2, 3, 1, 0] (InterleavedFixtures.model2.level 5 + 1) [] = some [2, 0, 4] := by
  rw [interleaved_replay_same_evidence InterleavedFixtures.model2 InterleavedFixtures.owner2 [5, 6, 7, 4, 8, 2, 3, 1, 0] events2 5 [] [] InterleavedFixtures.descending2 (.nil _) (.nil _) (bounded_membership_agrees 9 _ _ (by decide) (by decide) (by decide))]
  rw [agreement2, cold_replay_converges ChainSuccessorFixtures.graph2 (priority2 1) selected2 ChainSuccessorFixtures.acyclic2 (by decide) (by decide)]
  decide
example : interleavedUntilStable InterleavedFixtures.model2 InterleavedFixtures.owner2 5 [0, 1, 3, 2, 8, 4, 7, 6, 5] (InterleavedFixtures.model2.level 5 + 1) [] = some [2, 0, 4] := by
  rw [interleaved_replay_same_evidence InterleavedFixtures.model2 InterleavedFixtures.owner2 [0, 1, 3, 2, 8, 4, 7, 6, 5] events2 5 [] [] InterleavedFixtures.descending2 (.nil _) (.nil _) (bounded_membership_agrees 9 _ _ (by decide) (by decide) (by decide))]
  rw [agreement2, cold_replay_converges ChainSuccessorFixtures.graph2 (priority2 1) selected2 ChainSuccessorFixtures.acyclic2 (by decide) (by decide)]
  decide
example : interleavedUntilStable InterleavedFixtures.model2 InterleavedFixtures.owner2 5 [8, 4, 7, 6, 5, 2, 3, 1, 0] (InterleavedFixtures.model2.level 5 + 1) [] = some [2, 0, 4] := by
  rw [interleaved_replay_same_evidence InterleavedFixtures.model2 InterleavedFixtures.owner2 [8, 4, 7, 6, 5, 2, 3, 1, 0] events2 5 [] [] InterleavedFixtures.descending2 (.nil _) (.nil _) (bounded_membership_agrees 9 _ _ (by decide) (by decide) (by decide))]
  rw [agreement2, cold_replay_converges ChainSuccessorFixtures.graph2 (priority2 1) selected2 ChainSuccessorFixtures.acyclic2 (by decide) (by decide)]
  decide
example : interleavedUntilStable InterleavedFixtures.model2 InterleavedFixtures.owner2 5 [2, 3, 1, 0, 4, 6, 8, 7, 5] (InterleavedFixtures.model2.level 5 + 1) [] = some [2, 0, 4] := by
  rw [interleaved_replay_same_evidence InterleavedFixtures.model2 InterleavedFixtures.owner2 [2, 3, 1, 0, 4, 6, 8, 7, 5] events2 5 [] [] InterleavedFixtures.descending2 (.nil _) (.nil _) (bounded_membership_agrees 9 _ _ (by decide) (by decide) (by decide))]
  rw [agreement2, cold_replay_converges ChainSuccessorFixtures.graph2 (priority2 1) selected2 ChainSuccessorFixtures.acyclic2 (by decide) (by decide)]
  decide
example : interleavedUntilStable InterleavedFixtures.model2 InterleavedFixtures.owner2 5 [7, 8, 5, 6, 4, 0, 1, 3, 2] (InterleavedFixtures.model2.level 5 + 1) [] = some [2, 0, 4] := by
  rw [interleaved_replay_same_evidence InterleavedFixtures.model2 InterleavedFixtures.owner2 [7, 8, 5, 6, 4, 0, 1, 3, 2] events2 5 [] [] InterleavedFixtures.descending2 (.nil _) (.nil _) (bounded_membership_agrees 9 _ _ (by decide) (by decide) (by decide))]
  rw [agreement2, cold_replay_converges ChainSuccessorFixtures.graph2 (priority2 1) selected2 ChainSuccessorFixtures.acyclic2 (by decide) (by decide)]
  decide
example : interleavedUntilStable InterleavedFixtures.model2 InterleavedFixtures.owner2 5 [6, 4, 5, 7, 8, 2, 3, 1, 0] (InterleavedFixtures.model2.level 5 + 1) [] = some [2, 0, 4] := by
  rw [interleaved_replay_same_evidence InterleavedFixtures.model2 InterleavedFixtures.owner2 [6, 4, 5, 7, 8, 2, 3, 1, 0] events2 5 [] [] InterleavedFixtures.descending2 (.nil _) (.nil _) (bounded_membership_agrees 9 _ _ (by decide) (by decide) (by decide))]
  rw [agreement2, cold_replay_converges ChainSuccessorFixtures.graph2 (priority2 1) selected2 ChainSuccessorFixtures.acyclic2 (by decide) (by decide)]
  decide
abbrev priority3 := chainPriority ChainSuccessorFixtures.anchors3 [0]
def events3 : List Nat := [0, 1, 2, 3, 4, 5]
def selected3 : List Nat := [0, 1, 2, 3, 4].map priority3
theorem projection3 : PriorityProjection InterleavedFixtures.model3 ChainSuccessorFixtures.graph3 InterleavedFixtures.owner3 priority3 events3 selected3 5 := by
  constructor
  · rfl
  · intro p scope i member valid
    have bound : i < 6 := eligible_lt _ _ _ valid
    have checked : ∀ p : Fin 5, ∀ i : Fin 6, i.val ∈ events3 → eligible InterleavedFixtures.model3 p.val i.val = true → priority3 (InterleavedFixtures.owner3 i.val) ∈ selected3 ∧ eligible ChainSuccessorFixtures.graph3 (priority3 p.val) (priority3 (InterleavedFixtures.owner3 i.val)) = true ∧ priority3 (InterleavedFixtures.owner3 i.val) ≤ i.val := by decide
    exact checked ⟨p, scope⟩ ⟨i, bound⟩ member valid
  · intro p scope i member valid
    have bound : i < 6 := eligible_lt _ _ _ valid
    have checked : ∀ p : Fin 5, ∀ i : Fin 6, i.val ∈ selected3 → eligible ChainSuccessorFixtures.graph3 (priority3 p.val) i.val = true → i.val ∈ events3 ∧ eligible InterleavedFixtures.model3 p.val i.val = true := by decide
    exact checked ⟨p, scope⟩ ⟨i, bound⟩ member valid
  · intro p scope i member valid
    have bound : i < 6 := eligible_lt _ _ _ valid
    have checked : ∀ p : Fin 5, ∀ i : Fin 6, i.val ∈ selected3 → eligible ChainSuccessorFixtures.graph3 (priority3 p.val) i.val = true → i.val = priority3 (InterleavedFixtures.owner3 i.val) ∧ InterleavedFixtures.owner3 i.val < 5 := by decide
    exact checked ⟨p, scope⟩ ⟨i, bound⟩ member valid
theorem agreement3 : interleavedUntilStable InterleavedFixtures.model3 InterleavedFixtures.owner3 5 events3 (InterleavedFixtures.model3.level 5 + 1) [] = replayCold ChainSuccessorFixtures.graph3 (priority3 4) selected3 := by
  exact interleaved_and_priority_replay_agree InterleavedFixtures.model3 ChainSuccessorFixtures.graph3 InterleavedFixtures.owner3 priority3 events3 selected3 5 5 4 [] projection3 (by decide) InterleavedFixtures.descending3 (.nil _) (by decide) (by decide) (by decide) (by decide) ChainSuccessorFixtures.acyclic3 (by decide) (by decide)
example : interleavedUntilStable InterleavedFixtures.model3 InterleavedFixtures.owner3 5 [5, 2, 4, 1, 3, 0] (InterleavedFixtures.model3.level 5 + 1) [] = some [0, 2, 1] := by
  rw [interleaved_replay_same_evidence InterleavedFixtures.model3 InterleavedFixtures.owner3 [5, 2, 4, 1, 3, 0] events3 5 [] [] InterleavedFixtures.descending3 (.nil _) (.nil _) (bounded_membership_agrees 6 _ _ (by decide) (by decide) (by decide))]
  rw [agreement3, cold_replay_converges ChainSuccessorFixtures.graph3 (priority3 4) selected3 ChainSuccessorFixtures.acyclic3 (by decide) (by decide)]
  decide
example : interleavedUntilStable InterleavedFixtures.model3 InterleavedFixtures.owner3 5 [0, 3, 1, 4, 2, 5] (InterleavedFixtures.model3.level 5 + 1) [] = some [0, 2, 1] := by
  rw [interleaved_replay_same_evidence InterleavedFixtures.model3 InterleavedFixtures.owner3 [0, 3, 1, 4, 2, 5] events3 5 [] [] InterleavedFixtures.descending3 (.nil _) (.nil _) (bounded_membership_agrees 6 _ _ (by decide) (by decide) (by decide))]
  rw [agreement3, cold_replay_converges ChainSuccessorFixtures.graph3 (priority3 4) selected3 ChainSuccessorFixtures.acyclic3 (by decide) (by decide)]
  decide
example : interleavedUntilStable InterleavedFixtures.model3 InterleavedFixtures.owner3 5 [3, 1, 4, 2, 5, 0] (InterleavedFixtures.model3.level 5 + 1) [] = some [0, 2, 1] := by
  rw [interleaved_replay_same_evidence InterleavedFixtures.model3 InterleavedFixtures.owner3 [3, 1, 4, 2, 5, 0] events3 5 [] [] InterleavedFixtures.descending3 (.nil _) (.nil _) (bounded_membership_agrees 6 _ _ (by decide) (by decide) (by decide))]
  rw [agreement3, cold_replay_converges ChainSuccessorFixtures.graph3 (priority3 4) selected3 ChainSuccessorFixtures.acyclic3 (by decide) (by decide)]
  decide
example : interleavedUntilStable InterleavedFixtures.model3 InterleavedFixtures.owner3 5 [0, 1, 2, 3, 4, 5] (InterleavedFixtures.model3.level 5 + 1) [] = some [0, 2, 1] := by
  rw [interleaved_replay_same_evidence InterleavedFixtures.model3 InterleavedFixtures.owner3 [0, 1, 2, 3, 4, 5] events3 5 [] [] InterleavedFixtures.descending3 (.nil _) (.nil _) (bounded_membership_agrees 6 _ _ (by decide) (by decide) (by decide))]
  rw [agreement3, cold_replay_converges ChainSuccessorFixtures.graph3 (priority3 4) selected3 ChainSuccessorFixtures.acyclic3 (by decide) (by decide)]
  decide
example : interleavedUntilStable InterleavedFixtures.model3 InterleavedFixtures.owner3 5 [4, 3, 5, 2, 1, 0] (InterleavedFixtures.model3.level 5 + 1) [] = some [0, 2, 1] := by
  rw [interleaved_replay_same_evidence InterleavedFixtures.model3 InterleavedFixtures.owner3 [4, 3, 5, 2, 1, 0] events3 5 [] [] InterleavedFixtures.descending3 (.nil _) (.nil _) (bounded_membership_agrees 6 _ _ (by decide) (by decide) (by decide))]
  rw [agreement3, cold_replay_converges ChainSuccessorFixtures.graph3 (priority3 4) selected3 ChainSuccessorFixtures.acyclic3 (by decide) (by decide)]
  decide
example : interleavedUntilStable InterleavedFixtures.model3 InterleavedFixtures.owner3 5 [2, 1, 5, 4, 3, 0] (InterleavedFixtures.model3.level 5 + 1) [] = some [0, 2, 1] := by
  rw [interleaved_replay_same_evidence InterleavedFixtures.model3 InterleavedFixtures.owner3 [2, 1, 5, 4, 3, 0] events3 5 [] [] InterleavedFixtures.descending3 (.nil _) (.nil _) (bounded_membership_agrees 6 _ _ (by decide) (by decide) (by decide))]
  rw [agreement3, cold_replay_converges ChainSuccessorFixtures.graph3 (priority3 4) selected3 ChainSuccessorFixtures.acyclic3 (by decide) (by decide)]
  decide
abbrev priority4 := chainPriority ChainSuccessorFixtures.anchors4 [0, 1, 2]
def events4 : List Nat := [0, 1, 2, 3, 4, 5, 6, 7]
def selected4 : List Nat := [0, 1, 2, 3, 4].map priority4
theorem projection4 : PriorityProjection InterleavedFixtures.model4 ChainSuccessorFixtures.graph4 InterleavedFixtures.owner4 priority4 events4 selected4 5 := by
  constructor
  · rfl
  · intro p scope i member valid
    have bound : i < 8 := eligible_lt _ _ _ valid
    have checked : ∀ p : Fin 5, ∀ i : Fin 8, i.val ∈ events4 → eligible InterleavedFixtures.model4 p.val i.val = true → priority4 (InterleavedFixtures.owner4 i.val) ∈ selected4 ∧ eligible ChainSuccessorFixtures.graph4 (priority4 p.val) (priority4 (InterleavedFixtures.owner4 i.val)) = true ∧ priority4 (InterleavedFixtures.owner4 i.val) ≤ i.val := by decide
    exact checked ⟨p, scope⟩ ⟨i, bound⟩ member valid
  · intro p scope i member valid
    have bound : i < 8 := eligible_lt _ _ _ valid
    have checked : ∀ p : Fin 5, ∀ i : Fin 8, i.val ∈ selected4 → eligible ChainSuccessorFixtures.graph4 (priority4 p.val) i.val = true → i.val ∈ events4 ∧ eligible InterleavedFixtures.model4 p.val i.val = true := by decide
    exact checked ⟨p, scope⟩ ⟨i, bound⟩ member valid
  · intro p scope i member valid
    have bound : i < 8 := eligible_lt _ _ _ valid
    have checked : ∀ p : Fin 5, ∀ i : Fin 8, i.val ∈ selected4 → eligible ChainSuccessorFixtures.graph4 (priority4 p.val) i.val = true → i.val = priority4 (InterleavedFixtures.owner4 i.val) ∧ InterleavedFixtures.owner4 i.val < 5 := by decide
    exact checked ⟨p, scope⟩ ⟨i, bound⟩ member valid
theorem agreement4 : interleavedUntilStable InterleavedFixtures.model4 InterleavedFixtures.owner4 5 events4 (InterleavedFixtures.model4.level 5 + 1) [] = replayCold ChainSuccessorFixtures.graph4 (priority4 4) selected4 := by
  exact interleaved_and_priority_replay_agree InterleavedFixtures.model4 ChainSuccessorFixtures.graph4 InterleavedFixtures.owner4 priority4 events4 selected4 5 5 4 [] projection4 (by decide) InterleavedFixtures.descending4 (.nil _) (by decide) (by decide) (by decide) (by decide) ChainSuccessorFixtures.acyclic4 (by decide) (by decide)
example : interleavedUntilStable InterleavedFixtures.model4 InterleavedFixtures.owner4 5 [7, 4, 6, 3, 5, 1, 2, 0] (InterleavedFixtures.model4.level 5 + 1) [] = some [1, 0, 5] := by
  rw [interleaved_replay_same_evidence InterleavedFixtures.model4 InterleavedFixtures.owner4 [7, 4, 6, 3, 5, 1, 2, 0] events4 5 [] [] InterleavedFixtures.descending4 (.nil _) (.nil _) (bounded_membership_agrees 8 _ _ (by decide) (by decide) (by decide))]
  rw [agreement4, cold_replay_converges ChainSuccessorFixtures.graph4 (priority4 4) selected4 ChainSuccessorFixtures.acyclic4 (by decide) (by decide)]
  decide
example : interleavedUntilStable InterleavedFixtures.model4 InterleavedFixtures.owner4 5 [0, 2, 1, 5, 3, 6, 4, 7] (InterleavedFixtures.model4.level 5 + 1) [] = some [1, 0, 5] := by
  rw [interleaved_replay_same_evidence InterleavedFixtures.model4 InterleavedFixtures.owner4 [0, 2, 1, 5, 3, 6, 4, 7] events4 5 [] [] InterleavedFixtures.descending4 (.nil _) (.nil _) (bounded_membership_agrees 8 _ _ (by decide) (by decide) (by decide))]
  rw [agreement4, cold_replay_converges ChainSuccessorFixtures.graph4 (priority4 4) selected4 ChainSuccessorFixtures.acyclic4 (by decide) (by decide)]
  decide
example : interleavedUntilStable InterleavedFixtures.model4 InterleavedFixtures.owner4 5 [5, 3, 6, 4, 7, 1, 2, 0] (InterleavedFixtures.model4.level 5 + 1) [] = some [1, 0, 5] := by
  rw [interleaved_replay_same_evidence InterleavedFixtures.model4 InterleavedFixtures.owner4 [5, 3, 6, 4, 7, 1, 2, 0] events4 5 [] [] InterleavedFixtures.descending4 (.nil _) (.nil _) (bounded_membership_agrees 8 _ _ (by decide) (by decide) (by decide))]
  rw [agreement4, cold_replay_converges ChainSuccessorFixtures.graph4 (priority4 4) selected4 ChainSuccessorFixtures.acyclic4 (by decide) (by decide)]
  decide
example : interleavedUntilStable InterleavedFixtures.model4 InterleavedFixtures.owner4 5 [1, 2, 0, 3, 4, 5, 6, 7] (InterleavedFixtures.model4.level 5 + 1) [] = some [1, 0, 5] := by
  rw [interleaved_replay_same_evidence InterleavedFixtures.model4 InterleavedFixtures.owner4 [1, 2, 0, 3, 4, 5, 6, 7] events4 5 [] [] InterleavedFixtures.descending4 (.nil _) (.nil _) (bounded_membership_agrees 8 _ _ (by decide) (by decide) (by decide))]
  rw [agreement4, cold_replay_converges ChainSuccessorFixtures.graph4 (priority4 4) selected4 ChainSuccessorFixtures.acyclic4 (by decide) (by decide)]
  decide
example : interleavedUntilStable InterleavedFixtures.model4 InterleavedFixtures.owner4 5 [6, 5, 7, 4, 3, 0, 2, 1] (InterleavedFixtures.model4.level 5 + 1) [] = some [1, 0, 5] := by
  rw [interleaved_replay_same_evidence InterleavedFixtures.model4 InterleavedFixtures.owner4 [6, 5, 7, 4, 3, 0, 2, 1] events4 5 [] [] InterleavedFixtures.descending4 (.nil _) (.nil _) (bounded_membership_agrees 8 _ _ (by decide) (by decide) (by decide))]
  rw [agreement4, cold_replay_converges ChainSuccessorFixtures.graph4 (priority4 4) selected4 ChainSuccessorFixtures.acyclic4 (by decide) (by decide)]
  decide
example : interleavedUntilStable InterleavedFixtures.model4 InterleavedFixtures.owner4 5 [4, 3, 7, 6, 5, 1, 2, 0] (InterleavedFixtures.model4.level 5 + 1) [] = some [1, 0, 5] := by
  rw [interleaved_replay_same_evidence InterleavedFixtures.model4 InterleavedFixtures.owner4 [4, 3, 7, 6, 5, 1, 2, 0] events4 5 [] [] InterleavedFixtures.descending4 (.nil _) (.nil _) (bounded_membership_agrees 8 _ _ (by decide) (by decide) (by decide))]
  rw [agreement4, cold_replay_converges ChainSuccessorFixtures.graph4 (priority4 4) selected4 ChainSuccessorFixtures.acyclic4 (by decide) (by decide)]
  decide
abbrev priority5 := chainPriority ChainSuccessorFixtures.anchors5 [0, 1, 2, 3]
def events5 : List Nat := [0, 1, 2, 3, 4, 5, 6, 7, 8]
def selected5 : List Nat := [0, 1, 2, 3, 4].map priority5
theorem projection5 : PriorityProjection InterleavedFixtures.model5 ChainSuccessorFixtures.graph5 InterleavedFixtures.owner5 priority5 events5 selected5 5 := by
  constructor
  · rfl
  · intro p scope i member valid
    have bound : i < 9 := eligible_lt _ _ _ valid
    have checked : ∀ p : Fin 5, ∀ i : Fin 9, i.val ∈ events5 → eligible InterleavedFixtures.model5 p.val i.val = true → priority5 (InterleavedFixtures.owner5 i.val) ∈ selected5 ∧ eligible ChainSuccessorFixtures.graph5 (priority5 p.val) (priority5 (InterleavedFixtures.owner5 i.val)) = true ∧ priority5 (InterleavedFixtures.owner5 i.val) ≤ i.val := by decide
    exact checked ⟨p, scope⟩ ⟨i, bound⟩ member valid
  · intro p scope i member valid
    have bound : i < 9 := eligible_lt _ _ _ valid
    have checked : ∀ p : Fin 5, ∀ i : Fin 9, i.val ∈ selected5 → eligible ChainSuccessorFixtures.graph5 (priority5 p.val) i.val = true → i.val ∈ events5 ∧ eligible InterleavedFixtures.model5 p.val i.val = true := by decide
    exact checked ⟨p, scope⟩ ⟨i, bound⟩ member valid
  · intro p scope i member valid
    have bound : i < 9 := eligible_lt _ _ _ valid
    have checked : ∀ p : Fin 5, ∀ i : Fin 9, i.val ∈ selected5 → eligible ChainSuccessorFixtures.graph5 (priority5 p.val) i.val = true → i.val = priority5 (InterleavedFixtures.owner5 i.val) ∧ InterleavedFixtures.owner5 i.val < 5 := by decide
    exact checked ⟨p, scope⟩ ⟨i, bound⟩ member valid
theorem agreement5 : interleavedUntilStable InterleavedFixtures.model5 InterleavedFixtures.owner5 5 events5 (InterleavedFixtures.model5.level 5 + 1) [] = replayCold ChainSuccessorFixtures.graph5 (priority5 4) selected5 := by
  exact interleaved_and_priority_replay_agree InterleavedFixtures.model5 ChainSuccessorFixtures.graph5 InterleavedFixtures.owner5 priority5 events5 selected5 5 5 4 [] projection5 (by decide) InterleavedFixtures.descending5 (.nil _) (by decide) (by decide) (by decide) (by decide) ChainSuccessorFixtures.acyclic5 (by decide) (by decide)
example : interleavedUntilStable InterleavedFixtures.model5 InterleavedFixtures.owner5 5 [8, 5, 7, 4, 6, 2, 3, 1, 0] (InterleavedFixtures.model5.level 5 + 1) [] = some [2, 0, 4] := by
  rw [interleaved_replay_same_evidence InterleavedFixtures.model5 InterleavedFixtures.owner5 [8, 5, 7, 4, 6, 2, 3, 1, 0] events5 5 [] [] InterleavedFixtures.descending5 (.nil _) (.nil _) (bounded_membership_agrees 9 _ _ (by decide) (by decide) (by decide))]
  rw [agreement5, cold_replay_converges ChainSuccessorFixtures.graph5 (priority5 4) selected5 ChainSuccessorFixtures.acyclic5 (by decide) (by decide)]
  decide
example : interleavedUntilStable InterleavedFixtures.model5 InterleavedFixtures.owner5 5 [0, 1, 3, 2, 6, 4, 7, 5, 8] (InterleavedFixtures.model5.level 5 + 1) [] = some [2, 0, 4] := by
  rw [interleaved_replay_same_evidence InterleavedFixtures.model5 InterleavedFixtures.owner5 [0, 1, 3, 2, 6, 4, 7, 5, 8] events5 5 [] [] InterleavedFixtures.descending5 (.nil _) (.nil _) (bounded_membership_agrees 9 _ _ (by decide) (by decide) (by decide))]
  rw [agreement5, cold_replay_converges ChainSuccessorFixtures.graph5 (priority5 4) selected5 ChainSuccessorFixtures.acyclic5 (by decide) (by decide)]
  decide
example : interleavedUntilStable InterleavedFixtures.model5 InterleavedFixtures.owner5 5 [6, 4, 7, 5, 8, 2, 3, 1, 0] (InterleavedFixtures.model5.level 5 + 1) [] = some [2, 0, 4] := by
  rw [interleaved_replay_same_evidence InterleavedFixtures.model5 InterleavedFixtures.owner5 [6, 4, 7, 5, 8, 2, 3, 1, 0] events5 5 [] [] InterleavedFixtures.descending5 (.nil _) (.nil _) (bounded_membership_agrees 9 _ _ (by decide) (by decide) (by decide))]
  rw [agreement5, cold_replay_converges ChainSuccessorFixtures.graph5 (priority5 4) selected5 ChainSuccessorFixtures.acyclic5 (by decide) (by decide)]
  decide
example : interleavedUntilStable InterleavedFixtures.model5 InterleavedFixtures.owner5 5 [2, 3, 1, 0, 4, 5, 6, 7, 8] (InterleavedFixtures.model5.level 5 + 1) [] = some [2, 0, 4] := by
  rw [interleaved_replay_same_evidence InterleavedFixtures.model5 InterleavedFixtures.owner5 [2, 3, 1, 0, 4, 5, 6, 7, 8] events5 5 [] [] InterleavedFixtures.descending5 (.nil _) (.nil _) (bounded_membership_agrees 9 _ _ (by decide) (by decide) (by decide))]
  rw [agreement5, cold_replay_converges ChainSuccessorFixtures.graph5 (priority5 4) selected5 ChainSuccessorFixtures.acyclic5 (by decide) (by decide)]
  decide
example : interleavedUntilStable InterleavedFixtures.model5 InterleavedFixtures.owner5 5 [7, 6, 8, 5, 4, 0, 1, 3, 2] (InterleavedFixtures.model5.level 5 + 1) [] = some [2, 0, 4] := by
  rw [interleaved_replay_same_evidence InterleavedFixtures.model5 InterleavedFixtures.owner5 [7, 6, 8, 5, 4, 0, 1, 3, 2] events5 5 [] [] InterleavedFixtures.descending5 (.nil _) (.nil _) (bounded_membership_agrees 9 _ _ (by decide) (by decide) (by decide))]
  rw [agreement5, cold_replay_converges ChainSuccessorFixtures.graph5 (priority5 4) selected5 ChainSuccessorFixtures.acyclic5 (by decide) (by decide)]
  decide
example : interleavedUntilStable InterleavedFixtures.model5 InterleavedFixtures.owner5 5 [5, 4, 8, 7, 6, 2, 3, 1, 0] (InterleavedFixtures.model5.level 5 + 1) [] = some [2, 0, 4] := by
  rw [interleaved_replay_same_evidence InterleavedFixtures.model5 InterleavedFixtures.owner5 [5, 4, 8, 7, 6, 2, 3, 1, 0] events5 5 [] [] InterleavedFixtures.descending5 (.nil _) (.nil _) (bounded_membership_agrees 9 _ _ (by decide) (by decide) (by decide))]
  rw [agreement5, cold_replay_converges ChainSuccessorFixtures.graph5 (priority5 4) selected5 ChainSuccessorFixtures.acyclic5 (by decide) (by decide)]
  decide
end Archon.PriorityFixtures
