-- Generated by generate-registry-fixtures.mjs; do not edit.
import RegistryAncestry
set_option warningAsError true
namespace Archon.RegistryFixtures
-- Registry names: BTC:signet, ETH:sepolia, ZEC:testnet, hyperswarm
def graph0 : RegistryGraph := {
  size := 7
  root := 4
  initial := 0
  parent := (fun i => [some 2, some 6, some 4, some 5, none, some 4, some 0].getD i (none))
  depth := (fun i => [2, 4, 1, 2, 0, 1, 3].getD i (0))
  change := (fun i => [none, none, some 2, none, none, some 1, some 0].getD i (none))
}
theorem ordered0 : RegistryOrdered graph0 := by
  intro i p parent
  by_cases bound : i < 7
  · have cases : i = 0 ∨ i = 1 ∨ i = 2 ∨ i = 3 ∨ i = 4 ∨ i = 5 ∨ i = 6 := by omega
    rcases cases with rfl | rfl | rfl | rfl | rfl | rfl | rfl <;> simp [graph0] at parent
    all_goals subst p; decide
  · have outside : 7 ≤ i := by omega
    simp only [graph0] at parent
    rw [List.getD_eq_getElem?_getD, List.getElem?_eq_none (by simpa using outside)] at parent
    simp at parent
example : expectedRegistry graph0 4 = some 0 := by decide
example : receiptRegistryMatches graph0 0 0 = false := by
  apply Bool.eq_false_iff.mpr
  intro matched
  have different : 0 ≠ registryFold graph0 graph0.initial [2] := by decide
  exact different ((receipt_registry_after_prefix graph0 ordered0 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [2] (.cons (by decide) (by decide) (.nil _)) 0 0 (by decide) (by decide)).mp matched)
example : receiptRegistryMatches graph0 0 2 = true := by
  exact (receipt_registry_after_prefix graph0 ordered0 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [2] (.cons (by decide) (by decide) (.nil _)) 0 2 (by decide) (by decide)).mpr (by decide)
example : receiptRegistryMatches graph0 0 3 = false := by
  apply Bool.eq_false_iff.mpr
  intro matched
  have different : 3 ≠ registryFold graph0 graph0.initial [2] := by decide
  exact different ((receipt_registry_after_prefix graph0 ordered0 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [2] (.cons (by decide) (by decide) (.nil _)) 0 3 (by decide) (by decide)).mp matched)
example : receiptRegistryMatches graph0 1 0 = true := by
  exact (receipt_registry_after_prefix graph0 ordered0 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [2, 0, 6] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _)))) 1 0 (by decide) (by decide)).mpr (by decide)
example : receiptRegistryMatches graph0 1 3 = false := by
  apply Bool.eq_false_iff.mpr
  intro matched
  have different : 3 ≠ registryFold graph0 graph0.initial [2, 0, 6] := by decide
  exact different ((receipt_registry_after_prefix graph0 ordered0 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [2, 0, 6] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _)))) 1 3 (by decide) (by decide)).mp matched)
example : receiptRegistryMatches graph0 2 0 = true := by
  exact (receipt_registry_after_prefix graph0 ordered0 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [] (.nil _) 2 0 (by decide) (by decide)).mpr (by decide)
example : receiptRegistryMatches graph0 2 2 = false := by
  apply Bool.eq_false_iff.mpr
  intro matched
  have different : 2 ≠ registryFold graph0 graph0.initial [] := by decide
  exact different ((receipt_registry_after_prefix graph0 ordered0 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [] (.nil _) 2 2 (by decide) (by decide)).mp matched)
example : receiptRegistryMatches graph0 2 3 = false := by
  apply Bool.eq_false_iff.mpr
  intro matched
  have different : 3 ≠ registryFold graph0 graph0.initial [] := by decide
  exact different ((receipt_registry_after_prefix graph0 ordered0 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [] (.nil _) 2 3 (by decide) (by decide)).mp matched)
example : receiptRegistryMatches graph0 3 1 = true := by
  exact (receipt_registry_after_prefix graph0 ordered0 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [5] (.cons (by decide) (by decide) (.nil _)) 3 1 (by decide) (by decide)).mpr (by decide)
example : receiptRegistryMatches graph0 3 3 = false := by
  apply Bool.eq_false_iff.mpr
  intro matched
  have different : 3 ≠ registryFold graph0 graph0.initial [5] := by decide
  exact different ((receipt_registry_after_prefix graph0 ordered0 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [5] (.cons (by decide) (by decide) (.nil _)) 3 3 (by decide) (by decide)).mp matched)
example : receiptRegistryMatches graph0 4 0 = true := by decide
example : receiptRegistryMatches graph0 4 3 = false := by decide
example : receiptRegistryMatches graph0 5 0 = true := by
  exact (receipt_registry_after_prefix graph0 ordered0 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [] (.nil _) 5 0 (by decide) (by decide)).mpr (by decide)
example : receiptRegistryMatches graph0 5 3 = false := by
  apply Bool.eq_false_iff.mpr
  intro matched
  have different : 3 ≠ registryFold graph0 graph0.initial [] := by decide
  exact different ((receipt_registry_after_prefix graph0 ordered0 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [] (.nil _) 5 3 (by decide) (by decide)).mp matched)
example : receiptRegistryMatches graph0 6 2 = true := by
  exact (receipt_registry_after_prefix graph0 ordered0 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [2, 0] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 6 2 (by decide) (by decide)).mpr (by decide)
example : receiptRegistryMatches graph0 6 3 = false := by
  apply Bool.eq_false_iff.mpr
  intro matched
  have different : 3 ≠ registryFold graph0 graph0.initial [2, 0] := by decide
  exact different ((receipt_registry_after_prefix graph0 ordered0 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [2, 0] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 6 3 (by decide) (by decide)).mp matched)
example : expectedRegistry graph0 0 = some 2 := by
  have h := expected_registry_after_prefix graph0 ordered0 (by decide) (by decide) [4, 2, 5, 0, 3, 6, 1, 4, 2, 5, 2, 0, 0, 3, 6, 1] [2] (.cons (by decide) (by decide) (.nil _)) 0 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph0 1 = some 0 := by
  have h := expected_registry_after_prefix graph0 ordered0 (by decide) (by decide) [4, 2, 5, 0, 3, 6, 1, 4, 2, 5, 2, 0, 0, 3, 6, 1] [2, 0, 6] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _)))) 1 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph0 2 = some 0 := by
  have h := expected_registry_after_prefix graph0 ordered0 (by decide) (by decide) [4, 2, 5, 0, 3, 6, 1, 4, 2, 5, 2, 0, 0, 3, 6, 1] [] (.nil _) 2 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph0 3 = some 1 := by
  have h := expected_registry_after_prefix graph0 ordered0 (by decide) (by decide) [4, 2, 5, 0, 3, 6, 1, 4, 2, 5, 2, 0, 0, 3, 6, 1] [5] (.cons (by decide) (by decide) (.nil _)) 3 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph0 5 = some 0 := by
  have h := expected_registry_after_prefix graph0 ordered0 (by decide) (by decide) [4, 2, 5, 0, 3, 6, 1, 4, 2, 5, 2, 0, 0, 3, 6, 1] [] (.nil _) 5 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph0 6 = some 2 := by
  have h := expected_registry_after_prefix graph0 ordered0 (by decide) (by decide) [4, 2, 5, 0, 3, 6, 1, 4, 2, 5, 2, 0, 0, 3, 6, 1] [2, 0] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 6 (by decide) (by decide)
  exact h.trans (by decide)
example : registryAt graph0 3 = some 1 := by
  have h := registry_prefix_agrees graph0 ordered0 (by decide) [4, 2, 5, 0, 3, 6, 1, 4, 2, 5, 2, 0, 0, 3, 6, 1] 4 [5, 3] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 0 (registry_at_root _ (by decide))
  exact h.trans (by decide)
example : expectedRegistry graph0 0 = some 2 := by
  have h := expected_registry_after_prefix graph0 ordered0 (by decide) (by decide) [1, 6, 3, 0, 0, 2, 5, 2, 4, 1, 6, 3, 0, 5, 2, 4] [2] (.cons (by decide) (by decide) (.nil _)) 0 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph0 1 = some 0 := by
  have h := expected_registry_after_prefix graph0 ordered0 (by decide) (by decide) [1, 6, 3, 0, 0, 2, 5, 2, 4, 1, 6, 3, 0, 5, 2, 4] [2, 0, 6] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _)))) 1 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph0 2 = some 0 := by
  have h := expected_registry_after_prefix graph0 ordered0 (by decide) (by decide) [1, 6, 3, 0, 0, 2, 5, 2, 4, 1, 6, 3, 0, 5, 2, 4] [] (.nil _) 2 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph0 3 = some 1 := by
  have h := expected_registry_after_prefix graph0 ordered0 (by decide) (by decide) [1, 6, 3, 0, 0, 2, 5, 2, 4, 1, 6, 3, 0, 5, 2, 4] [5] (.cons (by decide) (by decide) (.nil _)) 3 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph0 5 = some 0 := by
  have h := expected_registry_after_prefix graph0 ordered0 (by decide) (by decide) [1, 6, 3, 0, 0, 2, 5, 2, 4, 1, 6, 3, 0, 5, 2, 4] [] (.nil _) 5 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph0 6 = some 2 := by
  have h := expected_registry_after_prefix graph0 ordered0 (by decide) (by decide) [1, 6, 3, 0, 0, 2, 5, 2, 4, 1, 6, 3, 0, 5, 2, 4] [2, 0] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 6 (by decide) (by decide)
  exact h.trans (by decide)
example : registryAt graph0 3 = some 1 := by
  have h := registry_prefix_agrees graph0 ordered0 (by decide) [1, 6, 3, 0, 0, 2, 5, 2, 4, 1, 6, 3, 0, 5, 2, 4] 4 [5, 3] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 0 (registry_at_root _ (by decide))
  exact h.trans (by decide)
example : expectedRegistry graph0 0 = some 2 := by
  have h := expected_registry_after_prefix graph0 ordered0 (by decide) (by decide) [4, 2, 5, 2, 0, 0, 3, 6, 1, 1, 6, 3, 0, 5, 2, 4] [2] (.cons (by decide) (by decide) (.nil _)) 0 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph0 1 = some 0 := by
  have h := expected_registry_after_prefix graph0 ordered0 (by decide) (by decide) [4, 2, 5, 2, 0, 0, 3, 6, 1, 1, 6, 3, 0, 5, 2, 4] [2, 0, 6] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _)))) 1 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph0 2 = some 0 := by
  have h := expected_registry_after_prefix graph0 ordered0 (by decide) (by decide) [4, 2, 5, 2, 0, 0, 3, 6, 1, 1, 6, 3, 0, 5, 2, 4] [] (.nil _) 2 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph0 3 = some 1 := by
  have h := expected_registry_after_prefix graph0 ordered0 (by decide) (by decide) [4, 2, 5, 2, 0, 0, 3, 6, 1, 1, 6, 3, 0, 5, 2, 4] [5] (.cons (by decide) (by decide) (.nil _)) 3 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph0 5 = some 0 := by
  have h := expected_registry_after_prefix graph0 ordered0 (by decide) (by decide) [4, 2, 5, 2, 0, 0, 3, 6, 1, 1, 6, 3, 0, 5, 2, 4] [] (.nil _) 5 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph0 6 = some 2 := by
  have h := expected_registry_after_prefix graph0 ordered0 (by decide) (by decide) [4, 2, 5, 2, 0, 0, 3, 6, 1, 1, 6, 3, 0, 5, 2, 4] [2, 0] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 6 (by decide) (by decide)
  exact h.trans (by decide)
example : registryAt graph0 3 = some 1 := by
  have h := registry_prefix_agrees graph0 ordered0 (by decide) [4, 2, 5, 2, 0, 0, 3, 6, 1, 1, 6, 3, 0, 5, 2, 4] 4 [5, 3] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 0 (registry_at_root _ (by decide))
  exact h.trans (by decide)
example : expectedRegistry graph0 0 = some 2 := by
  have h := expected_registry_after_prefix graph0 ordered0 (by decide) (by decide) [1, 6, 3, 0, 5, 2, 4, 4, 2, 5, 2, 0, 0, 3, 6, 1] [2] (.cons (by decide) (by decide) (.nil _)) 0 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph0 1 = some 0 := by
  have h := expected_registry_after_prefix graph0 ordered0 (by decide) (by decide) [1, 6, 3, 0, 5, 2, 4, 4, 2, 5, 2, 0, 0, 3, 6, 1] [2, 0, 6] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _)))) 1 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph0 2 = some 0 := by
  have h := expected_registry_after_prefix graph0 ordered0 (by decide) (by decide) [1, 6, 3, 0, 5, 2, 4, 4, 2, 5, 2, 0, 0, 3, 6, 1] [] (.nil _) 2 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph0 3 = some 1 := by
  have h := expected_registry_after_prefix graph0 ordered0 (by decide) (by decide) [1, 6, 3, 0, 5, 2, 4, 4, 2, 5, 2, 0, 0, 3, 6, 1] [5] (.cons (by decide) (by decide) (.nil _)) 3 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph0 5 = some 0 := by
  have h := expected_registry_after_prefix graph0 ordered0 (by decide) (by decide) [1, 6, 3, 0, 5, 2, 4, 4, 2, 5, 2, 0, 0, 3, 6, 1] [] (.nil _) 5 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph0 6 = some 2 := by
  have h := expected_registry_after_prefix graph0 ordered0 (by decide) (by decide) [1, 6, 3, 0, 5, 2, 4, 4, 2, 5, 2, 0, 0, 3, 6, 1] [2, 0] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 6 (by decide) (by decide)
  exact h.trans (by decide)
example : registryAt graph0 3 = some 1 := by
  have h := registry_prefix_agrees graph0 ordered0 (by decide) [1, 6, 3, 0, 5, 2, 4, 4, 2, 5, 2, 0, 0, 3, 6, 1] 4 [5, 3] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 0 (registry_at_root _ (by decide))
  exact h.trans (by decide)
example : expectedRegistry graph0 0 = some 2 := by
  have h := expected_registry_after_prefix graph0 ordered0 (by decide) (by decide) [5, 3, 4, 2, 0, 6, 1, 1, 6, 3, 0, 0, 2, 5, 2, 4] [2] (.cons (by decide) (by decide) (.nil _)) 0 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph0 1 = some 0 := by
  have h := expected_registry_after_prefix graph0 ordered0 (by decide) (by decide) [5, 3, 4, 2, 0, 6, 1, 1, 6, 3, 0, 0, 2, 5, 2, 4] [2, 0, 6] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _)))) 1 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph0 2 = some 0 := by
  have h := expected_registry_after_prefix graph0 ordered0 (by decide) (by decide) [5, 3, 4, 2, 0, 6, 1, 1, 6, 3, 0, 0, 2, 5, 2, 4] [] (.nil _) 2 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph0 3 = some 1 := by
  have h := expected_registry_after_prefix graph0 ordered0 (by decide) (by decide) [5, 3, 4, 2, 0, 6, 1, 1, 6, 3, 0, 0, 2, 5, 2, 4] [5] (.cons (by decide) (by decide) (.nil _)) 3 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph0 5 = some 0 := by
  have h := expected_registry_after_prefix graph0 ordered0 (by decide) (by decide) [5, 3, 4, 2, 0, 6, 1, 1, 6, 3, 0, 0, 2, 5, 2, 4] [] (.nil _) 5 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph0 6 = some 2 := by
  have h := expected_registry_after_prefix graph0 ordered0 (by decide) (by decide) [5, 3, 4, 2, 0, 6, 1, 1, 6, 3, 0, 0, 2, 5, 2, 4] [2, 0] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 6 (by decide) (by decide)
  exact h.trans (by decide)
example : registryAt graph0 3 = some 1 := by
  have h := registry_prefix_agrees graph0 ordered0 (by decide) [5, 3, 4, 2, 0, 6, 1, 1, 6, 3, 0, 0, 2, 5, 2, 4] 4 [5, 3] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 0 (registry_at_root _ (by decide))
  exact h.trans (by decide)
example : expectedRegistry graph0 0 = some 2 := by
  have h := expected_registry_after_prefix graph0 ordered0 (by decide) (by decide) [2, 0, 6, 1, 4, 5, 3, 4, 2, 5, 2, 0, 0, 3, 6, 1] [2] (.cons (by decide) (by decide) (.nil _)) 0 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph0 1 = some 0 := by
  have h := expected_registry_after_prefix graph0 ordered0 (by decide) (by decide) [2, 0, 6, 1, 4, 5, 3, 4, 2, 5, 2, 0, 0, 3, 6, 1] [2, 0, 6] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _)))) 1 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph0 2 = some 0 := by
  have h := expected_registry_after_prefix graph0 ordered0 (by decide) (by decide) [2, 0, 6, 1, 4, 5, 3, 4, 2, 5, 2, 0, 0, 3, 6, 1] [] (.nil _) 2 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph0 3 = some 1 := by
  have h := expected_registry_after_prefix graph0 ordered0 (by decide) (by decide) [2, 0, 6, 1, 4, 5, 3, 4, 2, 5, 2, 0, 0, 3, 6, 1] [5] (.cons (by decide) (by decide) (.nil _)) 3 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph0 5 = some 0 := by
  have h := expected_registry_after_prefix graph0 ordered0 (by decide) (by decide) [2, 0, 6, 1, 4, 5, 3, 4, 2, 5, 2, 0, 0, 3, 6, 1] [] (.nil _) 5 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph0 6 = some 2 := by
  have h := expected_registry_after_prefix graph0 ordered0 (by decide) (by decide) [2, 0, 6, 1, 4, 5, 3, 4, 2, 5, 2, 0, 0, 3, 6, 1] [2, 0] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 6 (by decide) (by decide)
  exact h.trans (by decide)
example : registryAt graph0 3 = some 1 := by
  have h := registry_prefix_agrees graph0 ordered0 (by decide) [2, 0, 6, 1, 4, 5, 3, 4, 2, 5, 2, 0, 0, 3, 6, 1] 4 [5, 3] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 0 (registry_at_root _ (by decide))
  exact h.trans (by decide)
-- Registry names: BTC:signet, ETH:sepolia, ZEC:testnet, hyperswarm
def graph1 : RegistryGraph := {
  size := 7
  root := 4
  initial := 0
  parent := (fun i => [some 2, some 6, some 4, some 5, none, some 4, some 0].getD i (none))
  depth := (fun i => [2, 4, 1, 2, 0, 1, 3].getD i (0))
  change := (fun i => [none, none, some 2, none, none, some 1, some 0].getD i (none))
}
theorem ordered1 : RegistryOrdered graph1 := by
  intro i p parent
  by_cases bound : i < 7
  · have cases : i = 0 ∨ i = 1 ∨ i = 2 ∨ i = 3 ∨ i = 4 ∨ i = 5 ∨ i = 6 := by omega
    rcases cases with rfl | rfl | rfl | rfl | rfl | rfl | rfl <;> simp [graph1] at parent
    all_goals subst p; decide
  · have outside : 7 ≤ i := by omega
    simp only [graph1] at parent
    rw [List.getD_eq_getElem?_getD, List.getElem?_eq_none (by simpa using outside)] at parent
    simp at parent
example : expectedRegistry graph1 4 = some 0 := by decide
example : receiptRegistryMatches graph1 0 0 = false := by
  apply Bool.eq_false_iff.mpr
  intro matched
  have different : 0 ≠ registryFold graph1 graph1.initial [2] := by decide
  exact different ((receipt_registry_after_prefix graph1 ordered1 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [2] (.cons (by decide) (by decide) (.nil _)) 0 0 (by decide) (by decide)).mp matched)
example : receiptRegistryMatches graph1 0 2 = true := by
  exact (receipt_registry_after_prefix graph1 ordered1 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [2] (.cons (by decide) (by decide) (.nil _)) 0 2 (by decide) (by decide)).mpr (by decide)
example : receiptRegistryMatches graph1 0 3 = false := by
  apply Bool.eq_false_iff.mpr
  intro matched
  have different : 3 ≠ registryFold graph1 graph1.initial [2] := by decide
  exact different ((receipt_registry_after_prefix graph1 ordered1 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [2] (.cons (by decide) (by decide) (.nil _)) 0 3 (by decide) (by decide)).mp matched)
example : receiptRegistryMatches graph1 1 0 = true := by
  exact (receipt_registry_after_prefix graph1 ordered1 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [2, 0, 6] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _)))) 1 0 (by decide) (by decide)).mpr (by decide)
example : receiptRegistryMatches graph1 1 3 = false := by
  apply Bool.eq_false_iff.mpr
  intro matched
  have different : 3 ≠ registryFold graph1 graph1.initial [2, 0, 6] := by decide
  exact different ((receipt_registry_after_prefix graph1 ordered1 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [2, 0, 6] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _)))) 1 3 (by decide) (by decide)).mp matched)
example : receiptRegistryMatches graph1 2 0 = true := by
  exact (receipt_registry_after_prefix graph1 ordered1 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [] (.nil _) 2 0 (by decide) (by decide)).mpr (by decide)
example : receiptRegistryMatches graph1 2 0 = true := by
  exact (receipt_registry_after_prefix graph1 ordered1 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [] (.nil _) 2 0 (by decide) (by decide)).mpr (by decide)
example : receiptRegistryMatches graph1 2 2 = false := by
  apply Bool.eq_false_iff.mpr
  intro matched
  have different : 2 ≠ registryFold graph1 graph1.initial [] := by decide
  exact different ((receipt_registry_after_prefix graph1 ordered1 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [] (.nil _) 2 2 (by decide) (by decide)).mp matched)
example : receiptRegistryMatches graph1 2 3 = false := by
  apply Bool.eq_false_iff.mpr
  intro matched
  have different : 3 ≠ registryFold graph1 graph1.initial [] := by decide
  exact different ((receipt_registry_after_prefix graph1 ordered1 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [] (.nil _) 2 3 (by decide) (by decide)).mp matched)
example : receiptRegistryMatches graph1 3 1 = true := by
  exact (receipt_registry_after_prefix graph1 ordered1 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [5] (.cons (by decide) (by decide) (.nil _)) 3 1 (by decide) (by decide)).mpr (by decide)
example : receiptRegistryMatches graph1 3 3 = false := by
  apply Bool.eq_false_iff.mpr
  intro matched
  have different : 3 ≠ registryFold graph1 graph1.initial [5] := by decide
  exact different ((receipt_registry_after_prefix graph1 ordered1 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [5] (.cons (by decide) (by decide) (.nil _)) 3 3 (by decide) (by decide)).mp matched)
example : receiptRegistryMatches graph1 4 0 = true := by decide
example : receiptRegistryMatches graph1 4 3 = false := by decide
example : receiptRegistryMatches graph1 5 0 = true := by
  exact (receipt_registry_after_prefix graph1 ordered1 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [] (.nil _) 5 0 (by decide) (by decide)).mpr (by decide)
example : receiptRegistryMatches graph1 5 3 = false := by
  apply Bool.eq_false_iff.mpr
  intro matched
  have different : 3 ≠ registryFold graph1 graph1.initial [] := by decide
  exact different ((receipt_registry_after_prefix graph1 ordered1 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [] (.nil _) 5 3 (by decide) (by decide)).mp matched)
example : receiptRegistryMatches graph1 6 2 = true := by
  exact (receipt_registry_after_prefix graph1 ordered1 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [2, 0] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 6 2 (by decide) (by decide)).mpr (by decide)
example : receiptRegistryMatches graph1 6 3 = false := by
  apply Bool.eq_false_iff.mpr
  intro matched
  have different : 3 ≠ registryFold graph1 graph1.initial [2, 0] := by decide
  exact different ((receipt_registry_after_prefix graph1 ordered1 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [2, 0] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 6 3 (by decide) (by decide)).mp matched)
example : expectedRegistry graph1 0 = some 2 := by
  have h := expected_registry_after_prefix graph1 ordered1 (by decide) (by decide) [4, 2, 5, 0, 3, 6, 1, 4, 2, 5, 2, 0, 0, 3, 6, 1, 2] [2] (.cons (by decide) (by decide) (.nil _)) 0 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph1 1 = some 0 := by
  have h := expected_registry_after_prefix graph1 ordered1 (by decide) (by decide) [4, 2, 5, 0, 3, 6, 1, 4, 2, 5, 2, 0, 0, 3, 6, 1, 2] [2, 0, 6] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _)))) 1 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph1 2 = some 0 := by
  have h := expected_registry_after_prefix graph1 ordered1 (by decide) (by decide) [4, 2, 5, 0, 3, 6, 1, 4, 2, 5, 2, 0, 0, 3, 6, 1, 2] [] (.nil _) 2 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph1 3 = some 1 := by
  have h := expected_registry_after_prefix graph1 ordered1 (by decide) (by decide) [4, 2, 5, 0, 3, 6, 1, 4, 2, 5, 2, 0, 0, 3, 6, 1, 2] [5] (.cons (by decide) (by decide) (.nil _)) 3 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph1 5 = some 0 := by
  have h := expected_registry_after_prefix graph1 ordered1 (by decide) (by decide) [4, 2, 5, 0, 3, 6, 1, 4, 2, 5, 2, 0, 0, 3, 6, 1, 2] [] (.nil _) 5 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph1 6 = some 2 := by
  have h := expected_registry_after_prefix graph1 ordered1 (by decide) (by decide) [4, 2, 5, 0, 3, 6, 1, 4, 2, 5, 2, 0, 0, 3, 6, 1, 2] [2, 0] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 6 (by decide) (by decide)
  exact h.trans (by decide)
example : registryAt graph1 1 = some 0 := by
  have h := registry_prefix_agrees graph1 ordered1 (by decide) [4, 2, 5, 0, 3, 6, 1, 4, 2, 5, 2, 0, 0, 3, 6, 1, 2] 4 [2, 0, 6, 1] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))))) 0 (registry_at_root _ (by decide))
  exact h.trans (by decide)
example : expectedRegistry graph1 0 = some 2 := by
  have h := expected_registry_after_prefix graph1 ordered1 (by decide) (by decide) [2, 1, 6, 3, 0, 0, 2, 5, 2, 4, 1, 6, 3, 0, 5, 2, 4] [2] (.cons (by decide) (by decide) (.nil _)) 0 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph1 1 = some 0 := by
  have h := expected_registry_after_prefix graph1 ordered1 (by decide) (by decide) [2, 1, 6, 3, 0, 0, 2, 5, 2, 4, 1, 6, 3, 0, 5, 2, 4] [2, 0, 6] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _)))) 1 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph1 2 = some 0 := by
  have h := expected_registry_after_prefix graph1 ordered1 (by decide) (by decide) [2, 1, 6, 3, 0, 0, 2, 5, 2, 4, 1, 6, 3, 0, 5, 2, 4] [] (.nil _) 2 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph1 3 = some 1 := by
  have h := expected_registry_after_prefix graph1 ordered1 (by decide) (by decide) [2, 1, 6, 3, 0, 0, 2, 5, 2, 4, 1, 6, 3, 0, 5, 2, 4] [5] (.cons (by decide) (by decide) (.nil _)) 3 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph1 5 = some 0 := by
  have h := expected_registry_after_prefix graph1 ordered1 (by decide) (by decide) [2, 1, 6, 3, 0, 0, 2, 5, 2, 4, 1, 6, 3, 0, 5, 2, 4] [] (.nil _) 5 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph1 6 = some 2 := by
  have h := expected_registry_after_prefix graph1 ordered1 (by decide) (by decide) [2, 1, 6, 3, 0, 0, 2, 5, 2, 4, 1, 6, 3, 0, 5, 2, 4] [2, 0] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 6 (by decide) (by decide)
  exact h.trans (by decide)
example : registryAt graph1 1 = some 0 := by
  have h := registry_prefix_agrees graph1 ordered1 (by decide) [2, 1, 6, 3, 0, 0, 2, 5, 2, 4, 1, 6, 3, 0, 5, 2, 4] 4 [2, 0, 6, 1] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))))) 0 (registry_at_root _ (by decide))
  exact h.trans (by decide)
example : expectedRegistry graph1 0 = some 2 := by
  have h := expected_registry_after_prefix graph1 ordered1 (by decide) (by decide) [4, 2, 5, 2, 0, 0, 3, 6, 1, 2, 1, 6, 3, 0, 5, 2, 4] [2] (.cons (by decide) (by decide) (.nil _)) 0 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph1 1 = some 0 := by
  have h := expected_registry_after_prefix graph1 ordered1 (by decide) (by decide) [4, 2, 5, 2, 0, 0, 3, 6, 1, 2, 1, 6, 3, 0, 5, 2, 4] [2, 0, 6] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _)))) 1 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph1 2 = some 0 := by
  have h := expected_registry_after_prefix graph1 ordered1 (by decide) (by decide) [4, 2, 5, 2, 0, 0, 3, 6, 1, 2, 1, 6, 3, 0, 5, 2, 4] [] (.nil _) 2 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph1 3 = some 1 := by
  have h := expected_registry_after_prefix graph1 ordered1 (by decide) (by decide) [4, 2, 5, 2, 0, 0, 3, 6, 1, 2, 1, 6, 3, 0, 5, 2, 4] [5] (.cons (by decide) (by decide) (.nil _)) 3 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph1 5 = some 0 := by
  have h := expected_registry_after_prefix graph1 ordered1 (by decide) (by decide) [4, 2, 5, 2, 0, 0, 3, 6, 1, 2, 1, 6, 3, 0, 5, 2, 4] [] (.nil _) 5 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph1 6 = some 2 := by
  have h := expected_registry_after_prefix graph1 ordered1 (by decide) (by decide) [4, 2, 5, 2, 0, 0, 3, 6, 1, 2, 1, 6, 3, 0, 5, 2, 4] [2, 0] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 6 (by decide) (by decide)
  exact h.trans (by decide)
example : registryAt graph1 1 = some 0 := by
  have h := registry_prefix_agrees graph1 ordered1 (by decide) [4, 2, 5, 2, 0, 0, 3, 6, 1, 2, 1, 6, 3, 0, 5, 2, 4] 4 [2, 0, 6, 1] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))))) 0 (registry_at_root _ (by decide))
  exact h.trans (by decide)
example : expectedRegistry graph1 0 = some 2 := by
  have h := expected_registry_after_prefix graph1 ordered1 (by decide) (by decide) [1, 6, 3, 0, 5, 2, 4, 4, 2, 5, 2, 0, 0, 3, 6, 1, 2] [2] (.cons (by decide) (by decide) (.nil _)) 0 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph1 1 = some 0 := by
  have h := expected_registry_after_prefix graph1 ordered1 (by decide) (by decide) [1, 6, 3, 0, 5, 2, 4, 4, 2, 5, 2, 0, 0, 3, 6, 1, 2] [2, 0, 6] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _)))) 1 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph1 2 = some 0 := by
  have h := expected_registry_after_prefix graph1 ordered1 (by decide) (by decide) [1, 6, 3, 0, 5, 2, 4, 4, 2, 5, 2, 0, 0, 3, 6, 1, 2] [] (.nil _) 2 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph1 3 = some 1 := by
  have h := expected_registry_after_prefix graph1 ordered1 (by decide) (by decide) [1, 6, 3, 0, 5, 2, 4, 4, 2, 5, 2, 0, 0, 3, 6, 1, 2] [5] (.cons (by decide) (by decide) (.nil _)) 3 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph1 5 = some 0 := by
  have h := expected_registry_after_prefix graph1 ordered1 (by decide) (by decide) [1, 6, 3, 0, 5, 2, 4, 4, 2, 5, 2, 0, 0, 3, 6, 1, 2] [] (.nil _) 5 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph1 6 = some 2 := by
  have h := expected_registry_after_prefix graph1 ordered1 (by decide) (by decide) [1, 6, 3, 0, 5, 2, 4, 4, 2, 5, 2, 0, 0, 3, 6, 1, 2] [2, 0] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 6 (by decide) (by decide)
  exact h.trans (by decide)
example : registryAt graph1 1 = some 0 := by
  have h := registry_prefix_agrees graph1 ordered1 (by decide) [1, 6, 3, 0, 5, 2, 4, 4, 2, 5, 2, 0, 0, 3, 6, 1, 2] 4 [2, 0, 6, 1] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))))) 0 (registry_at_root _ (by decide))
  exact h.trans (by decide)
example : expectedRegistry graph1 0 = some 2 := by
  have h := expected_registry_after_prefix graph1 ordered1 (by decide) (by decide) [5, 3, 4, 2, 0, 6, 1, 2, 1, 6, 3, 0, 0, 2, 5, 2, 4] [2] (.cons (by decide) (by decide) (.nil _)) 0 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph1 1 = some 0 := by
  have h := expected_registry_after_prefix graph1 ordered1 (by decide) (by decide) [5, 3, 4, 2, 0, 6, 1, 2, 1, 6, 3, 0, 0, 2, 5, 2, 4] [2, 0, 6] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _)))) 1 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph1 2 = some 0 := by
  have h := expected_registry_after_prefix graph1 ordered1 (by decide) (by decide) [5, 3, 4, 2, 0, 6, 1, 2, 1, 6, 3, 0, 0, 2, 5, 2, 4] [] (.nil _) 2 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph1 3 = some 1 := by
  have h := expected_registry_after_prefix graph1 ordered1 (by decide) (by decide) [5, 3, 4, 2, 0, 6, 1, 2, 1, 6, 3, 0, 0, 2, 5, 2, 4] [5] (.cons (by decide) (by decide) (.nil _)) 3 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph1 5 = some 0 := by
  have h := expected_registry_after_prefix graph1 ordered1 (by decide) (by decide) [5, 3, 4, 2, 0, 6, 1, 2, 1, 6, 3, 0, 0, 2, 5, 2, 4] [] (.nil _) 5 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph1 6 = some 2 := by
  have h := expected_registry_after_prefix graph1 ordered1 (by decide) (by decide) [5, 3, 4, 2, 0, 6, 1, 2, 1, 6, 3, 0, 0, 2, 5, 2, 4] [2, 0] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 6 (by decide) (by decide)
  exact h.trans (by decide)
example : registryAt graph1 1 = some 0 := by
  have h := registry_prefix_agrees graph1 ordered1 (by decide) [5, 3, 4, 2, 0, 6, 1, 2, 1, 6, 3, 0, 0, 2, 5, 2, 4] 4 [2, 0, 6, 1] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))))) 0 (registry_at_root _ (by decide))
  exact h.trans (by decide)
example : expectedRegistry graph1 0 = some 2 := by
  have h := expected_registry_after_prefix graph1 ordered1 (by decide) (by decide) [2, 0, 6, 1, 4, 5, 3, 4, 2, 5, 2, 0, 0, 3, 6, 1, 2] [2] (.cons (by decide) (by decide) (.nil _)) 0 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph1 1 = some 0 := by
  have h := expected_registry_after_prefix graph1 ordered1 (by decide) (by decide) [2, 0, 6, 1, 4, 5, 3, 4, 2, 5, 2, 0, 0, 3, 6, 1, 2] [2, 0, 6] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _)))) 1 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph1 2 = some 0 := by
  have h := expected_registry_after_prefix graph1 ordered1 (by decide) (by decide) [2, 0, 6, 1, 4, 5, 3, 4, 2, 5, 2, 0, 0, 3, 6, 1, 2] [] (.nil _) 2 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph1 3 = some 1 := by
  have h := expected_registry_after_prefix graph1 ordered1 (by decide) (by decide) [2, 0, 6, 1, 4, 5, 3, 4, 2, 5, 2, 0, 0, 3, 6, 1, 2] [5] (.cons (by decide) (by decide) (.nil _)) 3 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph1 5 = some 0 := by
  have h := expected_registry_after_prefix graph1 ordered1 (by decide) (by decide) [2, 0, 6, 1, 4, 5, 3, 4, 2, 5, 2, 0, 0, 3, 6, 1, 2] [] (.nil _) 5 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph1 6 = some 2 := by
  have h := expected_registry_after_prefix graph1 ordered1 (by decide) (by decide) [2, 0, 6, 1, 4, 5, 3, 4, 2, 5, 2, 0, 0, 3, 6, 1, 2] [2, 0] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 6 (by decide) (by decide)
  exact h.trans (by decide)
example : registryAt graph1 1 = some 0 := by
  have h := registry_prefix_agrees graph1 ordered1 (by decide) [2, 0, 6, 1, 4, 5, 3, 4, 2, 5, 2, 0, 0, 3, 6, 1, 2] 4 [2, 0, 6, 1] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))))) 0 (registry_at_root _ (by decide))
  exact h.trans (by decide)
-- Registry names: BTC:signet, ETH:sepolia, ZEC:testnet, hyperswarm
def graph2 : RegistryGraph := {
  size := 7
  root := 4
  initial := 0
  parent := (fun i => [some 4, some 4, some 1, some 5, none, some 6, some 0].getD i (none))
  depth := (fun i => [1, 1, 2, 4, 0, 3, 2].getD i (0))
  change := (fun i => [some 2, some 1, none, none, none, some 0, none].getD i (none))
}
theorem ordered2 : RegistryOrdered graph2 := by
  intro i p parent
  by_cases bound : i < 7
  · have cases : i = 0 ∨ i = 1 ∨ i = 2 ∨ i = 3 ∨ i = 4 ∨ i = 5 ∨ i = 6 := by omega
    rcases cases with rfl | rfl | rfl | rfl | rfl | rfl | rfl <;> simp [graph2] at parent
    all_goals subst p; decide
  · have outside : 7 ≤ i := by omega
    simp only [graph2] at parent
    rw [List.getD_eq_getElem?_getD, List.getElem?_eq_none (by simpa using outside)] at parent
    simp at parent
example : expectedRegistry graph2 4 = some 0 := by decide
example : receiptRegistryMatches graph2 0 0 = true := by
  exact (receipt_registry_after_prefix graph2 ordered2 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [] (.nil _) 0 0 (by decide) (by decide)).mpr (by decide)
example : receiptRegistryMatches graph2 0 2 = false := by
  apply Bool.eq_false_iff.mpr
  intro matched
  have different : 2 ≠ registryFold graph2 graph2.initial [] := by decide
  exact different ((receipt_registry_after_prefix graph2 ordered2 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [] (.nil _) 0 2 (by decide) (by decide)).mp matched)
example : receiptRegistryMatches graph2 0 3 = false := by
  apply Bool.eq_false_iff.mpr
  intro matched
  have different : 3 ≠ registryFold graph2 graph2.initial [] := by decide
  exact different ((receipt_registry_after_prefix graph2 ordered2 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [] (.nil _) 0 3 (by decide) (by decide)).mp matched)
example : receiptRegistryMatches graph2 1 0 = true := by
  exact (receipt_registry_after_prefix graph2 ordered2 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [] (.nil _) 1 0 (by decide) (by decide)).mpr (by decide)
example : receiptRegistryMatches graph2 1 3 = false := by
  apply Bool.eq_false_iff.mpr
  intro matched
  have different : 3 ≠ registryFold graph2 graph2.initial [] := by decide
  exact different ((receipt_registry_after_prefix graph2 ordered2 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [] (.nil _) 1 3 (by decide) (by decide)).mp matched)
example : receiptRegistryMatches graph2 2 1 = true := by
  exact (receipt_registry_after_prefix graph2 ordered2 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [1] (.cons (by decide) (by decide) (.nil _)) 2 1 (by decide) (by decide)).mpr (by decide)
example : receiptRegistryMatches graph2 2 3 = false := by
  apply Bool.eq_false_iff.mpr
  intro matched
  have different : 3 ≠ registryFold graph2 graph2.initial [1] := by decide
  exact different ((receipt_registry_after_prefix graph2 ordered2 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [1] (.cons (by decide) (by decide) (.nil _)) 2 3 (by decide) (by decide)).mp matched)
example : receiptRegistryMatches graph2 3 0 = true := by
  exact (receipt_registry_after_prefix graph2 ordered2 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [0, 6, 5] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _)))) 3 0 (by decide) (by decide)).mpr (by decide)
example : receiptRegistryMatches graph2 3 3 = false := by
  apply Bool.eq_false_iff.mpr
  intro matched
  have different : 3 ≠ registryFold graph2 graph2.initial [0, 6, 5] := by decide
  exact different ((receipt_registry_after_prefix graph2 ordered2 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [0, 6, 5] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _)))) 3 3 (by decide) (by decide)).mp matched)
example : receiptRegistryMatches graph2 4 0 = true := by decide
example : receiptRegistryMatches graph2 4 3 = false := by decide
example : receiptRegistryMatches graph2 5 2 = true := by
  exact (receipt_registry_after_prefix graph2 ordered2 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [0, 6] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 5 2 (by decide) (by decide)).mpr (by decide)
example : receiptRegistryMatches graph2 5 3 = false := by
  apply Bool.eq_false_iff.mpr
  intro matched
  have different : 3 ≠ registryFold graph2 graph2.initial [0, 6] := by decide
  exact different ((receipt_registry_after_prefix graph2 ordered2 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [0, 6] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 5 3 (by decide) (by decide)).mp matched)
example : receiptRegistryMatches graph2 6 0 = false := by
  apply Bool.eq_false_iff.mpr
  intro matched
  have different : 0 ≠ registryFold graph2 graph2.initial [0] := by decide
  exact different ((receipt_registry_after_prefix graph2 ordered2 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [0] (.cons (by decide) (by decide) (.nil _)) 6 0 (by decide) (by decide)).mp matched)
example : receiptRegistryMatches graph2 6 2 = true := by
  exact (receipt_registry_after_prefix graph2 ordered2 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [0] (.cons (by decide) (by decide) (.nil _)) 6 2 (by decide) (by decide)).mpr (by decide)
example : receiptRegistryMatches graph2 6 3 = false := by
  apply Bool.eq_false_iff.mpr
  intro matched
  have different : 3 ≠ registryFold graph2 graph2.initial [0] := by decide
  exact different ((receipt_registry_after_prefix graph2 ordered2 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [0] (.cons (by decide) (by decide) (.nil _)) 6 3 (by decide) (by decide)).mp matched)
example : expectedRegistry graph2 0 = some 0 := by
  have h := expected_registry_after_prefix graph2 ordered2 (by decide) (by decide) [4, 0, 1, 6, 2, 5, 3, 4, 0, 1, 0, 6, 6, 2, 5, 3] [] (.nil _) 0 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph2 1 = some 0 := by
  have h := expected_registry_after_prefix graph2 ordered2 (by decide) (by decide) [4, 0, 1, 6, 2, 5, 3, 4, 0, 1, 0, 6, 6, 2, 5, 3] [] (.nil _) 1 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph2 2 = some 1 := by
  have h := expected_registry_after_prefix graph2 ordered2 (by decide) (by decide) [4, 0, 1, 6, 2, 5, 3, 4, 0, 1, 0, 6, 6, 2, 5, 3] [1] (.cons (by decide) (by decide) (.nil _)) 2 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph2 3 = some 0 := by
  have h := expected_registry_after_prefix graph2 ordered2 (by decide) (by decide) [4, 0, 1, 6, 2, 5, 3, 4, 0, 1, 0, 6, 6, 2, 5, 3] [0, 6, 5] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _)))) 3 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph2 5 = some 2 := by
  have h := expected_registry_after_prefix graph2 ordered2 (by decide) (by decide) [4, 0, 1, 6, 2, 5, 3, 4, 0, 1, 0, 6, 6, 2, 5, 3] [0, 6] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 5 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph2 6 = some 2 := by
  have h := expected_registry_after_prefix graph2 ordered2 (by decide) (by decide) [4, 0, 1, 6, 2, 5, 3, 4, 0, 1, 0, 6, 6, 2, 5, 3] [0] (.cons (by decide) (by decide) (.nil _)) 6 (by decide) (by decide)
  exact h.trans (by decide)
example : registryAt graph2 2 = some 1 := by
  have h := registry_prefix_agrees graph2 ordered2 (by decide) [4, 0, 1, 6, 2, 5, 3, 4, 0, 1, 0, 6, 6, 2, 5, 3] 4 [1, 2] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 0 (registry_at_root _ (by decide))
  exact h.trans (by decide)
example : expectedRegistry graph2 0 = some 0 := by
  have h := expected_registry_after_prefix graph2 ordered2 (by decide) (by decide) [3, 5, 2, 6, 6, 0, 1, 0, 4, 3, 5, 2, 6, 1, 0, 4] [] (.nil _) 0 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph2 1 = some 0 := by
  have h := expected_registry_after_prefix graph2 ordered2 (by decide) (by decide) [3, 5, 2, 6, 6, 0, 1, 0, 4, 3, 5, 2, 6, 1, 0, 4] [] (.nil _) 1 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph2 2 = some 1 := by
  have h := expected_registry_after_prefix graph2 ordered2 (by decide) (by decide) [3, 5, 2, 6, 6, 0, 1, 0, 4, 3, 5, 2, 6, 1, 0, 4] [1] (.cons (by decide) (by decide) (.nil _)) 2 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph2 3 = some 0 := by
  have h := expected_registry_after_prefix graph2 ordered2 (by decide) (by decide) [3, 5, 2, 6, 6, 0, 1, 0, 4, 3, 5, 2, 6, 1, 0, 4] [0, 6, 5] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _)))) 3 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph2 5 = some 2 := by
  have h := expected_registry_after_prefix graph2 ordered2 (by decide) (by decide) [3, 5, 2, 6, 6, 0, 1, 0, 4, 3, 5, 2, 6, 1, 0, 4] [0, 6] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 5 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph2 6 = some 2 := by
  have h := expected_registry_after_prefix graph2 ordered2 (by decide) (by decide) [3, 5, 2, 6, 6, 0, 1, 0, 4, 3, 5, 2, 6, 1, 0, 4] [0] (.cons (by decide) (by decide) (.nil _)) 6 (by decide) (by decide)
  exact h.trans (by decide)
example : registryAt graph2 2 = some 1 := by
  have h := registry_prefix_agrees graph2 ordered2 (by decide) [3, 5, 2, 6, 6, 0, 1, 0, 4, 3, 5, 2, 6, 1, 0, 4] 4 [1, 2] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 0 (registry_at_root _ (by decide))
  exact h.trans (by decide)
example : expectedRegistry graph2 0 = some 0 := by
  have h := expected_registry_after_prefix graph2 ordered2 (by decide) (by decide) [4, 0, 1, 0, 6, 6, 2, 5, 3, 3, 5, 2, 6, 1, 0, 4] [] (.nil _) 0 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph2 1 = some 0 := by
  have h := expected_registry_after_prefix graph2 ordered2 (by decide) (by decide) [4, 0, 1, 0, 6, 6, 2, 5, 3, 3, 5, 2, 6, 1, 0, 4] [] (.nil _) 1 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph2 2 = some 1 := by
  have h := expected_registry_after_prefix graph2 ordered2 (by decide) (by decide) [4, 0, 1, 0, 6, 6, 2, 5, 3, 3, 5, 2, 6, 1, 0, 4] [1] (.cons (by decide) (by decide) (.nil _)) 2 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph2 3 = some 0 := by
  have h := expected_registry_after_prefix graph2 ordered2 (by decide) (by decide) [4, 0, 1, 0, 6, 6, 2, 5, 3, 3, 5, 2, 6, 1, 0, 4] [0, 6, 5] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _)))) 3 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph2 5 = some 2 := by
  have h := expected_registry_after_prefix graph2 ordered2 (by decide) (by decide) [4, 0, 1, 0, 6, 6, 2, 5, 3, 3, 5, 2, 6, 1, 0, 4] [0, 6] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 5 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph2 6 = some 2 := by
  have h := expected_registry_after_prefix graph2 ordered2 (by decide) (by decide) [4, 0, 1, 0, 6, 6, 2, 5, 3, 3, 5, 2, 6, 1, 0, 4] [0] (.cons (by decide) (by decide) (.nil _)) 6 (by decide) (by decide)
  exact h.trans (by decide)
example : registryAt graph2 2 = some 1 := by
  have h := registry_prefix_agrees graph2 ordered2 (by decide) [4, 0, 1, 0, 6, 6, 2, 5, 3, 3, 5, 2, 6, 1, 0, 4] 4 [1, 2] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 0 (registry_at_root _ (by decide))
  exact h.trans (by decide)
example : expectedRegistry graph2 0 = some 0 := by
  have h := expected_registry_after_prefix graph2 ordered2 (by decide) (by decide) [3, 5, 2, 6, 1, 0, 4, 4, 0, 1, 0, 6, 6, 2, 5, 3] [] (.nil _) 0 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph2 1 = some 0 := by
  have h := expected_registry_after_prefix graph2 ordered2 (by decide) (by decide) [3, 5, 2, 6, 1, 0, 4, 4, 0, 1, 0, 6, 6, 2, 5, 3] [] (.nil _) 1 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph2 2 = some 1 := by
  have h := expected_registry_after_prefix graph2 ordered2 (by decide) (by decide) [3, 5, 2, 6, 1, 0, 4, 4, 0, 1, 0, 6, 6, 2, 5, 3] [1] (.cons (by decide) (by decide) (.nil _)) 2 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph2 3 = some 0 := by
  have h := expected_registry_after_prefix graph2 ordered2 (by decide) (by decide) [3, 5, 2, 6, 1, 0, 4, 4, 0, 1, 0, 6, 6, 2, 5, 3] [0, 6, 5] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _)))) 3 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph2 5 = some 2 := by
  have h := expected_registry_after_prefix graph2 ordered2 (by decide) (by decide) [3, 5, 2, 6, 1, 0, 4, 4, 0, 1, 0, 6, 6, 2, 5, 3] [0, 6] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 5 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph2 6 = some 2 := by
  have h := expected_registry_after_prefix graph2 ordered2 (by decide) (by decide) [3, 5, 2, 6, 1, 0, 4, 4, 0, 1, 0, 6, 6, 2, 5, 3] [0] (.cons (by decide) (by decide) (.nil _)) 6 (by decide) (by decide)
  exact h.trans (by decide)
example : registryAt graph2 2 = some 1 := by
  have h := registry_prefix_agrees graph2 ordered2 (by decide) [3, 5, 2, 6, 1, 0, 4, 4, 0, 1, 0, 6, 6, 2, 5, 3] 4 [1, 2] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 0 (registry_at_root _ (by decide))
  exact h.trans (by decide)
example : expectedRegistry graph2 0 = some 0 := by
  have h := expected_registry_after_prefix graph2 ordered2 (by decide) (by decide) [1, 2, 4, 0, 6, 5, 3, 3, 5, 2, 6, 6, 0, 1, 0, 4] [] (.nil _) 0 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph2 1 = some 0 := by
  have h := expected_registry_after_prefix graph2 ordered2 (by decide) (by decide) [1, 2, 4, 0, 6, 5, 3, 3, 5, 2, 6, 6, 0, 1, 0, 4] [] (.nil _) 1 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph2 2 = some 1 := by
  have h := expected_registry_after_prefix graph2 ordered2 (by decide) (by decide) [1, 2, 4, 0, 6, 5, 3, 3, 5, 2, 6, 6, 0, 1, 0, 4] [1] (.cons (by decide) (by decide) (.nil _)) 2 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph2 3 = some 0 := by
  have h := expected_registry_after_prefix graph2 ordered2 (by decide) (by decide) [1, 2, 4, 0, 6, 5, 3, 3, 5, 2, 6, 6, 0, 1, 0, 4] [0, 6, 5] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _)))) 3 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph2 5 = some 2 := by
  have h := expected_registry_after_prefix graph2 ordered2 (by decide) (by decide) [1, 2, 4, 0, 6, 5, 3, 3, 5, 2, 6, 6, 0, 1, 0, 4] [0, 6] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 5 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph2 6 = some 2 := by
  have h := expected_registry_after_prefix graph2 ordered2 (by decide) (by decide) [1, 2, 4, 0, 6, 5, 3, 3, 5, 2, 6, 6, 0, 1, 0, 4] [0] (.cons (by decide) (by decide) (.nil _)) 6 (by decide) (by decide)
  exact h.trans (by decide)
example : registryAt graph2 2 = some 1 := by
  have h := registry_prefix_agrees graph2 ordered2 (by decide) [1, 2, 4, 0, 6, 5, 3, 3, 5, 2, 6, 6, 0, 1, 0, 4] 4 [1, 2] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 0 (registry_at_root _ (by decide))
  exact h.trans (by decide)
example : expectedRegistry graph2 0 = some 0 := by
  have h := expected_registry_after_prefix graph2 ordered2 (by decide) (by decide) [0, 6, 5, 3, 4, 1, 2, 4, 0, 1, 0, 6, 6, 2, 5, 3] [] (.nil _) 0 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph2 1 = some 0 := by
  have h := expected_registry_after_prefix graph2 ordered2 (by decide) (by decide) [0, 6, 5, 3, 4, 1, 2, 4, 0, 1, 0, 6, 6, 2, 5, 3] [] (.nil _) 1 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph2 2 = some 1 := by
  have h := expected_registry_after_prefix graph2 ordered2 (by decide) (by decide) [0, 6, 5, 3, 4, 1, 2, 4, 0, 1, 0, 6, 6, 2, 5, 3] [1] (.cons (by decide) (by decide) (.nil _)) 2 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph2 3 = some 0 := by
  have h := expected_registry_after_prefix graph2 ordered2 (by decide) (by decide) [0, 6, 5, 3, 4, 1, 2, 4, 0, 1, 0, 6, 6, 2, 5, 3] [0, 6, 5] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _)))) 3 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph2 5 = some 2 := by
  have h := expected_registry_after_prefix graph2 ordered2 (by decide) (by decide) [0, 6, 5, 3, 4, 1, 2, 4, 0, 1, 0, 6, 6, 2, 5, 3] [0, 6] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 5 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph2 6 = some 2 := by
  have h := expected_registry_after_prefix graph2 ordered2 (by decide) (by decide) [0, 6, 5, 3, 4, 1, 2, 4, 0, 1, 0, 6, 6, 2, 5, 3] [0] (.cons (by decide) (by decide) (.nil _)) 6 (by decide) (by decide)
  exact h.trans (by decide)
example : registryAt graph2 2 = some 1 := by
  have h := registry_prefix_agrees graph2 ordered2 (by decide) [0, 6, 5, 3, 4, 1, 2, 4, 0, 1, 0, 6, 6, 2, 5, 3] 4 [1, 2] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 0 (registry_at_root _ (by decide))
  exact h.trans (by decide)
-- Registry names: BTC:signet, ETH:sepolia, ZEC:testnet, hyperswarm
def graph3 : RegistryGraph := {
  size := 7
  root := 4
  initial := 0
  parent := (fun i => [some 4, some 4, some 1, some 5, none, some 6, some 0].getD i (none))
  depth := (fun i => [1, 1, 2, 4, 0, 3, 2].getD i (0))
  change := (fun i => [some 2, some 1, none, none, none, some 0, none].getD i (none))
}
theorem ordered3 : RegistryOrdered graph3 := by
  intro i p parent
  by_cases bound : i < 7
  · have cases : i = 0 ∨ i = 1 ∨ i = 2 ∨ i = 3 ∨ i = 4 ∨ i = 5 ∨ i = 6 := by omega
    rcases cases with rfl | rfl | rfl | rfl | rfl | rfl | rfl <;> simp [graph3] at parent
    all_goals subst p; decide
  · have outside : 7 ≤ i := by omega
    simp only [graph3] at parent
    rw [List.getD_eq_getElem?_getD, List.getElem?_eq_none (by simpa using outside)] at parent
    simp at parent
example : expectedRegistry graph3 4 = some 0 := by decide
example : receiptRegistryMatches graph3 0 0 = true := by
  exact (receipt_registry_after_prefix graph3 ordered3 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [] (.nil _) 0 0 (by decide) (by decide)).mpr (by decide)
example : receiptRegistryMatches graph3 0 0 = true := by
  exact (receipt_registry_after_prefix graph3 ordered3 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [] (.nil _) 0 0 (by decide) (by decide)).mpr (by decide)
example : receiptRegistryMatches graph3 0 2 = false := by
  apply Bool.eq_false_iff.mpr
  intro matched
  have different : 2 ≠ registryFold graph3 graph3.initial [] := by decide
  exact different ((receipt_registry_after_prefix graph3 ordered3 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [] (.nil _) 0 2 (by decide) (by decide)).mp matched)
example : receiptRegistryMatches graph3 0 3 = false := by
  apply Bool.eq_false_iff.mpr
  intro matched
  have different : 3 ≠ registryFold graph3 graph3.initial [] := by decide
  exact different ((receipt_registry_after_prefix graph3 ordered3 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [] (.nil _) 0 3 (by decide) (by decide)).mp matched)
example : receiptRegistryMatches graph3 1 0 = true := by
  exact (receipt_registry_after_prefix graph3 ordered3 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [] (.nil _) 1 0 (by decide) (by decide)).mpr (by decide)
example : receiptRegistryMatches graph3 1 3 = false := by
  apply Bool.eq_false_iff.mpr
  intro matched
  have different : 3 ≠ registryFold graph3 graph3.initial [] := by decide
  exact different ((receipt_registry_after_prefix graph3 ordered3 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [] (.nil _) 1 3 (by decide) (by decide)).mp matched)
example : receiptRegistryMatches graph3 2 1 = true := by
  exact (receipt_registry_after_prefix graph3 ordered3 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [1] (.cons (by decide) (by decide) (.nil _)) 2 1 (by decide) (by decide)).mpr (by decide)
example : receiptRegistryMatches graph3 2 3 = false := by
  apply Bool.eq_false_iff.mpr
  intro matched
  have different : 3 ≠ registryFold graph3 graph3.initial [1] := by decide
  exact different ((receipt_registry_after_prefix graph3 ordered3 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [1] (.cons (by decide) (by decide) (.nil _)) 2 3 (by decide) (by decide)).mp matched)
example : receiptRegistryMatches graph3 3 0 = true := by
  exact (receipt_registry_after_prefix graph3 ordered3 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [0, 6, 5] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _)))) 3 0 (by decide) (by decide)).mpr (by decide)
example : receiptRegistryMatches graph3 3 3 = false := by
  apply Bool.eq_false_iff.mpr
  intro matched
  have different : 3 ≠ registryFold graph3 graph3.initial [0, 6, 5] := by decide
  exact different ((receipt_registry_after_prefix graph3 ordered3 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [0, 6, 5] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _)))) 3 3 (by decide) (by decide)).mp matched)
example : receiptRegistryMatches graph3 4 0 = true := by decide
example : receiptRegistryMatches graph3 4 3 = false := by decide
example : receiptRegistryMatches graph3 5 2 = true := by
  exact (receipt_registry_after_prefix graph3 ordered3 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [0, 6] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 5 2 (by decide) (by decide)).mpr (by decide)
example : receiptRegistryMatches graph3 5 3 = false := by
  apply Bool.eq_false_iff.mpr
  intro matched
  have different : 3 ≠ registryFold graph3 graph3.initial [0, 6] := by decide
  exact different ((receipt_registry_after_prefix graph3 ordered3 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [0, 6] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 5 3 (by decide) (by decide)).mp matched)
example : receiptRegistryMatches graph3 6 0 = false := by
  apply Bool.eq_false_iff.mpr
  intro matched
  have different : 0 ≠ registryFold graph3 graph3.initial [0] := by decide
  exact different ((receipt_registry_after_prefix graph3 ordered3 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [0] (.cons (by decide) (by decide) (.nil _)) 6 0 (by decide) (by decide)).mp matched)
example : receiptRegistryMatches graph3 6 2 = true := by
  exact (receipt_registry_after_prefix graph3 ordered3 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [0] (.cons (by decide) (by decide) (.nil _)) 6 2 (by decide) (by decide)).mpr (by decide)
example : receiptRegistryMatches graph3 6 3 = false := by
  apply Bool.eq_false_iff.mpr
  intro matched
  have different : 3 ≠ registryFold graph3 graph3.initial [0] := by decide
  exact different ((receipt_registry_after_prefix graph3 ordered3 (by decide) (by decide) [0, 1, 2, 3, 4, 5, 6] [0] (.cons (by decide) (by decide) (.nil _)) 6 3 (by decide) (by decide)).mp matched)
example : expectedRegistry graph3 0 = some 0 := by
  have h := expected_registry_after_prefix graph3 ordered3 (by decide) (by decide) [4, 0, 1, 6, 2, 5, 3, 4, 0, 1, 0, 6, 6, 2, 5, 3, 0] [] (.nil _) 0 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph3 1 = some 0 := by
  have h := expected_registry_after_prefix graph3 ordered3 (by decide) (by decide) [4, 0, 1, 6, 2, 5, 3, 4, 0, 1, 0, 6, 6, 2, 5, 3, 0] [] (.nil _) 1 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph3 2 = some 1 := by
  have h := expected_registry_after_prefix graph3 ordered3 (by decide) (by decide) [4, 0, 1, 6, 2, 5, 3, 4, 0, 1, 0, 6, 6, 2, 5, 3, 0] [1] (.cons (by decide) (by decide) (.nil _)) 2 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph3 3 = some 0 := by
  have h := expected_registry_after_prefix graph3 ordered3 (by decide) (by decide) [4, 0, 1, 6, 2, 5, 3, 4, 0, 1, 0, 6, 6, 2, 5, 3, 0] [0, 6, 5] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _)))) 3 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph3 5 = some 2 := by
  have h := expected_registry_after_prefix graph3 ordered3 (by decide) (by decide) [4, 0, 1, 6, 2, 5, 3, 4, 0, 1, 0, 6, 6, 2, 5, 3, 0] [0, 6] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 5 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph3 6 = some 2 := by
  have h := expected_registry_after_prefix graph3 ordered3 (by decide) (by decide) [4, 0, 1, 6, 2, 5, 3, 4, 0, 1, 0, 6, 6, 2, 5, 3, 0] [0] (.cons (by decide) (by decide) (.nil _)) 6 (by decide) (by decide)
  exact h.trans (by decide)
example : registryAt graph3 3 = some 0 := by
  have h := registry_prefix_agrees graph3 ordered3 (by decide) [4, 0, 1, 6, 2, 5, 3, 4, 0, 1, 0, 6, 6, 2, 5, 3, 0] 4 [0, 6, 5, 3] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))))) 0 (registry_at_root _ (by decide))
  exact h.trans (by decide)
example : expectedRegistry graph3 0 = some 0 := by
  have h := expected_registry_after_prefix graph3 ordered3 (by decide) (by decide) [0, 3, 5, 2, 6, 6, 0, 1, 0, 4, 3, 5, 2, 6, 1, 0, 4] [] (.nil _) 0 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph3 1 = some 0 := by
  have h := expected_registry_after_prefix graph3 ordered3 (by decide) (by decide) [0, 3, 5, 2, 6, 6, 0, 1, 0, 4, 3, 5, 2, 6, 1, 0, 4] [] (.nil _) 1 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph3 2 = some 1 := by
  have h := expected_registry_after_prefix graph3 ordered3 (by decide) (by decide) [0, 3, 5, 2, 6, 6, 0, 1, 0, 4, 3, 5, 2, 6, 1, 0, 4] [1] (.cons (by decide) (by decide) (.nil _)) 2 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph3 3 = some 0 := by
  have h := expected_registry_after_prefix graph3 ordered3 (by decide) (by decide) [0, 3, 5, 2, 6, 6, 0, 1, 0, 4, 3, 5, 2, 6, 1, 0, 4] [0, 6, 5] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _)))) 3 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph3 5 = some 2 := by
  have h := expected_registry_after_prefix graph3 ordered3 (by decide) (by decide) [0, 3, 5, 2, 6, 6, 0, 1, 0, 4, 3, 5, 2, 6, 1, 0, 4] [0, 6] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 5 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph3 6 = some 2 := by
  have h := expected_registry_after_prefix graph3 ordered3 (by decide) (by decide) [0, 3, 5, 2, 6, 6, 0, 1, 0, 4, 3, 5, 2, 6, 1, 0, 4] [0] (.cons (by decide) (by decide) (.nil _)) 6 (by decide) (by decide)
  exact h.trans (by decide)
example : registryAt graph3 3 = some 0 := by
  have h := registry_prefix_agrees graph3 ordered3 (by decide) [0, 3, 5, 2, 6, 6, 0, 1, 0, 4, 3, 5, 2, 6, 1, 0, 4] 4 [0, 6, 5, 3] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))))) 0 (registry_at_root _ (by decide))
  exact h.trans (by decide)
example : expectedRegistry graph3 0 = some 0 := by
  have h := expected_registry_after_prefix graph3 ordered3 (by decide) (by decide) [4, 0, 1, 0, 6, 6, 2, 5, 3, 0, 3, 5, 2, 6, 1, 0, 4] [] (.nil _) 0 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph3 1 = some 0 := by
  have h := expected_registry_after_prefix graph3 ordered3 (by decide) (by decide) [4, 0, 1, 0, 6, 6, 2, 5, 3, 0, 3, 5, 2, 6, 1, 0, 4] [] (.nil _) 1 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph3 2 = some 1 := by
  have h := expected_registry_after_prefix graph3 ordered3 (by decide) (by decide) [4, 0, 1, 0, 6, 6, 2, 5, 3, 0, 3, 5, 2, 6, 1, 0, 4] [1] (.cons (by decide) (by decide) (.nil _)) 2 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph3 3 = some 0 := by
  have h := expected_registry_after_prefix graph3 ordered3 (by decide) (by decide) [4, 0, 1, 0, 6, 6, 2, 5, 3, 0, 3, 5, 2, 6, 1, 0, 4] [0, 6, 5] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _)))) 3 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph3 5 = some 2 := by
  have h := expected_registry_after_prefix graph3 ordered3 (by decide) (by decide) [4, 0, 1, 0, 6, 6, 2, 5, 3, 0, 3, 5, 2, 6, 1, 0, 4] [0, 6] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 5 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph3 6 = some 2 := by
  have h := expected_registry_after_prefix graph3 ordered3 (by decide) (by decide) [4, 0, 1, 0, 6, 6, 2, 5, 3, 0, 3, 5, 2, 6, 1, 0, 4] [0] (.cons (by decide) (by decide) (.nil _)) 6 (by decide) (by decide)
  exact h.trans (by decide)
example : registryAt graph3 3 = some 0 := by
  have h := registry_prefix_agrees graph3 ordered3 (by decide) [4, 0, 1, 0, 6, 6, 2, 5, 3, 0, 3, 5, 2, 6, 1, 0, 4] 4 [0, 6, 5, 3] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))))) 0 (registry_at_root _ (by decide))
  exact h.trans (by decide)
example : expectedRegistry graph3 0 = some 0 := by
  have h := expected_registry_after_prefix graph3 ordered3 (by decide) (by decide) [3, 5, 2, 6, 1, 0, 4, 4, 0, 1, 0, 6, 6, 2, 5, 3, 0] [] (.nil _) 0 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph3 1 = some 0 := by
  have h := expected_registry_after_prefix graph3 ordered3 (by decide) (by decide) [3, 5, 2, 6, 1, 0, 4, 4, 0, 1, 0, 6, 6, 2, 5, 3, 0] [] (.nil _) 1 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph3 2 = some 1 := by
  have h := expected_registry_after_prefix graph3 ordered3 (by decide) (by decide) [3, 5, 2, 6, 1, 0, 4, 4, 0, 1, 0, 6, 6, 2, 5, 3, 0] [1] (.cons (by decide) (by decide) (.nil _)) 2 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph3 3 = some 0 := by
  have h := expected_registry_after_prefix graph3 ordered3 (by decide) (by decide) [3, 5, 2, 6, 1, 0, 4, 4, 0, 1, 0, 6, 6, 2, 5, 3, 0] [0, 6, 5] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _)))) 3 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph3 5 = some 2 := by
  have h := expected_registry_after_prefix graph3 ordered3 (by decide) (by decide) [3, 5, 2, 6, 1, 0, 4, 4, 0, 1, 0, 6, 6, 2, 5, 3, 0] [0, 6] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 5 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph3 6 = some 2 := by
  have h := expected_registry_after_prefix graph3 ordered3 (by decide) (by decide) [3, 5, 2, 6, 1, 0, 4, 4, 0, 1, 0, 6, 6, 2, 5, 3, 0] [0] (.cons (by decide) (by decide) (.nil _)) 6 (by decide) (by decide)
  exact h.trans (by decide)
example : registryAt graph3 3 = some 0 := by
  have h := registry_prefix_agrees graph3 ordered3 (by decide) [3, 5, 2, 6, 1, 0, 4, 4, 0, 1, 0, 6, 6, 2, 5, 3, 0] 4 [0, 6, 5, 3] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))))) 0 (registry_at_root _ (by decide))
  exact h.trans (by decide)
example : expectedRegistry graph3 0 = some 0 := by
  have h := expected_registry_after_prefix graph3 ordered3 (by decide) (by decide) [1, 2, 4, 0, 6, 5, 3, 0, 3, 5, 2, 6, 6, 0, 1, 0, 4] [] (.nil _) 0 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph3 1 = some 0 := by
  have h := expected_registry_after_prefix graph3 ordered3 (by decide) (by decide) [1, 2, 4, 0, 6, 5, 3, 0, 3, 5, 2, 6, 6, 0, 1, 0, 4] [] (.nil _) 1 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph3 2 = some 1 := by
  have h := expected_registry_after_prefix graph3 ordered3 (by decide) (by decide) [1, 2, 4, 0, 6, 5, 3, 0, 3, 5, 2, 6, 6, 0, 1, 0, 4] [1] (.cons (by decide) (by decide) (.nil _)) 2 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph3 3 = some 0 := by
  have h := expected_registry_after_prefix graph3 ordered3 (by decide) (by decide) [1, 2, 4, 0, 6, 5, 3, 0, 3, 5, 2, 6, 6, 0, 1, 0, 4] [0, 6, 5] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _)))) 3 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph3 5 = some 2 := by
  have h := expected_registry_after_prefix graph3 ordered3 (by decide) (by decide) [1, 2, 4, 0, 6, 5, 3, 0, 3, 5, 2, 6, 6, 0, 1, 0, 4] [0, 6] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 5 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph3 6 = some 2 := by
  have h := expected_registry_after_prefix graph3 ordered3 (by decide) (by decide) [1, 2, 4, 0, 6, 5, 3, 0, 3, 5, 2, 6, 6, 0, 1, 0, 4] [0] (.cons (by decide) (by decide) (.nil _)) 6 (by decide) (by decide)
  exact h.trans (by decide)
example : registryAt graph3 3 = some 0 := by
  have h := registry_prefix_agrees graph3 ordered3 (by decide) [1, 2, 4, 0, 6, 5, 3, 0, 3, 5, 2, 6, 6, 0, 1, 0, 4] 4 [0, 6, 5, 3] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))))) 0 (registry_at_root _ (by decide))
  exact h.trans (by decide)
example : expectedRegistry graph3 0 = some 0 := by
  have h := expected_registry_after_prefix graph3 ordered3 (by decide) (by decide) [0, 6, 5, 3, 4, 1, 2, 4, 0, 1, 0, 6, 6, 2, 5, 3, 0] [] (.nil _) 0 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph3 1 = some 0 := by
  have h := expected_registry_after_prefix graph3 ordered3 (by decide) (by decide) [0, 6, 5, 3, 4, 1, 2, 4, 0, 1, 0, 6, 6, 2, 5, 3, 0] [] (.nil _) 1 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph3 2 = some 1 := by
  have h := expected_registry_after_prefix graph3 ordered3 (by decide) (by decide) [0, 6, 5, 3, 4, 1, 2, 4, 0, 1, 0, 6, 6, 2, 5, 3, 0] [1] (.cons (by decide) (by decide) (.nil _)) 2 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph3 3 = some 0 := by
  have h := expected_registry_after_prefix graph3 ordered3 (by decide) (by decide) [0, 6, 5, 3, 4, 1, 2, 4, 0, 1, 0, 6, 6, 2, 5, 3, 0] [0, 6, 5] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _)))) 3 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph3 5 = some 2 := by
  have h := expected_registry_after_prefix graph3 ordered3 (by decide) (by decide) [0, 6, 5, 3, 4, 1, 2, 4, 0, 1, 0, 6, 6, 2, 5, 3, 0] [0, 6] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))) 5 (by decide) (by decide)
  exact h.trans (by decide)
example : expectedRegistry graph3 6 = some 2 := by
  have h := expected_registry_after_prefix graph3 ordered3 (by decide) (by decide) [0, 6, 5, 3, 4, 1, 2, 4, 0, 1, 0, 6, 6, 2, 5, 3, 0] [0] (.cons (by decide) (by decide) (.nil _)) 6 (by decide) (by decide)
  exact h.trans (by decide)
example : registryAt graph3 3 = some 0 := by
  have h := registry_prefix_agrees graph3 ordered3 (by decide) [0, 6, 5, 3, 4, 1, 2, 4, 0, 1, 0, 6, 6, 2, 5, 3, 0] 4 [0, 6, 5, 3] (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.cons (by decide) (by decide) (.nil _))))) 0 (registry_at_root _ (by decide))
  exact h.trans (by decide)
end Archon.RegistryFixtures
