FROM node:22.15.0-bullseye-slim

WORKDIR /app

COPY package*.json ./
COPY packages/ ./packages/

RUN npm ci
RUN npm run build

COPY services/mediators/pinning ./pinning/

RUN cd pinning && npm ci && npm run build

WORKDIR /app/pinning

ARG GIT_COMMIT=unknown
ENV GIT_COMMIT=$GIT_COMMIT

EXPOSE 4273

CMD ["node", "dist/pinning-mediator.js"]
