name: Build React-Wallet webapp

on:
  push:

jobs:
  build-android-webapp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Use Node 22.15.0
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: '22.15.0'

      - name: Pin npm 10.9.2
        run: npm install --global npm@10.9.2

      - name: Install root dependencies
        run: npm ci

      - name: Compile TypeScript
        run: npm run build

      - name: Install dependencies
        run: |
          cd ./apps/react-wallet
          npm ci

      - name: Build extension
        run: |
          cd ./apps/react-wallet
          npm run build
