name: Build Docker images

on:
  push:

env:
  REGISTRY: ghcr.io

jobs:
  generate:
    runs-on: ubuntu-latest
    outputs:
      CALVER: ${{ steps.calculate-calver.outputs.calver }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Calculate Calver
        id: calculate-calver
        run: |
          calver=$(date +'%Y.%m.%d')
          echo "calver=$calver" >> $GITHUB_OUTPUT

  build_test_images:
    runs-on: ubuntu-latest
    needs: generate
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: Dockerfile.gatekeeper-ts
            image: gatekeeper
          - dockerfile: Dockerfile.keymaster
            image: keymaster
          - dockerfile: services/herald/Dockerfile
            image: herald
          - dockerfile: Dockerfile.drawbridge
            image: drawbridge
          - dockerfile: Dockerfile.hyperswarm
            image: hyperswarm-mediator
          - dockerfile: Dockerfile.satoshi-wallet
            image: satoshi-wallet
          - dockerfile: Dockerfile.satoshi
            image: satoshi-mediator
          - dockerfile: Dockerfile.lightning-mediator
            image: lightning-mediator
          - dockerfile: Dockerfile.cli
            image: cli
          - dockerfile: Dockerfile.explorer
            image: explorer
          - dockerfile: Dockerfile.gatekeeper-client
            image: gatekeeper-client
          - dockerfile: Dockerfile.keymaster-client
            image: keymaster-client
          - dockerfile: Dockerfile.react-wallet
            image: react-wallet
          - dockerfile: Dockerfile.herald-client
            image: herald-client
          - dockerfile: Dockerfile.gatekeeper-client
            image: drawbridge-client
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051
        with:
          images: ${{ env.REGISTRY }}/archetech/${{ matrix.image }}
          tags: |
            type=raw,value=${{ needs.generate.outputs.CALVER }}
            type=raw,value=latest

      - name: Build Docker images
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: false
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            GIT_COMMIT=${{ github.sha }}

      - name: Run Anchore vulnerability scanner
        uses: anchore/scan-action@3343887d815d7b07465f6fdcd395bd66508d486a
        with:
          image: ${{ env.REGISTRY }}/archetech/${{ matrix.image }}:${{ needs.generate.outputs.CALVER }}
          fail-build: false
          severity-cutoff: critical
          output-format: table
