name: Build & Publish

on:
  push:
    branches: [ "pre-release" ]

env:
  REGISTRY: ghcr.io

jobs:
  generate:
    runs-on: ubuntu-latest
    outputs:
      CALVER: ${{ steps.calculate-calver.outputs.calver }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Calculate Calver
        id: calculate-calver
        run: |
          calver=$(date +'%Y.%m.%d')
          echo "calver=$calver" >> $GITHUB_OUTPUT

  build_test_images:
    runs-on: ubuntu-latest
    needs: generate
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: docker/Dockerfile.gatekeeper-ts
            image: gatekeeper
          - dockerfile: docker/Dockerfile.keymaster-ts
            image: keymaster
          - dockerfile: services/herald/Dockerfile
            image: herald
          - dockerfile: docker/Dockerfile.drawbridge
            image: drawbridge
          - dockerfile: docker/Dockerfile.hyperswarm
            image: hyperswarm-mediator
          - dockerfile: docker/Dockerfile.satoshi-wallet
            image: satoshi-wallet
          - dockerfile: docker/Dockerfile.satoshi
            image: satoshi-mediator
          - dockerfile: docker/Dockerfile.lightning-mediator
            image: lightning-mediator
          - dockerfile: docker/Dockerfile.cli
            image: cli
          - dockerfile: docker/Dockerfile.explorer
            image: explorer
          - dockerfile: docker/Dockerfile.gatekeeper-client
            image: gatekeeper-client
          - dockerfile: docker/Dockerfile.keymaster-client
            image: keymaster-client
          - dockerfile: docker/Dockerfile.react-wallet
            image: react-wallet
          - dockerfile: docker/Dockerfile.herald-client
            image: herald-client
          - dockerfile: docker/Dockerfile.gatekeeper-client
            image: drawbridge-client
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9
        with:
          images: ${{ env.REGISTRY }}/archetech/${{ matrix.image }}
          tags: |
            type=raw,value=${{ needs.generate.outputs.CALVER }}
            type=raw,value=pre-release

      - name: Build and push Docker images
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            GIT_COMMIT=${{ github.sha }}

      - name: Run Anchore vulnerability scanner
        uses: anchore/scan-action@e1165082ffb1fe366ebaf02d8526e7c4989ea9d2
        with:
          image: ${{ env.REGISTRY }}/archetech/${{ matrix.image }}:${{
            needs.generate.outputs.CALVER }}
          fail-build: false
          severity-cutoff: critical
          output-format: table
