name: 'E2E Test Report'
on:
  workflow_run:
    workflows: ['Build & Test Docker images']                     # runs after Build & Test Docker images workflow
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flavor: [rust, typescript]
    steps:
      - uses: dorny/test-reporter@0f7d1ed661203449e0ee89fa7a0a7f9c9a7d9911
        with:
          artifact: E2E Artifacts (${{ matrix.flavor }})
          name: CLI E2E Tests (${{ matrix.flavor }} gatekeeper)
          path: '*.xml'
          reporter: jest-junit
