name: unit-test

on:
  push:
    branches:
      - "**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: "22.15.0"

      - name: Pin npm 10.9.2
        run: npm install --global npm@10.9.2

      - name: Install dependencies
        run: npm ci

      - name: Compile TypeScript
        run: npm run build

      - name: Run ESLint
        run: npm run lint

      - name: Run unit tests
        run: npm test

      - name: Generate Code Coverage report
        id: code-coverage
        uses: barecheck/code-coverage-action@d92cdaec187f89f0886ccec37acf11e2a6a85f70
        with:
          barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
          lcov-file: "./coverage/lcov.info"
          send-summary-comment: true
          show-annotations: "warning"

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b
        continue-on-error: true
